//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotTool.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 nN11lNtG2O9xgyzJlmRLtsMMDTMnDXPDDTMzMzXMzMzMjA0zU8PQYAMNM+P7nUnvOe+9f958zvj5zTMj2bveTRzVm7rcLpfrB79EFb9MDzfVKjZv0bZdkXZt2rRrmy5x1SYdO7Vo1zZfjgxZcmXIkilz7twZMufMnC1zusRFurTu3KVjk3xtm3Tp3LFB63SJK3Rp2LpFo9JNelRu16pJ23zZs2fJkitzk9w5G+XMnj171kw+cS8RefIMJZq0a9Okc8ceGco26dRcoa91/Xk/gQYdGzVv0bVJ1sZt/O3aN2nbtkvHhp2Uxg06NxCbdF33iIdop3S58lJPdWk/yu8lhMRNoVeKy/O5r8eV/ZUiP5wvPzyu6H8f2r0Ll8uVeHTe2XPfZQ90J32Zflu82l9Z//by595c2bO4XPmTulznEmSds+vj/R//v9X1//zK2/f4gRwJpxwIfGq13z9rYZEU7ycXmV5cK+py9Svwv8ae/zX+r97/eW5cHnnrpgpelwIf [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw_0 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd5NFXdwwfwfclQiDJnHiJzyHxdSkjmIRrMmRKuDLm4UiFjCBm7howlPKZEhpApVyRDpHDLNWUWXeO7e4a1fu9vve9a73rXev941/L9rHP2Xufsc84+Z6+zzzoAAQDYh/ld/g4tGVxZmLjc8EBroN3d0R7ivOaOXt430B6q8pIyipIyp6WVlCSlFaTPSIvzavi6+fh6Oap6OPr6eNm5ifMa+dq73biu6+hvhr7p6KEqJycjoyjtqKRwXUFOTk72NMXvqzD+eXJJbUe0u6OPl7+kvqO3yyG4ner2X9c5Yud13eXGbUdZB/fDaE9HDw9fL3vvQw52Pna/G1FTU5P97iKDMABIWPb4esYcJocV+t8rZWYAyLaCyYAk81+3s71PBpj+vrXvA8MG2rMfjzVNAYYQBP+yRC2H5Q7cv/F3A0Vx2D0HWOnnks1s+DW1/78twb+lLORdaw8hufWZtHeLjXmuhpZlssbpYqrzANxV+5el6V+W/7Ttn7EBZH+uEbAk [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw_CH_0 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN11lNtG2O9xgyzJlmRLtsMMDTMnDXPDDTMzMzXMzMzMjA0zM0ODDTRJw8x5vzPpPee998+bzxk/v3lmJHvXu4mjelOX2+Vy/eCXqOKX6eGmWsXmLdq2K9KuTZt2bdMlrtqkY6cW7drmy5EhS64MWTJlzp07Q+acmbNlTpe4SJfWnbt0bJKvbZMunTs2aJ0ucYUuDVu3aFS6SY/K7Vo1aZsve/YsWXJlbpI7Z6Oc2bNnz5rJJ+4lIk+eoUSTdm2adO7YI0PZJp2aK/S1rj/vJ9CgY6PmLbo2ydq4jb9d+yZt23bp2LCT0rhB5wZik67rHvEQ7ZQuV17qqS7tR/m9hJC4uZJTcXk+9/W4TuRU5Ifz5YfHFf3vQ7t/8Uq5Eo8vOHseuOyB7qQv02+LV/sr6xP/25trYhqXa1N8l+t8gqxzdn188OP/t7r+n1+fFg49EON5hgOlhlUs7J+1sEiKhxmKnK12vIjL1a/A/xp7/tf4v3r/57lxeeStmyp4XQp8 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw2_0 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNp3XE/vHzj8sw9CkhEtCUlpSCUtK2VUVlRStHeUtAuholSSokUoVEJEWtohRZOi0lba2ut+nfP5/h6P333/eXs+rvfrdV1ndnqfc73e3iEogiBz8I+JzL+FGLycOGJpZe+w28HOzsFefM1xM0cnKwd7ZTmJLdsktkhJKyhISMtLb5UWX7Pb2fa8s6OZsr2Z83nHM7biaw45G9tamRwwczvmYGNmrywru2XLNmkzBXkTeVlZWRkpkjkKN7tzCXUzBzuz845uEppmTpYEjNMX/jvOgjOOJpZWF8xkTO3mO5w1s7d3djR2IkzPnD/DrDRv3jyMOcUlIgiiBPGL89nA+TgknMxLayaCYJM+GFKX+d+PMzWHIcv+96O1Vddpqf+p4sptR5b4omsHNmfwGkzD8rj/rbstnkaQ6ySCVPLLxGaPt8/9/43I/+efks+nAjmBOwULJmzyHV0DCjaMhu++u5fegyAXVf+vlvt/tf/X2P/53SAY+4pCxBAcIRASUAiN [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw2_1 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dh3UBTLgwfwXjKKBEkiGRREkCiSQUEkCSgSRJDMgqRFlpwWE5IEAZUFCSJJEUkSJK1I8IEsQaIigqQlg7ISdknXvvd+V7/71V3Vr67q/rni+6mZ7prpmumZqeneWYAAAOzB/C5/h4ECrixMXG94obRQnp4oLwkBc2cf9A2Ul9oZSVlFSVlpGSUlSRkFmdMyEgJafh6+fj7Oal7Ofr4+9h4SApf8HDxuOBo4B5mi3J291OTlZWUVZZyVFBwV5OXl5aSpf5+F9c+DS+o4ozydfX2CJA2d0a5UcDut/1/nOWDv4+h6w99ZzsmTHuXt7OXl5+OApnKy97X/3YiOjo7idxeZRQFQhWWnn3ccPSWsMP1eabIDQEHGUIAz7H9dztYeBWD7+9Km+oeMdOb6WN5NA+Y7CKEfp2q4rbfh/t2/GyhKwO45wUovr1xmw+b03v+2BP+SE/n3m5/ekGzWjzLRdMLmaO1ES2pdu/JRC4AIjX9a3v3T8l+2/ePZAIo/1whY [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw2_CH_0 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw2_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3MB3dwwfwcyWipCCI3gmit4cbLR5JiJ4giF6uEr33kgSpWggiXIIoIbpoCR6EiM5FhEsIV3fD1et78pSZ3/ub95155515/3nH9zO758zumd2zZ2fPmQUIAMARzK/yV84QwZ3BLXsHF1dlV2dnVxdB9tsoD08HVxf534TFZYTFRcWQSGExaTFJMUF2ZW8nL28PlLwLytvLw9JJkF3H28rJwVod5a/n6ohykZeSEheXEUMhpa2lpaSkJESJf92F+s+LC6ugXJ1RXh7+wpooT/uT8DiJz1/3Ibf0sLZ38EFJ2DiTubqhXFy8Paw8T9pYeln+akRKSkr0q4uUvADIwbLL2+0Z2QlYofi1M6QFgGg3lAho0P71OHtHRIDm70ebxgxrqcwPUDXMAMoHCM6fQjVMJvu/zv/dVkYQds8GVvpZJNAft2eO/rcl+Ld4R35pZqVMbCatdWxCcz1sVq1JVL7aRXIVgDDFf9ka/mX7T8f+eTeA6M89ApZE4AQ4CYih [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tool_CircularSaw2_CH_1 {
            get {
                return ResourceManager.GetString("Tool_CircularSaw2_CH_1", resourceCulture);
            }
        }
    }
}
