//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_Aubo.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_Aubo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 nNp5PBXvHz/8Wc6MNoSEkPqotFiyZcnSSimpVGQtKoRk3wmFSrTasqsoW5IiW7JVtmTfs5N937nfZ/r+Ho/fff95n+fjdd4z11znOjNzzXFGQlAEQVbhQa/0xwYMnjTOG5vcsjhqYW5ucUtw26XrVtYmFrfkDwiLSQuL7ReVkREWlRKVEBXcdtTWzMbW6rr8reu2NlZXzQS3nbU1MDMxPHXd8YKF6fVb8pKSYmLSotdlpAylJCUlxfcT9HdhowYXVr5uYX7dxspRWPW6tTEN2hns/r3PuqtWhsYmdtfFr5mvtbh9/dYtWysDa9q1qzZX6Z3WrFmD0XdxowCCyEEtt73ttxaHBWb6E6sPgmAL7hhC+vw7nMVVDNn0v0Prrqk/ozxQzZLXg2z0Qv8bE8rk1lmC7RXe/7ZLr2dAEG/Yld+84hE5cz2r/38r8v95VO5t/uZX1vSNvnwitvmI+drmI9FN9kcQ5I7i/5W8/yv/r7b/MzcIRj2jUOlQBAc0hEBI [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_0 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNt5XEz/Az/6s2/Zs4QWW7JE2pXIUlJR9lDpYwkJadGiErIvhVJIsmeNVLYoS5QsqSiE0GYLJdF+X+d8f/fxuPf+eXs+6vWa95mZzsycOTNn5hyCJAiiDT9yyj/tKPxxmr7MY5XXBK+VK71W6faZ7e7j6+G1arTJcIORww1G6JuZDdc31TfS1+0zYc0KvzU+7qNXua/x81mwQrfP1DULV3gssncPmunl6b5qtLGxgcFIfXcz00WmxsbGhiNY+b+oKlc+3Mbda6W7n0/Q8CnuvssYjPP+//s/0gKfRcs8/N0NF68UvVa7r1q1xmehL7N4gd8C+UyCIFDyLHbSIQgL5NM1q3eJNEpH+c9IVZKgGsMoQlf1fzeoqY0iuv6fm1b+otjB5kth58wKolM42e/XsBu9XZoxva7L/8470kqFIPx5gijQMDxy+19F2//fJP4/P3eD4+7t5+/cm+o5c/xDx8PjLRLixp9W3zSBINZb/j9+M/8fv/+vsf/7sSEo5S9u [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_1 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNxzlCML4Kf9QpJiCsnYtm3btm3btm3btm3b5h3b+1R++56z7/658znT3yeVdNjT031n5gqiIAj/+OGt98OUeFO9UouW7doXbt+2bft2aRJUa9qpc8v27fJmS5cpR7pMGTLmzJkuY/aMWTKmSVC4a5suXTs1zduuadcunRq2SZOgQtdGbVo2Lt20Z5X2rZu2y5s1a6ZMOTI2zZm9cfasWbNmzuD3biUcufJ0xZu2b9u0S6ee6co27dzCx3Gl2//cjt6wU+MWLbs1zdykrda+Q9N27bp2atTZ16Rhl4behVRVlby76CQXhDzs2a4dxmgyYXtvpg2XBOlnf0kYNVyKPJxf/yQhyv9+aE+uXC9X/OVld/9TwRksJnqfdmfsOr85v9L/vmyOpjEFYZsrCJfiZp639/vTf/+vK/xfP9oVnXNovzb18MFkqwr9eDS30KW/aw9l9VcrIggD8v8fP/f/Hz//f8f+v9dG+J/7KbKSIAs+wY+AoAgqNEGnA4IhmLQm [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_2 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nLxztN1qA3e7Yier3bVt27Zt27Zt27Zt2z21bRun/GZy3jvGd++fd8+R5zcfxFlJVrvbkBAKhf7y46f/Y4sU1Su1aNmufeH2bdu2b5cmQbWmnTq3bN8ub7Z0mXKky5QhY86c6TJmz5glY5oEhbu26dK1U9O87Zp27dKpYZs0CSp0bdSmZePSTXtWad+6abu8WbNmypQjY9Oc2Rtnz5o1a+YMir+WiGDh6Yo3bd+2aZdOPdOVbdq5hUy71u2/9ZgNOzVu0bJb08xN2hrtOzRt165rp0ad5SYNuzT0B+m6LvqbGE4eCuUhz3btMMaQEM8vLkWXQuKP/mLoeHQp2J2ff8VQlP/t2uPL18oVf3Ep0v4nofBgIdH7tDtj1/lF//j/jc3xJWYoVCpqKHQxbuZ5e78/+fv/N0P/n5/ds5ofilDCh6+WyVEEL9TdinLwe9YtRUKhAfn/r2n//zX9v9r+n3MTEoNSIMWQFPqvWQ4pmBRSQxqmhHRSBT1kYBppYgZp [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_3 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nLxl1NRmA3YbnyQTHdzd3d3d3d3drcWKFC1QrAYUiktxl+IUKG7F3d1Lcb6dvD1rfef8PM9eybVzx+8kM8k8SQRREIQv/AUZ/FkSrQa1O3bq3qNMj27denTPmrJ+u959OvXoXix/9twFs+fOmatQoey5CuTKmytryjL9uvbt17tdse7t+vXt3apr1pQ1+7Xu2qlNlXZf1+3RpV33Yvny5c5dMFe7QgXaFMiXL1+enGowlzjhxLNXaNejW7u+vb/OXq1dn44K5ZH+/5uP2ap3m46d+rfL07ab0aNnu+7d+/Vu3Udp26pvq2AgXdelYBG9DIJQlDzar+cEQ0bcoLX2D0mQ3n8jCYv+kMLV+fBFEuL+t2q3z5yrXuHBaX/nHcEbKaZ+nm1LkqYf6d/9v2ELHkwoCL/4gnAqWZ7Z29/e+fL/N4X/z9/Bgdn3LD3Qc+9GYXHZ5H9lLb38nbF3cWRjWUEYVuL/anb+X83/q+z/2TbC/5ZTJCVBFhRBBQXTQiK4 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_4 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNx12BXVG/D7PXt6z5566AZBursbKWlERLqR7lJpUES6O6S7BGkFBQSlpUG6Q1oUeb9r8TvX9Z7z5+Fz3XPfa03nnueBTUSJRCJv+SOy+BOPMvi4bvsOXbpW6Nq5c9cuOdM3aNOjZ4euXUoVzp2/aO78efMVK5Y7X5F8BfPlTF+hd6devXu0KdWlTe9ePVp0ypm+du+WnTq0qt6mf/2uHdt0KVWoUP78RfO1KVakVZFChQoVyKuLtSSSC89duU3Xzm169eifu0abnu01+s0+79YTa9GjVfsOfdoUaN3Z7tqtTZcuvXu07Km1btGrhZjIsqyo2MQgSyRSkvxb725jbJXCFwPNi0airwdFI6/cqNydf95GI4n/t2vXT56uWfnOiXD3jUgwTHnvca4fUjX+l/F7/jdt0XKJIpGBXiRyPE2BuTtf3Xj7/zdH/j9/6rhpf3rv9tC9oyptrmhcS1O+5Tx378lCeypGIoPL/F+x+/+K/1ff/3NuIu+2UyFHGWoR [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_5 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNl3PFaPH/j9a0lSWUl2shoiI3uUFQlFRFZGRjbZq7J3RiQ7pLKzE7I3mdl7ZGdv7nfn+/k9Hr/7/vO+no/X9T7XOee6nOtcx0d8UGgUCnUCt3/z3+0sBu6eKBmbWFhKWJqbW1qwXVZ9bmNrYmkhwsvOxc/OdYtTQICdk4+Th5PtsoSd2Us7m+ciFs/tXtromrFdfminZ2aiL/fc6bGl6XMLkdu3ubj4OZ8L8Onz3b59m/sW3r+vQoa8OPu955bmz1/aOLHLP7c1xsF6fPv/fZ0zujb6xib2z7kNzAksrZ5bWNjZ6NniDHRf6v7b6fTp05h/h0jMikIJw2yzswoiwMIC0b+7b6YoFGbfA4P6ZPq/t3NwgkFd+O+tTff8Vrg3301SOYMi9kRf+XuzlFrzELZb/Lcv/zwcRhS8TBctd0L57szJ/9+J+v/cWokvVtOkR9Q8jyqSFGC9KK5U71HDaFYliUK9Evu/qvy/+n+t+z+fDQqD3KNh/oNGYQEGhftv [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_6 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLvgfwXiRKkoySQUQkJ8kuURQQVBREJAdBclhgWZY1EFREQCSvgATJoCgqEg8ZSSJIWgHJUZDMEl97zrmv7rv1XtWtW/X+4/upmV/vTNdMz05NTw1AAAAOYH7X36EhgSuTq45Obu6a7q6u7m6ivMb2Xt5O7m6qZ8WlFcSlJaUUFcWl5KVkpUR5NVEuPigve1U3e5SPl7WLKO9llI2Lk62ePfqau7O9m6qcnLS0gpS9orytvJycnIwk2e+zMP15cHEde3dXex8vtPgle29HUridwvev8xy19rJ1dPK1l7FzpXL3sHdzQ3nZeJPaWftY/+5ESUlJ8nuIx4QAUIG1HeXxhOoIbND/Xr1jBoBkG0cCcpj/upydAxLwdxNM9PQZ6Mx2M1RPgmMPEPy/xMo4bu3C/R5/d1AQhcOzg42vXDIplVuTB/9pBf+SzjOE2idtg7WvjVoqLmQQNFypCBovB/00ALiL/Kel+p+W/7HtH/cGkPy5RsBKAo4AUkAG [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_0 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7ddnUBTdngbwMyAiIhnEQA6ScxyJghIlSVZJ6gBDGiSKQ1CUoICggIASBFEyCohkkKCSc46SBsk5DmGP733v1t2t3apbW7XfeH7Vfbqmz3T/e8706WqAAAAcwfxp/+QMAVwZ37BFO2GUMY6OGCd+FiOUiysa4yQnKSgqLSgqLIJECopIiYiL8LMouzu4ubug5JxQ7m4uVg78LLrudxzQdzVRXgYYe5STnISEqKi0CAopdVdKQkJCTJjoz1lo/jq4oCoK44hyc/ES1EK52p6AnxN7/OM8p61c7tqiPVBi9xxJMM4oJyd3lzuuJ+5ZuVn96XTq1CmCPyVScgEgC9sWd+dQEkK4QfFnlUYHAMGeHwF4S/ePy8EfEQDavy9tqrtPW3W2i6pqGlA+QbCtCJRcvL0P99/9u680PyzvHtzoZBRLrNiZPvq/tuC/pQ37tkaO+VtNyycDpdPR8UrBcW+VDimfKgPwSOFflqp/Wf7LZ/8cG0Dw1xoBWwJACE4AIugk [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_1 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLogfgXiQoSEaQDJIlS1yiIkmSgCBKDhIl5xwECYIEkSiCkrMekiJREERYguQgKApLBomypH3tOee+uu/We1W3btX7j99XMz010zXdvbPTMwMQAAAszO/yd87jwJWBrp29s8t1FycnF2c+ltvW7h72Ls6y4gJXJAWuCAkjkQLCEsKiwnws170cPb3crWWdrb083S0c+Vi0vSwd7a3Urf30XO5bO8uKiV25IilsjZSwkhATExMRwvvdCuWfJxdQsXZxsvZ09xPQtPaww4X7Cbz/aofQwt3Kzt7bWuSe0zkXV2tnZy93Sw/cexaeFr8rnT17Fud3F8m4AJCBZa+Xa9y5M3CD9Peq5gIAOAchOKD4wl/DOcTiAKq/hzY3PKalsjRE3jIPyMIRl37y19MbH8Hjrn/XleSD3bsHNwYZRbKb9uex/2kJ/iU/E7LaqF6ktBN8K1Ug0cpWyJ+taPMzua0IQKj8Py0t/7T8j33/uDYA5881ApY44AzABXgQ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_2 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd5NFXdwwfwfc1lToZIIpIxZL6mUiF1L1FICJnn8RojCZUhs8wiRJSQmUzhcZG5zMLFzXzJzLt7nuf3rt/7W++71m+9a71/vb6ftc/e65y9ztnnnHX2WRsgAACHML/r36Eighud25ZW9g7KDnZ2DvaCZ++aObtYOdjLSwqLSQuLiYjKyAiLSomKiwqeVXazdXVzNpO3N3NzdTa2FTyr4WZia2Wqbuap7WBjZi8vISEmJi1qJiNlKiUhIXFJhPT3VRj+PLmwipmDnZmrs6fwLTMXSxK4n9z9r+scN3Y2tbRyN7v00O6Yg6OZvb2bs4kLyUNjV+PfnSgoKIh+D5GOFwA5WHe4OYYeI4YN2t8bO0YAiHb8iIAx41+3s3tIBE7+fWvTfYMolfle+roZQPcEwbUiVMF2fw8e5/u7r7QgHN5D2Ohhv5RaszVz+L+twb+kd9Gi4dUnukYXPemrSTMWVzCUJ+vFxUuuAuCv+E+l7p/Kf9n3j3cDiP7cImBNBIgB [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_3 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd5NFXdwwfwfSmSuRSiUB6SeSYuodwyV4TMwyXTvaaLayxDhgxJuBQiGUIqUyJkKvOszGUeQqYuruHdPc/ze9fv/a33Xeu33rXeP961fD9rn73XOXuds8856+y9DkAAAPZhfte/Q0MGN/o37thhsCpYJycsRoDzFtrVzQ6LQUoJickIiYmIysoKiUqLSogKcKrgHN1xrmgkBo1zd7VwFODUwVk62lmpo/G6WAc0BikpKSYmI4qWlbaSlpSUFBc5/Psqx/88uRAKjXVCu7vihTTRbncOwf2UHn9d56iFq9UdOw+0uLUTFdYZjcHgXC3dDllbuFv87nTkyBGy30Nk4AVAHtZtOOdIKnLYoP+9UTwBANl2ABkQP/HX7ZD2yQDT37c22ftFCzXXw1g9BRiCEGd/CpazGe/A46S/O8gIwOFZw0b3afHUD5tT+//bGvxLJI4L1xpvOtcFg+zLLxQFlbu3qOpsKUsvA3BX8Z9K9T+V/7LvH+8GkP25RcCaDJCD [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_4 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBRNgwfgXoKA5CSCuoAIq+QgSbIIvCggKgKSYQkSl4xIMoCghEVEchBQghIEJEcFBCQpUdJiAJYkecks176h6ruv7qqurur+ueL3VE93zXTN9Gzv9NQABADgAOZ3/Ts0JHBjcP22vQtGFePsjHER5NK3cfewx7goSAmLywiLi4rJygqLSYudFxPkUvVy8vRyt1FwsfHydLd0EuTS9bJyskdfsfHVwzjauChISoqLy4jZyEqjpSUlJSVEyX9fhfnPkwtr2GCcbTzdfYW1bTxuk8H9FN5/XeeopTv6tr23jYS1MxXG1cbFxcvdyoPM2tLT8ncnSkpKkt9DZEABIA/rLi/XCCpS2KD/vdFjBYBkJ4gE/MH61+3sHpAAlr9vbbJ/SEdjto+xYQowPEScXhaqOmGyB48z/N1XRhAOzxo2ek9JpNVtTR38b2vwbxnTR35owj9oElctu9T9DHlxLYG2qUqm8RIA95T+pTT8S/lP+/6ZG0Dy5xYBaxJACsgA [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_5 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBRPmwfwXnIOgiBKFBSQnEGioKCCgIISBImLIHlXchJMIElABEmLCpIkKBIlSE4LCIJIFkEyLLjktG/7C2+999Zd1VtXdX8d309Nd9dM10zvTs0zNQABACDA/O5/h4YINkbX7B1cXDVcnZ1dXYS5byBRaAdXF2VZUUl5UUlxCQUFUQk5CWkJYW4ND6e7HiiksgvS4y7KykmYW9/D2snBRhvpY+jqiHRRlpGRlJSXQCrI2cjJyMhIiZP+vgrTHycX1UK6OiPvonxEryDR9iRwP7nnn9ehskLZ2Dt4IqVsnSld3ZAuLh4oazSJrdVdq9+TKCgoiH4vkYEfACXYd3q4RVASwwH978abGQCinSAi4MT858/ZJRCBv4Zgqm9AV2vuC2PtT8BwH3FyRaTihNkePC791wR5Ybg8Wzjo5ZBKq976Sfjf9uDfgmVgqa98G9fw5mnpeQV+FnXNhqAGieC68wDcU/2XrfZftv+y7+97A4j+aBGwJwLEgASQQmSA [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Aubo_Aubo10_CH_6 {
            get {
                return ResourceManager.GetString("Aubo_Aubo10_CH_6", resourceCulture);
            }
        }
    }
}
