//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobimUpdate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"dh57MiKc9aGQmint9V+5WOKXNXVuMjyWufUWiJpgEjmRZTSDayNIOSPuHuYWZoP+ETcptunjF7gpURIRsVup2jyA+KSSlyyrDqcCOOvMFV/z1pk+7IDsu39egRLrCbRVU37pqXt28wkDslwX1bil9mhIM9+Awuz/srN1IsMu5/lcEq8g4nP9aLP4LN+byvlT/Xwd08y3FNFiJE09kNKdlVOPMQjDUm6JM9qP1BPaS3Sj8sowYTaikDcqsSpXdbmwQw1ea3qPMVs/wAidkDXMjf6rWf7tTIEEfDNxOhZ/9a/XMtJwL9Q8AhzmRm2YFckiRTdyb9sy5y/YTWNhjyJt71fO2Y0JuS63/qm8sDgBzG0ZZ5HatcTpnVjVypxW8cfYiYPq1iosqFjY/JZvb6XZQHm1Efx6U0gZA1F+dSqWDN1HcgsEcI1lasO1Qq/uBuKXIOLNJVSWex02h7nqC+R3NlGX5ApydNw3SblXxq3Lw0dXj6xUnuYvrZQk1SVJXPe2LP3pjXO7haqmxJucJs3SieX5/2z327FyZ70TSWnlFb37d5YNaB5NelcsxWtt1B/5rw9C0sdKU+Z+mYXd0uHqr8b3pFG/dZpG8fXXnysGYSqJ6cQgiBdnZ+19q9xWQjMWljwleMyjGYyy44zfftlVNYq7ccLamiyIRcGq8YlKEDPLTOUT0sr6aQ6m9Sa/c/uGsnAXKzbatcGqaTWr/iwrfEQeNzqwyeM0J0jYY5olYQZlmRXPLIwPhvfS/heSmIzxWF4moB8NfbOL/4I8RcDFgfc+hhNeSxghdCuah6DD5c1NKe7KE8G0brYsbNoIPbFFaU54Y0vhMDoQQEsaukYMtIb7HE3xRiAYxmXC0vPj32KA7kmtMh6BPKstXoRMFa15p3SIzRHoDcFVWgxoSiOepD63LCQyItUKYqkGqLBSuzULhX14F3TD6Kq1koqHy355oV8TLiunxvxE1E2g7j6TU9eamoyKJSZTw3Y5FgRC5vo4ldiPzSG1Rj8qGVoZhPNtSzLa7h3jDQuLCUr3QzhFOhopSj3DBzW9umOvQuXJxMfH+TKG+YYPGQNMd4d0uVorxEyC9XfTF7R+4cIpu8+2FYotnWrb29Yth1L0mxBTQnnmYoXg0G8IT+wkMRzFo9IOBiAYYP3i1aD/16hWMIX4lw==
")]
        public string A {
            get {
                return ((string)(this["A"]));
            }
            set {
                this["A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AxwDeiYz3wM=\r\n")]
        public string B {
            get {
                return ((string)(this["B"]));
            }
            set {
                this["B"] = value;
            }
        }
    }
}
