//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotTrack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotTrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nLl1WFTfF/975owSKmCQkooCSqN0KVIKgoJKd0t3gwpIlyiopEoppXQJglJKiQiCNAKCdDd3zfl+fs/zu/fPy+tZ57322nH2zJmBtTYIDkGQA/ghKOHnGAoXDTVLKzv7a/a2tvZ2XCz3zJycreztJIV4BER4BPj4RUV5+IX5L/NzsVxztXFxdTKTtDNzdXEysuFiueVqbGNlomTmecfe2sxOUlBQQECE30xU2ERYUFDwEt9hwl1OYYvzKJjZ25q5OHny3DRztjwEcWK3/93niJGTiaWVm9klU1tSewczOztXJ2PnQ6ZGLkaEQSQkJChhi8fZEUQCtM3VIYIUDw4F4aJmgSDotj+KyFv87+XsHKAI5X8v7U93r4rC9I8TtRPI8QDc2UXuCnrdXegn/2+sSDIscQusi/FSysfNiYP/v4r8f34yWZAvtixMXywFL362ZEFkVc8wyR6eUpZCkAfS/5fV/l/2/4r9n2eDoNgVB4oieAT3X+sQ1j6MEIFHAAf+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_AFN_0 {
            get {
                return ResourceManager.GetString("Track_AFN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3XM3//z/+5/M8V0RGKFpmRjRfGlr2imyJVKRC2iptIhQVMkIDIaNllbSlQimzqDS0pF3a63c75/X+rO+fP9fLrfv9+TjPdZ7P53mecwpBEgQxgn/8yv83hocfBlsPHrKxXWFrbW1rs3D6TnMHx0O2Ntqq8srq8sqKShoa8kpqSv8oLZy+wunIUScHc20bc6ejDvuOLJy+2Wn/kUNmeuau222tzG20Fy9WVlZXMtdQM1NbvHixiiLD34qoYOXya8xtrc2POrjKbzR3PEhjnHP+dzuj9zmYHTzkbK5ywHqUrZ25jY2Tw35H+sC+o/v4MwkJCfH4uzh+LkFooX5wsjs/ikIzjv/juA9B8Pq9ecRRn3+fzsAIj5j0n6dW87VYf03DlwnptcT4k+TMtkVJEkaDeFzrP/OqywoRxAKGID5LqYSn9taO/P+txP/zTzJu85t9q/zeiDVWZLVzIisPBH1dVSl8/jX2V/d/Jf1/5f+M/de5IXiCnyQqj6AImmCA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_AFN_1 {
            get {
                return ResourceManager.GetString("Track_AFN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXvvwfw55iLDCFO5iTJHELmjCUkJEIhU+HIMcTBqRCFIiKZir6SDEXmHBXVUYcjU2aZZ4djPsdwn77f7++u3/2te9f6rXvX/c/7tfZ+9trPs/Z+9t5nf87aAAEA2IH53f4OCw1cWZ939/BG6aK8vFDeUsIXXHzRHihvjRMyx1VkjsvJq6rKyCvLK8pLCev6e/r5+7poeLv4+/k6ekoJn/N38vRwNnYJskRdd/HWUFI6flxF3kVV2VlZSUlJQY7+91k4/zy4jKELysvFzzdIxsQF7U4H9zMG/HWevY6+zu4eAS4KV732oHxcvL39fZ3QdFcd/Rx/D2JiYqL5PUV2cQDUYdvk7xO7hxZusP1eVXMCQEPB0oAizr8uh7pDA7j+vrTR9p+mhlNtHHVjgD0ccWhBuorPbhP2B/w9VkUKTu8q3GgVUMisXR/b+d+24F/yUhg0eAkLNrgrHav3EgZ6ZiKCevQTZzUBuKX1T0vdPy3/Zd8/ng2g+XONgC0N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_AFN_CH_0 {
            get {
                return ResourceManager.GetString("Track_AFN_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNv5FsAjlrR2Q61VCUWVIlEVBFU0lqkwilpbqVQUCYmdiF3tO6VKKUO1Ha2qtcqUDopQVLXUNrFUjV1JxGRoZ96bN+edd+a8c977y+ec773fc7/3fL/3/n73fr8AFgAAwNxjX+/DDdwTtt9h3XF4A7yXFx6nBLbBEIjueJzOGWUYXBmmCtXUVIZqQE9DlcAGfp6+fgSMDg7j50tw8VQCW/ihPd2vmmGCLuI9MDgddXUYDA7FaGpc1VBXV1dTZd8/RfDL5spIDN4L40sIUr6AIWLZ9uwg/6/ncLoQrmLd/TFqrl6H8d4YHM6PgCayubr4uuw7HTp0CLgfIr88AIDY071+3kmHWfcmfPuijxMAANLJQEAb59d0dphAgNDvqVGH3pojPw4KtMwA+KNYpFdONUg4MvbWE3/3hefsCdjeGJBUK2zenmH+txrwF2A1Fu0uRvHtYp8m2pZAvIauqUNGk1xJLwCAcL0/jZY/jX+x/fFvAF8mLEAgKxs7O8fe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_AFN_CH_1 {
            get {
                return ResourceManager.GetString("Track_AFN_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1llKtIG7BrSEgCSUgIkGS7u7vLbHd3d3e32e7u7u7u7u7u7u5u3w3znrW+c36evtbT9VBVQAGVrnRP7x5BFAThLx9WaX34HXyqVrF5i7btCrVr06Zd2zQJqjbp2KlFu7Z5s6XLlCNdpgwZc+ZMlzF7xiwZ0yQo1KV15y4dm+Rt26RL544NWqdJUL5Lw9YtGpVq0qNyu1ZN2ubNmjVTphwZm+TM3ih71qxZM2dwWWcx7IOnK9akXZsmnTv2SFemSafmEvWerv+dx9ugY6PmLbo2ydy4jdKufZO2bbt0bNhJatygcwOrkyzLDmuIWnJByEN5ukv7UYqTJGh9ulvDJTh+9HUIF0msj59/HYL5v0t7dOlq2WLPL4b2Pha0gWKid2m3x679i/aZ/+ubw5tLEAIpBOFC3Mxzdn97/Pf/byn8fz6CjiqHxOo9Dte4vuugKJwr1DizVlgUphQShH75/6/Y+3/F/6vu/3k2gsP+LFI6BKcgCS64BY8gQxG8gg9+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Capsule_0 {
            get {
                return ResourceManager.GetString("Track_Capsule_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5PFRv/Cjws58pIS0oRaWFEtkSQoW0iKQka0hEkjVrKhVCKnuFIpQl2VWWFkshS4qQFCFbki37/Zz5/u7rde/988779ZnP53nOc55zpmaemTMGQREEmYcbk5nbIgzujh+xPnPOXtXezs7+nNgaPUtHpzP255S2i0vtEJfaJikvLy4pJykjKbZG1eWss4ujpdI5SxdnR7OzYmsOu5ifPWNx0NL9qL2t5TklWVkpqR2SlvJyFnKysrLS20jmKEvZk4trWNrbWTo7uosfsnSyJqCfdv3vOAvNHC2sz7haSp+yW2B/3vLcORdHcyfilJmzGTOIxWJhzCku3oQgOyF/cDkftACHgpu586pAEGzKB0POV/z3cKbnMWTZ/zy0n5+atDR6G3hKupDFvui6P1ufCxjNwPYd/zN2xzkWghwgEeTjaunYon9d8/+/Gfl/bugurVL0pGjpD6Nnb2tfSaiJvG9RFbmUooogl1T+jyj5P+L/6vvf/zcI9t90kDGE6cQB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Capsule_1 {
            get {
                return ResourceManager.GetString("Track_Capsule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTZvgfw3xAEBB0QSZKUIChxQHJSAVlUgoqIIiBhUJCgDAjDwKAoIkjQXZRBEFQWQVEwsCBZkWAgSJCc0yhpEIFhhvSO7u6r+269W3XrVr2/Ht9P9TndPae6T/epc6oHMACwivKj/hEeFlQcO3zGw8fX2Nfb29dHcast3o/g4etjoKmspq2sporT0VHGaeF24RS3Ggd4+Qf44Q188AH+fs5eilutA1y8PFwP4Ik2vmfxPgYaGmpq2ji8jparloaGhroq+4+78P+8uLIZ3tcb7+9HVLbAE86wofMcF/68z3pnP9czHhfw6m7eXL7n8D4+AX4uBDY3Z3/nH404OTlZfnSRVw5AH9V1AediuFjRDvZH4cEHwMIMYwEHvj8fZ3GVBTb/9WjDLW2WZl+b+cpHgPcyRmpaqVD05BL6XfavttqKqHtuaKdJXD21dGFk9T+t4Z+CZTlaibEjVh3vKHmLgU/Gbuq8Jhi4bQxw0egftvJ/2P7Hub/HBlh+lhhU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Capsule_CH_0 {
            get {
                return ResourceManager.GetString("Track_Capsule_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXhAxEESQBcmSBJSMgIRVQVAkqAQRJMqCIEFYluiyKIJKzlFAcpCgICAZCQKysEqU/MiyIFGihGvfe7+r3/3qrupXV3V/Hd9P9XTXbNdMz85Mdw1AAAD2YX7Xv0NFBjd3bj+wtndQcrCzc7A/x6mHdsJYO9grXBAWlxEWFxWTlRUWkxaTFDvHqYS1dcY6oRXs0VhnJzPbc5w3sea21vdvoN11HB6i7RWkpMTFZcTQstL3paWkpCREKX6fhf7Pgwuroh3s0M5O7sIaaMyDQ3A/pctf5zlm5nT/gbULWsLC7qjDI7S9PdbJHHPIwszZ7HenI0eOkP0e4gl+AORh3Y59FHiUHDZof28wDACQbePJgBXDX5fza58M/N0Ek919mqqzXXS1U+CED+LM0vlylns78HeRvzvInIPDs4CNTjaJpOrNqf3/bQ3+JcyXNBsRpgKNR23fNqRWiSiLfRlQolnKVQLAG/VPpfafyn/Z9497A8j+3CJgTQbI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Capsule_CH_1 {
            get {
                return ResourceManager.GetString("Track_Capsule_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1lcNzatmhhtVpSM6gldZiZHGZmZgYncRKHmZmZmZmZmZmZmclhZrhDyn5V972fL1+NzLlWq3fOqVPlcrIdH8EmCMJffpjT/OEV+almleYt2rYr2q5Nm3Zt0yeuEd2xU4t2bfPniMiSKyJLpsy5c0dkzpk5W+b0iYt2ad25S8fo/G2ju3TuGNU6feJKXRq1btG4bHSPau1aRbfNnz17liy5Mkfnztk4Z/bs2bNmks1fRbP+4RElo9u1ie7csUdE+ehOzSXuHV3//TruqI6Nm7foGp21SRtXu/bRbdt26diok9QkqnOU+ZDT6RTN/4jBVIKQj3mmS/vRLjtLwPxpa1KbIP7oJwork/77L/Tzryjo//1Xe3z5WoWSMZfUfU+E4CBb0ncZdsSr94vXO/73bK6J8QRhsCoIFxNknbvn25O//79T+H9+yDXth22rlaO2hvEON9k1tBh7ib9/Ox0ShP4F/1f7/lf/193/+d9GEK2f+a9obaJghyTIggKH4GST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Dolomiti_0 {
            get {
                return ResourceManager.GetString("Track_Dolomiti_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tPwJNJXfHzj+Pud5TiEhqcw0IZV5zFgJJaHMMiSEzFNmGkwRMpRkKjIlJGQmmRIRMs/zPM/z/318vr+1/ve/7l3rrrvW9Vpv7/fe+zmH9Jyz31trheAQBNmHD0ImfBxF4ZP6PRNTSyspKwsLK8vLp9WMbO1MrSzFBTl5hTl5uXmuXOHkEeLh57l8WsrB3N7B1kjc0sjB3lbf/PJpJYeH5qYGt42cVazMjCzFBQR4eYV5jK4IGQgJCAjwcR8ifBWqgyfnlDWysjCyt3XmvGNkZ4KHeaIn/32dI/q2BiamT4z4DC1IrKyNLC0dbB/a4Q317fUJFxETE6OEb/EYG4KIQf7jYP2KBIOCgvDJ9R6CoFueKGJ1778/zvY+ipz43x9t5F+7guxkC2XZKHLsBe7sAkcBvfYOrAv971phUfg2/sKTNzPyxZZsjO7//5qR/8dHheRQxVnBjQpjGaxyOEDpxjX6YzdmKd9cR5Cnkv+3KPu/xf/L3P/5u0HQg884yOjB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Dolomiti_1 {
            get {
                return ResourceManager.GetString("Track_Dolomiti_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNTvGsC/tpBibEljGSWj0gwGQ2Mw9vyyhCzZlwlhZBnSzBiyh8YS1SlRQxtZsoRsZYliSGks4Rc/JH7W7MZcWu7p/s499/zOPef+cc/xOed5n+e8z3Pe93m+z/u+X4AFAADmFtt6mz2sW4O1uacXzk/Hz9fXDycHscIGBHr54dAqMEVVmKK8gpoaTAGpoKQgB9HB+wThA7BoHBYfFODiIwcxw7v6eLn9hg219PPG4tDKyoqKqgpYNaQbUllZGSHPsb2L4LfFYQZYP19sUEAozBgb6Mm+Nc8Z/H2f3S4Bbp5ewViEuy+33wUsDocPcA1kd3cJctkO4uLiYt1OEQQFAPUt3Y6/kMjNtmXwbQ+C3ADAukZmBTi5v5ezzmQFhH6U9sd7uonBxDv+ulEAFMlycPZ4Jdh+Y8vfwfXdr5qxNShuSZc44k7Nyijzv9XAXzjpwNbIkr+rmcsZ3ChcG6O7ZeszmYENABCu+YvU/SL/MvezN8A3g4WVlY2dg2PX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Dolomiti_CH_0 {
            get {
                return ResourceManager.GetString("Track_Dolomiti_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV3UJPZFsBDkN4VAUEgBASBUAKGIoZQQgeloxhqCFITICRISUIRlGakLSUUFVxFEWUtCCJYUB9S3AUERDRIBylGhAgBs8HVN/t23rzZeTNv3j/8Zs4597v3zL3nfN859wNwAQAANoctu4UwkKO8XENCsThLXGQkDgsBeWJi8KE4LNxAW89IW08XamysDTWEHoBCQJaEiFhCDAaOxRBiYwIiICBnQmBEKNoBE++OC8dg4TCYnp4RFGNsiDaEwWD6ujxbp+z6trm2DQYXiYmNidd2wuBDdnDm+Yh/nCMYEIMOCSVi9IMiBXBRGCyWEBOI3xEUEBuw5cTPzw/cClFcDQA4xLHdhKgcAW7OQGxLvRMAAIDrFCCgV+CPdFhsIEDye2oT/YOHbWb7JNomAeJpXOCPWk1yqA3Oetl3X6OfOEqPI73y+pUPvkyy/1sL+At0q7EnYIMvT5RTuNvHs52RUbLiyAWJIgsAIBnxJ2n7k/zL3I9vA/g24AICuXfw8PBy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Dolomiti_CH_1 {
            get {
                return ResourceManager.GetString("Track_Dolomiti_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE7/Hz/+s/ex9yh7i+yMQsjee0XJFhpo2iMiGZkVQrxRUlKkkOxNouwWJSFFS9/H6/j8brfv7/fn732/Pa/n4/U6r3Ouc3XVcV2NN0VTFFWB/0gn/2kMbiaNnb/Acan10iVLljq2azTRwcl5wVLHPt3MOvUw69TR3MLCzLy7eRfzdo2sXRe7uDo59HF0cHVxmr24XaPRrnaLF9gPc3Abv3SRg2Ofrl07deph7mDR3b57165dO3fkyb1UNw5uZuOwdImDi5Ob2QgH5/kc5sUV/+5Hme1kP3/BCofOc5bIS5c5ODq6Otk5c3Nmu8wmiyRJYsgpVmlJUb3RH7ou85VZhMrk5ldDmmJKVjPU54b/HlBpBUPV+N9Dy3iRMtLmy/OqCZlUlfV0k+/tY+tPL8P28/9b2+OLTlGWMkU9a9g56OqfzIr/v536//w39+HIm+LLM0lPHz5LnNC32gB2tPWAVV863KCoNVb/VyX8X/X/mvt/nhuKMW7xEA00xQJH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingTimber_0 {
            get {
                return ResourceManager.GetString("Track_JiadingTimber_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5WE3fHzf8s+ezTRkLTeZQIiSkMockhJJEUkklmkjJPFOaVFJ9ydwkkaIBzSoZComSJlSUkNJwv/f2e67rfp4/H69r9f6stddae586nc45RUJIJJIe/BNS+NeHxAeT1dvsdjgtcHJ0dNqhNmKdtbOLndMOnRnqU2eqT52iMWuWuoaWxnQNtREL3Bxc3ZytdXZYu7k6WzqojVjptsXBzsrA2mONk731Dh1NzalTZ2pYz9Ky0tLU1Jw2hRHOMkjcXF3f2snR2tXZQ93Q2mUbjXHO/d95elk6W22zc7eettWRd9ppvWOHm/MWF3qrpaulMEkqlZLCJfZXkUjmIIvcdp7hKRQywodnbRIJ2bGflDxp+3dz/vaQksH/u2k1JW9W6H95NSCjVtL/MDGqeVKKvHknjp/639yZH3mJhOYkkpeK0yLS/tT2/P9Nyf/nHzF3WZZ5k0dWquntzE+n5y8kVsou7CdZsUAiOaD3f7WM/6v9v8b+n6+NhPy3HVKoKAkN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingTimber_1 {
            get {
                return ResourceManager.GetString("Track_JiadingTimber_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFT//wfw95CIMkWlPiSTslT2LCNrypLQJEKYLEPIjMa+pfDJliVLso1Ukr0Syl5RQ4ydoowYu5B9bPN9+yy/8/19z+93zuf8zvn95/k49/2658577n3fe8/7fc4FCAAAA2azbmYnE2yuXLrugCdoEJydCfiTAsY4oqsDAa8sJy6tIC4tKYVGi0vJS52SOimg4X7DzZ2IU8bj3N2IVjdOClx0t77hYKOL875McMLhlWVlpaUVpHBoeRt5WVlZGUmWzatw/3FycS0cwRnnRvQW18O5Xt8Gj7N6/HkddiuizXUHD5yMrfMOggsOj3cnWrtus7Vys9rsxMbGxrQ5xN3CACjB2uTucm8HM9xBbjaPuQBgWglgAg+4/rydVQYT2PvXrdE6uvW1xtr3VA+B3UGIIzNib3nN1+Dvln/1VZCGw7ODO22HZEiVy0OM/2sF/xG7Jv1a1q7cutamtg9GalxnmS9qnPUak3gPwG3Vf9uq/237b8f+fjeA6Y8WASsT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingTimber_CH_0 {
            get {
                return ResourceManager.GetString("Track_JiadingTimber_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dhnUBVPoybwblDAQFAyEkQEFCSJSAYFARVJJkSS5KCA5BwUEREQEOSQkQwSJUgOEkVAchQOSs4HOATJ2/7f+27dvbVbdWurtvYLz69mempmqqf79JyZrgEQAHCA8rf8m5MEaKV+19TM0krWysLCyvLS2YdGNrZmVpaSV3kvi/Be5hcQFeUVEBa4InDprKz9Mzt7GyNJSyN7Oxu9Z5fOqtrrPzMzUDRyvm/11MhSUkjo8mURASNRYQNhISEhQf6jf69C+U/lvApGVhZGdjbOvEpGtqZH0H5ih39d57iejYGpmYORoKHFMavnRpaW9jb6tkcM9ez0/p5EQkJC8LeJFJwASKCyzf55wDFCtEH+d0XJAgDBticBIGb5V3d2DggA1X90baKnX1lhtvtU9SSg8IbnlnlKz2jtouPtzP86LkKBKs5DG11MgnGVfyYP/m9L8F8Cr92u11p0rq94lFc35i9zA6rS3CADyrIAeEn/p6X6Py3/y75/jw0g+Fd1qCQA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingTimber_CH_1 {
            get {
                return ResourceManager.GetString("Track_JiadingTimber_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1ltBRH1Kjhnh7pHmk9ENxdg0vQ4O7u7m7BIbgFd/fg7u7u7u4W3OV7q+Cu9d378/KsPXtXdVV1HTjT0w2EKB5FUX7wQ2TxI6LyUrVCs+Zt2hZs27p12zZpE1Zp3KFj87Zt8mRLnylH+kwZMubMmT5j9oxZMqZNWLBzq06dOzTO06Zx504d6rdKm7Bc5watmjcs2bhbpbYtG7fJkzVrpkw5MjbOmb1h9qxZs2bO4BdniZKLpy/auG3rxp06dEtfunHHZj76tS4/zxOq36Fhs+ZdGmdu1DrYtl3jNm06d2jQ0deofqf6YpCu66rYop1CUXKTj3duNyLopbDEix7Np6if+6jK1yif/HK+/FCVaL++tHvnLpYp+viss/O+Yvf3JH6ZbnOcWl85vu/X2ByF0ilKkwSKciZe5pnbP97/8f+blf/nR/TVGfa3qnN835uTyQqH+u7cd//R6MKelLkLK0rffP8rdv6v+L/6/s+vjaLKVw9ZlS0vfIpfCcBHaNCV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingWelding_0 {
            get {
                return ResourceManager.GetString("Track_JiadingWelding_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxjtCNbG7f7JGWnrd22bdvWbtu2tVurbdvYbdu2bdvG6veatZ8zxnvOx9O/ced/16xZlaTCtZLVgWAgEPjDP5Hinx3ipGaVlq3adyjaoV27Du3TJarRrHOXVh3a58+RIUuuDFkyZc6dO0PmnJmzZU6XqGi3tl27dW6Wv32zbl07N2qbLlGlbo3btmpStlmvah3aNGufP3v2LFlyZW6WO2eTnNmzZ8+aSRHnEs3feYaSzTq0a9a1c68M5Zt1aSkzrnX/73zMRp2btGzVvVnWpu2MDh2btW/frXPjLnLTRl0biUm6rofERQynDATykae7dRxtSDSeOMnWJRgI/RgQCqTq8t8V+vknFIj+v6v26NLVCiWfX4yy93EgPDiY5F367fHq/mL9u87/zc01KhwIfDEDgQvxs87d/e3xn/+/Gfj//LuZvvDh7PN7H9p3pufBYKBj0Xy3ExdrtzF98UBgYMH/q/b+X/X/Gvt/bptAyD/lKkIiZQTpFKh0IkMBLaBD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingWelding_1 {
            get {
                return ResourceManager.GetString("Track_JiadingWelding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NJvbFsBDqwNqqLFEm6qxhkjMmqBFTY3pqlkJYqhEaoiI0mhpEzXPVHFbyi3upYariuQqoYOhhlIeWmOIW1OMNT1627fuu+utt+56a73//Nbae5/vnL3O2fv79j4fgAUAAOzusW/34WTdU7ZW3j5+WD0sBoP1kwfZoAICfbB+cDVFqIYiVAmiqakIUYeoQORBejh0EC4ABfdD4YICkGh5kAXODe3jbooiWGN9UX5wVVUoVAOC0lR3V1dVVVVWYts/he/r5oqGKCwGFRRAUESgAr0P780fDf7jHHZkgLu3TzBK2QNzHHsD5eeHC3ALPOyBDELuOx07dox1P0QeaQAAtmfbcTdijx/aG3DvKww7AMD6hcgKQLL/kc7mLiuA/1tqE739ZoYzPbzUSQBPJIv4gkKtqNPW3rrsN1+N9D0F3ZNuMeXchvXJ3f/VAv6CwDMlGvpaezOzU9LgOpLaPDmdaABUhRkAABE6fxLqn+Tf5r5/G8DXAQsr66HDbGxH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingWelding_CH_0 {
            get {
                return ResourceManager.GetString("Track_JiadingWelding_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UFPPogfwDaJIR0FQAQERQWkBBGlJpAmCUpSmgkgT6UhooaoI/KQFRSUUQUBBpFiQJgRQelfpSBcIvQZCk7z19/vdN/fdeW/mzpu5//H9zNk9ZWfPnuyczRyAAABQYX7Xv8NEAwuTy7ftXVzVXJ2dXV3E+I1t3bH2ri4oOQlpeQlppJSCgoTUWakzUmL8ap5OHp7utigXW08Pd0snMX59Tysne2sdW5yhq6OtC0pWVlpaXspW4az1WVlZWRnk3t93Yf+zcwlNW1dnWw93nMQlW+xtWniezuuv+zBYulvftveylbFxpnd1s3Vx8XS3wtLaWHpY/m60f/9+mt9DZBMGQBnWLZ5ukfR74A7r7+I7OwA0m0E0oJb9r8fZotIAjr8fbayjW1dzqv1AxThgC0YcXxQv4Tbbhtej/24rLwaHZ/O7F16ZZOL6OPX/W4N/yQ9xlZr+l77Vla0+VYmcbmrKAwLqzvniGgDcxfzTVvFP2/8494+5ATR/lghY04A9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiadingWelding_CH_1 {
            get {
                return ResourceManager.GetString("Track_JiadingWelding_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3XM3//z/+5/OM5/MYlZ20rIQoCQ0NZEchhJYkIdpD2yyjYTRpGCkjRWlpUZFEGS2VQosm7d339jyvz+f3eX8+3/fn+8ev6+V27vfn4/k4z3VOp04ngiQIYgxfTGW+JrJwo7fr6DFLK02rkyetLJfM3mtma3fMylJtlexyJdnly+SVlWXlFeVXyC+Zrelwwt7B1kzN0szB3tbkxJLZOxwOnThmqmXmvNvKwsxSbeXK5cuV5M2UFU0VV65cqbCMy+xlKn/jspvMrE6a2ds6y243szvKwTjt+M9+xpvYmh495mimcPjkOCtrM0tLB9tDdpzDJvYmzCQej8diDnGSNEGoon5wsPYZx0YjxNwstiEI1qAni5Cw+ed0hsZYxLT/OLX6knLtTb+/TM5uICadI+f+WZomajCM9Y3W/6xXMuIRxBouQXwWV4jI7G8Y+/9bif/xJRa/I4/ccCnvSntt7iNacH2Kf8mG8AifHII4rfEvyf6X/Lex/3xsCBb/lkRl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiaShan_0 {
            get {
                return ResourceManager.GetString("Track_JiaShan_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bp1UFXR/++9N0goLd2dBiXdUgJKCAbdIC3dISAhLQoK0gLSSCMpLamCdHfDoZu7Dt/fb+Y+d55n5s4zc/+4M7xf897vz1pnnbU3Zx8+5wwDBEMQdAmETKSwUcDhxdNXFrZ20nY2Nna2d+memzo4WtjZivHf5xG8z8PFLSR0n1uA+wH3XTppZ2snZwdTMVtTZycHQ+u7dKrORtYWxkqm7hp2Vqa2Ynx8PDyC3KZCAsYCfHx8vFxoyLMQXm1+X97UzsbUycH9/hNTx1c3wDyGy3/Oc8vQwfiVhYspr4nNTbvXpra2zg5GjjdMDJ0MkYswMTFRkJeIzwpBoiB7nF+H30QFBR7yYMYNQSgnviiQFvd/fpzTSxSI6L9+tPmBIWX5lX6ChgUIPwBm2L5XTalzBh5n+K+1gsvg8h4A/6XmTa47Wrj8/5vQ/6IaVqhFgI6mJVOVozmaC5KZpKeRqS4KEIcgP4n/yQ3/k/8fc/99byCUqyMMEgkqdAOAAt24mkWD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiaShan_1 {
            get {
                return ResourceManager.GetString("Track_JiaShan_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NJtpF8Bj32prVWhaS9QytiKILRFCKbXvHWqNrZWQiNoS+9ZSQamqZQYdu2ppU0rootRojErpKNoqTRex1TKEGDrLmW/Od74zZ875/vM75977nPve8zz3vu+97wNgAwAAO7vs2T0OsO8qN8fgEDQGiQkLw6BVZVxRWFwIBg3TVdfSU9fS0NTXV9eEamprqsog8ecj8VgUDI3CR2J9z6vK2OP9zof4W6NinDHnUGiYjo6Wlp4mSh/qD9XR0YFocO2dcujr5uoWKEwYKhIbo26DwgVz7vp5on47h98X6x8cEoWCBITxYcJRaDQe64fjDPCN9N0L4uXlZd9LUUQRADDatc/w4dl8HLsL4T1Vyg8AsG8msANI/L+Vw9xhB4j9XtoMbczW4uOIaPcsQCSFDbyo1g7y3Np97v57rF7RrtLalefHIOVdv8zu/FsL+BsKbfaP2cyzHq8zXj+q5xEyI+fSzMvKsx8CAInGf5Huv8h/+P74NoCvCzZ2dg5OLi7u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiaShan_CH_0 {
            get {
                return ResourceManager.GetString("Track_JiaShan_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV3UNPZFsdDTURpUiMRgqioQCihBOkCAlIDSBRwKSH0EEgIXQKGIkhbkVVWhLXjisLKomAksIDSpMMiCgnE0ATpbCChbHDL7Nt582bnzXv/8Zm593vn/s7cc87vd87vAngAAMA2lx3dYR8vd0I5BwaF4cxxWCwuTBXqhsETgnBhRrowLQRMS0NTXx+mqaeprakKNSeGRhLxGKMwDDES7xOqCnUi+oYGoW0xsa64EEyYkY6OlhZCE6Ovh9bT0dGBawjseJH4cjjMCoPDYiLxsTB7DCGQn7sPjPrNj5APHh0YFIWB+2H34MIxYWFEvC+B388n0mfHCAQC8e6EKKYMABhytYMYnrWHj7sQ3ZnKhQAAXjaJF3BX6Ld0ONu8AMnfU2P2DzpYTfeJ140DxMg8hxbUauQ8N7jPQ363RXzDnbS4o/cgvLh2bXz7v1XA36AoA5r0oPJN951ONOZpACxoivIWNeVkYwAgyeQvo+4v41/2/vg2gC8LHl5ePn4BAUHu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_JiaShan_CH_1 {
            get {
                return ResourceManager.GetString("Track_JiaShan_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PFb/Hz/+s88plbRUpJ0maQiFtjRo0kBD0jAykq2hbbRLikqlLRWSmYwWWkZk71FW9vo9rvP+fG+37+/358/99riez9frHBeKc73OORdBEgTRiw9JlXz0o/BguH7vPivrJdaWltZW08cYmNna7bO20lRVmqWmNGumirq6kso8lTkq08csOWRhf8jWTNPK7JC97U6L6WPWHtplsc90lZnTRusDZlaac+fOmqWmYqY+z3Te3LlzZ89kJV9lsPjkSjpm1pZm9rZOSmvM7PYymOcd/vs6fXfamu7d52A2e7dlH+uDZlZWh2x32TG7d9rvlOwkCAIl+RYHKhLEAtTUQwe9+tBopCUPrDtBUB0eFNHu9t+P09lLEUP+96OV/szS06n6IRNXRgw8To6rnxEpZ9SF7e/+t68a2YcgvrAE8X3U7ICYtrLe/7+V+P98xOfFJygT398P/ZoYY149ezm5cMdScmHeEoI4ov1/Je7/yv9r7v/83xCU+EiiUuKIBoZg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_KL1000_2_0 {
            get {
                return ResourceManager.GetString("Track_KL1000_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PNX/Gzj890QJiZBZCQ0zSTJLpa1CiSKEhCQqmyJ7RMMKpaGSlVlWIhKyyh7Ze+99X+/z+f7ux33ff96ej+tc1+t6v97jjM85r3P6ICiCIGvwR2XqbwMGN5cu3DC7ZaVqZWlpdUt060XjOzZmVrcU94vvPSC+V1JKTk5cSlZqn5ToVtW7FrZ37xgr3jK+a3vHwEJ067m7hhZmRqeM7TWtzI1vKcrI7N17QMpYTtZIVkZGRlqSpM7CRju4uJqxlaWx7R178TPGNjcI6NPf++886w3uGN0wu2csfd1yndVt41u37t4xtCGuG9gaUJMYGBgw6hI3iiCIAuSKu7f91+FQsFA3h+wRBFt0xRAZ+//uztIahrD/7651/6k/qzZQy5rfg2x0R7ePi33hubIM21fs/tt+4CAdgnyES6nhk47One9Z+/+bkf/PX3j45UOVg+WFa2tjh3wH4o6g1zSPoG4CRxDETfn/Efn/j/h/9f7Pc4NgtFsUMobgCIGQAIeg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_KL1000_2_1 {
            get {
                return ResourceManager.GetString("Track_KL1000_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZZ5UJNJFsC/JEQ55BIlCEFORQXCGQhHSAYQRlGCeACKQgIRUMgF4YrIJZeg4AkOiDgjowMoIMPhYkjCGIJy7XCGQwUxUKLIHa4AG5xxa3Zqa2tqq/aPreJX9bq7Xr/qfu/73utuAAQAwJqY9X6dLWBx4+EeGEQiO5BDQsgkA80TRFpoEJmEtkCYohCmxiZWVggTSxNzEwNNB3pwGJ1GRJOI9DAaPthA041OCA7ycyFGHSOfJ5LQSKSpKcqEaGXpZ4lEIs2Moeu7KH1ZHOFMJIcQw2hRiMPE0EAJsX5z+G/7SONpfoFB4UQz/xApMoVIItFphFAJf3wYft1IUlISvO6igh4A2Ir7FjolQwoiHsivN9rSAABeigUDytK/hbO8Bga2/R7a+84eV+cPHYosAaCQCNKeNHym5i0Sz7+R+m0edVvcmIqlXd0sn7kgWPtve+BP/P01u94IaP+lYqWBGTBm5rRF6OsIwb52AIA4zB+E9Qf5F93XfwN8GYDAYIgE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_KL1000_2_CH_0 {
            get {
                return ResourceManager.GetString("Track_KL1000_2_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UJPNgwfwDRYEEaSjiGB5RQSkl9AVQRGkiihFpBlRIFIlQEBFRAFBmhKqAgpKlSpIlSYQeu9NegkQIAYIufUtM7/7zd3Mzc3cHzfD9zP77M7z7DzPbp7ZTQIQAAAqzO/6dxho4MFI/56tA1oVbW+PdhDiu2Hj5GyLdlCUPi8ue15cVAyJPC8mIyYpJsSn6mrn4upko+hg4+riZGEnxKframlna6Vpg7mOfmDjoCglJS4uK2aDlLGSkZKSkhDd9/sprH/e/PxlG7S9jYsT5vw1G+d7e+F5Wre/nkNv4WR1z9bNRsLang790MbBwdXJ0nmvtYWLxe9OBw4coPk9xMP8ACjAusn1YRDdHthg+n3gYwWAZtOHBrCx/jWdLSps/z21n5092pdnO5jLJ8FhX8TJZeEibtNteH2Q5a/rskJweNaw0c4jEV/6a5L6v63BvwWHu3WhZQ5fRaUSLhivplz69e76pdeBvJcAeKz8L6X8X8p/OvfPuwE0fx4RsKYB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_KL1000_2_CH_1 {
            get {
                return ResourceManager.GetString("Track_KL1000_2_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN11uBVV+8Zx4pxN59mHbgnpLgFBGmmQkO7u7hQQEJQURVQkBEFCVEpAGqUEREkpEQVpkYbf/bi+c5318ufvva7PO/Pcsyb37LVmNqKxYseKFeu5/mdT+1/iOPq/Jg26dO3Vu1Lvnj1798qXpXHHfv279u5VrkSBIqUKFClUuHTpAoVLFi5WOF+WSgN7DBjYr2O5Xh0HDujXtke+LPUGtuvRtX3NjkPf6N29Y69yxYsXKVKqcMfSJduXLF68eNFCkbaXqP82XqBax949Ow7oN7RA7Y79u0QojzfI7Sdh237tu3Qd1LFoh54Jevfp2KvXwH7t+kd0aDugrTWKHz9+HDvE5LlixSqr6cGBfd5JEFczyez/JiXKFyvOo9FxYg3XjP3v8fM4scKc2u8//1qn2l/HUmy7HCv5+NjZbuXfmL7FEy2vRNtSO3bHjnUpdexYRzMW/XjLg8vP/7/TWC/8r+3a6rsSztu5u+LVczu/3nW/Urx5O6uUmr11R6xYY8p7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_M7DM1_0 {
            get {
                return ResourceManager.GetString("Track_M7DM1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxjtF3JF/f7vde2F3dsp2Pbtp2Obdu2bbNj27ZtdWzj+Vb1/47x3Pvyns/4nTlrVtXaJ+n06ZygbXabzfaHN1HFW1DhXfVKzVu0bVe4XZs27dqmSVitScdOLdq1zZstXaYc6TJlyJgzZ7qM2TNmyZgmYeEurTt36dgkb9smXTp3bNA6TcIKXRq2btGodJMeVdq1atI2b9asmTLlyNgkZ/ZG2bNmzZo5g0u8iiEfnq54k3ZtmnTu2CNd2SadmjuZe7r+9zr+Bh0bNW/RtUnmxm187do3adu2S8eGnZyNG3RuIA55vV5FfIhqCpstD/V0l/ajfQ6aiHj3MnXIpnzvp9ju0Yi3H38Um/m/b9qjS1fLFf/3orb3sU0dZE/8Nu32OHV+sr/8f2dzrBxls4Vq2mwX4mWeu/vr4z//f6vt//MWsYoc6uwtfOhcs+MHb2wpUeQfX+Ei4YxNCtts/fP/X9n7f+X/Nft//tnYFPneTlXkygGnzWVzw0k88Np8Nj+8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_M7DM1_1 {
            get {
                return ResourceManager.GetString("Track_M7DM1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV3UJPZFsC/0ItUqQKCFOmhRCCUJLCUgHQQWLoQIj1AQmgSipRIEQtFQAgiqCBtERRYaVKUobmKuywrRbqA9BpaHrj6xrfzZmfnzbz/+M2cc+6935l7z/m+c+4HgAAAoBxxbI85RXWk7Ky8vDEBugH+/gEYORFbNBbnHYCBqYKVoWBlRSV1dbCSmtIFJTkRXbxfMB6LhmHQ+GCsm5+ciAXe3c8bZYwOvxTgi8bAVFSUlaFKaHU1lJqKigpEkfb4lNNfNgcj0QH+6GBsONgUjfOiOVqnD/nzHCY3LMrLOwQN8fBnDAhEYzB4rDuOxsMt2O3YiYGBgeo4RHZJANA6sn34wFRG6qMB27FKYAIAqt1oKiCc6c909ihUANfX1KbeD5oh5wY4WqYB9jiQ6Ip8g4DT/tFzna++0KwjpXwk74QgpKadacr/aoG/4FZt2MGc3d75w/xY+5mYHV367HZ90YzmNgCIQXwnLd/Jf6x9+zbAlwGIioqahpaW7uhVMDIx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_M7DM1_CH_0 {
            get {
                return ResourceManager.GetString("Track_M7DM1_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTbngfwMwiCZAWUJCAiQckwInEQREBAEEREcpIkcchhECUHCRJEspcsiCRJAkoSJCeBISkZQbIgDAN7vPe+rbevdqtebdVW7R98P9V9TnWf6v51d/XpaoAAABzB/G5/h5wArnQ0raztHeQd7Owc7HnZ7lk4o60d7KWv8gtf4xcWFBIX5xcSExIV4mWTd33k4upsIW1v4eribPKIl03D1fSRtZmKheddB1sLe2kkUlj4mpCFuJiZGBKJFBEk+n0Wmj8Pzq9o4WBn4eLsya9mgbYihNuJ3f46D6mJs5mVtZuFiLndKQdHC3t7V2dTNKG5iYvJ70EkJCQEv0uk5gJACrZdro4Rp07ADtXvFT0tAAT7fgSAnPavy8EdEYC/u2B2cPi24tLA6YY5QP0Uwb7OV82kfwD3D9L8tf8aLyzPHHb6z4uk1f2aO/rftuBfIsN3o9mFRL45zrC9yT9T6Qbs39i6aSEPwGPUPy0N/7T8l23/eDaA4M81ArYE4AQg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_M7DM1_CH_1 {
            get {
                return ResourceManager.GetString("Track_M7DM1_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJwF1FVl165X7hV71QYkBWmQ7u6GjXR3h3SXpHSJgJIiDdKd0iEinYKAIqASCkhK/td64IzxnzPGea8x57znPeez9nq238APS5IlSXrLT1jDH0ch1a3VoWPXbmW7denSrWu21PXa9uzVsVvX4gVz5M6RJ1fefHlzFM5XOHe21GX7dO7dp2fb4l3b9unds2XnbKlr9GnVuWPreNsBdbp1atu1eP78efIUyt22cMHWBfPnz583lx5+RkLx6BwV23br0rZ3zwE5Pmnbq4OGb/R99yl2y56tO3Ts2zZvmy5Wt+5tu3bt07NVL61Ny94twyXTNJXwBYNMklSM6vbXJlsqwg9Tr1W2pLwYqkjtEeHPy7eKlOj9xW6eu1it4u2zsT23pOBzOe2D7NtTNHnFPOf73UINPpGk+sUl6UzKvPN2Pb/19v9Xc2/bVm5Fir1787yrpeSxSQ/Na71k7xe3/5WlQttKSf/Pz4ZduQ6ZC4oeers2bXl3x8yDL65VLS9XKlJe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ProductWelding_0 {
            get {
                return ResourceManager.GetString("Track_ProductWelding_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLwDtB7ZFq5drvpYVTu2bdu2OrZta8e2bScd27Zt27buU6vP/487bp4x5/vOuVD4stfXOafTkixJ0l9+eer9CiqkqpVbtGzXvkj7tm3bt0ubsFrTTp1btm+XL0f6TOkzZ8ySNUv6XFlzZUqbsEjXNl26dmqar13Trl06NWyTNmHFro3atGxcpmnPf9q3btouX7ZsmTPnzNQ0V47GObJly5Ylo+5dI4rYOn2Jpu3bNu3SqWf6ck07t9Dom93+u4q/YafGLVp2a5qlSVtf+w5N27Xr2qlRZ61Jwy4NvUmWZSneDTopJCkvGuqhjfWpGNtLK8pFlZQf/RRpDsb79fOvIkX934M9unS1fInnF929jyVnkJz4Xbrtcer8Yrzp/+bmHDpYktwG0v//a+rXAjGf/n5b4P+rI57+to/0/F/dYdm+/2lBocMX7Us5fIctHVtRUPp/fhXOVfCwXDDRIbn/iIOy1KHI87ori8o9shSTpP4F/q/Y+3/F/9P73y9FZFWS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ProductWelding_1 {
            get {
                return ResourceManager.GetString("Track_ProductWelding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NNRt/wfw65KSW9KiLCHuSpE1NGOdkFIUUaEsN5okMRjbZOtOliSSSvayVBJCkjAoS1pmELJlyr7vY5jBPJfu+znn+T3nPOc853fO74/fOd6v8/1+rvl+r/Pdv3PNAAgAYKOs1JVs4ECzMyaXHF0IugRnZ4KLjPhZvDvRkeCiiZFTlDugoKSsJKeqrKooI67recXD0x2v6YL39HC3vSIjbuxpd8XR3gBPOk1wwrtoqqgcOIBVxKti7DEqKipKCmtX9rH116bljuIJzngPd5LcCTzxEidazuX1115+s3W3v+TohVe64MxNcMW7uHi62xE5L9h62K50Wr9+PcfKAW7aC4AGqrw+nJHca1CDb2UmzQ8ABzOQA4jx/3UyLDYH+LsJepu+nTw69HVzeR/YFAR/n5Qt3mG5iNb3b/1rPXYUHV46ajSKKiWXzfex/7cV/FvyyxSqz6WpV2vdl9Db+PZhFbPLUA+jr6YHwDXcv0zl/zL9j2Urd+fXhjh+zSGq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ProductWelding_CH_0 {
            get {
                return ResourceManager.GetString("Track_ProductWelding_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBNfoOjxc44FLIiKikoXBPlJU5QiJSooKAKKChaKCkgnFCkBAioqXUSUXsSGBUSld5UmBIhKE0SQEgLSSygJkHv8/X7vzX135s7ceTPvr8f3M7tnJ9nZbDaZzZkACABg4/6Mf1qL8OqsgbWNI1GD6OBAdJQSNrR0cbUhOqopyuyR2Ssnv09eRnmf8h4pYQ03+2tuLpZqjpZu11wu20sJn3S7Ym9jrmNJOkO0s3RU279/716lPZbKiuaK+/fvl5db8ec1eP4+tIyWJdHB8poLSUbX0tV6OX6cw/2fV1l92cXc2sbdUt7CYRXRydLR0c3liutyi8vXLv/ZiZOTE/05wfUSAKjikctz+d1Vy/AG958VmR8AxPRDwJn/nzfDYiOw6d831tvYoqc10LChlAbW+8MdY9L5fMbz+Hnlf/dVAn8OgU/xm4B8UvEsjf1/O4L/0mHlgxXwoEg5vB5UBoGTxoDJK03oKX8EgOuE/7SU/qfl/3jsz6fz94HQ32uI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ProductWelding_CH_1 {
            get {
                return ResourceManager.GetString("Track_ProductWelding_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dt5VI3t/y/we9yZQ4g0mDOkJNEcQogyjw0IUZqkeUIISQgZGpCEJgmVJqGBKCRpVtFcu7l243nv7fme85vOOr911jrr/NP1et59Ptd13Xvf9773rlXPeh6CJAhiEINf+WMUhS87txw5amGpZWlubmkhM23HoeM2Ry0t1JfKLlaSXbxIXllZVn6Z/BJ5mWlatsdO2B4/pG5xyPbE8f3HZKZtsj1w7KixziHHbZZmhyzUFRUXL1aSP6S8zHiZoqKiwiKWfxYRwZPLah+yND904rij7MZDNkcYrAvZ/T3PiP3HjY8ctTukcNB8uKXVIQsL2+MHbJiD+0/s5x80bNgwin+JY6UJQg31s63VpeE0GmH+l02rCILqcaeIVav+vpzeQYqY8M9L+/09X1e7Nndcyh9irAc5o3lh/FT9PuyP+udYpR0cghiGS/kmoRCY1P1n8P+2Ev9hpNvNe09/UUkzWZP+jjz5RmswR2X1YoVFbwnipOa/Scq/yb9b+9d7Q1CC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Shandongluqiao_0 {
            get {
                return ResourceManager.GetString("Track_Shandongluqiao_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iGAEGsT0q56J4SszxDu//zMxiEC99uTKdT/3l5cF9z9lEGhmVPqgu1M65g9Qfi9UrYUBkJAB4kuyxvP2/nj6n1yaAQ0wNuw+zNhw5TCQeQjIdgaynSEyDfZIeD8SRhFjhBsEJoD+Z2JmZmBhZWViZGNjBnqZnYmNjYOTi4uDi5ubg4eXl4uPm5uTg5eXn4+LS0BQSEhASFhYRFRMTERMXFxCUkpKQkpaWkZWTk5GTl5eQVFJSUFJWVlFVU1NRU1dXUNTS0tDS1tbR1dP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Shandongluqiao_1 {
            get {
                return ResourceManager.GetString("Track_Shandongluqiao_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR5NNv5FsB/xNZSiVJqqdCOok2DpCRBpJqWtsZSap2oSAQhiVhC7NRWyzCqulLlGXTaotOWGrRRqm80pDtqVzKDtmhH7PKSLu/0zXlnzpx3zvvP55x77/f3/d7z/d77u/dcQAIAAKEIsRWjIClS7s6BVEYIPoROD2HAdNwoYeHUEAbWDI5AwxHGJhgM3ARlstcEpoNn0SJYYRQsg8KKCPOlwXScWCQalWxHiT4WEkxhYE1NEQi0CQWDIqNMTU2RxtLiV5Q/Xg63pYTQKRFh0XB7SniglGhfNvLTOxt9w8iB1EgK0o++IYRJYTBYYaRwKT/fCF+xk5ycnKQ4RIg+AFiKbCeLmbMBJFqAxSpZDgAklxIlAZbcp3SWhZKAyufUxp53O9hOPFO6Nw5AUiS2z+xp0CSsiM6xn33RZ0QKIZKn25CXmhfGhf+rBf5EYKxhG+ix+YMAm/bWTu59vJBnfhCBNL4PAEm4r+TeV/Ife19qA3xcSEhKgqSkpWVEv2LD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Shandongluqiao_CH_0 {
            get {
                return ResourceManager.GetString("Track_Shandongluqiao_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iOgAGsT0q56JoYYF4p3f/5kYRKBee3Llup/7y8uC+58yCDQzKn3Q3Skd8wco7wJVaxECJGSA+JKs8by9P57+J5dmQAOMDbsPMzZcOQxkHgKynYFsZ4hMgz0S3o+EUcQY4QaBCSYmZhZWVjZgUHBycXPz8PLx8QsICgoJi4iIiomLS0hKSUnLyMrKySsoKCopK6uoqqmpa2hqamnr6Ojq6esbGBoZGZuYmpqZW1hYWllb29ja2dk7ODo6Obu4uLq5u3t4enl5+/j6+vkH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Shandongluqiao_CH_1 {
            get {
                return ResourceManager.GetString("Track_Shandongluqiao_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZZ3MNxf18BXlxAlInqJEpFglbBWF0TPJiFKBJFYssouVttlrRC9rLb6EkF0IroQBFFDEi1ED9ESvYTFPvIrM7/3mXfeeeadef96fWbOPbecuffc7/fMuQdABgAASCf81r+hJz9pTO8+gcERGghnZwRcjN8E6oaEIeDKchLS8hLSklJgsIQUSOq6lBi/hoeTu4cbVBkO9XB3s3ES47/t8cgJ9lgfijJGOELhyrKy0tLyUlAw6DFIVlZWRpLq9yksf2wuoQ1FOEPd3VAShlDkE8qTeRrPP885a+P2+AnMEypj63wG4QKFwz3cHiEpbW3cbX4b0dLSkv92kUkEAFA60R88XCLPUJx0GH839kwAAPkBlhxgwfTndYgkcsCFv642NzhyS3tpgLlpHsAUSCawLl7H9eDwZF3wL1v50pPm9ol85pHJaPw1T/rfasC/sbSj1zZFdrGt6GF9a9GrnxpzIIWbJBLfOwDAX/Uf0vQP+S9zf/8bwO8OOQWAjJqGkuos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SMS_0 {
            get {
                return ResourceManager.GetString("Track_SMS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5XEz9Hz/8c+acM5EWSYk2IlFp0aadViQRLZTSqj3te1HatCG0F4rQpqK0ow3tRWmnVSpp0Z7u98z1/T0ev/v+8+75eM3n9fmcM+dMx0xXM10IiiDIJnxRRsoXHQlu9LStrB0clR3t7R0dBPfqWji7WDs6yEsKHT0mdFREVFpaSFRKVFxUcK+ym52rm7OFvIOFm6uziZ3g3nNupnbWZhoWXhcdbS0c5CUkjh49JmohLWUmJSEhISZCUM7CTD24kLqFo72Fq7OXkKaFixUO6zTu/52H1sTZzMra3ULM3H6r43ULBwc3Z1MX3NzE1YSy05YtW0iUh7idD0HkYGxyux65FYPCSLnJf4wgpNUAEvL08X/fztomCdn5v29t5EvXWfWJDqaqUWR7EMrz50gJu+E6bLf/377H4skIYgcPpZ1TLLVieXTz/++I/H++8quXq688Yq1Bj5dWX+vFVPyesKp4bctQQJAbiv9Xqv6v/L/W/s+/DUKi3qIwkqgzDOAI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SMS_1 {
            get {
                return ResourceManager.GetString("Track_SMS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5UJPXGsbDJihWoCyRIiRiKVIkyBoQSdgUK4sgIiIIGAgStpCQEDGQKC7IIjuXIJtIWy1UNtlkCwoYXBAklbAFFCFsgWAEggTMTdR2ejt37nTuzL1/8Zs55zlzvnfOed/ve875AGIAAEAgRKQitosLO4/jQahwtC06LAwdvg98EomNRKHDLU0hhmYQw/0G5uYQA6iBscE+sC0+FIfHIi3DkXgc9mzoPrALHhGK8ndARp9AhyDDLU1MDA3NDJDmUH+oiYmJ0X4p0S6KnxaH2CPRYUgcNhrihIwMkhTOS0d93mfbWax/ECoKaRQQthUdgQwPx2MRkZIBZ3FnRUEyMjLiohTltQGAg0Ltxkckb5UQDuRE3cBWAEB8jSwOeL71czl8gThA6UtpE78xnO1n6ArUSYD8ZTHNRb0Hat7rwudZX2LNbgs7U2HrUzcqbFmdFPy3CvgLM8tHO3aLq3SU+TW2zxbO27KgBw4LBKBHAMBF+J8a9U/tX+Z+/zaATwMx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SMS_CH_0 {
            get {
                return ResourceManager.GetString("Track_SMS_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNvZF8AjGGvtpfatGFVLLE0Iia2WWmMtrV2IItYIQVFN0SoqqraiqtVF7VsNokWNkaIoHbW0VdS+xF5kop2ZM785v/M7c37n/H5/+Zxz333nvXvevff7vfc9AA0AAKBQOdSHsAKpg70VygcdoBfg7x+APi1mhwwO8QlAa51RUIYoKCuB1NUVQGCQKui0mB7GLxQTjNRCIzGhwW5+p8UsMe5+Ph4myAibAF8kWktNTVkZAkKqgz3AampqKkr0h164vx2uYIgM8EeGBkcomCFDUHTUdYaw736Y3YI9UD5hSBVPf6aAQCQajQl2D6HzdAt1OzRiZGQEHobIIQMAaFL1a0xgMhMtdcJ+OIwwAwDA3RggoIf5ezpfKUAAz++pfR4cNjecHeAkTgE44mkkVuSfC17co+5n/m4LyaQOylTpF1bJb96eovy3GvA3Ktu225wKedtptBvbvN/T6kcX8epHsBTDAIBY+F+E+Bf5l7U//g3g24QGCKSlo6f/gfop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SMS_CH_1 {
            get {
                return ResourceManager.GetString("Track_SMS_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ0FsFRXt6137+7duh13l+DuLsFdz8Hd3SW4BpfggQDB3d2CuzsEd3eH+61FXtV9r+qdr+YaY8qSPiT8EPsVj6IoP/gSKr50laVG1Zat2nco3qFduw7tMySt2axzl1Yd2hfMnSlrpmxZsufInilvjrxZMyQt3q1t126dmxVs36xb186N2mZIWrlb47atmpRr1qt6hzbN2hfMmTNbtjxZm+XN3SR3zpw5s2fRxB0x5NGZSjXr0K5Z1869MlVo1qWlj3qg+89bwo06N2nZqnuz7E3bhTp0bNa+fbfOjbv4mjbq2kgMBYNBVTzQTqMoBVCjp29syIux5HJEV9TP/VXFixFfX36oSsz/Ptjdcxcrlnp01tl1T7EHe5K/zLglQd2v9I8e/jmbZ31dRXlTVlHOJMo+e8fHez/+f5p18+YSSxPs3p3tpxbxjIi7f3aTBbvHPXrtUfJsLqL8P18bdmTZv+PA5f35JyYvaW2dtq+fdaOkp3S+kooyoPD/il3/K/6v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelProductWelding_0 {
            get {
                return ResourceManager.GetString("Track_SteelProductWelding_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XN0FlNzWlrZhqUBSgUpSgZmZmd3dZmZmZmZmZmaMIWaM2TGzHTMzMzPTvDrJ/69Z08/a2t/Z50gFXpOx7zh3JFmSpN/82N3+8Tu4VKvcslX7DkU6tGvXoX2GJNWbde7SqkP76NyZsmbKliV7juyZ8ubImzVDkiLd2nbt1rlZdPtm3bp2btQ2Q5KK3Rq3bdWkTLNeVTu0adY+OmfObNnyZG2WN3eT3Dlz5syexW2/Rkg8OlOJZh3aNevauVemcs26tHQxV7v/+yreRp2btGzVvVn2pu08HTo2a9++W+fGXVxNG3VtZB/SNM1hv0EztSRF0fWervEeJ8GwLxXneCTHtwEOqSjB/vn+2yGF//tgDy5cLl/i6Xlrz0PJHCIne5Nxe/y6P9j3/3c2T6NCkvQjo/T/f+aXrDujZN3XBf7f+ueyHZ+W7Xj177rjsr3/9YKij1y8N83Ivw3p6IqC0v/56ZSt4CG5YNKD8sBRB2SpY5Gu21YUlXtmLyZJAwv8r9rz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelProductWelding_1 {
            get {
                return ResourceManager.GetString("Track_SteelProductWelding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NJXb/wfwz5ZCiqI6lCGRIxkyZT5HuYXQKVMpOZmSyjk4xCHcbgPRdEkiUSpDGpRKxtPNrOFkKJEhcwgZjtnx3e6937W+v+9a37W+67fW75/f8n6t59l7Pc9e+9nPsPZ+AAHAHM58OZ9lPHhna3XUg0Y3pnt60mlK6+3cfBgedJqhtoqaivoWDU0NFV1NXTWl9cZ+J3z9fNwMaW5+vj5OJ5TW7/FzPuHhYu7GtKEfd6MZammpq+uouelqu2hraWlpbFk8fw3RP7tWMXGje7r5+jBVLN0YR3nxcb6Tf11lqZOPy1GPk24arp4CdC83Gs3Px5nB6+rk6zTfiJ+fn2d+gCuIAAa4XB7Ae1lgEa4Iz+8sVgLwTIXygNHKv25meo4HVv19Yx21dbtNempWsjphxRm04adyzjqHGXye/++2Or54eKdwpVpSI7FgonPuf1vCv+VFwZaSgtL6Ev2oDTuEc28Uhwi37ECmejsAfiX/y8b6l+1/HJt/O392xPPn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelProductWelding_CH_0 {
            get {
                return ResourceManager.GetString("Track_SteelProductWelding_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwvY+KBm6zSihjPQqZx3vlknpMRVKZkiSJW+aLS0okySNF5uaUcp8MScYiQzIUmXORXGMXF3fA9e56nt+7fu9vrd9av/Wu9f7zLt/POnufe85e+5xzz1ln7wMgAGAB5Wf9M6swVFhZnHH1IBFJ7u4kj13bjjh7ermSPHTV5ffIKykqqyjLa6po7tm1jehzztvH01nXw9nH29Px3K5tB31OnnN1MnYmHya5OXvoqqoqKWnscdZUd1JXVVVVVlz68xjrfnUtb+RMcnf29iTLmzp7nVmCtvP7/nWUFY6eTmdcfZ2VT7kvJ5139vDw8TzpteSUo7fjz0YCAgLYzxNcLQuADqoF/ZfcWM6HVnA/iyPCAGDcEAz8LvzXxcwuYGD93xfW39xqZjTUtKb0O1h9GUqM7y4QsZ1D+9f+3VbDHnX8Aa18FlVOK2Z/X/jf1uBfckFJ7z3U214BL0aWQ3Ce6P36qQH0VzYE4CLhn5bSf1r+x7afd+dXR9iv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelProductWelding_CH_1 {
            get {
                return ResourceManager.GetString("Track_SteelProductWelding_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJx1VBZPuMd3d3ZnZmcVO1GwuxETxEZFLOzAwC4ULCzsVuzu/NndKCq2IjYiKioqJiAqoIje7yz+cc895/I588x3npl9N97dnXoHRVUU5S/+ZCz/smgwndoNHDTcv5H/sGH+wysU6dgvIHCQ/3D3mpWqulSqVtWlei2IKlWqVijSaPTQUaMD+rkP7zd6VEDvoRWKtBndZ+ggP69+Qe39h/Qb7u7qWq1arar9atf0q+nq6upSxZB7yWV/eCXPfv7D+o0KCKrk3S9woA4/G5O5H9E7wG/goDH9XPoOM/1H9Bs+fHRAn0C9b+9RvWUhzrkmDzF7aUVxQ/x8UvVFJoHIJk31oqqi/QrWlDJFM08o/a+m5P53am8eRrXy/PAgR9hbJft0tVhSxdOO3X8jP6lIZtla4yxFOS8U5X5hl43n0t7+/f/ieouOXv92avGFgNEP1n7t6Ve/WfbRzsriZRfI1gSivLtZX/k/f7vda18ZsD/+SngftUnvbDsvr7v/pUmv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteTest_0 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteTest_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJwF0BRH17ZnZndHdmR3cVvc3d09uAQL7u7uHiS4OwQLBJfg7k4CBHcIECy4y3d1w1/11Vf1c9WZ+z6nT5/unWepkLzJq6iKonzll1Dxy9F41KrWqnWHjiU6tm/fsUPGpDWbd+naumOHQnkyZ8uROXu2HDnzYrJmzZYxaYnu7bp179K8UIfm3bt1adwuY9Iq3Zu0a920fPPeP3Zs27xDoVy5smfPm615vjxN8+TKlStH1oA4JaYcnrlM847tm3fr0jtzxeZdW/mpGz2+nRNs3KVpq9Y9mudo1t7q2Kl5hw7duzTp6m/WuFtj0WSapiauGE6jKAXRa/1zjrN8mJB4+E75FO3DQE15e9InP87Hr5oS6/tHu3vuQqUy/56N7P5HCQ9Vkz/LtDVhvU+s7/7em7dwYkU5FFdRzkRzzNv57p+v/z9tsLx0M73/73uk/rO06P/LV1/yP2uQbllR5f/8UvcUPKgWTXZA3VPsgKq0KNFty/KSs3fEKaUog4r8r9j9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteTest_1 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteTest_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erbmeobGekaGxiQWQYWBgqKPgXJpTUlqUapuXWlpSlJijoxBQmpSTmeydWhmSn52aZ2tqamRkYZhqaZ5sbmpqamzACrJFGGy4nntqfm5qSVGlnm9qcQYLUJy9DGIPV2JRckZmWapxSi5nfkFqXl5pUVIxS0piSSJIEQcHBxPIiQLqDAw2QPpurUkfJzOQwQ8ifrAyMDD9qmdieMMK8c7v/0wMIlCvPbly3c/95WXB/U8ZBJoZlT7o7pSO+QOU3wJVa1EHJLSA+JKs8by9P57+J5dmQAMrbS2Ppq99fvRwEqNrIv+yI7MvvXVNOCftysDQYI+E9yNhFDFQ/IANAkcSIxMTMwsrKxswKDi5uLl5ePn4+AUEBYWERURExcTFJSSlpKRlZGXl5BUUFJWUlVVU1dTUNTQ1tbR1dHT19PUNDI2MjE1MTc3MLSwsraytbWzt7OwdHB2dnF1cXN3c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteTest_CH_0 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteTest_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ7NFRrHwfw33ZJUYghokSJ0LglxLh2v5B0FSlMU7lM7pIx3W9KJJHrqWR0OUl4GZcZlZJ7HeGg4ZVBjVuMSwwz7yPnvOu8Z62z1lnvWu8/7/L9rL1/e+1nr2c/e2bvZ2/AAECAMl2nM18IrfbtOnbch2xL9vYm++gs20v08z9O9iEY4/UN8Qb6hmtM0Iaenr7OMttAr4BAPyLBhxgY4HfES2fZzkA3r+Pu24indpM9iT4EIyMDAxN9oqmxu7GRkZGhnuj0WWR/dI7fRCR7EwP8TuF3EP2PiaD9YkEz5xE/4ud+7HgQ0dDDex75JNHHJ9DPzV/E40jAkemD5s6dKzQ9RGkNAHNUWZQ1kfOE0YbU9GrtAgChCaoQaC2YuRyeQAhwv10a+2Oj3aavdQuZnSB9HlP7tpqu5DyJ2ofmz7SbrEfD80IbvywxTCn+3in4byv8KViJ+RvMSrUUK7EuxeCobUD+o/WJRfIbAM5Y/mFh/mH5j33T/8+PjoRmukNV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteTest_CH_1 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteTest_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dNwFsBXX1q7h7iW9upd1L9m4u7NZG3cPEoK7u7u7EyRAcHd3d3d3d3d3h/+dk9yq/96qy1OjxzfHnC0kpyhycg6KqijKL36ILn54bVyqVmjWvE3bIm1bt27bJkOSKo07dGzetk2+HJmyxGSKZInJmpMQHZ0lQ5IinVt16tyhcb42jTt36lC/VYYk5To3aNW8YenG3Su1bdm4Tb5s2SKRnFka58rRMEe2bNliop3iLSH58Ex/NG7bunGnDt0zlWncsZmDuavL7/e463do2Kx5l8YxjVobbds1btOmc4cGHR2N6neqLw7pum4Tn2ilVpS89Bu9s44y7ARTXPqPMBTb1742pTNB/Pj2y6aE//up3T9/6a8/npwL7HqgWAPVZK8zbolf6zv7+f47m3NHNkVx8tyzCWNm7vj84Nf/r2fZvLno0vi7d0d+94Lq0DgHZjZcsHv0k7eqknNzQeX/+bHhReTAjoNXDuRZm6RYON6M/f3MW8VimuUspij9Cvyv2vW/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteUpdate_0 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteUpdate_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luFVFG7D32itm1tp7H+AcupVOiUOJSHcr3R3SKRbdAlJKKCivioAoKN1SSkl3SCNdkoLw3c8cfnzX9/PjvmaemJ41M2sW78Y3ZIVCoZf8ESl/omGixu906dqzV8VePXr06pk/a6OOfft17dWzTImChYsWLFK4aGJJlEKFCufPWnFA9/4D+nYs07PjgP5923bPn7XegHbdu7av2fGDBr26dexZplixIkVKFu5YqkT7EsWKFStayJVWEkzlBat27NWjY/++HxSs3bFfFwe/GpjUTtC2b/suXQd2LNqhh9+rd8eePQf0bdfP6dC2f1vJpLUOSxeT5wqF3kKe+SRxkm+jJJOo5bxwKPzvkHCo/rywGc6zl+FQyldDu3T4WJ2q1w6l2HQ5lHyE9frdAmsytHhOerpXeUuOJGenHKHQwUxF5254cvnl/68M/T9/+rSrsH1wude2/Tdk5lYrVLti/9ULK1kzC1cOhYaW/b/Cpv8r/D++V3+kn++GS4bbwOjw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteUpdate_1 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteUpdate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NJTf4wfw+9AmWUJaKCShDCEhpJJkF5Ot7MTYxpJ9mBIRIVSiImTLli2yjDZkibJvzXzs21jGbsbyvX0+n+8539/3nO853/M75/fXz/t17nPveZ57nnufeZa5AAEAbMH8rn9nHx3cGOjaYZyxSlgnJ6yzCK++jZs7BuusIC0qLikqIS55VgY2zpwRF+FV8nC84+Fmo+Bs43HHzcJRhFfHw9IRY6Vu44PGOtg4K0hJSUjIiNvISltJS0lJSZ7Z+XsU9j9PLqpig3WyuePmI6pp4263A+7f7fnXOHst3KzsMJ42ktZODFgXG2dnDzdL9x3WFncsfnfas2cP3e8psgoCIA/rX/5nIxnoYYPl98aaDQA6Kp4OGLL9dTm0LTrA8felDbd3aalMtO2vHgGs95Hjc6gPXLfW4XHev/vK3IXTuwsbrUclE6tWR7b+tzX4t5RMS9RU1fbUyBXyKnMcefX1LgtJWdJORhmOpvgvpfpfyv/Y9/v+/Hkiuj+3CKzp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteUpdate_CH_0 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteUpdate_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NNRt/wfw60olkakolS1JiCzJHqOQFmvZokyS7Y7BjLEzLe5bieRWIYzsKlEqsleULZQs2bdhUNZhNMbwXHXfzznP7znnOec5v3N+5/z+8H6d7/W55vu9zvX9zsx35poBEACwgvKz/gzPGtRYnXZxxXvoeri7e+Bld1s6EoiuHngtVTlFJbmDikqH1FBHQUFRdrcuyc2bRHDUwjuSvAn2brK7TUkX3VwdTjn6m3tcdsRrKSsfPKim6Kiu6qCqrKyspLDu51n4fk0uZ+Do4e7oTfCXM3IkuqxF+zl9/jrPRnuCg4urj6PSJXcuD09HPJ5EuEhce8ne2/7noA0bNqz5eYmbJQE4jGpP8KHbXByog/nZLPMBsGaRvAbM8v31dFgrawD/30+N2tJubDD2ZUvFMNh8He6ZPlAkeG4JHS/+e6zaLLq8TNRpFlailP0YXvnfVvBv8bp49H2IjlgVmxxXCYGRrvfrR3owTlEfgCvYf9kq/mX7H/t+vj+/Jlrz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SteelWeldOnsiteUpdate_CH_1 {
            get {
                return ResourceManager.GetString("Track_SteelWeldOnsiteUpdate_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJxzlB1N1O5LjarqPrFt27ZtOxNnYtu2J7Zt28kb27bt+1R/3x933bVufmtqPxtVp7vnnKp98oJQQsg//DHW/PEYhppVW7UO71CsQ/v2HcLTJ64Z1rlL6w7hBXJlzJonY9ZsWTLnypgtc+Ys6RMX69aua7fOYQXCw7p17dykXfrElbs1bde6WbmwXtU7tA0LL5AjR9asubOE5cnVLFeOHDmyZbbMi0QL1s5YKqxD+7CunXtlrBDWpZVA3On+Py+jmnRu1qp197BszdvLDh3DwsO7dW7aRTRv0rWJKXJdl5krjJyKkPywk4Z1HS85RCQzjDwtCPs5gJG+p0VwN7/+MRL9f+/s8eVrFUu9uBRl/xMSeQhN+j7Dznj1fyNf/H9rc38sggn5CLmYINu8vd+f/Pv/2SskMyMfFx5o1zZ9iDTfXbh32uWP/lVacSB4hFt3FCb/z5+Zm9ce5gN7HhHEPkIrWyXowH0lfg8YVoyQgYX+r5/9/9fP/xP73z/mxrcz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SWJTs4800_0 {
            get {
                return ResourceManager.GetString("Track_SWJTs4800_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL0DsJ3ZGm698K2PC99SbNu2bdu2bdu2nY7tjjrsjp101LHtf8yZc/+6dfeodz7jeefc6XOqTqV20js5DqfD4fjFh0jx4XVx1KjSqnWHjkU7tm/fsUO6RDWad+naumOH/DkzZMmdIUvWzJlyZsiaKVPmdImKdm/XrXuX5vk7NO/erUvjdukSVerepF3rpmWb967WsW3zDvmzZ8+SJVfm5rlzNs2ZPXv2rJk84h8Slj92hpLNO7Zv3q1L7wzlm3dtpbDXevz+x5iNuzRt1bpH86zN2hsdOzXv0KF7lyZdlWaNuzUWj3Rdd4n/hHZKhyMfOXl4twmGGwmIo84cy+H6OtDlqICIj2+/XI7I//6bPbh4pULJJxeCBx467KHOJK/T74pb7zv3Mf73NlecQw7HvK6O//9j6a4Fed//fFXw/+1/PDgw4nzX/gcfXUp7dlaNDoX+z/3/2//PhytR8iOKY9xh1bHisLvQ2KKfdiYutuNa9aIOx6CC/9cc+L/m/9n9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SWJTs4800_1 {
            get {
                return ResourceManager.GetString("Track_SWJTs4800_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR3UNPZFsdDAClRwaUJSJO3sCogRZqAoQjsCoKisKAUKZGe0EKIbBIWRUXaQ0UQhYAiCJaoNENJECKdAAoqUXoJGBNaIEASsgF1Zt/O25mdN/P+4zNzzvfOvWfuufd3fucCBAAAAI/Phm6wHch3bi5BwVCYDSw8HAbVUnWDREUHw6AWxjr6pjr6Bnq6xjoGurp6Wqo28LAYeBTEAgqBx0T5hmmpnoD7hQX7O0CQp2GhEKiFoaG+vokexNTY39jQ0NBAV3gjidTm3jr2EFg4JCYKqXMcEh0kxJ8Xif2aRtw3yj8oOBZiEBAuBouAQKHwKL9ooQDfGN+NIFFRUeDGCSU1AQBzvmYmxaSLCfIHEhsOJQYAANcwQECk2NfbsHlAgPS3m030vXeyn3m7izgJkLwosHdOG6/oyeGvm36LNeHw3Wm+vVEyyK9fmeT9rwr4CznlT5oEE+JIQoBtJIETwrYCCQRbDibJBgBIAP/JiH+y/5jbKM/mRps1EgACBYWE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SWJTs4800_CH_0 {
            get {
                return ResourceManager.GetString("Track_SWJTs4800_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NFT//wfw1yVJixFKSVkqirJ+bDHIkn3fKiE0lMo2xj6mPmSUjzafsnySFkvahCTJqJA2pk/Zw0iWLBlMDMbwfau+53y/33O+53zP75zff56P836/7rn3Pe9779x73ucCBgDzKAt1ISt5UOficPhIQKBR4PHjgQE7pFwIIcQjgQF4TUVVbUVVNRVlTUU1ZWWVHVJGpGOhpBACPoBACg3xOrZDyo7kfeyIjyUh0inwKCEAr66uqqqlQtDW9NFUV1dXU+ZbOInIj7kVTQmBxwmhIZGK1gTi4SVoP3/Yz9Ms9wrxOXwkjKB26LhAYBAhIIAU4k1ccsgr1Gth0LJly3gWrlBIDkAX1QunQs8K8KIN3EJHwgHwzFB44Aju591w5nlA9Ned9TQ025gOfFxd2QtCcZjM6M6yDQdm0XGVX2O1DqPLi0AbHzaqXa2Y6p3/v1b4j/BIba1eAn9ULYXcKl6DJCP2Y2nj0lZnI4AT+v/SKv+l/du+hcfzc6IfPYYq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_SWJTs4800_CH_1 {
            get {
                return ResourceManager.GetString("Track_SWJTs4800_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dNoHXI3/Gzj8+z73TBSK0PqaoZSkvRBCqJSihYYolUpL62uGUjRpIqu9VNpoD2W0NGlrqrTXc53z/T3P8389r9dz3q/rvq7P9bnu01Cd+5wDQREEWYIbMzNvyxlw0Dl16bK1jYqNlZWNtcg/OmZ29pdtrBWlRffIiu6REN8tLSqxe7e4yD8qDleuOdiZKVqbOVyzu3BF5B8NB+Mrl03UzFy0bSzNrBUlJffskRE3k5U2kZaUlJTYTTA/CBfrvkVVzWyszK7ZuYieMLO/hEOfcvzvwyy7YGdy6bKjmYSpFZvNVTNrawc7Y3vc9MK1C8whmqYZzM9wpRCCKEB+fOeaLxsGBSfz0LcCRRizngykZcV/X8/cEgPh/t9X1lXbcFL19/dVBd3Iylvopj+7sngN5mH/5f9mZdayIcgD+FS+8UtE5k13L/3/5fRMgfZonQcfam6et/t6Lnqf+HHUV2zC7IMoDfdSnbYP+f/cFtuti7j/nSpE92FF1IcmFfTMk0Pz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU3400_0 {
            get {
                return ResourceManager.GetString("Track_TJU3400_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZplVFVv1+7XWiAtSEmDgFLSIV0iIq2AdEl3d0t3SCudgkioNEgL0iUpjYR0N7wLnv9zxnPeMd4zzpczxvnA9Rv3Pa97rnuvtTdrMyd7DwAQAIArWNfxWhgQPCkrmJhaWYtZW1paWzE+UDa0sze1thLkZmbnZWbnYGPlZuZgZWVjfCDmaOHgaGcoaGXo6GD3xoLxwUtHPQtTfWlDVyVrc0MrQS4udnYeNkNebn1uLi4uDtY71xfBvTk3s4ShtaWhg50rs6yhvQkinEd2+tdl0N7Y6ZuYOhlyGFiiWtsYWlk52unZIxq8cXhzvQkFBQW6fob3aAFAAI4xAQ6RqAiwwbqeJDkAADr1hgBBjn+9mrMrCMD755UtDo/KSawOYTf8Ae75gVTbTNUkmufw8Tv/7OUxhU/MCD/FQTKOtPrjP1f/U9y//nnJhzReh6v8MhGc/tzzJT+pxvPr9WisCPDfdJn+vBUERltAQKoFGRgUgwCFZ3r4bWIA4CP8H6PhP8b/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU3400_1 {
            get {
                return ResourceManager.GetString("Track_TJU3400_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NJT7Hwfwz1DInkhutlKpWxSTjOzRVSm6KlosITdLxp5lmFFuKElyuyRLUUhZbpKsg+xkyZYYOyNkN2Mb8/tyu79zf/ece849v3N+f/28X+d5Ps888z3PMt/n+30GMADARFmpK+FmQStDA2sbvIOWg729A36fpKGVs4uNA15VUVZeSVYeK3dAURZ74IDcPkktt2uubs5WqngrN1dn82v7JE+7WVyzsdS18jzrYGeFV1VQkJfHyVkpKVoqKigoYA+sXznJptVjy+pYOdhbuTp7yp6ycrFeh/azX//9NJzmzpbWNtetsFfsNzg4WuHxbs4WLuuumLuarzTi4OBgWblCfmkAFVRDb7ne28CKNvhWVsbcACwLJBY4zf373SwyWUDw2531N7Xq6Xxp3EgeAH4/zPYJmeytxkvo+y3f2uK+Q5dnijY+imFj8ucGmP9thb9kuQtfIuhLf4/RYC1hL/yshTkfcXSJ2VUE4Kv+p4X8p+U/9q10z+qBWFbXGFRZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU3400_CH_0 {
            get {
                return ResourceManager.GetString("Track_TJU3400_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEWFBGZl6+c35ubn6ejkJYalFxZn6erbmekaWekbGhgbmesYGBoY6Cc2lOSWlRqm1eamlJUWKOjkJAaVJOZrJ3amVIfnZqnq2pqZGRhWGqpXmyuampqbEBK8gSYbDZeu6p+bmpJUWVer6pxRksQHH2Mog1XIlFyRmZZanGKbmc+QWpeXmlRUnFLCmJJYkgRRwcHEwgFwqoMzDYAOmJrSV9nMxABj+IkGJnYGD6Vc/EwMcO8c3v/0wMIlCfPbly3c/95WXB/U8ZBJoZlT7o7pSO+QOUv8YGkbeYACQMgPiSrPG8vT+e/ieXZkAD/+a7HWFkuH6YkcHrMDvDJWcmhiCXJNGjzgwMDfZIeD8SRhEDRQ/YIHAcMTIxMbOwsrIBg4KTi5ubh5ePj19AUFBIWEREVExcXEJSSkpaRlZWTl5BQVFJWVlFVU1NXUNTU0tbR0dXT1/fwNDIyNjE1NTM3MLC0sra2sbWzs7ewdHRydnFxdXN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU3400_CH_1 {
            get {
                return ResourceManager.GetString("Track_TJU3400_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLsF2BTXtq5bXdbVVdVV3X9w9+AQ3CG4WyBIcHeCe3AIhOBuwYO7uwV3d5fgFtzOO2dynrvvfu7lfcYc3/jGmGNWZ++TrLXPWkpAUZSv/BFZ/HFVjh+rtmjZrn2x9m3btm+XMdmPTTt2atm+XcHcmbPlypwte9aseTPnzpr1u4zJinVp07lLx6YF2zXt0rljwzYZk1Xu0qhNy8blmvao1r5103YFc+bMli3Pd03z5m6cO2fOnNmzGuKRb+TuzKWatm/btHPHHpkrNO3UQscPdv33Gbthx8YtWnZtmr1J21D7n5u2a9elY6NOepOGnRuKIcuyVPGFkW8VpQA5NKjFyJCG8MVxq6eqqB/6qsq5nqr8NR+/qkqs/37ZnTPnK5Z6cDq6464SGRhI8TzTpoR1PtGf+d9snpep2ZBQUU4lzj5z27u7X///spxuMWtn+fWD4yl3lhT5d/2w/1X/P3+qTmq/N9Dv7R61iLY3oFwpFrD+KvG1fqHFitKv8P+IHf8j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU5000_0 {
            get {
                return ResourceManager.GetString("Track_TJU5000_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJxnmBXFGq33DDC7cw4bjEcFFQERkYxKzjnnDEOGIeecJIkCZkHFdMyeo2JCJDPkYcg5hyEOMAwMA/et9vy4z/15XU+vWrXqq+rur6tq9579SCwpFos94D9Riv+0ZKh189S+gwbXGDxw4OBBJR5v3SttWN/Bg6qWL1WmXKkyL5YuXbFU+dKlXyjxeI0RA4aPSOtVdVCvEcPTug0o8XjTEd0H9O3RoNeYloP79xpU9aWXypSp8EKviuV7lH/ppZdeLF1InMSNxi5Vp9fggb2Gp40p1ajXsNSC+PGR/5xG6ZbWI7XvyF4v9hwoDx7Sa9CgEWndhxXs2W14NxEkSVKyuELr6VisCqU8PXWBXABhCuoxOimWfHdScqzN6H/uJ+9Bcsz7352dztzXuM6F3fZfZ2LWtKQnrpX89aGO92h/7H+xFT5NxGJDH43FMh558cM/c888+P8tY//Pf0mP116XFNu3Nin2DEdGjaRY85pJ358sHotNfuX/Ov76v47/x/vf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU5000_1 {
            get {
                return ResourceManager.GetString("Track_TJU5000_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBPd3gfwc5ZHwUZR7IaAYMFGkxpCUEREKSpgBRERAREi3VCCCj6gSLPRiaiogMKDqIA06WABUbpCBAKRXgIEkpDcoz535r535s7ceWfev16+n9n9bXbPnN3s7uzZBRAAIED5WX9mMYZmRw47OLqQ9cjOzmSXbdJH7NzcHckuRPUdymo7lFUUFTV3qCsqKm2T1vO84OHpZkd0sfP0cLO5sE36oOeZC462B+wo5mQnOxeiqqqysoaSnaa6rbqqqqqK4ryfO1n2q+8dBnZkZzsPN8oOYzt3hz/QemGv37tZaONm6+DoZady1nkB+aKdi4un2xn3P87aeNj8bCQiIoL9PELxTQBoo7ogyCF8gRBaEPs5s1sBAMYJwMDxFb//DVeAAcm//xmjodnEoO+LRHEPEA+E60e356215KHtMn+31TiGOq5GC59xKkmF0z2C/20F/5bD0eRyeJldhukKlUPwTQ+KVOgLrHXSALhM+pep+F+m/7Hu5+X51RH2aw5R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU5000_CH_0 {
            get {
                return ResourceManager.GetString("Track_TJU5000_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEWFBGZl6+c35ubn6ejkJYalFxZn6erbmekZmekbGBgaWeuYGBoY6Cc2lOSWlRqm1eamlJUWKOjkJAaVJOZrJ3amVIfnZqnq2pqZGRhWGqpXmyuampqbEBK8gSYbDZeu6p+bmpJUWVer6pxRksQHH2Mog1XIlFyRmZZanGKbmc+QWpeXmlRUnFLCmJJYkgRRwcHEwgFwqoMzDYAGnOlow+TmYggx9ExLExMDD9qmdiCGKD+Ob3fyYGEajPnly57uf+8rLg/qcMAs2MSh90d0rH/AHKS0HVWiwCEmZAfEnWeN7eH0//k0szoAFGBbcjjAzXDzMyaADxJWdGhiAXxgsPtBgYGuyR8H4kjCIGih6IQWCCiYmZhZWVDRgUnFzc3Dy8fHz8AoKCQsIiIqJi4uISklJS0jKysnLyCgqKSsrKKqpqauoamppa2jo6unr6+gaGRkbGJqamZuYWFpZW1tY2tnZ29g6Ojk7OLi6ubu7uHp5e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_TJU5000_CH_1 {
            get {
                return ResourceManager.GetString("Track_TJU5000_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx1WBVP/C/wjdmug93YHRiIimB3KwYqIigqBihii91dWKjYjS02FtjdjQ12Aibe98z3d5/n3vvn5fXM+Xx2Zne25hx2YYHjOY77hy8a6Zcp4KVj2z6hYeH1wgcMCA8rW7BDSMTg0PAwH6/yFSuXr1SxcpVqSDw8KpYtWG9I/8ghESE+YSFDIiOC+pct2HpIcP/QHs1CRviF9wsJ8/H0rFSpWsWQ6l49vDw9PSt7SHQtWVnn5RuFhA8IiYwYUb5FyOA+BPXK0P/WowdF9OgTOjSkcs8BWvjAkLCwIRHBg0nPoMggOpOqqgLdRFcJjquJ+DiqyhxNROLQl2ZBPCf8GitwtYL+26Hf/wQu2//s2stbd1s2enPT7fgrzjWRL/y53KG8Xf+gXfmfeav1cHHcL53jbuSvvOrYj1f//n8j9/98nTFciWMWFkyaIiadrptm13/3pGCDr5+duhw3rtb/UY7/H+X/qvvf54YT2Ct2EUSOcBIjcwqonMbpYHAmZ4HN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_XAUAT_0 {
            get {
                return ResourceManager.GetString("Track_XAUAT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1luNtWm7ZhW5ZlW5ZlWZLDTA0zMzMzMzMzMzMzNUwNMzMzpw1z0lCbhr9LK/kx3/ycnMfSfetZy7Czm3TvedOMy+1yuX7ww0nnhyZxqVG5Zav2HYp0aNeuQ/u0iao369ylVYf2+XKkz5QlfeZMWbLmpGTMmCltoiLd2nbt1rlZvvbNunXt3Kht2kQVuzVu26pJmWa9qnZo06x9vmzZMmfOmalZrhxNcmTLli1LRq/zKpZ48vQlmnVo16xr517pyzXr0lJm7uv+83XURp2btGzVvVmWpu0CHTo2a9++W+fGXeSmjbo2cg75/X7JeYvGby5XXvJOv6zjAx5K2Lkcy+VzSZ8HSK5dFOfHlx+Sy/71oT28fK18iWeXIvseuYwh7iRv0u2IW/cr+0N+nc2ZqoTLdTe9y3Uxfpb5e/579OP/mq7/9eN9hReH+mTcccjXstuhHMmeFckwZm3R2ffvFHG5Bhb4H2vf/1j/38z5/IgnksTVTUouj0t2eaG4fC4/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_XAUAT_1 {
            get {
                return ResourceManager.GetString("Track_XAUAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ7NFR7/wfwzxZJClGp3JXkuEyScIyGkEou0UkdSXJPTLlkmBm3QqnolBIHQ7l0odBF7pRr0VRI5TLKZdwvI4Zxmd9X5zy/9fyetZ61nvVb6/nP+7X2/nxn7+/a+zvz3fNdGzAA4KIs1sWs4kE7Gys3dy+iIdHTk+ilInvE2dvHneilp6WmrqG2Q11jpzZqbN+uriJr6HfG18/bWc/L2c/X2+GMiqyl36kz7o6mzgGHiR7OXnqamjt2aKs762g5amlqamps51u8i9jPi6uZOBM9nX29A9TMnH3ceNFx/vN/3Welg7ejm/t5Zw0nTwHiWWcvLz/vUz68Tg6+DoudVqxYwbM4RBFFADyq7dSd0QLLUEN4cdcgBMDDCeaBCqG/vs4slwfW/v3VuptazE36G9eU9YDIBUx+TLVA4vgcOn/5777almh4Z1Hjo5RGcsl0D/f/W+FfUi0oUhl0U7YqYlnV6z2TQkaDHbLGrDHhPQAhhH/ayv5p+z/HFufn54V4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_XAUAT_CH_0 {
            get {
                return ResourceManager.GetString("Track_XAUAT_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dl3UBRbgzfgDipGEFFBkKAkL4IkkRwUFUEByUi8ZIkjIGGIIipIRiSIBBHJWXIWQRBJgjBkRuJIcshhhoE93vfdqv22aqu2vqr9j99T3adnOp4Op/rMQDAEQXsgf8o/OY6AkY76Q2sHjDzG3h7jwMumbeHkbI1xkBa9Iih8RUhQ+KoYmBAQEORlk3exe+ziZCHtYOHy2MnEjpftvoupnbXZXQusJsbWwkFaRERISEzQQlzUTFRERERY4OCfvdD9s/ErChYYe4vHTtgryhbODw+A76lc/7WfoyZOZg+tXS2Eze2PYB5ZODi4OJk6HzA3eWzyZ6HDhw8jfw7xJDcESYFy1Ptq2BEUTND8GSGXwEDyRaAN7n9Vh7yHQKf/XbWp3n4VhdkftPXT0El/+OISXyWTwQ6YX/fvZcWawSZugEPsYRZOqt2a3vv/LaH/llXV+UZPgcpGqocujaIcs/L8wXk34ydG5SHoiex/Ger/y/D/fPfn+vyzIeSfMQxKBEKh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_XAUAT_CH_1 {
            get {
                return ResourceManager.GetString("Track_XAUAT_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE///z/+s9fTHhWSLZEGKtKwszJSUhqopDSozIoX2UpmQgORLYmyioyyEkISQioJqVBpfW/neP8ul+/v9+fvdf3cu93P4+xzns/zfNbr9f4QJEEQLfhHTvmfVhR+2Nss8vLzH+vv6+vvp9tztkdAoJe/n7mx3pDhekMMDEeM0DM0MRxmqNtz7DKfoGUBHuZ+HsuCAub76PacsWyBj5fbFI9Vtv6LPfzMjYyGDBlu6DHCxM3EyMhoqAEr76WjsnE9Kw9/X4+ggFV61h6BixiM88v/7UeaH+C2yGu5x1B3X9F/iYef37KABYGM+/yg+fJCgiBQ8iG20yYIM2TOsiXhIo2mrfxjdDuSoP6upQijdv9OqKGFIjr979Q+v8ifZlWe1/5mCdEujOz9c/DVbk6NmN/U9t+yw1eqCKKrQBDPuw+NS68rafn/m8T/55/PPU7f7bi95M6Bw0/vuutpjrl9oGQsOW/TOIL4z/L/qpv/V/2/xv6fe0NQyk+cItAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Xijiao_0 {
            get {
                return ResourceManager.GetString("Track_Xijiao_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZZ5MNtd28djr30t2qpYW2sIjUTErqVU7UtLaRAEEftSBLXvVbW0SKhqq7ijRYsbUYq7bkur1lbtpPY91vJwLzP3+8w77zzzzLz/+cxc53t+51xzznV+v+v6zQFQAQCAo2NO9AQW6uPGytQV7YnVxmIwWE8ZIUuUjy8a66mqBFKAgRTkwcrKIDAUfAUsI6Tt7+Hn74NS9UT5+/kgPWSEjP0dPNCOBqhgc6w7ylMVAlFQgIFRylBHKAQCUZSnO9mF+4/FQbooLAbl5xMMMkT5utIejzME/LkPE9LH0RUdgFJ0wjBivVCenv4+Dr60Tkg/5InTmTNnqE9C5LgMACCOtcvfK5mR5rjDftKUsgMA1Hvh1AAC+5/H2T+iBvD8dbTpvsGbunNfOEkzAI4oKpFV2doLtgfH8y5/+cJ+PW4ijq33oiK+YWfm6L9VwL8xDGBsgQBmm6kAcS1UEWe1jQGzWtGALK3j3dT/YaR/2P8Y+/vbAP7oUB2fn5qGhpaOnp6W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Xijiao_1 {
            get {
                return ResourceManager.GetString("Track_Xijiao_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXvvwfw55AkQzILEepIiMxzOaHMGSJldsxDkXk4faMkociUOUqSmYSQOTmmOsYMZQ45ODo4hnOfvsNav/tb9651113r/nW9X2vvZw/P2vvZ+1n7s9YGCAAAGeZ3+zt0FHBlaujk7OGJ8nR39/QQ4buK9vJ29vRQlhE7Jyd2TlxCXl5MQlZCSkKED+XjdtvHC63sgfa57WXjJsJn4GPr5mynjQ4w9nRFeyhLS587JyeBlpe1k5WWlpYUp/p9F+Y/Ly6mifZ0R9/2ChDTRXs7HYDHqX3/us9hGy87J2dftKS9O43nTbSHh4+XrfcBe5vbNr87HTp0iOL3EBmRACjBtsvn5iMaSrhx5PfKjxkAChKGArgy//U422QKwPL3o03jBvU0f3w52jADGMMQ/Cui1Vw3duB5yb/7yonA4dnDjc88khl1mzPk/20L/i3TvK9bmKNmmpOyelvsxbjVmlJmUAjr+xcBuKP6L0vDvyz/6dg/cwMo/lwjYEsBKMEB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Xijiao_CH_0 {
            get {
                return ResourceManager.GetString("Track_Xijiao_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR5NNv5FsB/SUQotRQ1QyWGGbogttglUVrdVKu19MmzJIIgi0RShlger5bWo09bPJSpwbSWqo7iUXtarwstpmIvY2lVm6ixS/ISbef0zXnnnTlzzvvP55x77/f3/d3z/d7vvfdcAAQAgEiMxEqQB4uVp1swiUJ1pJLJVIqBtgeRziBRKfYWRqZWRqbGJtbWRiaWJuYmBtqOzLAIJp1oTyEyI+j+YQbap5j4MBLhODHqLDWUSLFHoUxNrUyI1pYESxQKZWYMldyisnW4kTORSiZG0KOMXIiMYCnxPoz14Z4d/nRCMIlFNAsgy1JpRAqFScczpAL8I/wlTjIyMmBJiEr6AGAntk+ZtEuyEPFCUaLyYAAAXo8DAxmwD8/ZEIEB1Y9Pm+ofOOn8uk+5ZRpQSgTp8A0bNHGb4v+eH32t6GKlJ5ZeLbPr91enRX/UAr9hEJDtQAEz7SAguQMUr+Z4Cpg5mARcOwgA8ZjPpOUz+Y+9T7UBthYgMBgiBYVKi1Mh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Xijiao_CH_1 {
            get {
                return ResourceManager.GetString("Track_Xijiao_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3XE7/Hz/+s1fIDtkrM1tGyc6q7LJVUjRJ0UaIlGRlZ8+opEiDiKyKpJIGlZKipaH5fZzz/vxut+/v9+fP/f28Hs8zr3Od61KvV3oTJEEQrfgjp/ynDYUHo6WWW2ztZtnZ2NjZjui70ny7wxY7W52JmmMnaY4dPWbyZM0xWmPGjxnRd5aj9Q7H7eY6tuaOO7abWI/ou9jR1HqL2UJz5+V2Vua2OhMmjB07aYz5ZC0zrQkTJowbzcrP0kk5uaaeuZ2N+Y7tzpr65g6WDNbzTv89j2Sy3cxyi5P5uE02op29ua2t43ZTB2aTyQ4TeSdBECj5EttrEIQ2MsnR3lek0ajKDysfEwTV4EkRCx7/93IaWymi8/9eWmFahoFeyacOT38Q7b3I/hUjo9TXNmF7x//tO6mTCkFo8gSR2mvcxdj6H63/f5P4//xJyTRIIIlZL8lnH16Q0zvORj/n88s+zwlit+7/VU//r/p/rft/3huCUh5JJKUs0cAQLMEBTwiE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Yancheng_0 {
            get {
                return ResourceManager.GetString("Track_Yancheng_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp1UFXd+yjwvY8ggoQiJR0iEoKUgMSREpAOBaREQKS74SCgdIighHQICIKAdIkgISndndJdB7gL3vc787u/uXfmzp25M/cPno/PeZ691t77BOBaOEIwBEGnIM7qWeAiwIO6yisTSytxKwsLK0s22qdGtnYmVpbC99m5+Nm57nEKCLBz8nHycLLRijuY2zvYGglbGjnY2+qbs9EqObwwNzGQNXJRszIzshTm5eXi4uc0EuAz4OPl5eW+h3n2LDfOb84uZWRlYWRv68Iub2T3CgOMYzn+8zw4+rYGr0wcjbgNLbCtrI0sLR1sX9hhGOrb65+ddOXKFcTZS7zGBEFCoLY5WAdjXwINwdmDsgAEIQ49EZCkwD9v5+gUARH9+9ZmevoVpBa7r9fMQtd8YPr1u2UU2mgwj/fvufwK4MbB4CV2UXEnVO3Pnv7fVui/xS9yqB6mpa6fecRSV4EPSYBe4oGklAgEvUb+l6z5L/k/jf3nawMhzh9hUBHQJQgDdDB4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Yancheng_1 {
            get {
                return ResourceManager.GetString("Track_Yancheng_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NJvbFsC/UFMRQ5UaQmjRElOIoUKMRc2KlKogDWJIzKTGVquGXvSaemsoV29nLVXVEjEUFa2iA6roYKy5VxNDkBcd3uq766237nprvb+e31r77LP2t79z9v72PucDQAAAMFls6S342FgD2skfTyCaEoODiQQY1BUXFo4nEgy0VeG6qnB1DT09VQ0dDS0NGNQ0MigiMgxnQMBFRoR5B8GgDpE+QXisNY7kTAzEEQwQCDhcVwOnp4PVQSAQmuocW7vs+rq4qgWOGIyLCCOp2uLC/Xew7FxR3/bZ6R2G9cdH4TRPBPMQQ3AEQmSYT/iOE94R3ltO3NzcbFshCioCAJKluyJDzvOwsyYCW4MvDwCwrSWyAe4839JhMNkAke+pjb3qt7P49FKocRwQTAbJLao8kvRYZz2X++6rm88a4Cx5AdEsaVgZZ/63GvgL3QN2rSDAtA3U1PMYZCRsxpqbv26TaQGAJNRP0viT/IvtR22ArxMQGxv7Dg4OTtan4NnJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Yancheng_CH_0 {
            get {
                return ResourceManager.GetString("Track_Yancheng_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV3UJPZFsBDidKRpfcAi/RQQqiGSAsgNaAgSllKhFASCQQWEAIi0gUBAakPhaVIURGUvvJAcKVJld5BWuidyAbX3dm38+bNznvz/uM3c865c75z7z33+875LoACAACckDm1pzBQkpWVuSsag9XGenpiMdIgSxTOG43FwJTACipgBTl5VVWwvLK8orw0SBvv4YPHoWAYFN4H5+AhDTLDO3qgnQxR/lex7igMDApVUFCRR6kqOylDoVCIHPB0F9avi4P1UFhPlA/OH2yM8nalJvvP+/62D50DzskV7YuCOHvSYm+jMBg8ztGb2tnBx+E0iIaGhvI0xQtiAMAlsu3A346lpSIPmE9VIR0AQHlIoARk0v12nKMTSgDbt6PN9g2a6C32sjTOAS6EUQivy1Tz2hyTnzt/i1VJISsFsvTwQ7Lr9+dO/lsL+AstPIBmCpBA8yxC8p+1TAAd8lhHTVdPAwAIgf9JGv8k/+L7/dsAvg4oKCmpqIHAc+RXQUtHT8/A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_Yancheng_CH_1 {
            get {
                return ResourceManager.GetString("Track_Yancheng_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PFb/Hz/+sykrDaShqJTMFNkNUSQJEdlZWdmbllJIZVVWCIWUMopQWdkSMjIio8ge2d/ndb0/t9/te/v++XO/Pa/H83XG5Zxznetc51IIiiDIKvzQkvbDjMGDzjkra3uH4w52dg72gjvOmzs5WzvYy0kIHzgsfEBUTEpKWExS7KCY4I7jrrYurk7mcvbmri5OJraCO866mtpam6mae2o52Jjbyx06dODAYTFzKUkzyUOHDomLkrTfsoH+5MLK5g525i5OnsJq5s5WBExncPvv96w1cTKzsnYzF79kt8bhirm9vauTqTNxycTFhLYQIyMjRtvEdfwIIgtZ63oleA0ODRvt4WAigmAL/hiyN/G/3VlcxZCN/9u1X03fzyj//sZe3I+su4Hyjgu933JxCeaPJ/w3//AaBgQxhE1p3CYeV/ivf/X/byL/zw/rTqTU7ilHaafkvhJhXkRxw1MOxW9IigKCXP2/q/j/qv9n2v9+MPojCokhOBQKCIREKDoG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_YIMO_0 {
            get {
                return ResourceManager.GetString("Track_YIMO_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx5PFT/+zfws8zZRqJUStGiVSJJkq1dfUraUymholSSyK5VCamIkmhfZUmkjRZZWtBeKJWihYRsIb/XObofj999/3l/nt9rruu9nPc5c2bmzGD6EiRBEO34T8zif50o3Cya67Rmg8skl/XrXTZo91u4apPbGpcNpmN0Ro3VGTVSz8hIR89Qb7Sedr9J7us2u29aZbphlfvmTXbrtPvNdrdft8Zhxiqv+S7OqzaYGhiMGjVWb5WRoYOhgYGB/khG3IuKtLiOxSqX9as2b/LSsVzl5iRDP+fRsR+53SYHpzUeq/RXrhdcNq7asMF9k72bbKXdZjtxEs/zlHiIykMIwgT5ifvGEIFGoSTeBJcQBPUngCICSjruTks7RXT7d9c+v3g9y+Lb8y6ZXwjlHeSAXyOu97ZpxbjFv7ljP8oJ4g1PEM/U9WNvN31p///NxP/z3/c7s7LIx0kPyDs3769o/zIp8FSPye3tw+8RxFbz/xWZ/yv+r77/89gQlHRLIlME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_YIMO_1 {
            get {
                return ResourceManager.GetString("Track_YIMO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNT9GsDH0hsRkiX7FmMdjckyITtTUbZIBs0wlmQmw5hkZhCVZWwhEVqQRLxNuoxttCivGHtFoylhbEWGxNBc6n3vee977rnnnnvO/eOe43PO832+5/s85/t9nt/veb5fAA8AAOBusKk3EebdGDxdg0PQGBtMWBgGravsgcJGhGDQ5kYgAxOQwT4wFAoCG4P3g3WVbXBnInFYlDkahYvEIs7oKjvjkGdC/I+got0xoSi0uaGhgYEJGAU19jc2NDSE7Nu2ecruH5uDHFCYMFQkNhrkhIoI5t9Y3x7185wdCKx/cEgUChIQJog5i0KjcVhkBH8AIhKx6SQgIMC7GaIYEAAw29BduLNkQb6NiejmICkEAPCuxvICBIV+psPh8gIkfk9tbOD1UYep/l20cYBYAo/qvB5VDr62Ye/d8dNucnVjMNiQPgVIcfO3ce5/qwF/oVEF8OzMTalnI8ZaT3XVALY8N6Vs+wF3LACAuD8L7U/yT2t//BvAjwkPLy8f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_YIMO_CH_0 {
            get {
                return ResourceManager.GetString("Track_YIMO_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR5UNNZEsd/ATQghxxqPCaCZ1AwmEAIdwgIeCAwCrqMSEIgnJKQQAKRIxmYFVgw6KICCigyLoOKJKACw0BQQEaO4AJyrBdyagwJCIQjkmziMeVObW1NbdX+s8Wn6r1+1b+u97p/364GQAAAyBUorRItFcV2/EhoGInsTI6MJJNMjY4RqdFhZJK9JRxpBUfuRVhbwxFohAXC1MiZdiqGRiXak4i0GGrAKVMjLxrhVFjgISLDmxxBJNmjUEikFYJojQ5Eo1Ao870rlK8YfLwc7kYkRxJjqAz4YWJ0qJrCD6Z/emdVADUwNIxONA+K1CBHEUkkGpUQrRYUEBOgDFJXV1dRpqgLAwA7he2gRWVqqCoOq5WbizoAqCwyVQBr9U/lSOUqwJrPpY309Hm4ve3W440CuimgrZN7ajb5fVB8B32OtfpBsZkqVhfUvLBuflT+31rgdwgaPJpA7ZxmUENtI14+6nymeN0+udzkIQCwMF8t3lfrX3xftAE+HkAqKqpq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_YIMO_CH_1 {
            get {
                return ResourceManager.GetString("Track_YIMO_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx1vBRV3MfxyZ2dnVy4dHdz6S6lu1NQurk0EgpIh4QoIKIgJUgKIkiJlIAKqICAgHR3Svt8zsE/ntfz53Pfr7Pf3zkzOzu7OzN3ZveCoiqK8i8/IsWPq3HTvFHXbkm9K/fu1at3Uv7MzTr169+td1L5EgWLlCpYpFDh0qULFi5ZuFjh/JkrD+w5YGC/TuWTOg0c0K9dz/yZGwxs37Nbh9qdhjTp3aNTUvnixYsUKVW4U+mSHUoWL168aCFTPEpyufCC1Tv17tVpQL8hBet26t/VYNwa9PpxYu36dejabVCnoh172b37dEpKGtivfX+jY7sB7cRM0WhUE6sY5lKUcuSBgX0+tHWKQNxs2q8p2rMRmrJqvyafzvN/NSXhv6d28cixetWvHY5vv6SEo9WsdwtsStf6BdMH/jdvqVbpFeVMSkX5I0PRedueXPr3/5vK//mpUtfb3Wt/wm5V2b3r8qNkVRuk3l+1xqjtlRVlZMX/1bb/r/Z/xv77eb2eKikq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJU_Truss_0 {
            get {
                return ResourceManager.GetString("Track_ZJU_Truss_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1luBPXH/b7eDKTsUwmCe7u7u7u7u7u7sXdoVjRFofi7u5QnFK8uBaX57uG/7mu55yXh8/1y32vNZPJBrZl703rcDocjh/8Eil+KS5ualdr07ZT5+KdO3bs3ClDklotu3Vv27lTwVyZsuXJlC1L1rx5M2XNnTVH1gxJivfs0KNnt5YFO7Xs2aNb0w4ZklTp2axD2+blW/at0bl9y04Fc+bMli1P1pZ5czfPnTNnzuxZvOJRwvbFM5Vu2bljyx7d+maq2LJ7Gw/7/l4/H0du2q15m7a9WmZv0VHq3KVlp049uzXr7mnRtEdTcVIgEHCJF9FI7XAUIE/37DJeclN0cdOwt9vh+jzY5aja223/dr78cDms//3W7l+6Uqn044uhvQ8cxnBnslcZt8dv8JXjcf93bp7uSR2OOBGH40LC7At2f3zw4/9vOv4/v06N/nTQ6Zh4cM/wIQf7JOxQ/ONpo8Sag1OKOxxDCv9fs/f/mv/X3v/zd+Nw2bdO0uVwOzwO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJU_Truss_1 {
            get {
                return ResourceManager.GetString("Track_ZJU_Truss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBRNoy/gbgwgCKioIBlReUWCBAmSRARUkoqACoISJMdlgSUqklGCKEhckiKCBCVKznlBcnQJK0iQKDmd9v3er+rcU/dWnbpV5/zF76mZnprp6ume3dmeHQABALsof8o/OUyGVlp3TEytrOWsLS2trXjYNY3sMKbWVlIifIJifIIXBcTF+QREBYQFeNjlsBb2WDsjKSsjrL3dYwse9ltYfQtTAyUj3F1rcyMrqUuXBAXFBIzERQ1EL126JHTxwJ+z0P3dOJ+ikbWlkb0djk/FCGOyH+0nd/jXeSgf2xmYmDoYCRlaHrK2MbKywtrpY/YbPrZ//KcSBQUF2Z8uHuECQBKVLVibF4f2oQ3aP6slFgDINjzIwATLv4azuUsGjv8zNFJnj6riZMfRsh/gyHN4ep63kElnCx3P/Keu2CLq3nu00c4iFFey9mP3/7cE/yXXVKirLRuOV0NQXTW+fEz+FkOD/HXPMjkAnsr8p6XsPy3/x75/fzaA7O81RCUZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJU_Truss_CH_0 {
            get {
                return ResourceManager.GetString("Track_ZJU_Truss_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBTbngfw0wgKiEQzSJCo5AzCgIgKghIEASWDQ04ShCEHEVEBAcnICKIEBa4il8ygJIkjguQgGUkDkhmY2eN992293dqt2tqq/WeL76e6f13dPd2ne7rPqWqAAADIML/r79BRwJnhTTt7F1dVV2dnVxchTgO0u4e9qwtKRkRCTkRCTFxeXkRcVlxKXIhT1cvJ08sdjXJBe3m6WzoJcep4WTnZW2uiMfqujmgXlLS0hIScOFpe1lpWWlpaUozq91lY/jq4iBra1Rnt6Y4RuYH2sKOE6w/d/8d5aC3dre3s76Ml7zrTuLqhXVy83K08KO9aelr+3omampridxMZ+QFQhLXdy+0pzQG4wPB7pn0KAIqdIAqgeuofl0MkU4Cjf1/aZHevltrPLibcFGAMQ84uC5ezmuzC7Yf/3lcuAzbvMVz4dkYyo3privy/reA/pe3Rdh0CoutqwoLrfM44qW61M14uqItVBSBY+V8m3L9M/2HdP/8bQPHXHIGVAhwA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJU_Truss_CH_1 {
            get {
                return ResourceManager.GetString("Track_ZJU_Truss_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLxlFBTHFq7dMtM20j3dCTKDhxDc3d3dPbgFd3d3J0BwgkMIDsGCu0twd3eH7+nm/LjfXevyrF3vu3ftrqquPiSQcCKIgiB844er7o+gxFC9couWbdsVademTbu2aZNUb9qxU8t2bfPlSJ85V/rMWTJlzJE+S8aMmdImKdKldecuHZvma9u0S+eODVunTVKxS6PWLRuXadqjarvfmrbNly1b5sw5MzXNlaNxjmzZsmXJ6Hc3cby105do2q5N084de6Qv17RTCx91tev3bYyGHRu3aNm1aZYmbfR27Zu2bdulY6NOviYNOzd0mzRNk9wTWr8IQl50wpDOY3UZY7pDmR2iIH3sJwkFdnx/n0/fJOGH/73Z7TPny5d4cDqy445gDRKTPU+3OVb3M/Pq/3pzbk8gCO0ignAqYZbZ297f+fb/Uq97+IKdLVz9ZUdB6Q73127xzpQ6ecEdBYX/64c4vMRecW7GPXWfhvem+KVcMXF1y2Jv56wpJgj9C/wfseP/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000L_0 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000L_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJoHXI/92/fP9ROiIqm0KSFKpb0kJCOykhaSkPbWQmgXirTNKCpp06C9F+2991ZpP8d5Xtf9v5/7fl5P7+v4Hp9jfMfv9+v8KhcERRBkFb5IT35twGC4ePbmLVMzFTMTEzPTvbwXDS2tbpmZKkgJi8kIi4mL7pcSFt+/X3Qvr4rNHWsbS0MFU0Mba8urd/bynrG5dueWwQlDh/NmxoamChISYmLSooYyUgZSEhIS4vtp5CbM1NrCqoZmJobWlg7CpwytbhKQp7P9Z5v1Vy0Nbt6yNRS/brLOzNzQ1NTG8poVcf2q9VWyae3atRh5QiZBBJEH//SRtd86HAQjObxwQBBswRVDvBz+eTWLqxiy5d9X1vO7Xl118Nem7F6EyQ3dPrEvnUNnCepn/+2Vvk1DEBE4Sg2XeETm397V/59faM5+XGPl/OMzvU5jgWPkQWr2x+s/nEjP63MQ+V9fKGKei3Zsz0PvFeeiiMBh9J6jCvqjQwVB7in9X5b9f9n/yKHU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000L_1 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000L_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dV5NJT7Hwfwz1hCiKLcGhEpdcl6bTeMUmkRblolheaXuZZhxpplWpSEFDeRZSKhLJNcMVnGTaibpY1EyL6NkWFMjGl+X9X9nfu759xz7vmd8/vP+3We5/OcZ77n+zzPPM/3+wUMAAhQ5ut8pITQ7uA+N4IX0ZLo6Un00lxzEE8iE4heZkZaeiZaevq6OkZa+jo6upprLP08fP1IeDMvvJ8vydlDc42dn4sHwXUPPmg/0R3vZWZgoKdnrIs3MXI1MjAw0NcRnb+I3Je+tazwRE+8LylIay+e7CaCzov5f73MYmeSqxvBH69/0lOC6I338vIjuZBFTjr7Os83EhcXF5q/Q1l1AFNUr13wvSIhjA5k5nfhkgBCsxQhCJT8+jQ8gRDIf3uyvjdvbayGXy9l9IPseYzqx010rOMc+t3iW1vjJej2HNDBq9X6aRWf+gX/a4W/BHPJqgZzS+eJI2tJzXr1vdsx9wnbp6kPtgOcwf1pY/xp+69z86/nS0dCX7tD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000L_CH_0 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000L_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR5MNvpH8e/ibaUVfS0LYteqVYRR10R2pTYdRalWupqllSbaIgIkeglta2WbSt2rbjSWnpgtVUbxErrKrKOitYRJWRJhQoqrvyC7s7+OrMzO7+Z339eM8/n/czzfOa53w8AAgBAKmNJl/gCLAte7qFoDBaBPX8ei9HT9kLhItBYjLWZvpGFvpEx1NBM39jQEKqnjcCfi8TjUNYYFD4SF3hOT9sNH3QOHeyIInpiw1AYa1NTIyNzKMrCLNjM1NTU2HDt0iSblsfWR6Kw51GROKK+MyoidI2sXT5qZRrFQFxwKDoKZXzm/HpsOAqDweOCItacCYwMXEpSUFAAL61QFQIAMJmmXI28uV5OVlFZCngFAADPUsAAWmFlN3NSMLD508747VwX5HCbGmsQUL0M2jl+sGyH77ysH/op15wvC06y0qppTK+YGZT+rwp8BggIZ4P6dr4AxdezQcCeo6D4WASoqg8BAPE2fyusv5X/alu6nk8DLQUwWG7N2rXrZEex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000L_CH_1 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000L_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLxlFBTHFq7dMtM20j3dCTKDhxDc3d3dPbgFd3d3J0BwgkMIDsGCu0twd3eH7+nm/LjfXevyrF3vu3ftrqquPiSQcCKIgiB844er7o+gxFC9couWbdsVademTbu2aZNUb9qxU8t2bfPlSJ85V/rMWTJlzJE+S8aMmdImKdKldecuHZvma9u0S+eODVunTVKxS6PWLRuXadqjarvfmrbNly1b5sw5MzXNlaNxjmzZsmXJ6Hc3cby105do2q5N084de6Qv17RTCx91tev3bYyGHRu3aNm1aZYmbfR27Zu2bdulY6NOviYNOzd0mzRNk9wTWr8IQl50wpDOY3UZY7pDmR2iIH3sJwkFdnx/n0/fJOGH/73Z7TPny5d4cDqy445gDRKTPU+3OVb3M/Pq/3pzbk8gCO0ignAqYZbZ297f+fb/Uq97+IKdLVz9ZUdB6Q73127xzpQ6ecEdBYX/64c4vMRecW7GPXWfhvem+KVcMXF1y2Jv56wpJgj9C/wfseP/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000R_0 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000R_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLsHXE9v/P999jkfo2wZlb2VJGnbe0dGEZKQSqWMlr3JLEVlzwaSSgstRCGVhgYNtPeu+3WO7/9///7/+3H3dF2v13tc17nOyefgy5cgCYLoxJeo4lc3CpPRyu07rG1m2VhZ2VhPGGJkbme/w8ZaT1NlspbKZHW1SZoq6pMmqU0YMsth1x4HO3M9a3OHPXabd00Ystxhy64dZovM96+ysTS31tPQmDx5mpq5lqaZpoaGhvokVrxIb2lvlXnmNlbme+z2qywxt9/OIM87/rtMl812Ztt3OJqrb7WS2ew2t7Z2sNtiz2zdvGez2CQIAiWesMdogtCFXjy257yMhpEXp1exBEG1uFFEYOy/u2ntpIg+/91Z4beMpfP+pPaMKSJ6HCGHVU0MH2TShrrjf73TpssIYgZPEF8V1X2jmoo6///0X7vra/+uJpkJTn7Tw5N+drs/cdtrZzE95Ox04v/6IomRcWT+sDjy4PtYktg9izzoNIt8nT+LIA4a/I8R8z/G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000R_1 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000R_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dV5NJT7Hwfwz1hCiKLcGhEpdcl6bTeMUmkRblolheaXuZZhxpplWpSEFDeRZSKhLJNcMVnGTaibpY1EyL6NkWFMjGl+X9X9nfu759xz7vmd8/vP+3We5/OcZ77n+zzPPM/3+wUMAAhQ5ut8pITQ7uA+N4IX0ZLo6Un00lxzEE8iE4heZkZaeiZaevq6OkZa+jo6upprLP08fP1IeDMvvJ8vydlDc42dn4sHwXUPPmg/0R3vZWZgoKdnrIs3MXI1MjAw0NcRnb+I3Je+tazwRE+8LylIay+e7CaCzov5f73MYmeSqxvBH69/0lOC6I338vIjuZBFTjr7Os83EhcXF5q/Q1l1AFNUr13wvSIhjA5k5nfhkgBCsxQhCJT8+jQ8gRDIf3uyvjdvbayGXy9l9IPseYzqx010rOMc+t3iW1vjJej2HNDBq9X6aRWf+gX/a4W/BHPJqgZzS+eJI2tJzXr1vdsx9wnbp6kPtgOcwf1pY/xp+69z86/nS0dCX7tD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000R_CH_0 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000R_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR5NNTrH8e/tFgbihIR6Sdx7duQGWMriSwRcScumoYwk1ka26A0qSjixriyZUtCkSbLmIos2RIhe8ouawwzZuaH3Hvu755zz7nnd87v/P7xOufzeT/n+X7O53me7/N8PgAXAACcNdZ1HUHuNedwxtMLhTZB+/qiUUoyDggM1guNgoJVNPRUNDTV1cAqmmpq6koyJngfHB6DgKIQeBzGzUdJxgbv7uPlYYEIsEd7I1BQbW0NDV11hB7YA6ytra2ptmN9EZGN3CpmCLQvAocJUDmNwHpuX5vnufJjGX43jIen1xWE5gVfPvRlBAqFx7hjt19ww7mtB/Hy8nKv71BYHgAga3qPhLvLt21tILTuxngBgJsRyg308v44DZPDDYhunuxre6eV2XjbbtowIBzOJTurXHoAvrr2PXMzVndpzZ1Zsw9SminU5WHOf6vAX+AC5Kq5BmWrucLqq7iAyyZcYUEmXK8GTQAgDPYno/3J/mNu/Xo2E607bu5t23fs2Ln2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUg6000R_CH_1 {
            get {
                return ResourceManager.GetString("Track_ZJUg6000R_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx1vBRV3MfxyZ2dnVy4hHQ3XLpL6e4UlA6BSyOhXKRDUgERBSlBUhBRCZESUAEVEBCQ7k5pns85+Mfzev587vt19vs7Z2ZnZ3dn5s7sXlBURVFe8iNS/LgaN80bd+ue1LtK7169eicVyNK8c7/+3XsnVShVqGiZQkWLFSlcqlCxwoWLFMhSZWDPAQP7da6Q1HnggH7texbI0nBgh57dO9bpPKRp7x6dkyqUKFG0aOkincuU6liqRIkSxQqb4kFSymUXqtG5d6/OA/oNKVSvc/9uBuPWoFcPE2vfr2O37oM6F+vUy+7dp3NS0sB+HfobndoPaC9mikajmljDMLeilCenjxkwxdYpAnEz4LCmaE+SNaXbYU0+m6cvNSXhv2d2/tCR+jWuHIxvvaCEo9Rstwv+kL7NM6YX/m/e0q0zKMqp1IryZ8Zi87Y8uvDy/5vK//k5Md3buftkws7RyT/t2Ho+RbVdqfZW26XtqKIoIyr9r7b1f7X/M/bfz6v1VElR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUs6000_0 {
            get {
                return ResourceManager.GetString("Track_ZJUs6000_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1luBPXH/b7eDKTsUwmCe7u7u7u7u7u7sXdoVjx4u4Ud4oXpxQvrsXl+a7hf67rOefl4XP9ct9rzWSygW3Ze9M6nA6H4we/RIpfioubWtXatO3UuXjnjh07d8qQpFbLbt3bdu5UMHembHkzZcueNUvuTNmzZMmaIUnxnh169OzWsmCnlj17dGvaIUOSKj2bdWjbvHzLvjU6t2/ZqWDOnNmy5cnaMm/u5rlz5syZPYtXPEjYvnam0i07d2zZo1vfTBVbdm/jYd/f6+fDyE27NW/TtlfL7C06Sp27tOzUqWe3Zt09LZr2aCpOCgQCLvESGqkdjgLklF96TJTcFF3cXB3pdrg+D3Y5To9027+bLz9cDut/v7P7l65UKv34YmjfA4cx3JnsVcad8Rt85fj0/52bp3tShyNOxOG4kDD7gr0fH/z4/5uO/8+vb6HPh7ammXhoqK/foWiwffH5O40S6UrMKO5wDCn8f82+/2v+X3v/z1+Nw2XfOkmXw+3wOLzw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUs6000_1 {
            get {
                return ResourceManager.GetString("Track_ZJUs6000_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFT/w8Dxz0f1tZVRKiHZUxGGZB+VCilEUoTsW9ZhLJlRX1tlS9myFykUZZdlKmSJUdlCyDrZGfv+fPp+f79zfs/vnN85z3nOec7zj/fr3Pu5Z+6dO3funRVAAMAm6vf4u510aHZVx8bW0UnFycHByVGU96qlK97WyVFJRkxSTkxSCishIyYlIYEV5VVxv+Xm7mqp5Gjp7uZqekuUV9vd7JatuYal1xUne0tHJWlpSUlZrKWcjLmMtLS0lMSO3w/C9te+xVQtnRws3Vy9xC5Z4m22o9vpCX8/DJOpq7mNLcFSysKB0cnZ0tHR3dUMv93C1M3090YMDAx0v4+QVRgARTRGBLiFMW5DC5jfs9X9ANCt+NKBqf1/P5vVTTqw9x/PbLClXVN1pHk3eQiw+kH+6eMlXDfW0Pqif2wrS0OHl44WvnFLJZUvDW3+b0fwb/2I2FVV0723yt/3fSV5cM+56n1156rpKlUAuKP8LxP5X6b/dtvvy/PXjuj+mkM0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUs6000_CH_0 {
            get {
                return ResourceManager.GetString("Track_ZJUs6000_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NFXdwwfwvZWUCj2SZLiRMkYI0eUqiQiZM2e4hnDNmeJWChmSzDdTqaRCkTn0hFDGQqaIXFNml+sa393zPL+13vdd613rt971vv/5ftY++6x99jpnn3v3OWcDCADYRPld/84eOrQx1HVwJLgqu7q4uBJEDxviPTwdXQkKsmKScmKSUhInZMWkTpyQED2s7O3s5e2BVyDgvb08rJxFD1/ytnZ2tNHA++m7OuEJCtLSkpKnJPBysjay0tLSUifof1+E9a9zi6niXV3wXh5+Ypp4T4ftqJ3h2t+XYbTysHFwvIaXsnXZ5eqGJxC8Paw9t9taeVn97rRz50663yNkEQAAi+qYO173dm1DO8y/N9WsANCtEOlAMevfd7O6SQf2/3Nnw+3ftFTHv+6rIgOWYMg3e7yU02wNHSf+0/dUGhpeONr5wi2VVrFM3vzf1uC/ZX3fSnWh4L3qmzv8qw/sdlJOLWU5J3wuXhmAG7j/VKr+U/kvbb//nr9ORPfXFqKa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUs6000_CH_1 {
            get {
                return ResourceManager.GetString("Track_ZJUs6000_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJwFVFZd2613dwomBtgdIGK3YiC2qJgoKkgoYnd3t2J3F9jdYnd3Y7eoyD/Xej1j/OeMcbjGvea851p77wfe8fnB86y9GZZhmHR8ESVfBoehRZNuETGxNWKjo2Njinq3CI/rFREbUymguG+54r5+pUoGFPcrWbJUUe8avaPie8eFV4oJ7x0f1zGqqHej3mFREZ3qh/dvFts9PKaSv7+vb9lS4eUCOgX4+/v7lRTJRTzouYsHhsdGh8fH9S/eILxXNwG53Oe/y2gd4zp1i+gT7tc5Wo3tER4T0zsurJfQuWN8R7JIURSOvEKnAMNUhE4fHT9F5WFsMlzmeYb7NZRjTvA8/W5+p3OM57/v7Nm1m8GBr6+6h54zzkg298die7za/MH85H9ryx5xGearzjBXcvgtPvDzefr/T8WJwmrx7aTD9CjvjVWpPmp/mP4IB62oyvw/XxeCXh1jmAlHr1bNePzC2xc12A6ra7KNtFoMM6zK/6pD/6v+r+z//KdhODqy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUv2000_0 {
            get {
                return ResourceManager.GetString("Track_ZJUv2000_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bxnWBRL1+/d3aOiIqAiAiKgoqCSQXJSUYKKqKiARIkqCJIzqCigJDGA5K0SJAiSMyggQcIoOSNxyEPOA++a2fu+z3M/7znXc76dL6wfVeu/1qqq7uouR2BfWwRFEGQTjOzJtgeD7vaNe/ctLOUtHz60tOA5ctvY2ua+pYWMGJ+QBJ+QsKCAGJ+wgIAgzxF5O3NbO2tjGQtjO1vru+Y8R67ZGZjfN7xs7HTT0szYQkZEREhIXNBYQsxQTERERFhgO/ki9JS1+RSNLR8a21o78akY29zbBnkq+78vs/uuteG9+/bGwkYPd1k+MrawsLM2sNlmdNf2LnnQzp07MfId7uVCEGnwQc9tA3bhQNCRO42LCIKtemDIlYt/72ZtE0MO/LOzwabWq4qjjftKhpC9nuixad48Fu11cv2fseInYAl/WLyBVTiqaHlo8//k/x5+81u0/49ek7mnZ/+Omb5RHqFGyD/x/zL0sVJZWChDGfo4uQxDus4jjznkNzffnUeQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUv2000_1 {
            get {
                return ResourceManager.GetString("Track_ZJUv2000_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBTLogfgbtRDUEFFRAVBREEkiySJigoKgiCCIkFEgqQlrWRWRQT0CCgoQWBVkoCKkjMqSSWK5LAkyUnYhYWNrz333Kr77qtb9epVvf/4fTXTUzNdPT2hZnoGQAAAE+V3+TtbWNDMxMjhpitGC+PignGV2G9i6+F5E+Oqpih1VFnqqJysjKKUnIyMrMR+LayzF9bDVs3VFuvlYe0ssf8C9rrzTRtdW19jjJOtq5q8/NGjSrK2yoo2ivLy8nIym37vhPuvtqW0bTEutl4evlLnbT0dNqL1rLf+sRsOaw8bh5u3bOVuuLBj3GxdXbEe1z033rD2sv5diY2NjeV3D7eJAqCKyschXhHsG9AC1+/ZM14AWCg4FvCA9x9HQ2WygJ1/H9nP9i597akf26vGwLZgeOCXZAmfOQ1tN/q7rhIHavgdWmjbJ5dcsTrG/L+W4N/SrDdZDcCDzz80eWqaZ8e14LX0U/ACx2kAbmv8y1T1L9N/W/f78vzVEMtfc4hK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUv2000_CH_0 {
            get {
                return ResourceManager.GetString("Track_ZJUv2000_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZR/NNN9G8e/lh5EzY+6J+VHP1UYtjQqhpHKjaKbm2RtWixszBajmWikuv1IfizKU8kKC3FXM2sKE5GS4kHpiZbancxKZmPPpnrO/dzn3Ofc5znnOc8/Xudc1/X9fL7XuT4/vtf7C6gBAKBQoooqdEBK5+8bjicQUcSoKCLB0swfR4rFEwmOCCjMAQqD29ogoHAbG1tLMxQlkkwh4RwJOAqZhIm0NNtDwUbiQz1x1H3ECBzB0c4OBrO3xTkgQhF2dnZwm4WqRQzmakM9cMQoHJlEhXrhYsPVlfMaR78uswhDCg3HH8XBD0VpEaNxBAKFhI1VP4QhY1RJmpqaINUOdc0BYLsy5jDImVoLlA9glevXAADQNB0EPNL4ehqZAgQs/XaykZ5eb493T/X4bwDdVLXV41acFcFy5fv8b7n2HUrnprRuY/hF3tQbxX8bgT+glryz6TxzWZNacmUTCBh0BZLXoBSKPFcASEb+zvi/s/+YU32er4XmHAi0QH3hwr8p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Track_ZJUv2000_CH_1 {
            get {
                return ResourceManager.GetString("Track_ZJUv2000_CH_1", resourceCulture);
            }
        }
    }
}
