//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_UR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_UR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 7bp1UBfR//+7SyiKgghKN9Id0qAgIC3SjSDd3SAl0irSJUgoKSBdIq1091u6u4Q3cQ98Pt+Z3/3NvTN37sz9487wfMxrn689e/ac8949Z3eHAYIhCLoAuvRL3UEBG/WXZuY2tuK21ta2NswUasYOjua2NsKPWTn5WDnZOfj5WTl4Obg5mCnEna2cnB2MhW2MnZ0cXlkxU7xwNrQyN5I1dlextTS2Eebh4eTk4zDm5zXi5eHh4WJHv+wF96pxViljW2tjJwd3VnljRzM0UH7T5T/93H7lYGRm7mLM9dr6lq2dsY2Ns4OhI9rrV06vLithYGCgXA7xHh0ECQHvcrYLv4UKEuzLjS4XBKGc+KJASlz/+TnICxQI778/bX5wREFqZQCnYQG6FwBTbbNUEeucguOE/63LdwKGpwCin5Qrte7fwsX/W4f+N2Vtx/ySJY79pf26pi4SP1Ysi7xSzOgegRgEvRH9X6Lhf4n/U9n/3BsI5WoLA0eBUCE0CB2ACuIG [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_0 {
            get {
                return ResourceManager.GetString("UR_UR10_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNx3XE/vHz/+s6c9Ckk2JStCUbaEzDIqW6g0SEVUtsjehMyshhQRlVG2QkilQlqkKEkov8d13p/v7fb9/f78db9dr+fzus5+vc64zut1oGiKov7hj0TyV4/By7TJi53dPYZ7uLl5uBu3neq0zMvZw92iXw+TAT1MevU2M+vRu3/vvr2N2w73XrLce5mThbuT9/Jlc5cYt53oPW+J8/yxTittPVyd3C1MTU1MBvR2Mus/v7+pqWmfXjxZSlNt5j2snDzcnJYvW9nDxslrMYd20ee/5Shzl81f7Ozj1GeBm+zh6eTu7r1snhe3YO7yuWQkSZIYsoqNulDUIMRn3p7bZBZJQ/Iyw5KmmN+BDGVj+d8G/fnHUM3+t2mfXmWMtypJb5xUQDVaT7f/1v2GnuNfDG/+v3EHFKsU9VCiqJf6fY4n/Cr49/83Uv+fP/nYgbtRU8PvbmzVYliYxcFh1s8PDDs6atpwiloz+P8qSf9X+X+1/Z/PhmK0V2wisNR/zRzF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_1 {
            get {
                return ResourceManager.GetString("UR_UR10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNx1WBVP2DfwzdnetQsVuxtRDNSf3YXdhYoKGCgqdiF2Y3eg2J1gIijYit0FNgoG9Xxn9L2u533/fPlcs/c9M7uze/bsOWf3BBzPcVwm/mikf6aASef2g338/Bv4+/r6+5Ur1Ml75Cgffz/PahWqeFSoUqlyjRoVKlevXLVyuUINRg8LGD3S29PPe3TAyL7DyhVqO7rfMJ/+LbzHdfAf6u3n6e5epYpHZe8a1ftXd3d3d6sk07VkZ4NXaOLt7+sdMHJchVbeowZLaFfG/F2P3ndk/8E+Y7zdBvhq/sO9/fxGj+w3ShrQN6AvnUlVVYFuYpaSHFcbMW708HmaiMShk947eU74M1ngvHb+vUGpmQKX499Ne30nvnWThNtZI99wWabzRb6WP+HSIw39Lv/m9RCzcFxrg+NuFXBbf+bXm8z/38j9P38z2oWeP5U07ULJNu3r5/waWv9+Zvj5zWWbNuS4KXX/V4n8X+X/avs/9w0nsCluIoicxMlAOIVTQeN0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_2 {
            get {
                return ResourceManager.GetString("UR_UR10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNx1dNRO2C/wuEw8i7u7u7sUdymFIqV4ixUpxVrc3d3d3aG4u7u7u7/fGX73nPfeP28/Z/I8mchOskk2yWbL8RzH/cUfjfTPFNBpVLdd+8jO5TtHRHSOzJGmYXi37u07R5YslCtfkVz58uQtWjRX3sJ5C+TNkaZ8j05RPbqFl4wM7xHVrWWnHGlq92jVqX1YtfDo+p07hkeWLFgwX74iecOLFg4rXLBgwfx5ZPoqATbzXJXDO0eER3WLzlUjvHs7CfVqz3+vQ1p2C2vXvmd4/tYReucu4ZGRPbq16i61bhnVko6kaZpAm+hm5rgSiKd7dBmti0gc2vlSQeCEHwME7kUFgS3Oz78Cl+C/RXt06WrNys8vevsec+4gPt27nDuSN/2F4Rv/G7fIhkQcd8zmuAsp88/d8+3x3//fyP0/fx/fdY6/N/9ZfNey2Spk3RtZbpWwoOyzwysqcNzA0v+r7Ptf5f+q+z/vDfevnTyiwImcxMkgIVNAQlFB43SOgMGZ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_3 {
            get {
                return ResourceManager.GetString("UR_UR10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNt3PJX/Hz/+a48jaS9JaWihQYrwLpVU0lSStCgZlVWUtHdaSsloKYRShDIaQgolNLQlI6NEIvF9XFef3+32/f3+/LnfXtfz+Xpd85xzndd5vQ4IkiCIdvxIUfrpQGGxaN5aR9f1putdXNa7juxvZe/m7rje1Wic9pjx2mNGjZ4wQXu0/mjd0SP7m3o6e3i62Ru52nt6uK1wHtl/judKZ8dVM+29F6x3snc10tMbM2b8aPsJ+qv09fT0xo5ipbN0lQ+ubWa/3sXew81b28LefS2Ddt7r33kUK9xWrXX0sh+72kVcv8He1dXTbaU7s3qFxwppI0EQKOkSO2kSxETEXM8Nh0UaiYq0WKlEElSLH0VYKf17QH/aKaLb/x7al8KXs80qX3ROLyM67SI1vmslqy5txfp+/9t2vIeCIGbxBFGgNjY09XdZ+//fSPx/fmZoGz1wfzz34cy64Cmpp/Um3zQseTAi/doUgthu8n+V9P+r/L/a/p/XhqDkJR4i0ARD [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_4 {
            get {
                return ResourceManager.GetString("UR_UR10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNx1WBRf/C/w6Z6xW8DCBBsUVFAMMLERQREUQURQBBFQsANFBbsDExvEQJGvHWBhIXZgYCOimPd9xt99nnvvn5fXc/bzmTNnYncnztldpWiKov7ij0TypzF48OgfOCYktHPouHGhITa1BvuHTRwTGtLBvmnLtk1bNm/h4NC0RZsWrVvY1OocERweEebfIcQ/IjzMN9imVt8Iv+AxI3v6Rw0MHesf0sHOrmXLti38HdqMbGNnZ9eqOU+2UsFceVNX/9Bx/uFhUU17+08M5FAvTvq3HcU3bGTgmEn+rUaNk0PH+4eERIT5TeRG+Yb7kkaSJDFkF8s2oKj2iFcixi+UWSRlyMOiUTTF/IhjqBmj/j2hn38ZquL/PLUXt+72cX1zs1xWAVV2Jl3nk+2xGt6/ML/H/7Rtu9OgqGiZonItWm3I/F7w9/83Uv/PX8Ey+9PvN/qe2Zqxu0vAPHuXEam3T0uWR7tQ1DTn/6Nk/R/l/6r73+8NxZiPeIrAUhzFA4si [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_5 {
            get {
                return ResourceManager.GetString("UR_UR10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dl3UBTftyDwOwRBEBGJggKSc845g0gGBRREJOcwDNlBQAQkiyIgUTAQJCqCJEGSSg6O5CgDkkVy2gvf32/r7at9Va9e1f6xVZxPnTnn3r7T3cPY3RQCBADgCMZxPY5zOPDF2MDewdVN2c3Fxc2Vh/GmjSfSwc1VVoxPSIJPSEBQUpJPUFxQRJCHURnl7IXytJF1tUF5eVo68zDqoe45O1hdt/EzcnOycZUVFRUSkhC0kRS3EhcVFRUWwD8+CvnJzvnUbdxcbLw8/fi0bZD2eHCewPuf4xBZelrZO3jbCFu7nHVzt3F1RXneQ+JZW3pZHi8iJCTEOT7FC+wAyMDagXKPPosLG9LjF31GAHB2g3CAKuM/H2fvCAdQ/OujzfRjdNTn+8jqf4ELoQimVd4qOrN9uJ3kX2sl9OHptcCm94pwRu32r6P/aQX/KcYTxRpVLz74sjJcqLJ/XUxpMdbyC4KxUgWAB/L/Iev/Q/4fc//+bgDOySsCVpyTES50/KPD [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_6 {
            get {
                return ResourceManager.GetString("UR_UR10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTbngfwM4AKpoGrgmQEJCiCSA5DVEBQsoJKkCSSc44iQSQMSRCBAUSCRAVRMihpkKQSJAkCQ84MDDKE2eO99229fbVb9Wqrtmr/4Pup7t+p7q7Tp6enT1cDBACABPO7/s5xMrjS035oZe+g6GBn52DPx3bbwtnFysEeJcp/RZz/ymVBCQl+QTFBYUE+NkU3W1c3ZwuUvYWbq7OJLR+bppuprZWZmoWXroONhT1KROTKFXFBCwkxMzERERGhy4d+n+XUn53zK1s42Fm4Onvx37RweUgBtx9x/+s8R02czR5auVsImdtROTha2Nu7OZu6UJibuJr8PoiSkpLs9xCpuQGQhrXTzTGSihw2kL9X9KcBICMGkIETp/+6nB0SGfi7CXC939WV53po6qcA9WME++qlSkaDXbi/79Rf+8X54PDMYeMbsxCm9tcU6X9bwb8kZ/XZJzXGxE/3zKtro+kSFbJZKxTMqM8qABAo+09L/T8t/2XbP+4NIPtzjYCV [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_0 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBRNgwfgXlBRgoAgIBkDSdKCJAHJQSSD8AIqEpacYclBQEFQAREJAoskESSoiEjOkkEBCZJlWXLOca99Q9V3X91VXV3V1f3D76np7p3pmunZqemuAQgAAB7md/07pASwMNCxtnF0kndycHBy5GHVR7m62Tg5SonwCYrxCQogxcX5kKLIa0geVnm0vTvaFSXliEK7u5ra87Bqoc3sbcxvobz1nOxQjlLCwoKCYkiUuKi5qLCwsJDAyd9Xofrz5HzKKCcHlLurN586ys36BNxP5PHXdYhNXc2tbTxQQhYOZ5ycUY6OaFcztxMWpu6mvzudPn2a4PcQKTgAkIR1B9r56RlC2CD/XeCpASDYCyQA69R/3c4+ngD83QTY3n4N5dkeyuopQBGCuLjCW8pw5wAeL/+7gxgPHJ4FbHQzCWEqd6bw/9sa/Ften4mvK9TPqztNRyfXTx8v1/QhXq7D0EAegAfS/7JV/8v2n/b982wAwZ8lAtYEgBCcACehU4AI [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_1 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTbngfwM4CikpUokpMSJUoaQEHBwBAVTAxIUtKQhiBJQYIiCCKSk4BkUFC5hCGrhCEjeUiSozDkuMd779t6+2q36tVW7R9bxfdT3aer+1T3r7urz6kGCADAAczv9ncoSeDKQPfhIzuMKsbWFmMnzHnL3NHpEcYOKSMqISsqcV5cTk5U/IK4lLgwpyrWxhnraI60M8c6O5rYCHNqYx/YPDK9bu6uj7E2t0NKS0tIyIqby10wvSAtLS15/sjvq5z68+Si6uYYW3NnR3dRTXOnh2RwP7nLX9c5YeJo+vCRi7mkme1xjL25nR3W8YETmZmJs8nvTseOHSP5XSKtAACKsG3G2r88Tgo3aH6vzjEAQLLtQwLYGP66nZ0DEkD/962Nd/Wg1Gc66SonAK0fgvuXSAnrvV14fOLvDrLCsDwzuNHBJpmI25w4+N+24F9iSB9VU7biWzuwgbpklxh1iWk9q6ZKTUMNgCfK/7RU/tPyX/b9490Akj/XCNiSAFJA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_2 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTLgwfwXkABRRAQkJyjsLAIkkUERECCKKLkIFnJSxZEJKMgSlKCPJQkIChBMgoSJEkOAkvOsMCSlnjte+939btf3VX96qrunyu+n5rp2ZmumZ7pne4agAAAHMH8Ln+HjACu9HRsbB0cFR0fPnR0EGS7Y+niauvoIHcJKSqJFBVBSUkhURIoMZQgmyL6gRvaxVLOwRLt5mL2QJBNG23+wNZC3dLrtqO9pYOcuLioqCTKUkrCQkJcXPyiyInfV6H+8+RIFUvHh5ZuLl5IDUtXGyK4n9j9r+ucMnOxsLF1t7x4/yGpo5OlgwPaxdyV6L6Zm9nvSiQkJAS/m3iWFwBZWLahnSJJCeEGxe+VOg0ABLv+BECe5q/b2TsiAOf+vrWpnn5NlfluypppcDYQwbEqVMZouA+PE/9dV1IQNu8+3OhivphStTN99L8twb9Ee9jxGxnh/DdnBQGlPA7Hqx8I0hS8C7OVAHgs/09LzT8t/2XfP/oGEPy5RsCSABAC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_3 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBRNgwfgXlCCIkmUoARBQAlLZomCCUTiCyggAoIsQTILC0sGFZCoIAISVZAoKhjIIKikJQeJi2TJYUlLvPYNVd99dVd1dVVX9w+/p2a6q6drpnumpqcGIAAA+zC/y9+hIYM7A10bW0eny04ODk6OQlw30a4YWydHRWmkuAxSXFRMVhYphhKTFBPiuuxu7+builZ0RLu7uZrbC3HpuFvY295VR+P0nezQjopSUuLiMmJoWdRdlJSUlITo4d9XOf7nyZGqaCcHtJsrDqmJxtgcgu2U2L+uc8Tc9a6NLRYtYelA7eSMdnR0d7XAHLI0dzP/3YmKiors9xDp+QFQgGWzu3MENTms0P3ebTIBQLblTwbmmP6azvY+Gfi7Csa7fmipTncyVE0A+vsI7iXhklO3d+DxD393kBGCw7OElQ52idSKzYn9/20J/i3XkYo1XZF/1KovJl/pipG6VCg/UGNQlXcFgAClf9mq/mX7T23/PBtA9uceAUsyQA4OgcMQ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_4 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd5NFXvvwfw50SEpAyZhzJLhjjmISkSQqZEROYxjjEOmiiRmZNMURmSQoaMCeFrSubxRJxjPnHMHO7T9/v93fW7v3XvWr9117r3L+/X2s/nWXs/a+/nnL32s9cGCADAPszv+jtHD8HG9Jqjk7uHuoebm4e7KI+JnRfKycNdWUbsnJzYOQlJeXkxSVlJaUlRHnUfV28fLztldzsfby9rV1EefR8bV6fb2nYBRh4udu7KSOS5c3KSdvKyt2WRSKSUxOHfV2H48+RimnYebnbeXgFiunYoR3K4n9L3r+tQW3vddnTytZOydaPyuGPn7u7jZYMit7X2tv496MiRI4d+T/G4IABKsHb43ImkIoMdut/NJCMAh7ZDDoF+xr9+zs7+IfB3F0z1DlzVnO05UTcNjj9AnP519hO7xS48nv73ADlROD1b2PnOKZVeszm9/7+t4F8ipyT7ZTHDuuFV5duLDo9lLtwq7vtyiqviIgChqv+01f3T9l/2/ePegEN/tghY [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_5 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd5NFXf3wfwfc2++rpE8c2ceZ6HG1IJiaiMkUQRkcvlyjV/EzLPU1yajIlQRIYyJHWRISJTXGSeQq7L/W3f4bd+z289z1q/9az1PH95v9Y5+6xz9tpnn3vW+dxzAAIAQIHZa/dygAquLC46ObuhtdG3bqHdpPjNHTCezmg3TRUZBTUZBTl5FEpGXlVeSV6KXxvr6oXFOGi6OWC9MHauUvznsfauztcMHHCmaBcHN01lZQUFNXkHlOo1VWVlZUU52r2zsP0xuIyeA/qWgxcGJ3POwdOJBu6n9/7zPL/YYa45OXs7KF6/xYh2d3Bzw2LsPWmu23nZ7XViYGCg2psiiygAGrBtx7pHM1LDDeTeapQNACpSEBXoYfvzcrYpVID9r0sj9vYb6c30sDZMApYQxNFl6Wquy2R4PPOvvmpScHrX4UY3j2J23c9Jyv+2Bf+W0SSVRp2DwU1LX4tPkw1UTs3H2jUh+F+dBiBY61+Whn9Z/su+v+8NoPpjjYAtFaAG [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR10_CH_6 {
            get {
                return ResourceManager.GetString("UR_UR10_CH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nJp5PFdP/O/Prg1RliKUSNlSSWSphEpIiiyRLUkle/ZKi2RNlmSpyJItkcj2zS5bIqRQ9rRIRLLd9znf773397h/Xs/HnNdr3jNzzvnMnM+nmTkhKIIgi/BHK/23AoODwdEzthfsVe3Pn7e/ICGkb+3oZGt/QUlOapus1LZt27ftlJKR37pVRkJI1eWcs4ujtdIFaxdnR/NzEkJHXCzO2VpqWrsfs7ezvqAkK7tt2y4Za3k5SzlZWdntW0n6KquYk0tpWNuft3Z2dJfSsnY6Q0CcxfXf6ywzd7Q8Y+tqvd3q/FL7i9YXLrg4WjgRVubO5nSlJUuWYPQtrtyEIIqge/2sgpfiYNjpw6YKBMH++mIIX8W/H2d2EUNW//fRBto6tDW+tHKUDSIr/dANPyUL+UzmoLy//N/yXVMUgriQCPJ23fb4kj+Di/+/ivw/fzW9k+XlPZPlulfFi8DvK+uZ3DfZ0L4PQS6r/I9U9j/S/xP77w9jjigohuAIgZAMFMIC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_0 {
            get {
                return ResourceManager.GetString("UR_UR20_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nLl3PFb/H/9/zrlCSmTPSEiy96ZIZKSSEELJyEpWdmWPFmVkpaEICQnZssoMKXtklj2T+D3PeX++t9v39/vz1/32uh6P1/O1rus417lez1cIiiDIDvzDFf9HhcGL0Tk7e2cXdRcnJxdnoYMXrt5ws3dxVpYVkZAWkZCQlJAREZcXExMXOqju4ejuceOqsvNVD/cbVo5CB894XHa0v6Jz1fu8i8NVZ2VpaQkJOfGr8rJXZKWlpSXFyPBV6InJRTSvujhddb/hLaJ31c1uF8QpPP9bZ4/VjSt29p5XJa2dKF2uX3V29rhx2W2XtZW7Fd5p9+7dGP4W9/MjiBLo8SDre5QkMDT4S4k7gmCbgRiS4/7fx/m7gyEM//toP7t6TmtOd9JWjiP7g9BDC8Il7GZb0O7xv75ycTCFM5SvByRTyzfGd/7/KvL/+Xfc8n1NE0Je+6D5m5qQX6Fa878CNftnGeoIckv1/yqV/1f5f8X+z98GwYhXFBRDSMguhAzAo+QE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_1 {
            get {
                return ResourceManager.GetString("UR_UR20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNxlWFRduAbg3d12dysGohgYYAF2dytYICoidnd3YWG3YGNjd3c3dnecZy2/H+c6P4/39c77rLX37NkzzAx7z/B9DMswzF/8I538MzhcNKkf3iUiMiiyR4/IiMLZG3fq1btLZERAaZ8Sfj4lSviWKOVTvEyxYsULZw+K7t4nulengIhO0X16teteOHvd6Pbdu3QI7RTbMLJbp4gAP78SJfyLdypTukNpPz8/32IiuZVUdOM+1TtF9ujUp1esT61OvcMFzMt9/92O1q5Xh/AufTv5duyhRvbsFBER3at9b6Fjuz7tyEqKonBkF518DFMevfKIjpNVHsEmF6nnswz3YwjHKPP/3aGffzkm9X937fHla7Wrp1xy9z9hnBFszndFdmVq+QvLz8/7t67/R49hGusMczGL76K93578/f925v/8W3Fo26HyzRKSLcsOqjp5W+CDv2LydW5GFYYZWvF/1f7/Vf9n7r9/HL3EXQSeERgRJEZmFFAZjdHBYEzGAhvJ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_2 {
            get {
                return ResourceManager.GetString("UR_UR20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nJt3PJfd/8c/19R2t6iEtruFykhCW0taEllllpWMykzaJW1F0ZAGsiKyFSqhIoqKkiQ7GSF+r3N1//F7/P789Xycz+t13udcZ13nuq7j/j6+IkokEvXjH1HybwiNH/2NNjsdHJc62ts7OsyasMVyj/NORwcNVfm5yvJz586bqyI/R01Rcc6sCUtd7Vxc91hqOFi6uuzZbjdrwnrXHXY7zddY7t/saGvpoKGsPHfu/DmWaqrmqsrKyvMUOdLLSKFxeW1LR3tLlz375XUsnW1YxMXc/vYzaPsec5udbpbzLOwHOu62dHBw3bPDmbXY7rKdVBowYABNhviPnEi0ELrYz+L0QAZGnPw05IhEdLcPLarK+Tudnn5aNOq/qX0tKVunXVc8PKNG9I8fNalldrKUUS/K7/5Xdz4tJhLZ8CLRG+l5IWldNf3/XxX9n38W/wZmK8VLPMlQ9FlWt/TKkg/hg5f8+fJjmUh0QOt/pYz/lf5P7L9/tPBLQWkRI2JFHOBF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_3 {
            get {
                return ResourceManager.GetString("UR_UR20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nLl1WBbPG/a9uzchgg2iUioCitKNAioYtIjSXdLdqVIqAirSLakiIZLSKV3SKSEhICFdz3Xf3997HM/x/PnyOeY+z7lmdnZ2dnd2dkFQBEEO4A+v+D8KDH6UHxqbWFqJW1lYWFleO69kaGtnYmUpIsDOzcfOzc3Dzc/OJcTJyXXtvLiDub2DraGIpaGDva2u+bXzDxz0zE30pQ1dHlmZGVqK8PFxcwtyGQoJ6Avw8fHxcBLj93KK0Dj7PUMrC0N7Wxd2WUM7YyKIkzr+t5/Durb6xiaOhjwGFmRW1oaWlg62enZEBrr2uvhKhw4dwvBdPM6CIDdAb3kbBJHhwBzD/1yyQhBs2wtDzlj9dzg7BxhC+b9Dm/zZK3dvtutE+RRy3Bu9uMRWRKOxC+Vjlv+VCyZBE/KQOul44ko3pw7+/yry//zJ3rlf9Yzco5qrZVjCk/T+bW6erar2kkUJBHkq9n+l8v8r/T+x//1hhF8UFENwyH+njAg8MUCEkCCkABF4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_4 {
            get {
                return ResourceManager.GetString("UR_UR20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNl3WE7/Hzj+M+4bJYVUiqJCoqnSLiJpE0ppaO+tvVAUpVC0o0LR3kslGtqFhkqhJe2t/X3e5/35Xdf3+v7563G9zvP5Gve5zzn3Ga8DgiIIsgV/lEj5o8FgoaVhYWlnf87e1tbejuewpqmTs6W9nbQo3ykRvlOnhE6d5hMUFxAQ5Dl8zsXmlouTqbSdqcstJ0MbnsOXXIxsLI2VTT2u2lub2kmLiJw6JSZoKi5qLCoiIiIkQKZ8Cz2xcj4FU3tb01tOHnyqps4WJGjf7vrf91AbOhlbWLqaCpnYUtk7mNrZuTgZOZNMDG8ZUgbt2LEDo2zibi4EkYJ41t8klAqHhI6ymA1FEGzVD0OGQ//bnbUtDNn3v10b+talpjD2dU/lMLLbH+WY4S05oLsO/Rn/GysWTEaQ37CaL6xCCeX/hrf+/0bk//l7qKf4MTz62afm91Pn5WgU5Z782vvp7MPN8whyW/b/KpX/V/l/2v73hxFLFCKG4AgJIQMUCglsQ7Yj [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_5 {
            get {
                return ResourceManager.GetString("UR_UR20_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nNl3OJZv+Dj++7lnQyRpWaUhFCEJoVKpiEpWVrKzyt6aqEQhMzQp8x0hu8zsJCMze5O9+Z6Pz+d3HN/j++fveR3Xc57Xdd/u+dzjLISGIMgqfOiR/mFA4UvtqomppZWslYWFleWh3aqG1jamVpZSYgLCogLCwiLCxwSExI8cETq0W9bO3NbO2lDK0tDO1lrP/NDuy3Y3zU315Q2drlmZGVpKiYoKCx8XMhQX0xcTFRUVOULQ18KytnABOUMrC0NbayeBS4Y2JjiMU/b/s54Netb6Jqb2hiIGFuutbhtaWtpZ37TBDfRs9egzrVu3DqVv4mYeBDkB8dQDA9/1GCRM9K/qYARBFzxQpCD4f3ZncRVFtv7vrnX/blCUG6hlzutBNj+gcf87nMGmtQTTn/7vvMdbKARph8X84hCJzJnrWf3/G5H/5zP13/l87+jPBeEME2em/zt/2jX0ZQGr+OoZBLkr83+1vP+r/T9j//tB175pEFEEQ/C1SCAkQgECWQcZ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_6 {
            get {
                return ResourceManager.GetString("UR_UR20_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7ZV3UBPIHsdDLIBB+klAAoHIRVrA0EMJ9YIgHQMIJgQJnYChd44iVUmkKBxSRBBFRYog0jwRiBxNQEBAEAUkIJGiUkJ5oHdv7t28eXPzZt5fj8/M/nZn9zu7v9/ub34LYAEAADu77PV7cAB3jY2lmzvJR8/H29uHJAPFEsl+7j4kTRUEUgmBRCoglRGn1OTlT8lA9QK8/APIRE0SMcCfTPCSgZoHOHm5XzAmhlj7eBJJmkpKSKTqKaKaygUVJSUlBflDe6fwfdscgSH6eBP9ySEIE6Kf28HdedbA7+ccIZAvuLkHEhWcvdl9fIkkUgDZye+gM8GfsCdiY2MD7rnIDQcANHZ7nVjnK+wHdgdce8YVBAAAN6KAAHvQ93CYO0AA/++hTQ0MmWLo/TzN0wDuWBbxRdm64w6bu+uw37WqWbsGudv6IAp5jWvTO/9tD/gLmIWNZ6/kmc+mUVc12WFAPbgiU7dka1AXAIhG/6k1/6n9y9wfbwP4NmABAg8cPHTo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_0 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBRNgwfgXoKgIAKCvGRQFBDJkiRLViSIoOSMgMAKS5SwJkRRQVByFgmSFZC4gARJS3QBQXLOSGZJe+0bqr776q7q6q7uP35P9XTXTNdM73ZNdw1AAAAIML/r36EkgofbN+0dXJBKSGdnpMslDgNbN5QD0kVWQkBETEBERFREXEBYSkhI+BKHkoeTu4ebrayLrYe7m6XTJQ4dDysnB+vrtj63kPdsXWTFxEREJIVtpSSsJcTExESFSH8/5fSfNxdQs0U627q7+QjcsEXZk8DzZJ5/PeeEpZu1vYOnraiN83HkfVsXFw83KxSJjaW75e9O5OTkRL+HSM0NgAysFZ/YhBwnho1Tvw9ldAAQ7aKJQC7dXz9nj0AE/m6CSVyfltrcd5rqKUD9BHH2F38Zs8k+vO7xdwfJS3B4NrDRzSqaiNmZIvxva/Bv+WO1qLYZHKtzNem9Oi1SdNVZoPBqVFO6EgAP5f+lVP9L+U/n/pkbQPTnEQFrIkAMSAApdAyQ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_1 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTLgwfwXgEBQZGgiJKDJMkgOUsSJAiSkSQCCiySERAjgiCIgAQJksMiPCSJZMnBJSdJknYlSFhy3Gvfe7+73/3qrupXV3X/8f1UT3fNdM30pJ4agAAA4GF+179DfgIujG46OLoglZHOzkiXK8yGdm7ujkgXWXF+YTF+YWER4av8QpKCgkJXmJU9nTw83exkXew8Pdysna4w63raODnaatr5GiDv27nIiokJC0sI2UmK24qLiYmJCBL9Pgr1nzvnV7NDOtt5uPny37BzdyCE64m9/jrOKWs3WwdHLzuRO86kSFc7FxdPNxt3wjvWHta/O5GQkJz4PcSznADIwFrx2Z1wUgLYoPi9CDkHwIm9wBMg4Nxfp7OPPwFo/j612f4hbbX5PsraOXD2GYJ1la/ikvkB3K7yd1+JK3B4d2Cjl0EkuXpnDv9/rcG/BFVT+nVBpbjhkfBp5bmQUqXQGKKGD/JR1wB4LP9Ppfafyn9b9497A078uUTA+gQgAISA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_2 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTLgwfwXkQBlZxEchBQMggIu2QBQWBR0iMogsLCIwkLLjkjIAIKgmQkSJIgUZAkCihxEfaRgwTJQbICwrXvvd/V7351V/Wrq7q/ju+nerprpmumZ6amuwYgAABHML/qXzlLBDdGN21sHZ1UnBwcnBwFOQytXLC2To5y0sLiksLi4hLiUsJiMqKiYoIcKm72rm4uVnKOVm6uLhb2ghy6bpb2tnevW3noO9lZOcpJSoqLXxGzkpG+Ky0pKSkhevLXVWj/PLmwupWTg5Wri4ewthXWhhjuJ3nw13VOW7jctbF9YCVxz4HM6b6Vo6ObiyWW+J6Fq8WvTqSkpES/hkjFBwAK1kpB96LITsAG5a+NOz0ARHt+RMCe/q/b2T8iAnR/39oMYUBHfaGPuvEroApCcH0TqmE2O4DHL//d94ogHN492OhllUir//716H9bg39JSPLz9/GTDB/GLvtdXVBJVOb+elb5Gs3SVQD8Ff6pNP5T+S/7/vFuANGfWwSs [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_3 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTbggfgM2RFCRIlZ5AkOQdhQCRJFlEcwpCjMOQsXC8gIJIzSJIoQUTJIEnCAOIlR0WC5DDkuO299229fbVb9Wpr9z9+X51Q3ae6z8ypPl0NYACACyi/2l+5hgVVhro2tk7OcGdHR2cnXqYHlq4oW2cnWXF+IVF+ISFhITF+QUkBAUFeJri7g5u7q6Wsk6W7m6uZAy+Ttru5gy1S3dJb39ne0klWVFRISELQUlIcKS4qKiosgPvrLmR/XpxfxdLZ0dLN1Ztf0xJlgwMdx/f46z5XzVyRNrYelsIWjlecn1o6Obm7mqNwLMzczH4NIiAgwPo1RRJOAGSgViHE4uUVbKhD/KvqJAcA6zgQC9SR//VzTi6wwN9dMD80el9l+Q/S5gVAEgJj2eKrpTU+hc4H/z1AgheangXU+UovnNl4uHDxv23Bv0S9715rGJl/W177tJKk0z1FFaajVvvhDSUAguT/qTT/U/kvx/6xNgDrzxoGtVgAG+AAXAgewAcE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_4 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7dd3UBTLgwfwXoKACAuSQbLAA4QlSE4iSA4iwYQEJUdhJUlSgiQliCB5RVAySJYsWXQBJUqWjOScw7Xvvd/V7351V/Wrq7o/rorvZ2d6qqdrpnunprsGIAAAJzC/y985hwN3N29YWTs4Kjja2zs6XGIxMHdGWzs6yIjxC4nwCwkJC4nyC0oICAheYlFwsXvk4mwu42Du8sjZ1O4Sy3WX+3bWD9TNPfQcbc0dZEREhITEBc0lxB6IiYiICAvg/74LxZ8X51c2d7Q3f+Tswa9pjrbCg/UErn/d56yp8wMra1dzYTN7IseH5g4OLs730Xhmpo9MfzciJCTE+d1FMi4ApGEp728WToQLD5C/dzxUAODs++IAJqq/hnNwggMo/x7aVE+/lvKvbvK6aUDmj2Bb5atgMDyE52f+biB+CXbPDB50MQqn1OxOn/xvS/AvCb2n2iCSEdPoXr2sePWc6tWo8fONkUHHigA8kfunre6ftv9S949nA3D+3CNgiQNwAR7A [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_5 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7ZV3UJPLFsBDAFEQQgBFpXcVDVIChCS0ICIdpIjSIRgQCCShhUAQBCnSRYqQYOCioIgIiCKIykWjNEGw0LxSBFRQmpSQ5AW9d959d968ufNm3sz7g9/M2bPf7pndc749ZxfABQAA2Bw29SY7gZzG2R7jH4xFYYOCsMGHZJ3QOLw/NhipA9GAQjQ0NDW0IeqwI0fUD8miwgIJYTg0MhgdRsB5BR6StQ3zDvT3sUBHOWDPooORUKiGhq46GqbjowOFQjWP8G7uIvpjccgxNDYITcBFQazQeAwPZ5wv/Oc+/F44H4x/OFrTN2gHNgQdHByG88bz+HoRvDaNtm/fDtx0UVgFAEBwtFGCb8YObk4HtNkw+AEA4DoZCPjK/zMcBhsIEPs9tIn+N9bHZl6BWycBwglc8t8O35dw3eDMN/5uq3uZ02hwpE9Kk9KyOsn+bzXgL/QEmT+Rqqptu7JzwaTDz9yYNyOvjeLCNgEA4gz+JK1/kn8Z++NsAD86XEAgNw8v [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UR_UR20_CH_6 {
            get {
                return ResourceManager.GetString("UR_UR20_CH_6", resourceCulture);
            }
        }
    }
}
