//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_Estun.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_Estun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 nNx3XE59/D/wc65zznXmZZOdWQgJRaiMCJEtZUQpI7NUtKzbimTLiqyMSNmjsrdCdhSlkhUqbb6vz+e+f4/H9/f78+f5+Fzv8RnnXFfdlwo3wzIM8xe/SCS/NB0enEdOnzFnbr+5s2fPndO+2VhPH98Zc+fYWHXs3L1j504W1tYdLbpZdLVo36yf36wFfj6eNnM8/Rb4TJnVvtlwP/dZMzwcPReNnuvtOcfG0rJz5+4WntbdPLpZWlp26SSQq9Smh3d08Jw723OBz6KOQz19p/Poi/7/XkeZ4uMxfYa/Z5eps+W58zznzPHzcfflp05ZMIUskiRJR26xhinD9EJ85DdvncwhqU4eLtmzjK58sY45af/vE6r4q2Pq/PfUPj576eSQn1YzOYepsZxt8aPDxUYTKjHv/9/a7qMNDJMnMczTJl2iEktz/v7/Rub/+bWBs7zxtGazG7PlssvVajbr10No1m/tn3n9GGaJ3f8ayf9r/F+9//OxYXT0EU+RYhkO [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_0 {
            get {
                return ResourceManager.GetString("Estun_ER16_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNxjeFzfG+7xwd579sxWbdu229RuUytVatuprV9tO7Vt27ZtpsH5rtX/i3Odl6ef65nnXthrJpNkmrRpXW6XyxXDL9HFL9PDTf3a7dp36RrUtXPnrl2ypaoX2qNn+65dihfIkadQjjy5chcunCN3wdz5cmdLFdS7U6/ePUKLdwnt3atHi07ZUtXs3bJT+1ZVQvvX6doxtEvx/Pnz5CmUO7RwwVYF8+fPnzeXKu4lrjw8R4XQrp1De/Xon6NaaM92CvO+Pv/uJ9CiR6t27fuE5m3d2d+1W2iXLr17tOyptG7Rq4XYpOu6RzzEWBldrmL0C727TfR7CY648c1yuzwRYR7X35n/3qC/MR5XvP+9ac+v36pe4c212IdeuGKNcKf5nH1P0iaRrB/7395C0Y7LVddwua4mz7vowO8XMf+/3fX//Dp2Ks6xZA8/HN0VXSVopDMgyF1qcpA7VeKyLtfQkv9XHfq/6v+Z+98vj7zlTYTb5ZVdcakuTVJdPnjpCnSX [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_1 {
            get {
                return ResourceManager.GetString("Estun_ER16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNt5PBV9+DfwmTlnzpz2FFJEpVIkqVSytamoEEpkCSHZCqWs7VpIhTahklBRSJLQSlRkSYlSqaxZk53nM9P9PK/f6/fn4/26znV9r/l+Z8Y543SG+yZIgiCG8MVm9mskhQcTwx2Orm4r3Vxc3FznTNls5+7h6OaqsWju/CVz589TVlWdq7xYeaHynCkr9zh77nG303C12+Ppbu08Z4rBHhtnR9t1dvuN3ZzsXDVUVObPX6Jsp7rYdrGKisqCeTR7lPHczueusXNzsfN03z93g53HDj76zN5/xxlu7W67w3Gv3YLtLsPcdtm5uu5xt/Hgb7f2tGYnCYVCij3FsXIEoY78ds+uoGE8FGPYB/mPBEH1BlCE9Md/307fEEWI/vet/Sj7oLemvlQk5ycx9jA5rVUxQ9K8H9t/ffi3fck+IUGsExBEyeQFUVndP4f+fzPxv77EfMJX5Orten79bMzKN8v2rBwacnpWHX1mFUEc0PofkfM/4n/1/vuiuEcSmcIj [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_2 {
            get {
                return ResourceManager.GetString("Estun_ER16_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN11mNRW/O/xkcwkmSSTSQZ3d3enxd3d3d3d3aG4FSnuFHd3Ke7u0gKluP3e57T3eX73/nl5PSef77GM7O5sdlkWj9fj8fzgj0jxx/RxqFmlVesOHYt2bN++Y4cMSWo079K1dccOBXNlypYnU7YsWfPmzZQ1d9YcWTMkKdq9XbfuXZoX7NC8e7cujdtlSFKpe5N2rZuWbd67Wse2zTsUzJkzW7Y8WZvnzd00d86cObNnCYhbicqTZyrZvGP75t269M5UvnnXVgrjao9/byfUuEvTVq17NM/erL3esVPzDh26d2nSVWnWuFtjsUjTNJ+4i5HUHk8B8nT3TuN0P4UtDgUveD2+zwN9nqwX/n1AX374PDH+e2gPL16pUPLZBWfvI09kqDfZ64zb49f7yvyn8/+uzTMg6vEsNT2e8wmzz9/98dGP/9/0/D9/ajYsceCzc/5Al5s9i3VOPaRo7DKli377aWkxj2dQ4f/V9v6v9n+N/Z+3jccnjzxE+D2KJ4Ag [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_3 {
            get {
                return ResourceManager.GetString("Estun_ER16_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN1lmNtGtIBh2TLJtshymJMGGsaGmZmpDTMzMzMzMzMzQ8PcMDND0zQM95tJf9zn/rz7PuNz5syMNNJuvHay3SouRVF+8CGi+Ai7eaheqVnzNm0Lt23dum2btImrNe7QsXnbNnl/S585R/rMGTPlzJk+U/ZMWTOlTVy4c6tOnTs0ztumcedOHeq3Spu4QucGrZo3LN24e5W2LRu3yZstW+bMOTI1zpm9YfZs2bJlyegVZ3HkwdMXb9y2deNOHbqnL9u4YzMPdX+Xn+cJ1u/QsFnzLo2zNGqttW3XuE2bzh0adPQ0qt+pvpgUCATcYotWSkXJQzzVud0oTSUxxcOBNm7F/bmvW9nSxi0v58sPtxL979Ie/HW5XPGnF+y9DxVroCvpm3Tb49X6ynif/+bm6BRbUZJYinI+QZY5uz8+/PH/jcr/+Ri0s13hjiOuHMg9d2QRtVKnIr5OcwttUBcXUZR++f9X2/u/2v+p/ffxc58uoltRFY/ihU/xKwFoSlAJ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_4 {
            get {
                return ResourceManager.GetString("Estun_ER16_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNl3PJX/Hz/+c67rnHapyA6V7MjeVEQkKtkrm+y9qSRRqMjKSEJlE7KzR7YQiuxEZG9+z3N93t/b7fv7/flzv72ux/M1rtf1Oke3Q4XD43C4PfgiJenrCAIXjdsWlrZ2MnY2Nna2XEzqpo5Olna2kkLcfCLcfBd5RUW5eYV5BXi5mGRcrJ1dHE0lbU1dnB0NrbmYbroYWVsaXzf1uGNnZWorKSjIxyfCayoqbCwsKCjIf5FIego5tjm3vKmdjamzowf3DVMnCwKM73f933MOGToaW1i6mvKb2By0sze1tXVxNHIimBg6G5IWHThwACEd8TgrDicB2epi/+wgCgUZ6aL5FIdDNv0QnNLT/72crT0ER/HfSxv/1qcsP919onICd9wff/bfhWI63W3S/H9rRV4QcbhG2KbrNH9C+frE3v/fxP1/vt5cVJflErpWbTz4QnZW1Vm21Zbril1joiwOd1/6/2qV/1f7f439n+8NDsGueEgERxpEAQGr8TgiNo9A [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_5 {
            get {
                return ResourceManager.GetString("Estun_ER16_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNl3PJbv+zDw+7quuzSknZkVUVZU9khECCHZhOy9yQqJMpM9kyIyUmYZycoIUXZkb7I3z3Hf3+/r9/o9z5+P9+u8juM8znGd110un3xwCA6H24cvQiR8kaJwUVM2NbO2kbCxsrKxZqe/b2TvYGZjLcLLycPPyXOFW0CAk5uP+xo3O72Ek6Wjk72RiLWRk6O9viU7/V0nA0szQzkjt3s2FkbWItev8/DwcxsJ8BnyXb9+/eqVA4S7nCZuziltZGNl5Gjvxilv5GCKhzqJ83/uc0Tf3tDUzNno6kOrwza2RtbWTvYGDviH+o76hEmHDh1CCUc8wYLDCUP84WQbfBiD5Djh8skeh0O3vFFchv1/Hmd7H8Wd+e+jjf7qUpCe6jhZOYY74Ycw/uMopdbegXGb/87lz4VjcMI27eevJpdvjO3//0bc//OF/nSUDOxEv53sjZTU7HCX9MC2xO/mJkricI/F/ler/F/t/6oh/7MR8YpARHEYDo87AA7iSHCHwGHc [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_6 {
            get {
                return ResourceManager.GetString("Estun_ER16_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd5NFT/wwfwz1BRki1fZBnKvktibCNLyBrtyL5mibHEYCpFkj2MCknZKkK2xJQlkkY0ZZd9GbuxGzyfvss5v+d3nuec5zznef7zfp3Pcu79nHs/997zufdcgAAA7MD8bn/nIA2sLpq5uHp6aXl5eHh5SvJfcPTBuHp5qp2UPq4kfVxWDoWSllOUOyEnya/l5+7r5+Oo5uno5+tj6y7Jb+pn5+5qb+AYeM7rmqOnmoLC8eNKco4oRXtFBQUFedm9v8/C9ufBpXUdvTwcfX0CpY0cMS574HY6/7/Oc8DWx97F1d9R3sFjv9d1R09PPx87zB4HW1/b34Po6elpfk+RWQQAVdh+9bv+YD8t7DD9rhrYAKDZwNGASra/LmdzhwYc/vvSRkgdxrqT31kIo4A5DHF0XqqS25IK99/6e6ySJJyeA+y088qnV6+N7vxvW/BvceRQqMul5a/T0kQQyDT8WsW0/Fq1W9e1ALiJ/pdC+Jfyn7b982wAzZ81ArY0gBbs [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_0 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLogfgXiQISEaCRDGRkSRhgUWiCOISlCBBxAURBFlyFslHyaggkg5JFFSCIDlnASUtGYkrOed023O8r+679V7VrVf1/uP3VYea6Zrp3a7pqQEIAMARzK/2V04RwEpP+4GVrZ2i3aNHdrb8nLcxWAcrO1vZK4IikoIil4WlpASFJYTFhPk5FZ1sHJ2wGFlbjJMj1syGnxPtdM/Gylwd46ZrZ42xlRUXFxGRFMZISZhLiIuLi14m+nUXur8uLqiKsXuEccS6Cd7AODwghMdJnP++D5kZ1vyBlTNG9P4jUrvHGFtbJ+w9B8L7Zo5mvwadPHmS4NcUqS8BIAPbNqfHz0lPwA7Vr8qfHgCCXR8C4Er/98/ZOyIAv7tgshunqTrTRVM5Baj9EFzLAsUsRvvwvPzvAZL8cHr3YaeTTTSxfHvq6P/agn/LuCFdrcHllZpPbzQUe/rdFFe/hylK6jErAfAE9S+l8l/Kfzv2z7UBBH/VCNgSgBOAEBBBxIAE [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_1 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBXLggfgPgRBEZAgoJIUSZKT5CRIVKLgRQkiHDIcyZIVlSyIiATJGSQJKJlDFIFDkChBFCTnDId0tr33vq23r3arXm3V/rFV/L7q6a6ZrpmemZruGoAAAOBgfte/cxYPbu7qWFk7oBRQ9vYoB25mfaSTszXKQfo6r6AYryC/gLg4r4CogLAAN7OCq52LqxNS2gHp6uJkasfNrOX60M7aTB3pcQdli3SQFhERFBQTQIqLmomKiIgI8RP+vgrVnyfnVUai7JEuTh68t5HOVgRwP5HbX9c5Y+pkZmXthhQytz+NeoR0cHB1euhMYG7qYvq7EzExMd7vIZ5jB0AK1p2uj8JO48MG+e/N9fMA4O374YFr5/+6nQMcHqD++9am+oc0lOf7KNDT4NwzxJU1nspLhofw+MbfHcS44fDMYaOXQSipdm8a97+twb9kJzP6xmeNR03SzOkKPSKuCgh2y0bVD68UAXgi+08F/U/lv+z7x7sBeH9uEbDGA/iAABBC [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_2 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd5NFXdwwfwfUUSGSKSuGaFrnnKTKZkKEOGyHTJLEJcQ8icZMiQqQwhMqdk6jGkZMqQ3AzhGkLkGq7p8u6eYa3f+1vvu9a73rXeP961fD/r7H3WOfues8/d5+yzDkAAAA5gfte/Q0UCi+vXbjm6uau6u7q6uwmyG6M9vRzd3eQlUaLSKFFhERkZlIiUiLiIILuqt8sdb0+0vBva+46ntYsgu763jYujrTbaz9DdGe0mLyEhKiotgpaRspWSkJAQEyb7fRb6Pw+O0kC7u6LvePqhdNBet0jhdnKfv85z3NrT9pajD1rMzpXC3QPt5ubtaeNFamd9x/p3o2PHjpH87iItHwBysO729nhAcQSu0PwuUKcAINkJJgGcp/66nN0DEsDw96XhBod1NX4M0DXPANowBOevC3UsN/bg/oW/G0gLwu7ZwZV+VrHsxq2Zg/9tDf4t9BfVWwgqQy1mfL6XLEJDVa9Kaql6qD6/BMA9xX9Zmv9l+U/b/hkbQPJniYA1 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_3 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBRNgwfgXoLoSxYUFRQlCEoQRCQnARGQjJJRhCUILGHJWQTJKDnnIEFBkRwlC6yAuICgiJKWBQFhCbKka99Q9d1Xd1VXV3X/XPF7arp7Z7pmerZremoAAgBwAPO7/h0qEljoaVvboBzkHeztHVC85+8indE2Diip6/xXRfmvCgiKifELigheE+Q9L+9q5+LqjJRCIV1dnM3seM9ruj6wszFXRXrqOtgiUVLCwlevigoixUTMRYSFhYUEyH9fheHPk/MrIR3skS7OnvxqSLQ1GdxP4fbXdf4wcza3tnFDClnYH3NwRKJQrs4P0GQWZi5mvzsdPXqU5PcQ6bgAkIT1e1fHyGOksEH7u1A+AQAJ0Z8ESJ3463Z2DkgA49+3NoMdVVfCf6RvmQV0jxFsP/nqmI134XHyv/uK8sLhWcDG0FmhzKZfswf/2xr8W07XO8qjwz+1IQMiFEi1XRSOuGTdyKcqUAAgQOZftpZ/2f7Tvn/mBpD8WSJgTQJIARkg [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_4 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLgwfwXoIEERRRJAcJgkiOkpMokpT0QILEBSQvK0myKEEQAWWXDIKACCggGVEByRnJQYmS85Lh2vfe7+p3v7qr+tVV3R9XxfdT0z010zXTvbPTUw0QAIBjmN/175DhwUL/ro2to5Oik4ODkyMPs56VK8rWyVFalFdQnFeQX0BCgldATEBYgIdZEW3vhna1kna0Qru5mtnzMGuhze1tLW5beeo4PbBylBYRERQUF7CSELMQExEREeIn/H2X839enFfFysnBys3Vk1fdCmVDAI8TPfzrPqRmrhY2tg+thCwdSJycrRwd0a7mKAJLMzez342IiYnxfnfxLCcAUrBuQzs/I8GHOxS/C64LAODt+eEBhgt/DWf/GA9Q/T20qd5+DZW5nnM10+BsEIJ19Vo5ndEBPD/9dwNxHtg9S7jTzSCUXL0zffy/rcG/5L2onlKg3c2vuZ0vlBa13ZTaHHkUZHtSlADwl/2nreaftv9y7B/PBuD9WSJgjQfwAQEg [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_5 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7ZV5NNT9GsAH2TWMRLYoiSwzhgbD2IqmrGN5yTDGNoxdxjTIMtahQkjZl2QppBKRF5FKDNIMZYks0YssKVuYS73vve99zz333HPPuf/c43PO8zy/8/0+5/k+z+88z3kATAAAgLHDrt2Fh3lH2VjgPXz9Tvv5+Pj5Kkha4wIIHn6+WqpgZXWwshIUDgdD1aAnoQqSp4negcQAnJYvjhgY4OStIIkiOnt7uBjhgq38vHC+WjCYsrI6FAdXc1GDwWAqSqy7rxz4ERyMxPn54AIDgsEmOAJ+3845+8Wf73A5BbjgPS7iVFx9OP38cb6+xABnwj5Xp0CnXScODg7m3RT5ZAAAxI7tIvpf5WTZ+eDdVUrcAADzRgQz4Bj3z3K+M5gBAr+XNkl/a4r8jQZq/gjgi2Y6uqhYL2q/uXM/x/XzXv3GjlLekTfiKnmNax8Z/60F/AWmF4H6CS3MrUsD1/Vv9F7SD2XZ0EPdy9EHAMg6f5LmP8k/nTH9PdAPxczMso+V [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER16_CH_6 {
            get {
                return ResourceManager.GetString("Estun_ER16_CH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN1jlCRZsMDxzKrMymJWZtbYtm3bOzM72Nmxbdu2bdu2bdu2/f73zn545318/TtRETduJKr29HT3THevoiqK8ps3kcVb0MVD1YpNmrZqXbh1y5atW6VJUKVhu/ZNW7fKmy1dphzpMmXImDNnuozZM2bJmCZB4Y4tOnRs1zBvq4YdO7Sr2yJNggod67VoWr90w66VWzdv2Cpv1qyZMuXI2DBn9vrZs2bNmjmDLq4SkSdPV7xh65YNO7Trmq5sw/ZNNPpGpz/X8ddtV79J004NMzdo6WvdpmGrVh3b1WuvNajboa4Y8nq9LnGLVnJFyUM+2bHNCJ+bIiwextsuxfWtt0sZbLvk0/n+26VE+e+pPbhwuVzxp+ft3Q8Vq7+a6E3arbH//cF++f9mcwxhsr2pKOfiZp6188vD3//frPyft5knXu8/8GPV/pxfCu18pqwu7HevL/zG16OwovTJ/79i9/+K/9P77+3Pfapkl+JWNEWHRzEUr2QoPviVgBJESDGV [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_0 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNxjmBxbtIDhdld3VXepJ7Zt27Zt29aJbdu2bdtOToyT5MTW/fbO+XGf+/PO+6xea6+9d1V1z2Qy3QOH0+Fw/OZNZPGmubipXqlFy3btC7dv27Z9uzQJqjXt1Lll+3Z5s6XLlCNdpgwZc+ZMlzF7xiwZ0yQo3LVNl66dmuZt17Rrl04N26RJUKFrozYtG5du2rNK+9ZN2+XNmjVTphwZm+bM3jh71qxZM2fwirPY8uDpijdt37Zpl04905Vt2rmFh76/25/zBBt2atyiZbemmZu0DbTv0LRdu66dGnX2NGnYpaFYpCiKS1yikdzhyEM+07XD6ICbQhc3uZt4HK5v/V2O9E088u58/+1yRP67a48uXytX/Pklc99jhzHImehN2h2x6/xg/nPjP2tzzE7jcBSP53BcjJt57p4vj3//f7Pj/7zlG7nq0MfBCw79/l2t8Lzfzwq/m3Sv8MubVYs4HAPy/6/Y97/i//T+e3PJWyfZJUdueBxehw8ewg/FEXAE [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_1 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN1llBTXF7D7qmqt6qouGdzd3d3dJQR3d4cgwd0J7gQI7hac4BYcggYnwd2DvM85/O9a770f7/zW6b3PPlLVPT0zPUx3o6iKonzjQ0TxYWpc1K7Rpm2nziU7d+zYuVOmZD+27Na9bedOhfNkyZEvS45s2fPnz5I9b/Zc2TMlK9mzQ4+e3VoW7tSyZ49uTTtkSlatZ7MObZtXbNnnh87tW3YqnDt3jhz5srfMn7d53ty5c+fMFhBHiZGbZynbsnPHlj269clSuWX3Nn7qoV7fj2M07da8TdteLXO26Kh37tKyU6ee3Zp197do2qOpmBQOhzVxik5aRSlEPNmzyzjdR2KLi5qupmifBmpKWVeTV+e/b5oS639X7d6FS1XKPjzv7r2vOEPVFC8yb0/Y4DPj9v/m5ssfoyizLUU5lzjn/N0f7n/7/xuV/8/Hwr9Wl1BKnDjwcsjjkpXKfymZK2e14sdbvimlKIOK/l9t7//V/l+1/+dzo3w/T5WoKT7FrwQQ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_2 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN1llNtWG7BrS7Jsy7Yky/aEmZmZOWmoYYYGG2ZmajhpOG2wYcaGmZmZmZmTBr9777xnre+cnyfXevzA3pJlD2Qy9Uxdisvl+sEfkcWfoMpNzSotWrZrX7x927bt22VIUqNZp84t27crmCtTtjyZsmXJmjdvpqy5s+bImiFJ8a5tunTt1Kxgu2Zdu3Rq1CZDkkpdG7dp2aRcs57V2rdu1q5gzpzZsuXJ2ixv7ia5c+bMmT2LLu4lIk+eqXSz9m2bdenUM1OFZp1buJl7u/28H3+jTk1atOzWLHvTtkb7Ds3atevaqXFnd9NGXRqJTT6fTxWXGErtchUgH+/aYbShUdjipksyzaV+7q+6WiTT5MP58kN1Rf/30O6du1ix9OOzzs77rtBgJdmrjJvj1/vKepb/7c1TN7HLVYPdZxJmn7X90/0f/3+z6//zp9i1lcXiD+yyd8iVIyWyD0xY4s7cocUnLfaWdLkGFP6/Yuf/Ff+v2f/ztnGp8lYhqy7N5Xbp [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_3 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nN11tBNX3O7xSTKaTDIzCe4O5eBOcXd3d3d3hwLFvVhxd9dCkeIORYq2eFukghV7v3u3d6333j/v+ayd57dlJDkhJzkSFJ+iKJ/5ECk+bD8X9Wq279C1W6luXbp065olVd02PXt16Na1SL5suQpky5UjZ8GC2XLmz5knZ5ZUpfp07t2nZ5siXdv06d2zRecsqar3adm5Q6tKbQbU7tapTdciefPmylUgZ5uC+Vvlz5s3b+4cmjhKTO48W7k23bq06d1zQLYqbXq1Vxk3+v57nGCLnq3ad+jbJnfrLla37m26du3Ts2UvtXWL3i3EItM0/eIU3YyKUpg826f7RCtA4YiL3Jpf8f8zzK9k1Pzy6rz/7Ffi/XfVHly5VrXc08vewYeKO8qX5mXWPUkbf2D+hfrv2gLXY4rSP6wol5Ln/va7tw8///+m8v98tEwar/TF1gmP5HWelV5Q6mTp+RVKlXr3lVFGUYYX+1/t4P9q/9fY//ncKP+ep4/0KwFFVTRJ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_4 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNxlWBXP+z/w7d7FBBvFLgzsxha7sAsFFANFsAg7UUxsxA4MFBsDW1EswsDARAUVRDAA5f+e8fPge/0e/nldc+577pmds3vg7CmAYRmGKcAXieTL4HAxoM/YcZO823lPnOg9qVZ5V3efqeO8J7Vs5Fi/iWP9uvWaNnWs17heg3q1yrfzm+Dr5+PecpK7n6/PqAm1yvfyc5swbnRX95n9vMe7T2rZsGH9+k3quTdtPLpxw4YNneqK5FqK0sUdO7l7T3T39Znp2N196lgBdXnav+vRRvmMHjtumrvTmImq92T3SZP8fNymCmNG+Y4ikxRF4cguFqrKMC0Q7/pNXq7ySGzIRZHpLMPlzuYYafq/A8or4Jhi/x3au8THPTp9Sigc854pNJ91yKx9tvTQfIzfm/ZvbpOiNgzTUmOY+LJO2y78el/w/xuZ//N1QTjQvsGCR1cKIjPbbzmb0L5M9zttK84SOjDMnNb/02L+p/2f2n9fHL3EIQLPCIxISch5RmYU [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_5 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nNp3PJX/Hzj86zrXOdepZJSMyiiShi2kjCRJikpDyEyyRfaqELIioqxKqMwiI6KUmRWi7D2zyeZ+Xefz/T0ev/v+8/bsdV7j/b7e56LCUQiKIMgGvBGZeNtKgodrl26bWlkrWltaWlsJ7LlqbGtnam0lKykkdlRITERUWlpIVEr0iKjAHkV7i7v2tsayVsb2d20NLAT2XLA3tDA1UjV2vmxtbmwlKyEhJnZU1FhaykhKQkJCXIRCPAsz7XAhZWNrS+O7ts5C543tbpNhTnX473m2GNga3TZ1MBa/abnZ2sbYysre1tCOfNPgrgGxadOmTSTiFpn4EUQGco29TeBmDApG4uFFBoKQlj1JSHjGf+/OygYJ2fG/d62/qUVNeaRxW/EAwuSF8kwJ5u/WWYV1nf/tPWpFRZAyuJUGTvG4z4sDG/9/M/L/eZsJaTyV0BRbIik0e0r0Zcsp7xdxJy+GY0oIck/+/4ri/yv+X7P/83uDkGiPKGQSgiFkWiamZEBB [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_6 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3MF3bowfwdYhIkSCCaCEIKTi66EH06BFRonNIOAeHcLQjISFESUR0gigJwUUiRA3RW/R+RPTee3kr997fm9/7zXszv3kz74834/uZvdaevdfsvfZas9eeDRAAgEOY3/XvkBHBQk/bxhaNkcPY22PQXCx3rZywthi0pDAP/w0efl4+UVEePhE+QT4uFjkXO2cXJytJtJWLs5OZHReLpou5na2FqhXuDuahFVpSSIif/waflaiIhYiQkJAAL8nvu1D9eXEeRSuMvZWzE45HzQprcwweJ330131OmTlZ2Ng+shKwtD+JcbBCo12czLHHLM2czX43OnHiBNHvLlJwAiAB62YXhxcnieEO+e9CmBoAoh08EbhG/dfj7B4SgfN/P9pYZ4+64nQHZfk4oPBFsC5xFzEY7cHzK383uMEFu2cJd9qZBBJKt8YP/7c1+JeQFSxWMcxmV+ViJUr7F7LlnpDny6VIesoB4CP9T1v5P23/5dg/5gYQ/VkiYE0EiMEx [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_0 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLgwfwXiQoIDkpUXKGBZEgSZEk+YEgQZGcc9yVoIKSk0uOEhSQpIAoWckZAQFBgiAZCRJcyde+935Xv/vVXdWvrur+Or6fmu6umd6Znu2anhqAAACcwPyuf4cYBxYGf9jaObsouDg5uTjzs+hbuXvYuTjLXBEUkRAUEUZKSgoixZGXkfwsCl6Onl7uVjLOVl6e7maO/CzaXuaOdhZqVig9FwcrZxkxMRERCaSVpLiFuJiYmKgw3u+rUP55ckFlKxcnK093lKCGlYctLtxP4P3XdQjN3C1s7bytRC2dzrm4Wjk7e7mbe+Bamnma/e509uxZnN9DJOMCQBrWvV6ukefOwAbp78KXGgCc/UAc4Ej91+0cnOAAqr9vbe7TqKby8hB54zwgC0KwbgpU05scwuOX/+4rwQ+HZwkbg4yimfW/5k/+tzX4lzQ8LWvOr81u/iiiqXBbYUVBPnxGwYRG/wYAD+T+aWv8p+2/7PvH3ACcP0sErHHAGYAL8CB8 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_1 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLgwfwXhRRUKIISjQgApIkCZIRccmggJIEZVlyTkuU8ECCoKJkFkGy5JxBgqQlCAiC5JyRIAhLuPa997v63a/uqn51VffX8f3UdPfOdM307NR01wAEAOAI5nf9O2cJYKGlbmJqZS1jbWlpbXWTWRNlZ29qbSUmyHXrNtctHl5hYS5eIV5+3pvMMo4WDo52KDErlKODnaHFTWZVx6cWps8UUJiH1uYoKzEBgVu3bvOihIWeCQkICPDxEP6+CtWfJ+eSQ1lbohzsMFxKKHuTk3A/kdNf1yE2tHtmYuqE4jOyPGNtg7KycrR7an/SyNDB8Hen06dPE/weIjkrAKKw7nC0CTlzAjbIfhfO1AAQ7HkRAHPqv24Hf0QAzv99a9N9A8pyC70UtTOA3Bdx5QdnOZ3uPjzO93ff2zfh8Ixgo4eBD1v9a+bof1uDf8mIaba0o1F7w57aoowi8kDGfS5Yqg21dReA5xL/tNX+0/Zf9v3j2QCCP0sErAnACXAS [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_2 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBRNgwfgXrKCgIAEySBJRLJkUbIiIIIiOQm6Ciyw5CCCBMlJkhJEkmQVkMwCiiiSM0t6CZKWjOR07Ruqvvvqrurqqu6fK35PzXTvTNd0z05Ndw1AAACOYX6Xv0OGB3d6dx4h7VCKKFtblN0ltntWjmgkyk7uymURycsiQsJSUpeFJYTFhC+xKTrbODk7WsnZWTk7OZrbXGK77Wxhg7RUt3LXRT2xspMTFxcRkRS2kpKwlBAXFxcVIvzdC/WfF7+saoWytXJydL+sYYV+RACPE7v81c9pc0fLR0gXK9EHtqdQ9lZ2ds6OFmiCB+ZO5r8bkZCQ4P0eIiUPALKwbHO2DzuFDysUv3fK5wDA2/PBA1Ln/rqd/WM8QPP3rU33DmiqzvecxfwElM8RHKsClYxGB/A84u+2kpfg8B7ASjezaGrtzs/j/20J/i0KI0UKeHZOn/2xLUrZGGalfp9Axe58YmUAnsn/y4b5l+0/Hfvn2QC8P/cIWOIBfEAACCEi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_3 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTbggfgM6CCpCEISBxyUAEJggMMIFlQQVFBJUgYAUkShiBJsgRhBgQlIyAgKCioREFgJCeVKEkJEi9pQDLs8d77tt6+2q16tVX71/L76oTqPtV9urv6dDVAAAD2YX63v0NDBivDKza2jk5qTg4OTo6neK5jXVxtnRwxsuJSZ8WlTkui0eKScpIykqd41HD2bjgXLMYRi3NzMbc/xaOPs7C3tdTFel11ssM6Ys6ckZI6K4lFy1nKnTlzRvr04d9nYfrz4OJaWCcHrJuLl/hFrKvNIbidwv2v81CZu1ja2Lpjpa0cjjrdwzo64lwsXA9ZmbuZ/x5ESUlJ9nuK9MIAKMK2HXcv6ig57CB/V3eZASDb8icDpsx/Xc72Phk49velTXT3XdKa+cpQMwnogxB8S2LlHMY7cL/Q32PPnoLTs4KdL1zSaR82Jvf/ty34l8iNMam3BrLWS6/Nq6sbNKvHnVFTqyNQaADwQPmfSs0/lf+y7R/PBpD9WSNgSwbI [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_4 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLgwfwXlSiCkiUnB55QUAEBAHJKhkEJIq4JCUuCMjCqgiSc1SSgiDZAEhGJCNBBEFQQcKS48KSw7Xvvd/V7351V/Wrq7r7i++nZrprpnemd7qmuwYgAACHML/L3zlJBHfG+vYOzi7KLk5OLs7CHEYod7SDi/OlCyLi0iLi58RkZETEpMTOiwlzKHve9fB0R11yRnl6uFvfFebQ9bx118HmGsrH0OUOyvmSpKS4uLQYSkbKRkpSUlLi3Infd6H58+Ii6igXJ5SHu4+IFgptfxweJ7n3133Ird1t7B3uoSRuO5G5uKKcnT3db6GP37b2sP7diJSUlOh3F6n4AJCDZZenazjZMVih/L2boQWAaAdLBH7Q/vV3dg+JwN9VMNk/qK0+20ddjwNUAQiuFWQls/kePJ/9dwNpYdi927DyhVUivXYLd/i/LcG/xJsoT0UwaeBjnNeKysGHPpUA4U6l6ojjqgA8UPinrf6ftv9y7B9jA4j+3CNgSQSOgePg [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_5 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7dd3UBTLogfgXiSKEiRnUEkKu4RDkiSCIoJEFZGkyAKKxCUtUeFIRkBAchJEVAQliCBBjoAkCZIkCyxLDgILwrLsbc8999Z9t96ruvWq3l+P31fT3TXTNdO7M9NdAxAAADLMr/pXjlDAwtTY4Y6zi6aLk5OLs4TgNbQ75o6Ls6o8UkYRKSMlraSElFaQ/k1aQlDT856Hpzta1Rnt6eF+656EoKGnzb07t3XR2CsujmhnVTk5GRlFabSSwm0FOTk5WSmqX1dh+fPkSG20ixPawx2LvIzGOFDC/TRef7/O4Vvutx3ueKFlbZ3oXFzRzs6e7jYYSttbHrd+daKlpaX4NUQmUQBUYP3F0zWa7hBsMP4q/FkBoNgNogCurH//OUQyBfirCXB9g/ra873M9TOAKQRxfE2yisdiDx5X/KuDogQcni1sfOWTzar9OUP+39bg31IY3auV15f5hzxyQ6s3Z1ArLyfrnFHiofMA3Ff/l63+X7b/su8f9wZQ/FkiYE0B [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Estun_ER170_2650_CH_6 {
            get {
                return ResourceManager.GetString("Estun_ER170_2650_CH_6", resourceCulture);
            }
        }
    }
}
