//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_Cobot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_Cobot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jtFxZt4ZrV22rYtu2bScd27Ztq2MnHXds27Zt23bus1b6xx13jHueseZ8Jxb2rnN21cmX9BdQAoHAb76EF19uEFO1YvMWbdsVbtemTbu2aRJUbdKxU4t2bfNmT5cpZ7pMmTNmyJ4uc4YMGdMkKNyldecuHZvkbdukS+eODVqnSVC+S8PWLRqVbtKjcrtWTdrmzZo1U6YcGZvkzN4oe9asWTNn0MQmkeXa6Yo3ademSeeOPdKVbdKpuUre6PpnG7tBx0bNW3RtkrlxG6td+yZt23bp2LCT2rhB5waiyTTNoDhhhOSBQB78+CGdx1ghRFiYg3tDgeC3fsHA1r0heTXffwcDUf67sgcXLpcr/vR8xN0PAxEGKYnepN0au/YP6gP+683xL53jogYC5+Jmnr3zy8Pf/5/PlJmvTmX2vPlWKO3DySMK9P5R2hz1tcKelF/3Rc1yp0GBwP/5UgIl9m0IZNnXKWmqbRHS5i60+XfmQkpgQqFAoH/+/zV2/6/x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_0 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJt5WA591Mdn5r5nblHKkkSiUkmKsiRUCKVFSIo2raR9kVZRCEVkKYosCdEuSaGkUlG2NmUpUZTsLVK93xnPH+/1Xtfrc/3O+Z7zO79l7mV65p55CJIgiGH8Yz37T5iC2bh+m4uHp66nu7unx6xpG518fF08PbQ0VNU1VdXnqs3RUJ07Z47arGm6O9z8dvg4aXk47fDzsXObNW3tDns3FwdDp8ANnq5OHlrz56urL1Rz0tRw0Jg/f/7cOTS7yDhublU9J093Jz+fQFVjJ99tfOQF/v+WGWnn47DNxd9prqO7kKeXk4fHDh97X76jnZ8dWzRixAiK3aGYIkEsgT+2z++IEA9ClDUJC0mC+hNGETEL/x3PwDBFjP/vyNpe1q/R+/RizP0PhFgEKftNJX+y1V/0m/9Xu/CRgCC6GYJ4PmXuubt9H4b/P++w4NF0ua0GRY9Ev5UlxzgtPfpR/JrWTf2iDxsfTPrFc1hK/J9/EkRRsZr82AdyvIPLb44pWkYS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_1 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dL0DsCZL07bb9hrbtrnGM2ts27Zt27a1xrZt27btmf+q2u+J+M+JOHNFZd6ZlVVd1f005v323p+iKoryjz/Ciz+BhqlWqUXLdu0Lt2/btn27dImqNe3UuWX7dvlyZsiSK0OWrJkz5cyQNVOmzOkSFe7apkvXTk3ztWvatUunhm3SJarQtVGblo1LN+1ZpX3rpu3yZc+eJUto5qa5cjbOmT179qyZTHGQqHLuDMWbtm/btEunnhnKNu3cwiBvd/vvMF7DTo1btOzWNGuTtm77Dk3btevaqVFno0nDLg1FkeM4mlhhpJSKkhc/cWiXca6OiCjMzfiWov3srylnEeLPr3+aEu1/O3t8+Vq54i8uRd73RIk0WE3yPv2OuHV+0z/tf7WhJeIoSrn4inIxftZ5e74/+ff/57OKP5ty7s/yvuajL/G6FDQyvMr0vnOR/bvmNZn+o1mngsr/54+q7D/Qduyqg9sSXAtDFwrr9/7AumODCyvKgAL/V9v3f7X/V+7/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_2 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLoJNFffF/997/3cq0HRoFSKRpUiQsYMaSQ0SCpDklCGzDKm0qCiEsqYCM2SMlSGyhDKkChJRCRjyRTyf9/7/T1r/Z9nrcdrnb3fZ5+99zkfn2F9hkuQBEGM4Y/17N8kCsZwh7WNvYOWg52dg/3K+YaWTs42DvZrFaRWK0mtlpWRVpCSlZaWWTlfy9XWxdXJcq29pauLk7ntyvnbXA/Y2ljoWB4zcDhiab9WXn71akUZSyUFCwV5eXlZaYbdZDrXW2qTpYOdpYvTMSldS2drGvFxbv9tM9HcycLaxs1S9qDdBIejlvb2rk4HnOmD5i7mbNL48eMp9oRTlhKEKvzlAJegCTwIQdaIaJIE9dePIgQ1/7s9w2MUIfS/W9ZcVaO3qe391JzvxJST5MIeyUwR4xGs12j8l6s4no8gfjEEUTlPNubF4Pex/z9/6Tr7J5/bMXL6wLFDThqno+Xn9QvI567y726JPeGmQfx//t6V3ssr2cL/cpmxsRa05sb0dE3v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_3 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dHkFVFVR1+05F4MQEQFRGlFRWkIalBAFBEEEBOlWGulSKZESkC6RLgHpVqSURpRQGunu5q17v+9/4703xmOOvebca6+17rn37L1PgKAIghzDH5axf2cwYFSVTc0srSStLCysLNkYVI1s7cysLEX5ObgFObh5bnLxc/Bwcd1kY5C0N39hb2skamlk/8JWz5yN4aG9vrmZgZyRs4rVcyNLUT4+bm6Bm0aC/Ab8fHx8PFwnsR9ChqvNIWNkZWH0wtaZ44GRnekJ8J92+M/HEOrZGpiaORjxGFoQWFkbWVra2+rbnTDUe6GHDcLHx8dgj/AcM4KIAIf6vAgmwANBgjWDVgiC2fPEIB1W//k2+8cYhPy/32yyt09BZvYnad0/5JwXenmFvYL66QGMR/43VuATFG6F1kPLk1iz8+/4/8fcPLi/Lyz8EkzDc7q3uf7bj/YOk7s8p30b+X/+cmNivgZHJdTL6CVJgr7DULD09b5emSSCvBT/P1rd/9H+L9//nBoE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_4 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJt5WE1f1MfPeEtkTqXMFAkVpYEiFJrQYCikQdI8SCWlEEqFkCJKgyGVKRGpJBkrRSmShBApRUj1fvfx++N93ud5+zxrr+9ae+19hrrndu7Zl6IpiurDD/HkZwCDxmrFJmd3jwUebm4e7spjrRy9fZw93OfOnq6mNV1tpqrK7OkzVVRUlccu2OLqu8Xbca674xZf7w2uymOXbbFzdbY3cgyw8HBxdJ+rrq6mpqnqqDXbfra6uvpMFZ5sZJgw93RDRw83R1/vgOkmjj6bOOTF/P5tRmKDt/0mZz/HmQ5u/Tw8Hd3dt3jb+XAOG3w3kCJxcXGG7OFgRYqaA39wt290PxZiEGmUNGiK+RPCUKM1/h1Pdx9DDf/vyN49qzE1/FQ1pOA9NXgnPb5t2g05m7/o/6D+r1azSURRuWIUVTlq5sn8X+/7/j9fOHp3y/LraoVfizKz6YeO8zRmCj+FYxM/9IZJrZhH/Z+fi48vFIWdSryjvyF3QbiThn55zLg7Ee1V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_5 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zt5NJXvu//vB5EkyZQyhdIgU8lMNFBiVyohfDKkkjnjNqSURIYUYkclpEwRMpdZhh3KkHnINs/zNpxr78/3c37fc9b5rXX++K31+8f1Xo/rdV/Dfd/P/TxiryWEIYTWwSieYltp4MuVizdvWducsLGysrEWFbhibu9wy8ZaSUZMSk5M6oikhIzYEQkJSVGBE4537jramytZmzvetb9+R1TgvKPJnVummuaul2wsza2VpKWlpGQlzeVkTGWkpaWPSGyiLMJGnVtM3dzGyvyuvauYlrnDTTqIMzj9vcyW6/amN285mR8xs2K0sTW3tna0N3GgM7t+9zqlaPPmzTSUHW4XQUgRfMjDu4GMtAAslC/iUgjRLHvRICGpv++GvE6D2P91Z/0/m7XVhxpZi/6g7Q8wwcnDObuvrUB+RPLvvCwnTOz/zzn8p02q/N/G76oysd7Thsf/GWcdrDn52HhZ5S+uyjBxiJ9SDjtvwnzieMSqjNqkM6H4/qZvJ7ovKqht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_6 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nPp5WE3fGzj87+Hsvc+e9zHPmeckSZpkDhkjSRMSmmkiTeZZIZUkGTJUCKk0v4moJKRSGqQJUTSqVL+7z/f7x/N7/nzu13X2Ptc559pnWtda677XQlAEQXoh+s59wWFw2Gi4y8bRaZGTg4OT4/TRG62dXWycHHU1ZszSnDFLTXWmxgy1mTNVp49e5Gbv6uZsreto7ebqvNV++ui1btvsbawMrD02ONlZO+qqq8+aNVfVWlPDSkNdXV1tJtH3Jv3/d+0Z+tZODtauzh4zVlm77JLB45T7/3kbZquz1S4bd2u17Q60025rR0c3520usu1bXbf2vUgul2N9n1CahCA6cD5/1NWPxuGO2Hdwf4MgWKcvhti++T/fpqsXQwb8329W/bFotf73fEV6DSIdRsf+Vk4cbvYPnp/1f18794UCQX4SCPJhpNrV1L81vf9fz8j/K1Bk2fMnyOznLhOmJknK2gsTetUWosiFhQhyQO//cUv/f9z+/x7r+3v+dyHs/14O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_0 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3XI1v/Dj++9x7RAilKSukkrRoINmVENKiJKRSSbu8rTQUQmiZJZqStJH2QmlpUClpaWv/Xj6f7x/f3+/P3/V8nPs+j3PuzrnH635dr+s6ITwEQWag/Vv/a3woLA7uO3nK1k7LzsbGznbN4oOWDo6n7GzVlWXXqcquU5BfqyyrsHat/JrFWk5nzjk5WKrbWjqdczh2Zs3ivU7mZ05Z7LZ0PWBnbWmrrqi4bp2KvKWqsoWyoqKiwlri35cI/M9ny263tLOxPOfgKqtj6XgSh9ep8//7NewxB4uTp85bKhy3YezOWtraOjmYO+LHj5079m8jmqbRf3s4RwpB1GB988q5QAaDJ/z/FmUXEQQd90aR9xf/92gmZlBk/v85sraqGt3tnZVzc34icy7xlvyRSRMxnoT3ff/PtirL+ODwYVe+iClEZP39OfP/d438f5og8u69/PJ5H5Zivltez323mYe822wSJKKFIBc0/69Hzv/1+H+99u/y/M8Hof+z5MEa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_1 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxTlCRdGzboyMhIRGRk2Mq2bdu2bdu2bdu2bdu2bb49d37zH8zM4exrFVZ1rayu7r02HgThIwjiH0b8Y3ywJN5Vq9SiZbv2hdu3bdu+XZoE1Zp26tyyfbu82dNlypkuU+aMGbKny5whQ8Y0CQp3bdOla6emeds17dqlU8M2aRJU6NqoTcvGpZv2rNK+ddN2ebNmzZQpR8amObM3zp41a9bMGQLxHyL/77XTFW/avm3TLp16pivbtHMLCl8Pdfu/fwzTsFPjFi27Nc3cpC3dvkPTdu26dmrUmWrSsEvD+DeFw2Ey/jcUkhNEHnycOLTLONqPT/j4uxOFKIL81Z8k9hSi/vfb/P5HEsr/+c2eXLlervjLy+L+p4Qw2JfoQ9qddp0/+PMh/+d7cyTIRRANZIK45Gaet/fH03//fz8S/5/hIw4cbDt29aHt3vVC+LxgoX4fDq4/PrgwQQzI//942///ePt/fS3+3/O/FyL/z8uR4CcoIgBBIkSEgSYYIgIs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_2 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5PBVf/Dj+We7M3LmjtLzLkqV9UUiSnUppURRRCEUIIWTfKu9osSRUylLJli0kkeVdyhrKWpYW+5rsO79Xn8/3j+/v9+fvPB/u3McYc2fOeZ1zXmcuBEUQZBHK3+3fwoXBi47mRQsbWxVba2tbmx1rdUztHSxsbRSlxXbJiu2SlNgpLSa5c6fEjrUqjpeuONqbKtqYOl6xP39px9oTjsaXLEzUTF1P2VqZ2ihKSe3aJSNhKittIi0lJSW5k/j7ISv/59xih0xtrU2v2LuKHTd1uMiC/ZTT/34M57y9yUULJ1PJC9a07WVTGxtHe2MH1oXzV87/PYjNZmN/r3DZFgRRgG3wjSuBNA5vuP++vL+LINiMN4a8vvu/dzO7iCH//J8766hrVD/UW7u8sBNZ5oOu/yOas+bsHPze6/8cK7ORC24fLqVGUDIqf6pz8f/vFvn/lKpPye8qjjDvt549qwLv96lmZ+/zCM1QQZCryv/XT+H/9fP/2ve3ef7nRNj/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_3 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsHTBZN+zD67YsVOx3sKAoICIg0FQUVBUURBQTpAgLSOzxWLCBKlf4oAtKliXQV6U2ld+nlpkiXfi7f/3uS73zJl5yc5MwvW7I7bJmda2Z2yY2gCIKsQvq7/JvWYzC7pnLb2NxCzsLMzML88M5rBlbWxhbm0uICwhICwiJCR8QFRI4cETq8U872jo2tlYG0uYGtjZXOncM7L9nq3jHWUzRwvGphamAuLSoqLHxMyEBCXE9cVFRU5Aj59yRb/3NsAQUDCzMDGytHgYsG1rcJ2E7b/c9p1upY6d02tjMQ0TdbY3HXwNzc1krXmtDXsdH5m4mJiQn7e4WbeBFECpavHtm8WIPDCvPf2co1BMEW3DFk8tr/3M3iKoZs+++d9dY1KikM1W4u6EM2PUB3/+bP4tBcgv3Z/817TIUJQYrh4D+5RMLz/vSt/n9dIv9bSggK+vIiMOyrgk6EHKyf3Plh7Ms5nUw5BPlH9n+ZCv6X6f+x7e/j+c+BsP/MUVhiCI4Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_4 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsHUBRN3yj6yaOCIKIiksyoJBGRDI8BERFQERFJkgUUJGdQUREkoyBZRQUkKUEyq5KzEgWBlbgSVzJL2tvP+3636txTdapu3arbv5pQO7Pd093/7pmBWgiGIIgJ0r/bfxMrAlbXr962srU7a3f3rp2t8N7r5g6OVna2ClKiJ2RET0iIH5cSlTh+XFx471nnO07ODuYKtubOTg7Gd4T3XnY2uWNlqmbufs3OxtxWQVLyxAlpcXMZKVMpSUlJieP4v4Vw/idvURVzu7vmTg7uourmjrcx8Dnp8t9ithg7mN62cjGXMLu72e6eua2ts4OJI2Zm7GT870mbNm1C/r3CbYIQJA+24Y+dQjajYIf939VBLQhCVnwRaLfWf2uzykSgHf9Ts+H2Lg2VsTYOygi0zQ/e/1ekiEd/DRz/ffW/x6U3SAj6ADJv5ZNILFseYf5/3UL/W/rYmPH1YVLCtzPGBWefWJ460xK671vgTNtZCLqv9L8slP9l+X989m/3/Ccj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_5 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp5NFSPH/j/u9KKqKRC2iShUtmNUlS2aFHWNm9J9n1vlyWSSvayS0iUdWixpEII2bNOxr6OMYPvq/fn8z3n+/ue8z3ne37n9/vP83FmLvfeuXfm3jvLHRAUQZBF6O/wb6swuDqnd83C2kbVxsrKxnrPlnNm9g4WNtZKMpL75ST3S+/bKyMpvXfvvj1bVJ1uODrZmylZmzk52l+6sWfLKafLNyyuaJi5nbGxNLNWOnhw/37ZfWZyMldkDh48KL2X/LsSvn+XLaluZmNl5mjvJqll5nCNgPGczv9ZzYpL9leuWTibSV+1Wm5ja2Zt7WR/2YG4esnx0t+Zli1bhv29hzyiCKIIw5B7jkHLcfiB++8Vtg8ucz4YMrP3P4+GtYgha//7yHp/NmmrD9SvKelDeO6gW8ck8jcZsWF68X/nld3LAcuFhdcJSsdQZ/sW/98Okf+t5/MyR8Zcoj7dJj+q/tZTOMLTsu1TaEq9KoLcpPwvl5L/5fL/GPd39/y7IOzf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cobot_Cobot1_CH_6 {
            get {
                return ResourceManager.GetString("Cobot_Cobot1_CH_6", resourceCulture);
            }
        }
    }
}
