//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_Googol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_Googol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1j2BxZu7arqt1dXVWxbdu2M7Ft27adiW3btjOxbWuiifOd93ryY3/7OHbOY9V13Vjoqn6638ybyWi6pmm/+SUqv0yDS9VKLVq2a1+kfdu27dulTVitaafOLdu3y5cjfab0mTNmyZolfa6suTKlTVika5suXTs1zdeuadcunRq2SZuwQtdGbVo2LtO0Z5X2rZu2y5ctW+bMOTM1zZWjcY5s2bJlyeiRPaKopdOXaNq+bdMunXqmL9e0cws3eV+3iF2CDTs1btGyW9MsTdoG2ndo2q5d106NOrubNOzSUJr8fr8hB3RSaFpeNNzDPS7gwthyuVzbpxnf+hvaCYz8+v7b0KL+eWGPLl0tX+L5xUj7HmvOYD3xu3Q74tT5QX3in96cp1nzXnpNuxAvy9w9Xx7//r80wdCXFbfHb7L/9WtmFWxZUM3e32h/Wb+taesHF9T+1684Wp1DecNxDhXZNH3PAc1X5Ik7epHHSXMX0bQBBf7H2Pc/xv+Xk6ejFjLU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_0 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jlOVatLaTrWQn2Ujatrurbdu2bdu2bdu2bdu2bX3PWn1+3O+OcesZM+8755prZQVdVX26u46iKorylw+h4sNycahcoVnzNm0Ltm3dum2b1PGrNO7QsXnbNrmzRqSPyJAuY6aMEdkzZU+fOn7Bzq06de7QOHebxp07dajfKnX8cp0btGresGTj7pXatmzcJnfmzBkyZEvfOHvWhlkzZ86cMZ1XnCOSXDqiaOO2rRt36tA9onTjjs081LUu/85i1O/QsFnzLo0zNmrtb9uucZs2nTs06OhpVL9TfdGk67pLbDCcTFFyoYFunjF+NyYkDpvr+RXXj74uZTlGfPz861Ii/3dhjy5dLVP0+UV772MlPFBN+C7N9li1fjHe/r/ebFszKcrdCEW5ECfjnN3fHv/9v9TVr+DqM0qjfXV0cT2N89VRv58LzGm4790s0n5D8in/62OfHTr4we062GNF0oKL9JIFx8cpXvDR35iFaM77P2Lv/4j/ryaejlzIJY8q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_1 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCRLt7bhymJmZVVqtW3btm3btm3bts3dtm3btv3dEd0/znfGOOsaUfOJGZEorN797r26X5ficrn+8CWq+Aq5eahcoVnzNm0Ltm3dum2bVPGqNO7QsXnbNrmzpkmfJkO6jJkypsmeKXv6VPEKdm7VqXOHxrnbNO7cqUP9VqnilevcoFXzhiUbd6/UtmXjNrkzZ86QIVv6xtmzNsyaOXPmjOl84hoR8tRpijZu27pxpw7d05Ru3LGZl36gy9+rBOt3aNiseZfGGRu11tq2a9ymTecODTp6G9XvVF9sUlXVLW7QSupy5aKGu3nHaB6CKR5+FdFc7u993a53BPH144/bFenfE3t48UqZos8u2HseuayBSoK3qbfFrPWT9W3/9mYrn8nlupvG5TofO+OcXV8f/fm/arLC1dOmuVd3b664qxumid88X6oNs98sHVNnbz794p8/ZQfmc/2vr5/F4+9LcLD0gTXddxb8ebpYwXc7huy/0ndMIZerX97/Mfb8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_2 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1ltNRItLbTnXSS1nTj7u7u7u7u7u7ugw7uLoO7Mwww+OAOg7v74A7fswt+3O+udc+zKu+7d+2qVFVyzgHmwGguTdN+8CEqHwE3l+pVWrXu0LFox/btO3ZIl6hG8y5dW3fskD9nhswZsmTKmi1rhtzZcmdOl6ho93bdundpnr9D8+7dujRuly5Rpe5N2rVuWrZ572od2zbvkD979ixZcmVunjtn05zZs2fPmskj94iqps5QsnnH9s27demdoXzzrq0M8laPn3fxNe7StFXrHs2zNmvv7dipeYcO3bs06Wo0a9ytsRTZtu2WBYZTalo+NNjLGOfVMY5cji23NffngW5tN0Y+vvxwa9F+beze+YsVSj4+F9l9XwsPdSX5L/32uPW+0j/iV22uiZk07VYGTTsbP+u8XR/v//i/9G6c00k8L5rs8d1cMD9m4Q6Fpp6amGlVnTp7msQtcSv78ZGFtP/1Ee/AoMI7yl3fd/h9t2Kfxu4o+iBbkqLzui4rpmmD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_3 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1z9B3ZtrZ3bVVt1Y6tjm3bts2ObVsdq2Pb6dg2O+zYts3vmfOXP+53x7h5xqr3XXPNNReqcnK6T5LjMBwOxy9+iMqPoJNHtcotWrZrX6R927bt26VNVL1pp84t27fLlyN9pvSZM2bJmiV9rqy5MqVNVKRrmy5dOzXN165p1y6dGrVJm6hi18ZtWjYp07Rn1fatm7bLly1b5sw5MzXNlaNJjmzZsmXJ6JE1omrp9CWatm/btEunnunLNe3cwk3c7Baxir9RpyYtWnZrmuXPtr72HZq2a9e1U+PO7j8bdWkkSZZlOWWDkVI4HHnRUA/3WJ8LE5bH85jRHM6v/Z2O2xj58e2X0xHt98HuX7hUvsST85H3PHBEGmwkfp1uW9y63xlf9js3Z7w2Dse80Q7HufhZ5uz6/ODX/6WPZzWJu/FNm73eL7P3fwx0LrjJWtA4Wt66ex/kGN/CG2t8Qcf/+jEs0aoi/Q5d3D/i5OiiFxPVLBon5u3C/7VfWtThGFDg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_4 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1zuBxL17d7Zno8PRPnxLaxY9u2be7Y1o5t27ZtOyc2T2x991rJH+/3Xte776v696tVq1ZVV/dMTs6Tk8ewGYbxmx9R+QnYuVSt1KJlu/aF27dt275d2oTVmoZ3atm+Xd7s6TOlz5wxS9Ys6XNmzZkpbcLCXdp07hLeNG+7pl06hzdskzZhhS6N2rRsXLppjyrtWzdtlzcsLHPmHJma5szeOHtYWFiWjE5ZI6qWTl+8afu2TTuH90hftmmnFiZxd9c/q/gahjdu0bJr0yxN2nrbd2jarl2X8EadzCYNOzeUJI/HY5cNRkphGHlQq7s5xuvAhOTy3zi3Yf/Wz27cx8jP9992I9rfG3t46Wq54s8uRt77yIg0yJb4Tbrtcer8YHzF39wcOVMZxt30hnEhXpY5u788+v1/adj0gwtzPqy479RbZp1rUGDrjkMJ122osO/epGO/f+/tXsD4Xz87NmYusi/z8AOPU00ocqhkwyLzzOuFdi9bUMQw+uf/H23v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_5 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLsJPFZf9O9/JqlUKiGR6tugIpqQiBKaDKmkJEKSOSSZm1BEhgZDaDZUlCHJ1ByZGlAkEiVkFpn/n3P0e/3vva97vV/LWmetdfbej+c55zx774UgCYIYxQ+r2Z9JFH7p7ThsaWe/0d7W1t5Oau5uc0cnS3u7dfLSK6RXLl+1epW0wmqFFVJzNzrbHHV2NF9nZ+581NHERmrudmdTG0uzbeauu+ytze3WycquXLlmhbmCvJm8rKzsquU8bB8CXNPSm8ztbc2POrpKa5k7HWbg5z021stEE0ezw5bHzFcdtJ1gf8Tczs7Z0dSJOWhy1IRNGj9+PMUOcKoEQShBTz7OBE2gYfCzv5pSCIIa8KaIryljL2ZwlCJm/HthDWWftDc1fZyW94OYepr8r2NZpqjhEOK3/+WumchDEKrjCOLD7FUxOX9/jP6/dC/75/Le/DQuWk27aeWR9f9znHlI4Kn7fd31xP/xU7rSRG210ubnJxdeVJvCY6UmVLhJdWH8NTWC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_6 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNoHUBRN3yj6iYuJIOhDDoKKiIKACEhYFRUVCQqISJIkIjlLXBUVBSRIlrASJAuSJINKDoISRJAgOcclLwu3n/d7b9W5p+pU3bpVt3+1M1M7vT3dPf/unoWFYAiCdkH6d/9vOoCAjdbthxY2toq21ta2Nqf47pg5OFrY2shLiYiJiJ+ROCshInNWRuwUn6KzlZOzg5m8jZmzk4OR1Sk+dWdjKwsTZTM3TVtLMxt5SUlxcWkxMxkpEylJSUmJM/i/12D5T9EiSma21mZODm4iKmaODzHwPp3L/1xln5GDyUMLFzMJU+u9tnZmNjbODsaOmKmRk9G/mfbs2YP8W0EmQQiSA3v6x1jgXhQcMP67UVGCIGSLhEAXlf6nMdRdBDr034aNdnarKk11HKwag5h8YP7F0yWcetvg/N7/5pUuIIAyQeHt3BLxFRtju/9f99D/ljghvWo5es5qxfyoiq8QneI49o/i2NHzihD0hPi/vKr+l9f/471/785/CkL+s4XB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_0 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dx5NNTR4z/+10orlYrsUkmFJNlniiIJlaSQqSRZIrvB0KLsOylZEoWE0mIn+xIme/Z9X8Y+tuF7e38+33O+v+8533O+53fO76+f5+PMXDPzmvt6zX3de1+vWQ4IhiBoA+Rf+S87EHClfe2hiYWlkuWjR5YWJ/hvGFnbmFhaKEiJioueOilxWkJU5rSM+Al+JTtzWztrIwULIztb67vmJ/iv2N0zNzFUMyJftzQzslCQlDx1SlrcSEbKUEpSUlLiJP5vHWz/qVpUxcjykZGtNVlU3cjmIQbuZ7b/r7Vsu2tt+NDE3kji/qOtlo+NLCzsrO/ZYPfv2t79t9CWLVuQfxu4SwiC5EG50xHz34qCP1j/XRUrQRCy4oZAGUr/9WJWNxBo73+/sIHGFg2V0YbdBYPQrufwwWmRLC79NfC4238vK32dCYK4QeX1PBLReUuDG/9vS+h/y6/drMWzKFLs9OmIUvwWNaUgHlWlgQ3O8xD0hPi/XAr+l8v/475/e+c/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_1 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNwHUNTe+zD6ZLNJNouCHekqIioCItKbioqKgIiK0lQQUKqA9Pa1YqEIKCgiqCi9iEhvX6V3pUqXIiBVeof7+Pv/7sx735l35s6dueczu8nsZpPNOSfneU5gFkERBFmF8nf5t6yhwdP5s9dvWFkrW1taWlvt23bB2NbuhrWVgpSImMiB/eIHxUVkDsqI7dumbG9xy97WWMHK2P6W7VWLfdvO2Bta3DBSNXY+Z21ubKUgIXHggLSYsYyUkZSEhIT4fvzvMTb+Z9ciKsbWlsa3bJ1F1IztrtPhddLhf47CvGprdP2Gg7H4NUvK+qaxlZW9raEd/drVW1f/bsRgMGh/v+A6QQSRh+VaJ7ovhcEK29+nRRsEoS140pAxm/85mcVVGrLpvyfWW9+krvK7bn3+L2TdXXTHH+FMLr0leD/9v9tKuzARxAN2U8sjHpY792v1/+sS+d/K0sntX3YUqhUkOucoL1WfUB7PfvC1ydP3KIL8o/S/PPL/l8f/47W/rfOf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_2 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsJVE3v/zj6PZy9t7EQiiiEDClJGk99SEVUaJ6JpKI0aT4HIaGSNGmSaB4oaa4PpVkHTZqleZ7n6b59v7+71v/+1/qvdddd6z6vdfbe6+zp2c/0fnatg6AIgqxA+rv+m9ZhsNC4dMPM0krO6tYtK0uBXZomNrZmVpZ0MUFhwWNHRY6LCEoclxAW2CVnf9PO3saEbmlib2dz5abArgv2xjfNrp4zcVK3sjCxpIuKHjsmLmwiIXZVTFRUVOQo8fceHP+5tKCiidUtEzsbJ0FlE9sbNPieuvPfu6y5YnP1htkdE5Frt1Zb3TaxtLS3MbalXbtid+XvQatWrcL+ZnADP4JIw3q9I817NQ4b7H8XhuoIgs0zMeSS+n8fZmEFQzb/z4N11tSrKPZVbyzoQja4o3tGj2Rx6y/C/u3/c6z4OIUg0XDxnztFwvNmu1b+v66R/y3tKLp7Mud8y5fSabvTc145ct3H98iF28acRpC7sv/Lp+B/+fw/vvtbO/+5EPaf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_3 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNtlWBXdGz/62dPds+3uwsQWu7ALRRETA8UACwXsbgzsFgPsTh5bEWzsVkSwEUUU5Xz5/c+Lc87Lsz7XnuHa7GtvBhZrrfte9xAugiBy0HLPuU0mcejWecjQESObjgwKGjmiYlGfgOCQoSNHNKjlUdWjWpXqNap71KlRp2rFok3HDh8zNjigwYiAsWOC+w2vWLTj2P7Dhw5oExDadeSwgBENPD2rVatdNaBOrQG1PD09q1dhcj/D+t9be7QMGBkUMCY41KNdQMgQGs9z4/7Pp4j9ggcMGTouoPrAIGHkqIARI8YG9w+hB/Yb0y/3RTzPk7k/oF6GIOrjrEygFwkUvtByD4rgIsjfk0nCJfyfy/mTQxL2/31hb+89aN8y9a4Rl0zo013Fv1Y6UcAvG9+/xv+f19aOdBPELI4g7hSqvuHMr+Sc/79n4v/TZhWNbRpx6f75uQkLmt0v2qNZ/jwvmySN3NGMIKY0/H884v4fj//Xc7l/nf+9Efm/Iy4RKIIm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_4 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsHUBRN+yj6ybO+opgFSSbAQBCRnFRURARUVDKIiIAICEhORlARUJAoQUBFJInkrKIgkgUXya+Ss+QM9/H7f7fq3FN1qm7dqtu/2p2t2dmeDk93z+zWIiiCICuQ/m7/JhYMni6cMzO3sla0trS0thLYftHE1s7c2kpOQkhE6OAB0UOiQlKHpEQEtivaX79pb2siZ2Vif9PW6LrA9jP2l6+bG6uYOJ+3tjCxkhMTO3hQUsRESsJYQkxMTPQA+fccG/+TtZCSibWlyU1bZyFVEzszAvbTDv9zln+MbI3NzB1MRK9YrrK+YWJlZW972Y64YnTT6O9BDAYD+1vAdfwIIgvbNU6E3yocXrD+farRQhBs3hNDSrT+pzILKxiy6b8V62poVFPqr19f3I2su4vu/COYy6G3CO/7/PdYyTsMBGFC5t+5RKMKZ7tX/r9ukf8t5aUfPPbh4INPPXsDjn1WNjr2gmg6Wvgm9hiC3FL4Xx7F/8vj/7Hvb+/8JyPsP88o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_5 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5OFXfHzj6PZ599nQ0T5JmDSIkIVQqlUozZQqhCGWeNWpSihBCo1KGIokMn1LJnCFCaDALZcx8331/94977593vZ6993n22c8e32et9V77ICiCIONQ/i3/FQ6D2f49R4/Z2mna2djY2UrPPWBu73DMzlZNSUZORn6lwioFGeVVynLSczWdjjs62Zur2Zo7OdqbHJeeu8vJ9PgxM21zt3121ua2aoqK8vJr5MyVlcyUFBUVFVaS/44x+X+7ltEyt7Mxd7R3k9lh7nCUgPWU8/85CmNib3b0mLO5whEb2u6Eua2tk72pA3HExNHk30ZCoRD7d4ITpBBkLSx5V+IajcMHsX+zkjAEwYZ8MOR92P+5mOFxDJnyf19YQ3nlTq3WsolZjciEs+j83ytSxQ1G4Pur//e2a2JFsBGcSqmEQmTG38bx/79L5P9TiuVNNq5au+Xt6UU3N4pIq43T8rU2LHp8ZyOCnNL4f0xZ/4/p/7Xu39P5346w/81RWGIIjhAI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Googol_ZK_1400_06_CH_6 {
            get {
                return ResourceManager.GetString("Googol_ZK_1400_06_CH_6", resourceCulture);
            }
        }
    }
}
