//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotPlatform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotPlatform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3PFZ//Dfw6zrnOkNaSpFoaVNSkayGojSEhqQpZSsjstpLRoNKiUooisoKoUnJyCwKZRbRMEPcr3P63vfjd99/3p6P93m/Pp/zOeca6LrO1/UVCAUCwQC+uM59DSaw2WRkaWXvoONgZ+dgrzhho4Wjk5WDvZbq7Llqs+fOUV64cLbyAuX5yooTdFxsnV0cLbTsLVycHXfaKk5Y57LL1sp8lcXB9Q42FvZaKipz56opWyxcYL5ARUVl3hyKu5WR/Mln61k42Fk4Ox6cvcbCyVKEeebAv9sZtNPR3NLqgMW83XZiDvss7O1dHHc5iXbvdN7JLWJZluDu4vBpAoEmep7LPl8xEmEYt6mpFwiInkOEoKz+38PpHSAEkv89tLqS92v1vhVLZNYLhh8TTvo5K2WsWR/2h/63Vm2KmECwkRYIiuTmhaZ31w/8/3bB//N1++C1F7304Rc+RVWpmqev6WiEjlo25ozyMoHg8KL/UZn/o/6vuf/9vREQ/FaITghI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_0 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJp5XA79+/ava67FEpIkoaKQ0I72ui0V2uxFad9XadOibCnaECqpLCkpKVpUKrQhCm2EurWXFpX27Tlm3L/X6/c8fz69X8ccx3l+zs/MXPn6ds+IRqfRaLP4Ip38WkDgoHfAxtbJeaezo6Oz0+bVRyxPuto6OylvE5eWE5eWlJKXF5eSldoitXn1TncHN/eTlspOlu5uJ00dNq/e527mYGuuael1yNne0kl561ZpaTkpS3lZc9mtW7fKSLLIq3BTJxfXsHR2tHQ76SWubelqw0R/jsff68w3PWluY+thKWPhOM/5hKWTk/tJM1emhambKTk0d+5cgrzFxSI0mhL8g/uJkHkMBE7y8CmbRiMm/AlaafbfjzM5S9CW/vfRWmvqdTS6qrmK2miLz9OFfovlrjScwnrof7NyvmwaLZFFo33ml4krGGub/f912v/zVWFmWLxX3LC4vSdhZyqn4c4yXcOd+98r7KLRzqj+LxX9L/1fvf/5s6ER1JEOJ2FQFZPG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_1 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zh5NNT/v8ffaKGy9JXIvoSKlCX7VhJSCYVK9jWyNva1iGQN2Wq0KKkspbI3ZM1aIkvFICbr2HfmvmZ8v+f87u/ce84995x7zv3D63Ee83z3mtfn/f4wmnEgKoQQCYqc5NpFDQ+Genb2Ts5qztevOzuJ8hpYu7nbOzspSYtJyIpJHBWXkxMTlxGXEhflVcM43sC4WSs5WWNuuJk7ivKex1g42ltqW3tfcHawdlI6dkxCQlbcWk7GUubYsWOSR7eST2GmbC6mYe183fqGm7fYWWt3uy3Q3+6xcc4OczdLO3sPa0mr63TOLtZOThg3C/ctVuY3zMlDtLS01ORbZBJGSBGyCeMSSUcDC0bywwEOhKiXA6kRJ8fGl7NCokZ7/v7Sfrd1nNMY/rYbN4iYblHxTx4u4jBehed/s288L0sFt7cIi1YuSWzZ4iDpf5vo34oqyLqy5IdVpcVL+ZOwVoO1GpWqwUmEglT+Rdy/+J96/7w2iHpjO0jyigZtAbaibdCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_2 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLvgfwXhABQUBAEBABUUHJOUhQCQsKiChJJUclLC5xSYuJlaAIiGQRUIKkQ5acREByziDZXQQkhyXc9txzb913672qW6/q/fX4fmq6u2a6Znp3an5TAxAAgAOY3/3vUJPARl/H9oEjSgnl4IBy5OfUs0I7P0A5yksKikoLigqLyMgIikiJiIvwcyq52ru4oq3kHa1cXdBm9vyc2q7m9g8sblhh7qDsrBzlJSRERaVFrGSkLKQkJCTEhMl+X4Xhz5MLIq1QDlYuaIygppWz7RG4n9zt79c5Zoa2sH3gZiVm6UCJcrJydHRFmzsfsTRzMfs9iYKCguT3Eul4AJCDfaurUzAlKRzQ/m7sGAEg2cGSABPGv/8c4gEJ+GsIpnv6tZD47hNVM4DuKeLsL4EStvu78DjPXxOk+eHyLOGgi13sXcXWzMH/tgf/lmC32LoLR/zqmIo7ZcyexSoppDApswSIKAPgp/gvW9W/bP9l3z/uDSD5s0XAngSQgiOA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_CH_0 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXpAg0RWRnJNkAclRQBEQQcSwRMmZJcojyUNASZIRQVxEkKAoIFmyBEFgQeIDSbIgYUEyCEu49oWq3/3qrurqqq7q/uD7qQ410zXTuzPTUwMQAIAjmF/tr1ARweq2oYOjG1oD7eqKdhPhvGXr6eWIdlOWEZOUE5M8LyEvLyYhK3FBQoRTw8fF28fTVtnN1sfb09JFhNPAx8rF0VrX1s8I7WzrpiwtLSkpJ2ErL2stKy0tLXWe5NdZ6P48uJiWLdrV1tvTT0zP1svhBNxOdu+v81BYelo7ON6zlbJxPYl2t3Vz8/G08jphY+lt+WsQOTk50a8pnhIAQAm23T7uMSeJYYf2V0VGDwDRXjARIJz56+cQjojA310wMzB8TWuhH9kwC06FIrhXRatZTPfh/ua/B8iJwOnZwE4fmxSm7ufs0f+2Bf+WTivTZv8ws+a4uzkaZIxmGqaWphppXQqaAPyu+i+l4V/Kf9r2z7UBRH/WCNgSAWJwApBA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_CH_1 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV7NNT7FsAHlddokEdXD9KDZGa8H+WZ92MQIsdEhjHEzGC8hxmSR4gS5V1SqYjkkFHohJgakxDGqyTdEoYxRswwd9TprnPPunets+5ad637h89ae+/v2t+9vt+9f9+99g/ABwAAuDw27AZAfp5ydw4IxGDNsGg0FqOq4IYMwwViMYY6EA09iIaaur4+RF1XXUtdVcEsIjg8IgxpiEFGhIf5BKsqOEUgggN97ZAxrtggJMZQW1tDQ08dqa/rq6utra2ptnXjlh3fD4dYIbFoZHhYDASGxAVs4fkFI3/cI+IT5hsQGInU9EMLY0OQGExEGAK3xc8n3GcjSEhIiH8jRXElAMCAZ7sjQjKFBXgL0IYSFQUA+FeJ/ACuyI9y2Fx+gNTvpX3sH3Sw+tIn0ToFEE/iU5wHk3bBObz9zt9j9a7ylAZPevdoljZ/m+L+txbwJxp7A9qOb0G1zRYdNfd542d2QxVlFmHnZg4AJBj/QVr/IP/i+/k2gO8LPn5+gS1b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_DKP_400_CH_2 {
            get {
                return ResourceManager.GetString("Platform_DKP_400_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zd3VJPNl8dD7wQUaQaISJUeeiD0XkVp0ktCJ9TQIfTeQqgiIAoiKEXFVwSRSBEUpCOggsCLdAXpPRv059l39+zu2XN2/+STzP3Oc+fmzjxnyskAiAAAAJ7AmZ5BS0ww5jfc3JE+6j7e3j5IYbA5wj/A3QcJkxWVEIWIQ+TlRSGSEuISwmB1lFcgyh8BQyJQgf6OXsLg6ygnL3dnfUSoqY8nAgmTloZA5CQQ8rLOstLS0pLiZGedXPyVW1Qb4eONCPQPFTVEBLiREvwUQb+7oXb0d3ZzD0JIwr2pfHwRSCTK3ymAFO4Y6HgWRElJSXw2QgZ+AECRoLbBpJlUJIQK8Mw8ZwQAiA/RxIBqxt9vc4QnBjD9683mR8eNtJdHGNu+ARjiiLg3RF5etjkmtPv9K1auiGDKCWWYQ7K0df8b/r/TqJ9v7/COuOD0NYq9ZbAYFUal7AJsBS3uVxZcrArgPzE0A+l4swfpaDK53OkoJ6selimlPvsg7w0AEK38j9L2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_JiShi_0 {
            get {
                return ResourceManager.GetString("Platform_JiShi_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZhXVFNbt8cjgkCoIl2a9E6ooSb0XgQElA4hdEjoEEoEJEhHWqgBREFRAaUIcjBSlIM0I026hSotCopSv6Dn3HvuN76H+3Af7gO/sfeaa/zXXHOutdfIHDsbcAYAAByTOLEn0JKRGlsrb59AhA4iIAARKMlnCw8O8UEEaoClZaXlQHIqKtJy8rIgWUk+nTD/0LBguEYgPCw02M1fku9ymLu/D8wEHnUF4QcP1FBUlJNTloWrgGFgRUVFeRDFSZILv2JLG8ARAfDQ4ChpM3iINzlJpwz/nQboFgzz9gmHy3sEUCOQ8MDAsGD3EHIPt1C3EycqKiqykxUyigAA6iTrFEGeSX2W1GE4aQ7PAwBke2gywJfzv3ezf0wGYP5rZwujE+YGqyPn8YsAxsQz/ESptouOB6Txtr98lW+TmlDAf7Ojb8DAP7cABfyTnS0o5RY4D+b95IXoyUIA0prAE7OS/OLkMR4vJ2sC/o2lOLWeabRazyfr/k5sspoudaKa7oT1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_JiShi_1 {
            get {
                return ResourceManager.GetString("Platform_JiShi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zd3VJPNl8dD7wQUaQaISJUeeiD0XkVp0ktCJ9TQIfTeQqgiIAoiKEXFVwSRSBEUpCOggsCLdAXpPRv059l39+zu2XN2/+STzP3Oc+fmzjxnyskAiAAAAJ7AmZ5BS0ww5jfc3JE+6j7e3j5IYbA5wj/A3QcJkxWVEIWIQ+TlRSGSEuISwmB1lFcgyh8BQyJQgf6OXsLg6ygnL3dnfUSoqY8nAgmTloZA5CQQ8rLOstLS0pLiZGedXPyVW1Qb4eONCPQPFTVEBLiREvwUQb+7oXb0d3ZzD0JIwr2pfHwRSCTK3ymAFO4Y6HgWRElJSXw2QgZ+AECRoLbBpJlUJIQK8Mw8ZwQAiA/RxIBqxt9vc4QnBjD9683mR8eNtJdHGNu+ARjiiLg3RF5etjkmtPv9K1auiGDKCWWYQ7K0df8b/r/TqJ9v7/COuOD0NYq9ZbAYFUal7AJsBS3uVxZcrArgPzE0A+l4swfpaDK53OkoJ6selimlPvsg7w0AEK38j9L2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_JiShi_CH_0 {
            get {
                return ResourceManager.GetString("Platform_JiShi_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZhXVFNbt8cjgkCoIl2a9E6ooSb0XgQElA4hdEjoEEoEJEhHWqgBREFRAaUIcjBSlIM0I026hSotCopSv6Dn3HvuN76H+3Af7gO/sfeaa/zXXHOutdfIHDsbcAYAAByTOLEn0JKRGlsrb59AhA4iIAARKMlnCw8O8UEEaoClZaXlQHIqKtJy8rIgWUk+nTD/0LBguEYgPCw02M1fku9ymLu/D8wEHnUF4QcP1FBUlJNTloWrgGFgRUVFeRDFSZILv2JLG8ARAfDQ4ChpM3iINzlJpwz/nQboFgzz9gmHy3sEUCOQ8MDAsGD3EHIPt1C3EycqKiqykxUyigAA6iTrFEGeSX2W1GE4aQ7PAwBke2gywJfzv3ezf0wGYP5rZwujE+YGqyPn8YsAxsQz/ESptouOB6Txtr98lW+TmlDAf7Ojb8DAP7cABfyTnS0o5RY4D+b95IXoyUIA0prAE7OS/OLkMR4vJ2sC/o2lOLWeabRazyfr/k5sspoudaKa7oT1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_JiShi_CH_1 {
            get {
                return ResourceManager.GetString("Platform_JiShi_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE5//Dfws+d1zmWGImSFQrTJnhkhMxESDYUGMjKy9wxlk1E2WRlfM1tEyKaMQiRC4vf6nNyPx+++/7x7Pt7X6/35nHOdc66rrnOdK32/FE1R1F98kSRfJgY3/XsHBoWNaTcmNHRMmF2NfgHhEUFjwjycGzV1bdS0iYObWyMHFwdHB7sa7aJGR0aFB3iEBURFhg8bbVejZ9Tw0UH+XQOi+4wJCQjzcHJq2tTVIcDNxd/FycmpWROe7KW8sfFGnQLGhAZEhkc36h4QEchhXhxfuh9lWLh/YND4gGYjQuUxYwPCwqLCh0dwI4ZFDiMrSZLEkEMsU4+iWiBvRo1dJLNozOSm2nyaYn5NY6iy80sfUPFfhqrw76Fl33vQo9P7jLJnc6gysbTNZ/sTVr6/sfzRvNJ1XSebKSpQoai71ZptPP0j5+//b1L/zxdNxV2wZMZe+Pu3epurVFw7/4fV29eu7tieoqa3+l919n/V/zX3f743FPNvc4zRsehoiqN4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_0 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN11+NNW2PDxpJI0jTRtYbi7u7sMdxkM1+HuNnwMhgxnuLvDcHd3d3d3hj3fc+C9rud9/3z5XHfu+5xI0zSNtP1tiqooyjf+iSz+WR4GNao0b9G2XbF2bdq0a5s+8S9NO3Zq0a5tgZwZs+bOmDVzljx5MmbJlSV7lvSJi3Vp3blLx6YF2jbt0rljw9bpE1fq0qh1i8Zlm/ao1q5V07YFcuTImjV3lqZ5cjXOlSNHjmyZ/eJRonLhGUs2bdemaeeOPTKWb9qpuY9+vev3xwk27Ni4eYuuTbM1aWO0a9+0bdsuHRt18jVp2LmhmCgQCHjEKrqpFCU/+WiX9sMNL0VIDLzPVMXzX1+P8v7p9yf06ZtHifHjqd05c75CyYenw9vvKu5ANemLDBvj1fnM+O0/ps19Jaooay1FOZUg2/StH+5++//Nyv/z73zTtLtv5S21O7h8abGG69IUm9G3b7FnZXIUV5R+hf5XbP9f8X/1/Z/XRvHIIU8RXsWn+KEpuhKA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_1 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE5v/D/ws/dtbyoioUKSGdk7s9KQlagolJVSH7JDRvYWEoWQnezMUEplZJRIWRkN9H1dh9/j8f39/vx5Pt7n9b6uc51z3+7q7pw++VA0RVGV+EOS/NEYbEaP9Pbxn957up/fdH/Lxs5eAYE+0/27dWjdrlPrdm2tO3dubd3Rur21ZePes6fNmh3g1c3fa/asgAnTLBsPnz1xmo/nYK8gx+lTvfy72dq2a9fJ2qtzR8+Otra2Nm158ig19ZO37u813c9rVkBQawevQG8O8+Kcv4+jTAjw9PaZ42UzyU+ePsPL3392wMRAbtKEWRPIIkmSGPIUq5lTlB3y/uwZq2QWTVWyaTGCppjyMIZqNOLvX6iikqFq/fur5T1+MrT/+/TqyflUtXDa9LPVuYZjfmF/3vC/azvtMFDUWJmi0oxsdiWV5lf+/yb1//z5/rv/tXfx/a5JbK0+takBvWdzg3ufnN+jD0X9Z/+/Kvl/1f81938+NhSjb/FXBJpi9eSo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_2 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UFTLggfgHiQqDiBJkCCChCuSo4BDGjEAAooIgkMacpIhRxVJooKg5KCCiiQRECQMIEEYGUSJkhWBISOZGRC2vfe+rbevdqte7db+x++r0911Ttc5PdN1uusABABgF+Z3/TuMVLAwMXJwdHPXcnd1dXcTP3oF64lzdHdTU5CQUZKQkZJWVpaQVpSWkxY/quXt4uXtiVVzw3p7eVq5iB818LZ2cbS5gPW/7O6MdVOTl5eRUZLGKivaKMrLy8tK0fx+CuufN5fQwbq7Yr08/SX0sDgHaniezuev5+y38rRxcPTBytq6Mrh7YN3cvD2tcdS2Vl5WvzvR09NT/R4iswgAqrBu9/a4x7APNph+F7VsAFBRQqlACdtfP2drlwr83QTj3X36OtNdLHUTgDkMceznycoj5tvwesDfHZTE4fBsYaOTVzYTvzmx+7+twb9k4FxiY323R2OOyVENJsVErbIHR7WF+OW0AbiJ+qej7p+O/3LuH3MDqP4sEbCmAvsA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_CH_0 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFVfwwfwfcmUMkSZyRiS6WbMvUQRMpYhY+KSec5MMlWEQlLGKGQKXVNc+pnKmMyZEtcQIdc83Wf3/H7Ps573We+71rPed73/+X7W2Xvfc849Z99z1tn7HoAAABBhfte/c4wEFkb6t+1dXFVcnZ1dXUROG2I8PO1dXVDSopKyopLiEnJyohIyEuclRE6reDt5eXtgUC4Yby8PKyeR07ret5zsrTUxftddHTEuKCkpSUlZCYycjLWMlJQUUpzs91kY/n5wUTWMqzPGy8NPVAvjefsIXE9x58/zHLXysL5tfweDtHGmcnXDuLh4e9zyPGJj5WX1eydKSkqS312kOwOAAqw7vd1iqEhhg/Z3gWMEgGQnhASUMf75c3aJJOCvJpjuG9RWm++lr8cDujAEz8q5ajazPbjd/68dZEVg92xg4wsHMr1uC0/839bg3zKIEW6kvqPeeLS4UMWqQkglIyREBeUhdQmAu4r/stT/y/Jf1v3j3gCSv5cIWJMAUnAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_CH_1 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBRPogfwXlDJIEFBMiI55xwUFckgEgQlB5GwwrKkJZlARAmKiLCAZCQqCIpECSJZYQHJQaIKS1wyXPsLV/eu3qu6uqr3H99PzXTXdNdM74SeHYAAABzA/C5/h5IIrswu33DxQGog3d2RHsKcpo5eKBekh4qsqKS8qKS4hIKCqISchLSEMKcG2s0b7eWo4uGI9vaydRPmNETbubnY6zj6X0G6OnqoyMhISspLOCrI2cvJyMhIiR/9fRT6P3YuqumIdHf09vIX1XNE3TgCt5P4/Hkcclsv+xsuPo5SDu5kyFuOHh5oLzvUEQdbb9vfnUhJSYl+D/E4HwDKsOxA33pERgwrNL9XZQwAEG2HEIFXDH/+nJ0DIvBXFUzh+vU153toa6fB8buI00siFSzXdmG7518d5IXh8BxgpZtNKqV6c/rgvy3Bv4VEVathrvBig7kb7XnnB5c00Ed0NEoD1M8DEKr2L0vtvyz/Y9vf1wYQ/bFGwJIIEIMj4Ch0DJAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_M8DM1_M9DM1_CH_2 {
            get {
                return ResourceManager.GetString("Platform_M8DM1_M9DM1_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxlWFRdtAfw011joIKKjQqiiKSK3WIrJia2WGB3d3cndncXNlgoIIiFiAEWJoLe/z6+H+5zP15/z5q19tr7nDNzZkAGZoaiKYr6i38kk38ag4uQVn37hQ+uM3jQoMHhHsXahQ0b3m9weHVfz8r+npUreQUEeHr5eVXx8ihWJ3JgROSwsOrhYZERw7oP9CjWIrLHwH49m4SNbjN4QFh4dR+fypX9vcIC/Hr6+fj4eFfiyVHy2jv3bBA2eFBYxLDRnsFhw/ty6Isj/h1H6T6sZ99+I8K8ew2SBw8JCw+PHNZjONere0R3skiSJIZcRcuNoqohx0YOmSezKExy0S6JppjsiQzVOOnfDfr9l6Hy/XfTXj1MaNbgbZzjQhplTaVLfKpwyqVzDubz/LfWv6ODogYqFPWgiPeGcz/T/v5/M/V//rWYOO3KQ+Nr9LZNS6MPT5pWp8Ssp3UKnipch6Im1fhfceF/xf/p/fePsS9xE4HcXA54SqBE4BESkM6/LGEN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Revolving_0 {
            get {
                return ResourceManager.GetString("Platform_Revolving_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx1WBXdGzf66U4DFbsDRFFBULEwwVZMDFRAUUTBwO4CbFTs7u7uwG6xC0VExcLC4v2ueX7nut5z/jx8rjX3vdasWTN7Zth7BvbeFE1RVA5+SCQ/GoNJhzZ9+g6I8o+KjIwa4F6sfWh0TN+oAX7eHlV8PKpU9vT19fCs7lnN072Y/5D+g4dEh/oNCB0yODqkv3uxVkN69u/bKzB0eLuofqED/Ly8qlTx8Qz1rd6rupeXV9XKPFlLbmdwj8ahUZGhg6OHezQPjenDoV0c+t96lJDoXn36Dg2t2jtSjhoYOmDAkOieMVzvkMEhpJMkSQzZRKssRdVCvDpkYILMIjHJ5PMTmmJ+jWWotCf/PaDfOQyV538P7dWdey0aZ9y2T6RR1kS6xKeKhwoG/8H8bf/r63PDpqhhCkXdKlx1+bGfaTn/fyP1//kR5yadyR2ZdXZ8uHZGmZ3kv7xGUf8/wZo/RY2r83+VE/9X+X+1/T/HhmKckgubSVMsxVE8CJRISSBT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Revolving_1 {
            get {
                return ResourceManager.GetString("Platform_Revolving_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNTvHsfHlr1JjWSLhlCWMRjrmMnWWMaaKGtomLHMYGbCiCEla/ZikomUtOiXpaxRSZQljEHEz2S5RIgi66V+3fO7v3PPPb9zz7n/eZ3zeT7PeZ73eZ7P5/v9nM8DYAMAAJtbbPttBNi3Bkc7LA5PMCIEBBDwStIOmGAijoDX11RR01ZRU4Xq6KhAtaAaUCVpI7I/iRyM0cdjyKRgD38laRuypz/OywITZk/ww+D1YTA1NW0oRkfLSwsGg6mrcm3fsu/H4SooDCEAQwoOU7HEELGcW+vc537ew+cR7IXFncOonw3gJQRi8HhysCeR86wHyWNbxMPDw74d4h55AAC+5dvIgUm8HFsT4PZA5AcA2Feo7AAf/p/prG6yA0B/pDbK6LVCTXYL1Y8B9sSwgeeUq8Rd1rb2IX9ota9uDWpb1iWpnle3PLb5v3rAX0DBL71E8C025t/MaLTXv2Sk927IKI8XbAQARCH/ZPV/sn9b+/VvAD8mbOzsHJxcXLu2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Revolving_CH_0 {
            get {
                return ResourceManager.GetString("Platform_Revolving_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5NNR7G8CHCNmVJiFCWQeDychuzCW7IbtkGWMdDDNMGbQwYydh7JK1hEu3UrqJsWStLFG2NLYpqWtnMi9173vue8/7vuee95z3P59znu/zPc/3Od/v8/x+z/f7AJgAAABjlz29Bxfz7mCP8PFFB8GCAgOD0AridkhMqG8QWvuMogpUUUUZrKGhCFYHq4EVxGHYgDAsBqmNRmLDMO4BCuJWWI8AX09TJN42yB+J1oZAVFSgYKSGuqc6BAJRVWbdO+Xw980VjZBBgcgwDF7RHBnqw7JrZ8P9OOeQO8bTxxeHVPUK5AgKRqLRWIxHKIuXe5j7nhM7OzvzXoh80gCA1q7uxQYncRzYnfDuDVc5AQDmrWhmAI7zRzrbDGbAkd9Tow6+sTBaGOB/NgPgu8Yk8QXUKOxC313X+d0XmrU7qOzKa1HVwqcbM4z/VQP+AraG3NpGWKdcQXG1ijwkw+4GqsHoLlwwACBG90/y7E/yL7Y//g3g+4SJmfkACyvrwd1P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Revolving_CH_1 {
            get {
                return ResourceManager.GetString("Platform_Revolving_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ7PJTpHgDwd9wvidwLuUfrTozbGFGNImxJ65IhJnfDMLmbaSKpmKRCbrXqlK2wtRYlapE6thSq3ZzlpJBSQmgM5vyGd3btfs45f+2f8/t8vvO+M8/jfX7P8/w+jxfBIAjCgeBeubFKAD68d4WFx5CdydHR5BhDDW8SJT6cHIPDGpvbGJtbmJlijS1MTc0MNZypUQlUCgkXQ6ImUIKiDDU8qfujwoNdScle5EhSDM7S0tzc2oxkgw3GWlpaWpgKcweRW3q2MYFEjiYlUJKNd5Liw4Tgd9GDy8NIBFGCw8IPkixCosXJsaSYGCplf7xQSFBCELeTmJiYADdDGT0EsYdrflZCnrgg3EhzP4qkEERgjiaAnJBang2bI4DIozN70/vCnTDas6ZlCJE5jNH6ZNSo4j8P7V5oX+vz8OECutUsyu98GeL8ryv6PGRpyZQvOfK+c/NBYrN//86Lx7T+VhF6fyuGbtK2id7vPE/rd+Zw6n9CEDp+hZYV/vQbZuWA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_RP22P920600_0 {
            get {
                return ResourceManager.GetString("Platform_RP22P920600_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bt5ONbP2/8/Q6VSqUQpUSmi7IQKlUqLIirZiywRQrJTSZKlQvY1IpJdKaHFXrZk37Kv2ff1d76u63Lf3ffv8/sex+84vn86n8dj5pw55zUzr1m4er8vCCOEFsGInLB1VJBclde7ZWQsZWxoaGx0cNdVbVOzW8ZG4iI8AmI8AoL8fCI8gnx8/Ad3SZnfvmtuqi1upG1+1/TG7YO75Mw1b9/SOq9tddnYQNtIXFhYQECUX1tMREtEWFhYkG8lMQg9qW8eaW1jQ+27plY8F7TN9FZAPc098jBrb5hq6d26py1403CN8R1tIyNzU02zFTdv3L1BNFq9ejUVMcONHAgdhfyF012PNdTg0BFJ3yGEqGYcqFDzIfLbzC5SoS2UN2v/XX1RuqdiU3YH2uiI9wxxf9yhOgfxaEpb0U6Y3k3g107BkMypjsX/r9wsOqMnY/7ll5r27Me/zN4dO35fWND6w8Mvx8j5MfS/rPcFQ878IkOOhdHot52eDCenFhlOtpeZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_RP22P920600_1 {
            get {
                return ResourceManager.GetString("Platform_RP22P920600_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEWFBGZl6+c35ubn6ejkJYalFxZn6erbmekaWekbGhgbmesYGBoY6Cc2lOSWlRqm1eamlJUWKOjkJAaVJOZrJ3amVIfnZqnq2pqZGRhWGqpXmyuampqbEBK8gSYbDZeu6p+bmpJUWVer6pxRksQHH2Mog1XIlFyRmZZanGKbmc+QWpeXmlRUnFLCmJJYkgRRwcHEwgFwqoMzDYAOmJrSV9nMxABj+IqAAaxPSrnokhhwXim9//mRhEoD57cuW6n/vLy4L7nzIINDMqfdDdKR3zByhvAlVrEQIkZID4kqzxvL0/nv4nl2ZAA+fq7x1ma7h3mLFB/4hJwz3nP/X3nP//336IgaHBHgnvR8IoYqDoARsEjiNGJiZmFlZWNmBQcHJxc/Pw8vHxCwgKCgmLiIiKiYtLSEpJScvIysrJKygoKikrq6iqqalraGpqaevo6Orp6xsYGhkZm5iamplbWFhaWVvb2NrZ2Ts4Ojo5u7i4urm7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_RP22P920600_CH_0 {
            get {
                return ResourceManager.GetString("Platform_RP22P920600_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFV7/wfw73c3SEQlIZmTqcjUMRx0U5kyXA0kQ0SmOJnHwy1K5uRmSMiVpEimogyJzFEyZIjMGXJwcBzncH7feu6z1vN71nrWetZvrd9/3q+192efvb/ru/c+e6/93RtAAAAD5Wf9GVYMzc4bOzi6EjQJLi4E10OC5+3cPRwJrmo4aTllaTl52SM4afkjR2QPCWp6XfX0crdTc7Xz8nS3vnpI0MjL5qrjZT07v7MEZztXNUVFOTklWTtl3GWcoqKi/JEtP3fC8atvaS07goudp7uftL6dh8NmtJ7J+x+72W7tftnB0dtO3taFmXDNztXVy93GY7Ottaf1z0bbtm3Dfh7hTjEA8KjG3fSMYd6EFth/znr3AoCtBmOgde8/zobGwMCev89stKPbQGvy866qMbAzBArPHS7jNaej7Ql/t1U6jTquRQvtfPJpFStjjP9rBf+WqTjO2jUGZ62PK/kd313OEysMzhOjH91yAfhD41+mqn+Z/te6n5fnV0fY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_RP22P920600_CH_1 {
            get {
                return ResourceManager.GetString("Platform_RP22P920600_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zh1UFzdlrdxQvBAgtMEEiRYgDTWWLB+A8EtBAsJ7sHdneA07u4QCC6NhSY4wd3dtdFmOu+9t+p+U19NTU3V/DFVPFV7r33W+q11rM7epzYKKgoKyj2SP/YPeGjITkPZxNTKWsLa0tLaio1O3dDWztTaSpiXg5ufg/s1l4AABxcf1xsuNjoJBwt7B1tDYStDB3tbfQs2OkWHzxamX2QNXVStzQ2thIFAbm5+LkMBvi98QCCQ5zXmn7OQ/F2cA2xobWlob+vCIWdoZ4KB9GM7/uM8j/Vtv5iYOhryGFjiWNsYWlk52H62wzDQt9f/I3r06BHan0skYkJBEULaAQebbzjoyAHhn06WCgUF7doLDUWU6h+3c3OPhkL6z1tbG5uUB2+PEkPXUYj8UOmP2BuotG+Rcex/avl3kN0gsv2m4UlvuVy//59alP/EMBpXl204sKuuUrhrtklAMtMAKIl1FN+BguIt+m8N+m/t//H9692g/D1ARUNDx8DExEI+CpzH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_SMS_P_0 {
            get {
                return ResourceManager.GetString("Platform_SMS_P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp1UFbR1+/PAQWUUlBQUlBEurtUQAQkVVq6uzskFJBuaQUJpUNC4hHpkFS6u7vzbh75zbz3nXtn7tyZ+88dvp/ZZ6/1XeucZ5/9HIaDIwRDEHQGdD6fCwsFHBTlDY3MLYQtzMwszOnvKehZ2xhZmAtwMrJyM7Iys/DwMLJwsbCz0N8TtjO1tbPWEzDXs7O11jKlvydrp21qpCOp5/TKwkTPXICDg5WVm0WPh0uHi4ODg4356vmn4CMvziimZ2GmZ2vtxCilZ2N4Bfjo9v8+57qWtY6hkb0em67ZNQtLPXNzO2ttmyu6WrZa500YGBgo50u8QQ1B/GD+bWcZeA0VBLjnh7csEIRy6IEC2bL8u52jMxTo1sWtTf/pkxZb6LmJmIFueMOU6wzlxGrHoM5/0csdCZanBkY3KVtS1f7M2f/tDP03+WJG1xngRddlu+P+eokdLdJxGiXC8gLrCViv0H8ZiP8y/ifvP98NhII8wmBGQWaoSK5AVwGoYPzrgSE0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_SMS_P_1 {
            get {
                return ResourceManager.GetString("Platform_SMS_P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXgUREYm65KisiBIls2QEBZGkoLAgYUkiS5ScBEGSgCA5CoIICJKUHBVQ2JUs+YlkBCWzSLj2vfe7+t2v7qp+dVX3x1Xx/dR0d810zXTv7PTUAAQA4ADmd/07J4/AQl/H2sYep4S7fx9nf5HjFtbJ2QZnjxbjF5bgFxYUkpTkFxIXuix0kUPJ1c7F1QmLtse6ujiZ2l3k0HI1s7MxV8d66OHuYe3RoqLCwhJCWElxc3FRUVERQdLfV6H78+T8qljcfayLkwf/dayzNQncT/bgr+ucMHUyt7Z5gBWxuE+Oc8Da27s6mTmTWJi6mP7udPz48SO/h0iNAkAG1l2uDhHkR2GD6ndx6TQAR3b8jgDO039N59fBEUD/99Sm+gY1Ved7aRqmAXUgguvnpSpmo114fP7vDhIX4fAsYKOHVSS9bnv64H9bg3+JxQuh1nZSsdaX9ehWnRlJ5fEnospVDPHNAPjL/dPW8E/bf9n3j3sDjvxZImB9BBwF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_SMS_P_CH_0 {
            get {
                return ResourceManager.GetString("Platform_SMS_P_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBRPmwfwXkQByQKCRMkICkiQnERYgpIMCIjknFlyEFAByUFyFlSCJAVEkCRZJOccFxCQHCTvte/vfa/ee+uu7q2ruv/4fmqmp2a6Zp7Z3umpAQgAAAbmT/snBFhwpalhbmFrJ2tnY2Nne/3qIxNHlIWdrcQtbj5hbj7emyIi3DeFbgrcvH5V1tnaydnRRMLWxNnJ0cD6+lU1Z0NrCyNlE/cHdlYmthKCgnx8wjdNRISMhAQFBfl5z/+5CtnfTs6NNLGzMXFydOe+Z4Iyx4b7cVz+us5FA0cjcwsXE35jGzw7exNbW2dHQxS2sYGTwZ9OuLi4WH9KJGEHQBy2Hc72oXjn4Abxn1UGBQBYhz5YIIbir9s5wmAB8r/fGrp/SAW51EdaOw9IXiCYNm5U0Dw5hsef/L2v8HVYnjHc6KXjT6ven8f8X1vwL1keim18uxjbWHqfuH6aNu6O4M+4O1KqhDIA+Er901L7T8t/2fePsQFYf1sjYIsFzgFscB66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_SMS_P_CH_1 {
            get {
                return ResourceManager.GetString("Platform_SMS_P_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iEgAEky/6pkYQpgh3vn9n4lBBOq1J1eu+7m/vCy4/ymDQDOj0gfdndIxf4DyMlC1FhIg/wPxJVnjeXt/PP1PLs2ABlLTkhz2f7Y+8v//T2f7NbYuzjzWLofNpF0YGBrskfB+JIwiBosbBjCDEeh/JmZmFlY2NhY2dnYOTi4uDi5ubh5ePj4ePn5+AUEhISFhAQERUTExMVFxcQWgJkm3rbcYGRoYHEKgBlXc8vb2Lrrx/eYvDubD+um7TbfpvXjjnHZJLzPAVMFsl5S6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_WoodMove_0 {
            get {
                return ResourceManager.GetString("Platform_WoodMove_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iGAGGsT0q56J4TszxDu//zMxiEC99uTKdT/3l5cF9z9lEGhmVPqgu1M65g9Qfj9UrYUBkJAA4kuyxvP2/nj6n1yaAQ2YbPfdd+Cz9REQe9rPny5OPNYujAy/nBkYGuyR8H4kjCIGixsGMIMR6H8mZmYWVjY2FjZ2dg5OLi4OLm5uHl4+Ph4+fn4BQSEhIWEBARFRMTFREXFxCUkpKQkpaWkZWTk5GTl5eQVFJSUFJWVlFVU1NRU1dXUNTS0tLW0NDR1dPT1dHX19B2Do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_WoodMove_1 {
            get {
                return ResourceManager.GetString("Platform_WoodMove_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iGgDEky/6pkYqpgh3vn9n4lBBOq1J1eu+7m/vCy4/ymDQDOj0gfdndIxf4DyTlC1Fiog/wPxJVnjeXt/PP1PLs2ABlLTkhz2f7Y+8v//T2f7NbYuzjzWLofNpF0YGBrskfB+JIwiBosbBjCDkYmJmYWVlQ0YFJxc3Nw8vHx8/AKCgkLCIiKiYuLiEpJSUtIysrJy8goKikrKyhuAmvYtcdjJyNDA4JAENajilre3d9GN7zd/cTAf1k/fbbpN78Ub57RLepkZWXMq1sRu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_WoodMove_CH_0 {
            get {
                return ResourceManager.GetString("Platform_WoodMove_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erZmekYWekYGhpaWeobmhiaGOgnNpTklpUaptXmppSVFijo5CQGlSTmayd2plSH52ap6tqamRkYVhqqV5srmpqamxASvIFmGw4Xruqfm5qSVFlXq+qcUZLEBx9jKIPVyJRckZmWWpxim5nPkFqXl5pUVJxSwpiSWJIEUcHBxMICcKqDMw2ADps6UFPZzMQAY/iFgFJJh+1TMxzGOGeOf3fyYGEajXnly57uf+8rLg/qcMAs2MSh90d0rH/AHKp0HVWmgBCT4gviRrPG/vj6f/yaUZ0IDJdt99Bz5bHwGxp/386eLEY+3CyPDLmYGhwR4J70fCKGKwuGEAMxiZmJhZWFnZgEHBycXNzcPLx8cvICgoJCwiIiomLi4hKSUlLSMrKyevoKCopKysoqqmpq6hqfkDqPlE3kE/RoYGBodcqIEVt4zvvdud/z/9tTKPg8HX5/7iPt/005NNTPef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_WoodMove_CH_1 {
            get {
                return ResourceManager.GetString("Platform_WoodMove_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV5UNNJFsd/+UHIAbkg1w8ICSEoqJwRBYFJdvAaD3RRzlUOISMIJBhIEAWCouIxCLtYAgqig47rAEEREBaQI9kREdABERnlFkHMAAIOIMRM4uiua21tzW7V/sen6vXr/v2+1f2636tuAAYAgEqNxmvQA9WNt0doGF/gJoiMFPBXMLx4wugwAd91tbUd29rejr3SUd2xtbVbwXATRcSIhDxXPk8UIwyKWMHYLtoTERa8mRe3UxDO47s6ONjbO9rxnFYHr3ZwcGDbwjWrGLyf3HoDTxDJixHGWW/lRYdqq78jxL+tgw4SBoeGiXnskEiUIIrH54uEe6K1Q4JigjQiJBIJakLELwUAF7XvTlh5BqWl7uA0TQYSAMC3EhBIQf62nXkVCBA/bO35o073DS/bCbVDAD4ZxpywqjTataD+v+2D1nGJutmotjYa+2LN7JDqf/XAZ8CA72UaE6vYcrV301hau6ABAJI4n1jtJ/Yv32D/nAgAzLVA0BxksbTUAy0A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_XAUAT_P_0 {
            get {
                return ResourceManager.GetString("Platform_XAUAT_P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJt5XE1f9PfPORpUiCKkAUUi0jyXEqk0T0ST0qBJJUkTqaRRmjQoKVGkUSoNaEAoDUqz0qRBE6GiZ+3d9/d6/Z7nz6f3a9/P2vvse+4553b2WmuffQmSIIhl+EOK/tZQ8GKka2vn5HzY2dHR2Ulgu+FZVzc7Zyc5iQNCIgeEhUREJcE4eFBIYPthd4cL7q5n5ZzOul9wtXAQ2K7tfsbBzlL9rKe+s/1ZJzkxMWFhSaGzUhKWEmJiYiIHadGnsOKdH1A56+x49oKr5wGNs262NNBOf3HlcxgtXC1t7S6eFbFyZHA+f9bJyd31jBuNlcUFC9Rp9erVFDrE9XwEIQva4yMawbAKDGb0ciuBIKgFP4oISlg5ncVlitj436kNtrZrqnxr2VA1RKy/Ru6c3l+67fQSbNf8r6/kHOzYlY4gmjlFUip+Dy3//yrx//ztJtlqbqxnq3nJeP5Vw9ImZUZaNmUL7kdyBHFF4X+Vqv9V/q+2//luCHTi74h64i3QQbQS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_XAUAT_P_1 {
            get {
                return ResourceManager.GetString("Platform_XAUAT_P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEeFBGZl6+c35ubn6ejkJYalFxZn6erbmeobGekaGxiQWQYWBgqKPgXJpTUlqUapuXWlpSlJijoxBQmpSTmeydWhmSn52aZ2tqamRkYZhqaZ5sbmpqamzACrJFGGy4nntqfm5qSVGlnm9qcQYLUJy9DGIPV2JRckZmWapxSi5nfkFqXl5pUVIxS0piSSJIEQcHBxPIiQLqDAw2QPpurUkfJzOQwQ8iVIEGMf2qZ2KQZIF45/d/JgYRqNeeXLnu5/7ysuD+pwwCzYxKH3R3Ssf8Aco/ZIbIW4DMAym+JGs8b++Pp//JpRnQACPDqsMgXPbf+AiQdgbh/sv5hxgYGuyR8H4kjCIGih+oQSCCiYmZhZWVDRgUnFzc3Dy8fHz8AoKCQsIiIqJi4uISklJS0jKysnLyCgqKSsrKKqpqauoamppa2jo6unr6+gaGRkbGJqamZuYWFpZW1tYXgKH51IpLhpGhgcFhO9TFFbeSEyKenmE4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_XAUAT_P_CH_0 {
            get {
                return ResourceManager.GetString("Platform_XAUAT_P_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBPto+jxfTYqKihNOhILiliIyouAVAGNioIIgkiTJiBCgNCrCFJEQUQFlCJNkCoCL50gUgSB0JHeidJ7CYScx/f3OzPnnpkzc+bO3Jn7B9/PJM+S3Ww2m52wGwQgCEKH/Rn/xITCO63b5hbWBEWClRXB+vQhTVM7ogXBWkZc5JyoyPlzon9JwImzZ8+dPqTo8Mjewc5UxtrUwd7O8NHpQ7ccjB5ZGCubumgQLE2tZcTEzp+XOGcqKW4sLiYmJnp2559XYf9n5SJ4U4KVqb2di8hNU6L5Dvg4g+O/XmevoZ2xuYWjqaiJ1R6Cjam1tYOdEXGHiaG94Z+Fdu/ejf7ZRBYhBJGGY5/HX8F7MHCC+c/deUEEQaleKHJc8F9vZ4OOIgf+/dZG2zpV8L9bWUljCIsPODJ3ppBPdxPOnzn6r/kSV+EquOEmthwUjSldG6P/347If+s44KwMZOGs/LrXpqJxk0Np705OJUNsmgyCPJb7LzfSf7n9H4/9+Xz+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_XAUAT_P_CH_1 {
            get {
                return ResourceManager.GetString("Platform_XAUAT_P_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5PFV7+C/wtfaw1mrSIKWIJikyFhIpzaU0IFNSpDKXuUynpJSiSWlAk6EklSkJDaJQMiSJVETIlGTmftY6597X794/r/frWc/zfb7ftTb71Pbd7XUIkiCIYXyxmf0azcPBeOs+WyfnFc6Ojs5O86dvs3FxtXV2WqKuqLpIUVVZRVNTUUVDZaHK/Okr3B3c3F1sljjZuLu57HKYP32zu5WDrbWezUFDZ3sbpyVqaqqqi1RsNDWsNdTU1BYoC9lHEeUurrjGxtnRxs3loOJGG9d9AvRpj38fZ+QuF+t9th42C3Y7jnDeb+Pk5O5i5SrYvcttF7uIYRge+y2OkyUIbeS37vtPjeCjGMsemFKC4PX584iBkn9/nP5hHjHxvx+truyj/prG0vHZP4hxAeTMdoV0ie0DmM/5b+2iFwxBDAkJomTagsjMnh/D/7+Z+H++5hPtLzeLt79UI+e+vDrctmKDePuKf2f+Wfo/Ivt/xP/V+9//bQgedySReQSfEBBC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Yancheng__P_0 {
            get {
                return ResourceManager.GetString("Platform_Yancheng__P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nPt5XA3//wd+z3LOzLHvyZIQQpsWtGfPViFLKkUp0kaLpO1NlrTaIrRIFMoSaaWkhUJRFKWitFBJJZW232Pm871ut991/Xl1vz3P8/laZs7MnDmjzhkESRDEEH64zP2MpPCwY8t+GwfHlY729o4OsjO3Wzk52zg6aC2RV1KVV1qkqKYmr7hUUUVRduZKVzsXVycrLQcrVxenPXayMze5WtjZWG6wct/qaGvloLV4sZKSqqKV2lLLpYsXL1ZeJOSeZQK/cnldK0d7Kxcnd3k9K+f9AvSzh//3PMP3OFnutzlspbzXfpjjQSsHB1cnC2fB3j0ue7hJIpGI4jZxrDRBaCK/dT0YOIxGMYZ7mP+BIKh/PhQx/cP/dqdviCIm/t+uff9Qrq/7o3RcVj0x1pec/VsubZppP8a/l/5vXPWEiCCmMwRRIqEc+aynfuj/30z8//wM/FedMwnx6D+5XOSVSgiZrrk5BPGfzv8rsv5f8f/V9/95bQiKfySRKYImBIQQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Yancheng__P_1 {
            get {
                return ResourceManager.GetString("Platform_Yancheng__P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXiSnJSkiQYIgSE4iSEZBCZJUQEBUMgJLWmDJUVSUJDksyUAQ8LEYkKSCuEjOsCQJkiWvIPHa997v6ne/uqv61VVd3T98P9XTXTNdMz2ppwYgAAAHML/r36ElgQsTIwdHV5QGysUF5SrCfd3Ww9MR5ap0VkzqnJiUhKS8vJiknKSMpAi3BtrZC+1hq+Rqi/byuO0swm2AvuPsaK1ji7mKumvrqiQrKyV1TtJWXs5aTlZWVlqC7PdRmP/cuZiWLcrF1ssDI6Zn6+lACtdTeP91HOrbHtYOjt620jYuVCg3W1dXtMcdT1Kb2163f3eipKQk+T1EhtMAKMK6Fe32iOoIbCB/LzZZACDZDiYBCyx/nc7OAQn4uwmmevqvaM11M9Z9BwzhCN4V0Up2i124Hfd3h3MicHg2sNHFKY2t2fp+8L+twb+EB7FSL5u0Vk/UFKp3/bCmoS+4oqHD3agMQIjKP5W6fyr/Zd0/7g0g+XOJgDUJOAJIARlE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Yancheng__P_CH_0 {
            get {
                return ResourceManager.GetString("Platform_Yancheng__P_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ZV3UJPZFsBDr9IhSg8tIiUCIgktYpQICJEu0ksUpAQCASGQRBABpaqAtMSGENtTUJASFUFERXCRIosQxUgE6eCGSMkGyxvfzpudnTfz/uM3c+655cy9537n3PMBeAAAAIfLul5HnJfbeLqEhkVhEJjISEyUvroHGhsbhomy2mloDDU03m4EgxkamRntMNJXR+Ai4nBYtFUUGheHDYzQVz+AC4oIC3ZAJ7phwtFRVqamxsZQIzTMLNjM1NTUZLvA+imy3zY3RKIxkeg4bKKhIzo2lJ87LxT//RzRQGxwaFg82iQkUgQTjY6KwmGDYvlDAuMC142EhYV5112UAgMAllz9EhedLcLH7UiuN6kiAADvVyIvIF7k+3WWObwAuR9XY/QOOCHHX0s//AiQSuPRmDVoUPJZ4a5b/7CFFnEbY670qJiQaUsfOf+rBvyFVdJIqzxXakgGbVyNMOaK3hftVgCABP9FHv4i/zH3MzaAbx0eXl4+fgEBQe6nEBEVExPf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_Yancheng__P_CH_1 {
            get {
                return ResourceManager.GetString("Platform_Yancheng__P_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5WA3//zfw2c6cOccSQvYQilQqkRZZUkSLrcUWknbRHilKSEhkKZSQbEmbSmUrIillSUoRSokkSkV+z5mP+7p+9/3n/X1cr3m+3u9ZzlJnzkw+X4IkCOIv/scn/7/eFBZWSxydNrnPdXdzc980ebSlvYenk/sm/WmqGtqqGlPUZ8xQVZ+uPlV98ui53q5e3h72+pvsvb081rlOHm3hvd7VyW6hvf8ydxf7TfpaWhoa2ur2M6bbTdfS0tKcIuIfRVY4uKqxvbubvZeHv6qpvacjg3mxz3+PI13nYefo5GOvucFN4r7ZftMmb4/1nsyGdV7r+I04jqP4p9hPkSD0kE+8N++X0Ghk+EXwAJKguoIowmfAfy+o+y9FDPz30j48rzAzbnzW//ZHol8IOfabSvbwVb+xfua/bbWLpQRRJCaI8pGasXm/Pv79/03i//kfSSTnz0BtC1EqQD+XL5uC/HsEscPgf9Xt/1X/19z/+dkQ1L/DUUATDCECmmDRCW8g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_YIMO_P_0 {
            get {
                return ResourceManager.GetString("Platform_YIMO_P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNl3PFV//Djwc8+5RkaUkJ2ISvaqrCayJXvvZO9NRighSZRZGckeERlJqMxKETKLsmXv3+veT7/f4/v7/fnzfLzer9d7nHOPew7nuBAcgiB78EXIhC8qFBrdq9ftnJwvOjs6OjudOqJj7eZu5+wkIyEgclpAREj4zBkBYUlhMeFTRy56Onh4ulnLOFl7eriZO5w6ouFp4WBnqWzte83Z3tpJRlxcROS0sPUZSUtJcXFxUSESwqvQEXcuoGDt7Gjt4eYroGrtfh0P42Re/70Ohbmb5XU7L2tRK8d9zi7WTk6ebhbueCtzD3PCInJycpRwiLS8CCINucPT5e4+DAoaQuMcgCDoZjCKWAb89+1s7aHIoX/f2s+eXjWFP18ONPxCaMNwRxf4q1mMtmGe79/a06lwGFGwm89soul167/2/n8z8v98mVxeaPqrtdB0SKTzrQnpwkXRlfmLRXZDMghyU+5/RMP/iP9r7H+fGwQltjjIKLQYggc4CEIfQ0iIfVKE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_YIMO_P_1 {
            get {
                return ResourceManager.GetString("Platform_YIMO_P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXoKASM5KlKwILrAEySIiIlEERQGRHARJwhIFyZJBQSRnROARFCQqOUgGkaySs6xI2GXh2vfe7+p3v7qr+tVV3R9Xxfez3T010zXTs13TUwMQAIAjmN/t75wigJWBrrWNg6Oy48OHjg5CnPoWzi42jg5yEsKiUsKiF5HS0sJISaQ4UohT2c3e1c3ZQs7Bws3V2dReiFPb7YG9jZm6BVrP0c7CQQ6FEhWVQlpIS5pJolAosYvEv69C9+fJhVUtHB9auDqjhTUsXKyJ4H6Sx39d56Sps5m1zWMLMfOHZI6PLBwc3JwfuBCZm7qa/u5ESkpK8HuI1PwAyMK2x+1RBBkh3KD6XSEZACDA+hEAXoa/bgd3RADo/761ueFRTdXlIZrGeUD9FHH2x4X3Z+4dwOPrf3eQEoLDM4cbg2xiafV780f/2xb8Sy4SlDbLEJU233kq0LJIUKqMhiWuvbkJgCcK/1Qa/6n8l33/mBtA8GeNgC0BIAREgBg6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_YIMO_P_CH_0 {
            get {
                return ResourceManager.GetString("Platform_YIMO_P_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd1UFTto8DxZxFZQFpCFKRLSpollRAUBESkREppASmBhQUEBJGSRkJAUlI6F0TwBWmRECmRBunu+/jGzO/+5t6ZO3fu/Y/vZ07MnjNnn90z59lZgAAAnMB+b39HhANXOpqWVnb28va2tvZ2PIzaZo5OVvZ20qJ8guJ8glcFUCg+ATEBYQEeRnmXx84ujmbSdmYuzo4mj3kYNVxMH1s9VDFz17K3MbOTFhERFBQXMEOJPRQTERERunr297uc//PifEpm9rZmzo7ufLfNnCxx4evIp3+9D6GJ40NLq6dmQo9sCeyfmNnZuTiaOuE+MnE2+X0SPj4+zu8hknEAIAW3nS5PQgjOwB3S36smKgBw9r1xQCXVXx/n4AQHUP790ab6BtWU5r+SN0wDMj8E8ypv9SWDQ3jc++9zxXng8B7BnV56oTfY3emT/+0W/FtinmtNB9yrTfI7XR9bRNfkNddW5BMO8WQB8PnXpeFflv/02j/3BuD8uUbALQ44A3DBWQgP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Platform_YIMO_P_CH_1 {
            get {
                return ResourceManager.GetString("Platform_YIMO_P_CH_1", resourceCulture);
            }
        }
    }
}
