//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_ABB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_ABB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3PJZ//C/w+772paESGaG0ZSRRshpaJKWhzCKVrG8km/YgVLJXQ1ooq0LSEBlRUWYpkoySvTnv61PncX7n/Hl6Pj736/X5XOMebrpIPD6PxxuHP1xyfyZicGNkeMjGwXGto729o4PcrF3WTs42jg6aqgpLVygsXaKkpqagtFxpmZLcrLUudkddnKw1Haxdjjrts5ObtdXF0s7GSs/afYejrbWDporK0qUrlKzVllstV1FRUV5CcvcihE6usMHa0d76qJO7gr618yEC1uljf+9HYJ+T1SGbY9bK++1Zx/+sHRxcnCydif37ju7jdmIYBuMe4pQFPJ4G5FuX/y6yOBRB7qZghMfDhnwxXvbI36czPI7xpv97at8rKrdsaCmfmtvEm3KKL/NHPlPCdAS2n/q374o5AjzeI4rH+yCpHJsz0DT+/5u8/+ePYMKbVyP+x191tB1/pid3YW37yeNr++nta3m849r/Y+T+j/F/rf3vjw0PQ7d8SK7h0LhO8EiA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_0 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XM1v/Dfwz56ySUXZM9KiVMjKDCEiZUWRohSJQvYo2bNsMiIjIrJlz6xKCGlYhaTo97ou3/vx+N33n3fPx/u839f1ua7rc51z6nTOccKwDMNU4otk8lWFw8VwN1+/gMDugVOnBgaYN3T3CQr2Cwxw6tDOyq6dVXtLe/t2lh0tbSzNG3YP8Z8REuTjFOATMiNorL95w0Eh4/z9xvfzCRsaOMUnwMnW1srKztLHvuP4jra2ttbtRXKWWnTxdi4+gVN9ZgSFtRvgE+wroF8O/XcebWzQeF+/UB/rCVPVwGk+AQEhQeOChQljZ4wlgxRF4cgWq7dgGEfkuyHTVqo8imrkwqUDy3C/IznGocO/K1ReyTG1/7tq7548c3XJf1wj7T1TPYpt/LVtiolnBY7z/421e6EzTKLCMI8aWMed//W+8v83M//PF8ssvDL8XqsrPYcZd7cefrx7w6vx3XM9zXswzLwu/yvS/lf8X33/575huP+W42jFoyJ4RqB4RgSJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_1 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PJV//Dfwa5xzLqVSCBHtNAhZkVFRVlIhFREqhCR7V0JCUkhZZUTZWSmjshpkFLJDVlb25n5fV9/f4/G77z/vno+P1+vzudZxzkXUQVAEQZbhD5nkn1UYfNA5bWp2zUrBytLS6prA5jOXb9iYWV2Tldi3/8C+/cIiUlL7RCRFxEQENivYWdja3bgse+2yne0NQwuBzSftjCzMjNUuO2lZmV++Jisuvn//AZHLUpLGkuLi4qLCdPIqbNTJ9yldtrK8bHvDaZ/6ZRtTGqwT9v+us9LwhrGpmf1l0UuWK6yuX752ze6GkQ3tkqGtIbkTExMTRj7EtfwIIgNZaXfdfwUOhYX8YFCGINicB4Zolv37dOaXMYT9v0/t94+GE0r939cVdSNrPdGtfwXzePQWYDvPf/se2MaEIFl0BKnlFY0qmOle/v9N5P/5w9rBfOR5o1Nx/esMBas7kQpI24WP6IMfighyU/5/jaL/Nf6vtf95bRCM+ohCYghOzTGEhtCp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_2 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5OFT/Hz/8c86cpV2bCkUlW0hEoiRJkiIkJGSLsoVs2SqRlKQikmQplSjZQihbZRfZI4Rky5J9uV/nfL6/6/rd9593j+s9z+d5n3Vmasw0EBRBkAX4Qyf9ZxkGNzqaludt7RTtbGzsbEU2nzJ3cDxvZyu3e4fEnh0SO8VlZHaIS4tLiotsVnSyvuTkYC5na+50ycHYWmTzCScT6/OmquZuJ+2szG3lpKQkJPaIm8tIm0pLSUnt2knQZ1nDHHyHsrmdjfklB7cdx80dLXGYp5z/O88SYwdTy/PO5rvMbBbbXTS3tXVyMHHEzYwvGdMbLVq0CKMvcaUAguyDLHe6eHsxCwobffOzGEGwaW8MqS3+7+7MLGDI2v/dtV+19WrKvTWr8rqQlT7o1r+imVxnZmH94/9tu+c3hSCrCQT5tmnXk5zJroX/v4n8f/7YVxR/3BGzvKB7OPXQXBfrkJ6bm+LG9X8PIcgV+f9r5P1f4/8193+eGwRjblFIGoqwAI4Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_3 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5PFTvGzj8mbNPkfZQqCTJFllCaJek0ELZypKdrNlbaFNoEVFRCSUqIWVtkX1fi1DZSULZl991zuf7vF6/5/nz6f265rru+9znPveMMzNnhlhsFos1B//oTP/jQuBGX8/axtFpp5ODg5OjxOqjli6uNk6OqgpSslukZDfJKClJySjKyMlIrN7pbu/m7mKp6mjp7uZy0l5itY67mb2NuZal12EnO0tHVXl5WdktMpZKiuaK8vLymzfh9FGWMJNLaVg6OVi6uXhJaVu6WmPQT3r8d5x5J13MrW08LDdbOHCcTls6Orq7mLliFifdTtKDKIpC6CUuFGWxtkIudz99nYNCwUPfhLeyWMjkWYQV1Prf3ZmaQ1hL/3fXOuoaD2j01i7K62QtDGCv/SP5bqXRNGzX+9/YLQc4LNY8gsWqEdgcnTPeOff/N7P+P/+K1GZ2cu9o+HjZvGrXolMfdj2d+LVDqbhnF4t1Tv3/irz/K/5fff/Pz4aFMLdsyHSFQkXD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_4 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNx1VFTR+zD6mTOCgoQg3ZKKdHenEhLSgnQqjTQi0p3SKCFKd4d0SChKlzTSIV3vnvl+f2u99133rnXXXevOZz3zPGfvZ+9zZmAGhj+AwWEw2A24ITPyhgWBO211K+vX9tL2r17Zv2ah0TJ3cra2fy3Kx8YlwMbFwSkoyMbJz8nDyUIj7Wrn4upkLvra3NXFydiOheaZq4mdtelTcw9Ne1vz16K8vFxcApzmgvym/Ly8vNwcaMiz3EdtziZvbv/K3MXJg03Z3NnqFhi/7faf82AaO5laWbuZc5u9wrB3MH/92tXJxPmWmbGLMbLpzp07EPIS7zHBYCIgD7o6RGAgQIGLvON6AYNB534QjPHFfx7OxQ0EI/jvQ1v+Pa4i//cXXusK7F4AnHaPtZ7c4BLM7xj8Z15gAGxhAzYfoeTObD5dufn/mmH/x80rv0BmDSeonSxxRKbic4uMA9dbKYecVRkY7K34/xat/1v8X8b+52sDg1D3cJCRFQJUSLdQxxDI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_5 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp3UBRduOa7QbKAiBIko0iQKCKZAVFyEslRRKIIkjOISJKkBMmgIIJkQckwZCQ5BJGcw5Bzjnvg++7W3Vu7Vbe2aqv2D55fved5+4S3T/cwbVsAwRAEnQKd+ZkuY4BGU9XcwtpG0ublSxtrdnoNEzt7Cxtr0fucdwU473LzCApy8vDz3ONhp5d0tHJwtDMRtTZxdLAzsmKnV3F8ZmVhLG/iqmbzwsRalI/v7l0BHhNBfmN+Pj4+Xm6ss7OQnhfnlDaxeWniYOfKqWhib34J9OM4/XMefCM7Y3MLJxPe5y/xbF6ZWFs72j2zv/TcyMHobBIuLi7G2RavMEOQCPAOx1cheJggIT5reNkgCOPAGwNiZvvncg5PMaBr/17a9J8+Jen5HhLkDHTFF2Zc4yij0jsC46us/4wLVIPtYYPopuFNrtqbOf2/dei/KBen/CG+rltdqH3Hw3SC5odfYNcHnz4PPYSg14j/FMj/FP9L3398NhDGeQsDx4AwoUsQFgAb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_6 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwfUWGFDJlvKaiwZyMucYQoRIy92RIprhuIlxDZSiEjJlFJBQZblzzVG5XIUKIzNN1zWPe3TOs9Xt/633Xete71vvPu3w/6+x91j57nbPPOevsvQ5AAAD2YH7Xv0NPAQuTK7ccXd3U3Vxc3FzP8BnbeaAd3VzPnxOTkhOTkpCUlxeTlJU8K3mGTx3j7InxsDvvaofx9LjhfIbPEPOHs+NNXTtvIzcnO9fzMjJSUnKSdvKyN2VlZGSkJah+X4X5z5OLadm5udh5eniLXbJD36KE7dR3/7oO3Q2Pm7cc79pJ27rQut2xc3XFePyBprS94XnjdycaGhqK30NkFAZACdafMHee0B6AOwy/C1NWACi2sBRAj/Wv29neowAsf9/aWHevvtZ0F1PtOGAMRggsiuK4LHZ+H/+7r9wZODxbuNPJI52G3xjf+9/W4N+y2dTWuPM4oDGFaFDDGBimPhcUoO5NNlIHIAD1L1vtv2z/qe2fdwMo/iwRsKYA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_0 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBRNgwfgXoIklSwgSYIgOQlLdAkiIggoKEHSkpccJIOI5CQSJCMZSYqIiGQEESSKJAnCS4YlSQ4Srn1D1Xdf3V1dXdX9x++pnu6a6Zrp2d7pqQEIAMAJzO/6d87iwI32XSuMvYOCg52dgz3vpfvmzi4YB3sZMX5hcX5hQSEJCX4hpNBVId5LCq62D12dzWXszV0fOqNteS9puJrYYkxVzD21HGzM7WVERYWFxYXMJZCmSFFRURFB/N9Xofzz5PxK5g525g+dPflvm7tY4cH9BG5/XYcY7WxqhXEzFzGzI3JwNLe3d3U2ccEzQz9E/+5ESEiI83uIZJwASMO6y9UxkggXNkh/b9KpAcA58MMBMdR/3c6vExxA9fetzfQPqSkt9pE3zAKyAATrT74qev1DeFz3777ivHB4ZrDxjVHkRd3e7Mn/tQb/luLHQc0meNzNeqQXFRol3yqwf8pQKPHmvQ7AY9S/lIZ/Kf9p3z9zA3D+3CJgjQNwAR7Ah84A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_1 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXhBBQbKiZEEECUuWzCJBlCAgIJJzUthV1gWWjIoCEgQkw2J6BFGQnBEFyUFyEEGQJCJpQVjite+939XvfnVX9aurur+O76e6e2qma6ZnuqanBiAAAPswv9vfoSGDlclVF1c0Rg3j7o5BC3Nfc/TAumLQSueRErJICTFxOTmkuIy4lLgwtxrO7Q7Ow1EJ7Yi742HrJsytj7Nzc7XXdsQbYW46opWkpSUkZMUd5WTsZaSlpSXFKH5fhenPkyM1HTHujnc88EhdR6zLIbif0vOv6xy19bB3cfV0lHRwP4K55YhG4zzssIccbO/Y/u5ERUVF9nuI9PwAKMK2A3cr4gg53KD7XbkdB4BsK5AM2Bz/63a298kA89+3NtU3eEXzey/Du2lAfw/BsyxSwWaxA48L/N1XVhgOzwFu9HBIEmo2p/f/ty34lzBOUKuqy/nUV9wuUGuLSVdLPmn2wW+1Tx2AINQ/lXf/VP7Lvn/MDSD7s0bAlgyQg0OA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_2 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTbggfgMwTJOUsGAZEwgpKzZAFBUTAQJEscBUZyUC4KIjlJHECUIEFA4ZKVICACCoNKzmkIg0MYmCFse999W2+3dqtebdX+x++rE6r7VPfp7urT1QAGADiG8rv9HVoSqLK8ds/VC6GN8PREeEkKWDh5+7givNTkpWUVpWXPyygpScsoyFyUkRTQRnr4Ir2d1LyckL7edh6SAmZIew9XByOngOsIdycvNTk5WVlFGSclBQcFOTm5C+fJf5+F5a+DS+s7ITydfL0DpE2cfO6RQdspHv7jPNR23g73XB86XXD0pELcd/LyQnrb+5A52vna/R5ESUlJ8nuKjGIAqEJtH/L+cypSqMPwuypgA4CEEEYC0tj+cTnEYxLA+velzaN/XNFfGWJqXQCMETChTal6bqsDaL/N32MVJaHpOUKdQd4Luc17C8f/1xb8t6j/OfrhXRRju/zIOx1KJJlONCJQ20dtUweAcI1/Ka3/Uv7Ltn8+G0DyVw2DWhJACsgA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_3 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwfc1K5CFkVokMcUmGa6aUKZIkyhQSriljXEkRGULmsYwhoiRy3YyFa5aKzPOcXK57Te/u+T3Pu37vb73vWr/1rvX+9fp+1jl733P2Omefu9fZex2AAADswfwuf4eBAu5MLt92QLtouDg7u6DF+K/auns4uKCVzp6WkjstJYmUlz+NlEWeQYrxa3g63fV0t1VC23redbdyEuM38LR2crDRsfW94uJoi1aSkZGSkkPaysvayMrIyEhLUv++C8ufFz+tZevibHvX3fe0nq3HbSp4nNbrH/c5YOVuc9vBy1b6ljO9i6stGu3pbu1BdcvqrtXvRnR0dBS/u3hYCABFWLZ7ukbQU8IK0++dHSsAFORACnCd9R+Ps7VHAf6qgsm+r/pac73MuClwOBhx7Kd4FZf5Njx/7K8GcmKwe7dgpYdHOgO7ObX3vy3Bv2RPcUdjVLi/PtSmS/PInTrNAtKiekLzrCYA91X+acP90/Zfjv09NoDizz0ClhSA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_4 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NNTfwwfwO9YiZN8JiazZsm+lCCElUVpoQhjrYLKMrJWlZCQSvshOi32vCFlmsosiwhhC2Zdhntt3Oef3/M7znPOc55znnOcP79e5n3vP53PP53Nn7nzuZz4AAQCgwPyuf+cAFdxYWzo5o9xPuru5uaNkDl1Eenk7u6O0j8spqskpHlNQV5dTUFVQVpA5dBLt6oP2QmqjkGgfrxuuMocs0Pauzg4mSMwFdxckSltFRVFRTQGpruqgqqKionSM9vdV2P88uZwh0t0N6eOFkTuL9Haigfvpff+6DsMNLwcnZ1+k0k23/e4eSBQK7WXvTXPzhs+N35327dtH9XuIByUA0IJ1F9ojZj81bLD83uzjBIBqC0sFyBx/fZxtChX4uwkm+wbNDEm9rI1T4GAYQvSnbDX/FTI83vx3BzUZOLybsNEjqJRWvzFF+d/W4N8iXFJgICoa+f7c4x6DuNwGg/dn754Izp82ACBE919K47+U/7Tvn7kBVH9uEbCmAtSA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_5 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UNReuwfwsyDSlI6I0gSR3nsH6dJFpIMgSC+yLJ1FbHRRBEHpTRQBQRDpIKAgvSNFitJEivS6u+/hV9557zv3zrz3ztz/+H4mOUn2JDlJJs9sAAIAgIM5ao9yCg/OjK86Orl7KHu4uXm487Jct/dCOnm4y4nzC0vyCwsKSUnxC0kIiQrxsiijXL1RXvZy7vYoby8bV14WfZStq9NNLXv/ax4u9u5yYmLCwpJC9lISNyXExMREBAmOzkL9x8H51e093Oy9vfz5deyRjifgdkKfP89DYuN109HJx17Ezo3Yw9Pe3R3lZYs8YWfjbXPUiYiICO9oiBQcAMjCthPlGU2MDxfIj2aF1ADg7YfggUzqPy/nAIcHaP66tJmBYV31n/2U9bOA4h6C9Tdf5XmLQ/i70199JXnh8OzgQh+jSFrt7izu/9qCf0shYZUKiXlAYwyyUyWXtEUlB+F/OSNzTAWAOwr/MtX/y/Rftv39bADeH3MEbPEAPjgBCKCTgBAQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_ABB_4600_CH_6 {
            get {
                return ResourceManager.GetString("ABB_ABB_4600_CH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxztOvcG/frtE2aNEmDtf1s27Zt27Zt27Zt27Zt27bfz8z+nTHec/48+xp3v/ecM0nTha52r3ZJPkmS/vJPpPhn+rmoWqFZ8zZtC7Zt3bptm1TxqjTu0LF52za5s6TJkC1NhnTps2dPkz5r+kzpU8Ur2LlVp84dGudu07hzpw71W6WKV65zg1bNG5Zs3L1S25aN2+TOnDlDhmzpG2fP2jBr5syZM6ZTxLVE8g6epmjjtq0bd+rQPU3pxh2bycyrXf5dj16/Q8Nmzbs0ztiodahtu8Zt2nTu0KCj3Kh+p/piI03T/OIUnaSSlIs83bndqFCAxhYX/Xf6JP+Pvn6p885/N+jnX78U+X837dGlq2WKPr/o7n0sOQN9Cd6l3h6z1i/Wc/9v22yxIyRpnyFJF2JnnLP72+O//39T+v/8S5+r4kE9xZYD91OP2xVnx6YCqRNvKVCmUpKCktQv7/9Ve/+v+n/N/T+fG8nvXXITEZBkSUFQUiUNqhSSdIQkw0tD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_0 {
            get {
                return ResourceManager.GetString("ABB_IRB120_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNl3PJX/Gzj+e8goo1JEMpKRLdk7oVQUkiRERPYmqyVkVcjMrKREInumkBnJXtl77/m7znl/vo/H9/f78+f5uM51va7X677PzXGcV3cIiiDIHnwRMuGLEoOHG5rmFja2SrbW1rY2fKw6pg6OFrY2smICZyQEzggJS0oKCIsLnxXmY1VytnJydjCVtTF1dnK4Y8XHetXZ2MrC5JKpu7atpamNrKjomTMSwqaS4ibioqKiIkL7CM9CSzy5gKqprbWpk4O7wBVTR3MS6JO5/Pc8++84mJhbuJiK3LWmsLUztbFxdjB2JLl7x+kOYRE5OTlGuMSDXAgiA7nB2S6IAoeChvBQa40g2KYPhpRa//ftbO1hyJH/fWvDre3qqhN/DpWNIAefoCfn+QuO62/D/LP/rZXgh8tYhJO3nBCJL1kf2fv/m5H/z9dGdvt37X2d379uMSp1DLWdi6bsPNfyK1MJQR7K/19R9n/F/6v3f14bBCM+opAx4ggHJMh/04Qf4T5A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_1 {
            get {
                return ResourceManager.GetString("ABB_IRB120_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3PFZ//Dfws0d7Gw3tEiWVioxKKFLJSFOLUkZJA0l7EFrSFiIiUkbDqJRKoaiESpFESSGi8Hud0/d+PH73/eft+Xhf7/fnc/bnnOu6znWBIAmCaMePlKWfThQeFsxf6+jiaujq7Ozqoj7Qxt5tk6Ori97EMeMmjxk3VlNbe4zmJM0JmuoDDTc7uW92s9dzsd/s7rbCSX3gvM0rnRxXmdl7WLmut3fR09IaN26ypr32pFWTtLS0xo9lpa30lFc+xsTe1dne3c1jjLn9prUM+vkt/7bTYYXbqrWOW+zHr3YWXTfYu7hsdlu5iVm9wn2FNJMgCJS0i91GEIQucs7mDYdFGkVX6WEitkC1+FDEKPbfAf1pp4he/x3ap5eFc0yqCrpnVBDd9pCDf4y+1XfJX0yvY/7NO7lYJIgZPEHk9x9/Ie13Rfv/byb+nx+6+Mj9ulVv7/vWLDQsWnF0+kLtd9MP9VWcQRA7Df5XZPyv+L/6/s+5ISj5EYcoowkGKIIl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_2 {
            get {
                return ResourceManager.GetString("ABB_IRB120_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5PBXvHz/8mTNnZtpVikpo3xRJEVlSSlGkxR5FkmyVZMnSXkLapBLKUiqRtVQohWyJkC1Loo2Q7NvvNefzvR+P333/eXs+3t7v65pr5syZc505MweCJAhiBD9c5n7G8fDLYPsBGwfH9Y729o4OS2fpWx1xsnF0UJGXXrFaesVyWUVFaVkF2ZWyS2etd7Y76nzESsXByvnokb12S2dtc7aws7HUtnLb6Whr5aCyatWKFatlrRQVLBVWrVolt5zmHkVYsHFpTStHe6ujR9ykt1o5HeCjnz323+OM2XvE8oDNMSu5ffajHQ9ZOTg4H7Fw4u/be3QvN2jUqFE8bhcnLiQIZeRC50N+oykUQtwv5SKC4PV784jlRf89nYERHjHlf0/tW+lnHc2fnyZlNBETT5Nz2pelipkOYnnvh/+Wr/7LEsRNmiBKxOVC03qbRv7/ZuL/83PrT0ImJbUnc/MsQuPB7Rnrr/fbr6vpk9YgiBNq/1dk/F/x/+r7f14bgif4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_3 {
            get {
                return ResourceManager.GetString("ABB_IRB120_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE7/Hz/+M66zz4WQ7KzMklR2QpJkJcksShoaqCQie6UI2YUGEUIpVDLKSFYhNOysShkR4vs45/353W7f3+/Pn/vteT2er9cZ17lG1ywESRDEP/xTUvknUzhxmuTp5edv5e/r6+9n2GGK+6IAL38/i369+w7o3bePycCBvU36m5iZGHawCvIJDFrkbuHnHhS4aI6PYYeJQa4+Xm527iGT/ee7+1mYm/ftO8DEfWB/t/7m5uamfRjlXJqpO+9t4+7v6x64KKT3OPcATw3mucX/nY84Z5Gbp9did9O5voL/Anc/v6BFrgGauXMC5ygr8TxPKYfYpBtBDEHeCVqwRaDRNFZOpgwnCepXGEWMGf7fBfr9jyKa/++ivXlYPN7mQ5FOzluiyRqyU43RhTYz/2B50/+tO8BTSxDfeIIobGcam/3z7b//v0n8f/7t3dvcalp+2NUYqenIOjHZqisbOqJwueFIglhp+X9Vzv9V/6+5/+e2ISj1FBcRaEJDMMAS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_4 {
            get {
                return ResourceManager.GetString("ABB_IRB120_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5XE3dGz/8vc/Z4ylCFELIUJoUSmkwZyxziFIkQwMpaRKSqdJNSELILDQQobpRmssQqRClSDTSnH6fve/v83r9nufPx/t17etaa6+99lr7pE4FQRIE0YM/Qhb+yEtwsF6yabOr2ww3Fxc3V63hKxzdd2x2czU10NGfrKM/Xs/ISEfPUG+intbwGZ7OHp7ujqaujp4e7vbOWsMXeTo4b14/39F7mdtWR1fTSZP09SfrORoZrjecNGnShPG0cBdFcXIdC0c3F0cPd2+dhY47NlHoZ3f+dx+Zvfv6TZt3Ok7Y4MK7bXN0dfV0d9hBbbD3sBcGcRwnEZbYZyxBmCDne24L4aUoFIRDJU8Sko4ACVHM/7ehzh4J0f9/W/taVGxpUfOmb1oV0SeQHNmgnayypgvno/83drKjjCA2sQTxeuiE8yltVT3/fzPx//mTorp1hvzsXs96zBVn/iN9OKOvhvx08t+xMwlij/n/FWn/V/y/+v6f14aQiEdsEaQERdDA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_5 {
            get {
                return ResourceManager.GetString("ABB_IRB120_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tLsFUFXh9/e79zZQkRIJaaQEEaSkQQEBaZVuBKS7WwlpkJYWVBARAemWbpCQ7u7ufJ9zfr//zHvfuXfmzp255zPfvdaz1tr7hOesZy9mhGAIgi7BA2VRj9sIOKi8MjaxtBK1srCwsmSmUja0tTOxshR8wsLOw8L+mI2Xl4WNm42TjZlK1MHc3sHWUNDS0MHeVs+cmUrB4Y25ib60oYuilZmhpSAXFzs7D5shL7c+NxcXF8fja6hnwUdfnEXC0MrC0N7WhUXW0M74KohjOP7neW7p2eobmzgachhY3LSyNrS0dLB9Y3fVQM9eD1V048YNBPUScRkgSADYTgfrkJtXgIODOtyXgyDkxAuBCOX+83ZOLxHo7n/f2lz/oJzEch9ezTyE6wPf33pURqp5BvITsv/J86yCC6sD9ZJzpFQdzV/+f7XQ//E48ioUVaD4XIvvTiymDFWg/Gd7nvfFIOid8P+mmv9N/5fY//zbQAj6CAOLQKjgFcBV6Bp0HYAB3YBu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_6 {
            get {
                return ResourceManager.GetString("ABB_IRB120_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwfVwyZa6kzELmDNc8S4aEiqJE5hIu95qHSymXlJSEcKlIFCKZx0ia7lVEegzhmi8yhive3fM8v3f93t9637V+613r/ev1/axz9r7n7nXOPmevs/c6AAEAbMH8Ln9nJx3cnT5x4aIvxgjj44PxlRU+5Y7FXcT46qjKK6nLKx1S1NCQV1RTVFGUFTYK9A4IxLrr+LoHBmCdvWWFrQNdvC+6HnUPtcFccvfVQaOVlNQV3TXUXNXQaLTyIYbfV+H58+TyJu4YH/cAbKj8MXfcBXp4nDHor+uwOGNdL1wMcld282HG+Ln7+gZiXXD0bs4Bzr8bMTEx0f3uIqckANqw/Bjod4MZBSscv3c+uwCgW4+iA867/rod2hYd+LsKKF09liaTnVyNo4AzBhH9IVe932ED/i/1dwN1Wdg9N1j5LKBMrF8d3frfluBfoqh9soVFuuJVx1hLvWBNuaGceIWh/WkJIwCi9f5pa/yn7b8c+8fYALo/9wgs6QAK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_0 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXlCRHCQnESRJziwZURDJoCCSw5JhgSUKkgygKKCggKRFVoIgoIiIwIIiTzKSRBBcCUvOQZB47Xvvd/W7X91V/eqq7o+r4vup6e6a6erpmanpqQEIAMABzO/6d6hIYGFh6ubug9ZCe3ujfUR5zFH+GHe0j6q8uLSiuLSkFBIpLqUgJSslyqMV6BUQ6I9S9UEFBvg7eInyGAc6erk76aFCL6E9UT6qcnLS0opSKKSCk4KcnJyM5NHfZznx5+DiOii0NyrAP1TcAIVxOwL3kwX9dR4KB38nN/cglIyzNznaF+XjE+jviDni7BDg8LvT8ePHSX5PkU4QABVYdwT63iMnhQ3a34UQEwAk25EkgJPpr8vZOSABjH9f2kTfgKHOTC99PRHQ3UDwLotVc1jvwuMTf3dQFIXTc4aNHi6Z7Lot4sH/tgb/En/r/g8CSkMf0I7sWl/Hv5wtGRg868JYrgVAlPo/bfX/tP2Xff94NoDkzxIBaxJACo6A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_1 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXkQREJGMEkQQAckZJAdFJAcl5yzuroQVYYUVURAlPEBkAclIkqACwhIVUEQWUMlIUEGQLFlWlr32vfe7+t2v7qp+dVX3x1Xx/dR0d810zfTM1HTXAAQAgALzu/6dQ1SwsDL39kGhddBIJBolxnfJwz/AB41SU5CQUZKQkZJWVpaQVpSWkxbj08FcCcT4e6ihPDCB/i5XxPhMMa5XfNwMPIIt0b4eKDV5eRkZJWkPZUU3RXl5eVmp/b+vwvLnySX0PNBIj0D/YAkjjwBvarif5tpf16Fz8Xfz9rnmIeuOpEVf9UChMP6uAdTuLoEuvzsdPHiQ6vcQjwgBoArrLszVGNp9sMH4uxBmA4CKhKMC3Gx/3c4vChVg/fvWpvoGjfVme5mav4EjEQj+H+IELvsdeHzq7w5KYnB47rDxkUc2s/HnN8r/tgb/kn0jf7Ssuo22vDllqzPskqBtozymfZKFUxeAmxr/tDX/0/Zf9v3j3QCqP0sErKnA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_2 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXnKSIEEliwKSk0gWEQFBJJoWEEVYcl5yDpIkB8kCCgKCgYxkySALSJIHkiUnybDEa997v6vf/equ6ldXdf9c8f3UTHfNdM1071T37AAEAOAE5nf5O2Q4cPdQy9TM2kbexsrKxpqX9QHKHm1mYy1zjV9YnF9YUEhCgl9ITOiqEC+rvKOlg6M9SsYa5ehgb2DJy6rh+MzSzPAOyvWejQXKWkZUVFhYXAglIWYoJioqKiKI//su1H9enF8JZWOFcrB35b+LQpviweOETn/dh8TA3tDUzAklYmRFbGOLsrZ2tH+GxjMycDD43YiIiAjndxcpOQGQhmWno20YMS6sUPzeKdICgLPvjQMkaf8azsEJDqD5e2jT/YNqSgt9VHUzgNIfwbbGV8GgdwjP4/zdVpwXds8IVnqZRNJq9mZO/rcl+Jc0JRc3NHU8bRAdPZE3aKWXf09ve3MEy38LAB/Zf9rq/mn7L8f+8WwAzp97BCxxAC7AA/gQASAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_3 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXnIUEBQUECWKSn7kxUWCSBBJSo6y5KAssIAEBVEeEkQkyhIkK0kRkQwSRN7CkiUjSFwEJMgKEq597/2ufveru6pfXdX9c8X3UzM9NdM7070901MDEACAA5hf5a8wkMGVsYGTs4enqqe7u6fHhdM30F4YZ08PJRlRSTlRSXEJeXlRCVmJ3yQunFb1cfP28UIreaB9vL1s3S6c1vOxc3O+qY32N/J0RXsoSUtLSspJoOVlb8pKS0tLiVP+ugrrnycX1UB7uqO9vfxFr6IxThRwP7XvX9ehs/W66eTsi5ayd6f1vIX28PDxssNQ2Nt62/6qRENDQ/aricxCACBh2elzK4qWHG4w/VqZHAOAbCeEDOgc+6s7Pw/IANvfXZvp/6SrsdjH0jALmMMQvN9Eqjgtdn8d/7uu3AXYPHu40cstlV73Y/bgf1uCfwmyg1YVIXnuPY7+qBpFeK6qf9MLlRAGETUA7qL+aWn4p+W/7PvH2ACyP9cIWJIB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_4 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwfYVShgw9FKFEpoyZ5yhlHlPm6ZLMLhkvKSFCkilcZR5CESJTyRS54RoLma55CNfMfXfP8/ze9Xt/633X+q13rff9y/ezzt57nbPXOfucs87e6wAEAIAI87v+HUoSWBjp3XFwcVV2dXZ2deFnv4n0QDm4usiJC4hICogICUtJCQhLCF8W5mdX9nLy9PJAyrkgvTw9rJz42XW8rJ0cbNSRvgaujkgXOTExERFJYaSUhI2EmJiYqBDZ76vQ/3lyAVWkqzPS08NXQBOJukMK9x+999d1jlt52NxxuIcUtXWmcHVDurh4eVijSG2tPK1+dzp27BjJ7yGevAiALKy/erk9oTgCGzS/i3kGAEh2gkjAKMNft7NLJAF/N8Ekrl9LdbaHtn4KnHyIOL9yqYrZdA8ez/27gyQ/HJ4tbHSfFcXUbk0R/7c1+JfUsjkqU16j+kRUoFfJIn2vvE1HeQXRcFEFgPsK/7TV/9P2X/b9490Akj9LBKxJwBFA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_5 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd1UBbdowfw8yCltHR3SJfkQyuhAkoIKiktKd2ogJSEICnx0A1KKSCgAgICItJIvORDSXfe4xszv/ube2fu3Jn7x53h+5ndc2b3PLtnn7N7dhYgAABnML/L38HHgCs9LWsbB0clR3t7RwdeprsWzi42jg4yYvzCEvzCgkKSkvxC4kKiQrxMSm52rm7OFjIOFm6uzqZ2vEy33R7a2ZjdtPDScbS1cJC5elVYWELIQlLcTPzq1asigli/z0L658H5VSwc7S1cnb341S1crDHhdhz3v85zydTZzNrG3ULE3P6io5OFg4Ob80MXTHNTV9PfjXBxcTF+d5GYEwAkLLvdnF5cvAArRL9XQuQAYBwGYAB28r8u5+gMA5D9fWmz/UMaKot9JE1zgDgQwbLOV0trcAz3//q7gQQv7J45rPygF0lv2J87+9+W4N8i/qRK6cFxxqdiX6pr7KBeKUYMpbDsy3INgCdy/7I0/cvyn7b9MzYA4881ApYY4ALABFgQNsAB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB120_CH_6 {
            get {
                return ResourceManager.GetString("ABB_IRB120_CH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNwHUBTr9jfq7pk2ICgiIpIFUVQkS04qKCooKEiSjEgGBclJRUEkCSo5iAgYkJyjEiVLzjnnnNO3Zs75V333q3urbt2qy1O/Wetd/fbMwN4zZ3p21UFQBEH24YdQCT9kOLhReWBkbGEpZWlubmlx+YyygZW1saWFuAAnrxAnLzePsDAnjyDPFZ7LZ6RszJ7bWBmIWxjYPLfSNbt8RsFGz8xYX9bAQcnS1MBCnJ+fl1eIx0BYUF+Qn5+fj/sA4VEoiXfOKWNgaW7w3MqB866BtREG80O2/3mcI7pW+kbGtgZ8j81JLJ8aWFjYWOlZY491n+sSNh0+fBhHeIrH2RBEDGqdzVMfEjw05ISbNdiD23LDIVO6//l1tvdxyMn//mojLe33ZCabKYpHkePuKMsCRy6dxg4cT/vvXqFueBov4G6aGPiiCjdG9/+/VuT/+HnPXFza8OJZqZsFTwGKeEuNlD6TIkHZpeDRJP+3FP9v+b/M/uefDYIj3qJQcQgewZAD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_0 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx1dNRa2O/xmUkyk0kyAQ5wcHd3SoHi7g7FaXEpUAGKu7sVKK7F3d3dikNxd6c473dvzl3rvffPy2f95nn2zk5G2jMTSnocTofD8Yc/ooo/loubxvU6dgrpXr57t27dQ3Knb9QuNKxT95CAonkLFstbMH8Bf/+8BfwKFC6QO335iK7hEaHtAkLaRYSHtumaO32diKCunYKrt4ts0L1Lu5CAIkUKFixWoJ2/X7BfkSJFCuXXxL0klgfPW7ld927twkMj89ZsF9ZRZd7T6+/9GG1Cgzt26tWuUNtu3u492oWERIQGhalt24S3EYt0XXeJh5gwm8NRkno2osd4r0KTQNwcqud0uL4Pcjm21fv7hH78cTmS/PfUHl2+Vqvy80uJ9j92JBzmzPguz85UzX+yfeB/a4vF2w7HA8PhiE1TaP7er4///P9Wx//zZ8TvYYdLJM50+M+fr+WCp8wr7xxcpvyrpxkrOByDS/+v7P9f+b/m/s/XxuGStzxF2bkcClSH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_1 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsHNNZ//D/8a1SokBBlVRISsjchlAqRkYxs2bJ3mZWVSjaVnZW9KTOys/cme6/Lxf91XX1/5/zv/7nvc+5zn3N7nOf1er1fn9c1MtP3fBFIBAJxDG+4ins7i4IbdWXT51bW0taWltZWNy+rGb2we25tJcbPwS3IwX2LS0iIg0uAi5fr5mVpBwt7hxdGYlZGDvYv9CxuXlZy0Ld4bnDfyOWxtbmRlRgfHze3IJeRkICBAB8fH8+tk7hnIcc/OIeckbWlkf0LF46HRnamJ2BO4PjveU7rvTAwfe5oxGNoSWRtY2Rl5fBC3+6EoZ69Hm6JkJAQhXuJ55gRCFGorQ42QURoaEhxN0+UEAjUgRcK8VDp3x8Hc4xCUPz3R5vu7lOQ+/uHrHoGcc4HeXWNvZRG6xCuU/63K1gHD0EL6aLjia/cmzn+/1oR/8fbFQVXKeRL99pd7kZpLwtL6cvH3TVOPbF3EIiXEv9bqv+3/F9m//OxQaDwt0ioKPwJDU4gTiJO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_2 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PJX/Gzj+cy9NFEWZFdkzW0YSkqJFRiorycqWkaJSIaWUkZGRUUhaZCRCMorsVcjO3vN33ff78308vr/fn7+ej+tc1+t6ve4znHNejvtEQ2g02hr8IzP5bzMKF2dOXrJxcFR3tLd3dBDZZWDl7GLj6KAsK7ZPXmyfhKSCgpiknKS0pMgudTc7VzdnK2UHKzdXZzM7kV3H3cztbCx0rK6edrS1clCWkdm3T17SSkHOQk5GRkZKgiBvhZm6cjEtK0d7K1fnq2LHrFwu4dBf5/7f7Ww0c7a4ZONuJWVpv8HxipWDg5uzuQtuaeZqRi5av349St7FLfw0mhLkarcrwRswKBjJi+QoGg1d9ENpkVH/PZylNZS27X8PrfdXk67WYP3Wor+0LQHInnHRXPazyzBv9r+18uvoaDQ7uCt1nFKxBfN/1/7/Ztr/59/GewXF25jGv7zWDziE0AbUldR2qzd8f36IRruu+n9F0f8V/6/e/3luaCh1iUBGaRhkHGAQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_3 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3PJX/Hz/+a56GJCOUkGSVTUZCJamstpCErBRFyE4iK5IiO4RKGaWskBTJHhkJyd57r9/znPfne7t9f78/f+6353k+rtfrOudc1xnXOdcpBEUQZB3+qJ36twWDC52zFpbWNio2N2/aWAvvvmhqa2dpY60oIyopJyopLiEvLyohKyEtIbxbxf7GHXtbU0VrU/s7tkY3hHeftje+YWmibup03sbK1FrxwAFJSTkJU3lZE9kDBw5IiZPUe2Gm3biomqnNTdM7tk6imqZ2FgSMb3D47342G9maWFg6mEpdu7nJ5paptbW9rbEdcc3ojhF1pY0bN2LUTdwmgCCHoFfZ3wrchENgoF7UBCEItuSBISVB/+3O8jqGsPxv13oam7XUBhsYi3qRbV7ongmRXI7LKzAf8L915dQpCHIYNqWeUyq2YKF3/f9vR/4/fylr/Sqbde99Xdd+dEzY5+Sx3CuOR+UvRR1DkHvK/1cV/V/1/xr7P88NgtEuUegYbQkHBEIi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_4 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zh5NJVvu8fvrRAylAyZZWoQaZuHraL8kKgIFTJF5nlIm0qSBhRFhGaVuYHIUMg8VOYUGXfJtG1s23iuZ/d73/Wed52z1llnrfPXcX3W97m+13Vf+97Pfiz3YiMcQmgFAstYrGeAi/kR5zMenjqe7u6eHrJixxx9fM94emgpy+1Wldu9S0FNTU5BRUFRQVZMx9/Nz9/HUcvD0d/Px9ZNVszE387tjL2hY7Cpp6ujh5aS0u7dqgqOair2KkpKSvhdjNi7cNM3l9Nz9HR39PMJljNy9HVeC33mgD/vw2rrY+98JsAR7+DO4unl6OHh72Pnu9bB1s8WG1q3bh0DdotcMghpQm7097rOsgYMJ3bx40eIYT6MATnz//k4CysMaNPfH22wteOQ3q+WDWVDiCsct2VyZ6HgyUVY3/X3rKoW3N560BdhfGrJ3NDK/zajfwuL2V26PxfefchTiNGdYzygK7C2eK+xx11dhM5r/4vK/kX/qfePnw1ioF9xkBkQ9nHX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_5 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zl1VFR/9+/PMUBExaCRLhGQ7pQQaQVJiS8NSsOItIgKCIIgICApICgqIkhIiZSEdAgS0iUdQwj89ozPc9fv/ta9az3rrnX/Y798z3vvffbnc87AzJxZgqAIguxD4BwXJw7Bg56WrZ2jk7yTg4OTIxeDrpWrm52To5TwJX7RS/y8fGJil/hE+AT5uBjkMfbuGFcrKUcrjLurmT0XwzWMub2dhaqV5w2n21aOUkJC/PyifFZiIhYiQkJCArxHcWc5h9/8kpKVk4OVu6vnJXUrN9sj0Ce88/c8x81cLWzt7lgJWDoQOTlbOTpiXM3djliauZvhho4dO3YId4mn2RFEEvw7xjmM6DAkJLiHKmYEObTtfwj5xPz36ezsH0JI//XUxrt6NZRmOs9UTiCnA1GmJe4SGqM/cNz3X7Oi3nB5LKAOWoHk8s2J/f9XR/5H7PtLKAxO11ax80YqnPmiqnBqufZyn9NzBQS5J/PfVPnf9L/1/v27QQ7hH1HwQ8hhEAoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_6 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5MFX//wfw9yUfSVH2fU0U2W+WuAhJZCvKkv3KvtzrZr0URWXJvoVLslWiTWRLQrhItgjXeu1kyS6/d59l5vv7zu83853fzO8/z8ec9/vMOe85533OmfM6cwACALAH87v/ncMUsLlq5Ojk7qHu4ebm4S7GZ4LGYJ083JXPiEvLi0tLSikoiEvJSclKifGp41y9cRi0sjsa542xcRXjM8DZujrZ6aD9rni4oN2VkUhpaXkptIKcnRwSiZSRpPp9FsY/Dy6uhfZwQ3tj/MQvobGOB+B26pt/neeQDcbO0ekmWsbejcbDE+3ujsPYYg/Y23jb/B508OBBit9TPCoMgBLsW3GekTSUcIX+d3ObEQCKrWAKgGP863K29ygA09+XNt7Vq6c13XmsZgIcDUUI/DhdzmmxA/cr/z1WXgxOzx6ufOWWyazamNj7v/bg3xLDX1N3QRtTN92bVo0AEepzdV7qiRKi6gDcUvmXpeZflv+27Z9nAyj+bBGwpwCU4ACg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_0 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXpIgkkFEkLQCkiXnuCBKlCxxHzmzZGFJIkoQVgQRRAEVkCAgCiogSRFE4koSQQEFFiTnnK597/2ufveru6pfXdX9dXw/Nd1TM10z3TM13TUAAQA4hPld/84JIliYG7m6eWNQGC8vjLcQp5mTn78bxltJWkRcVkT8vJicnIiYjJikmBAnKtAzINDPScnbKTDAz85TiPNyoL2nm4OOU4gJxsPJW0lKSlxcVsxJTsZBRkpKSuI86e+7MPx5cREtJ4yXU4BfiIiek78rCTx+LOiv+xy383NwdQtyknD0osD4OHl7B/rZ+5M42gXY/W5ETk5O9LuLtHwAKMK6M9AnkYIY7tD8LsKZACDaiSQCvkx/DWf3kAgw/j20ib4Bfa3pXroGAqCNRnAvCVezWu/B83J/t5UVgt1zhDs9ZySy67YIh//bGvxLrNajPyAA8sOl85vqz+yyUOe/qKL017k1ALim8k9bwz9t/+XYP94NIPqzRMCaCBADEkAK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_1 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBRNgwfgXpAgOSmSBCQLS5CcUVAQFAQUJUgQl7QueQkiC4KCgEoWQYKKSg6KgiRByRKWVwmSRXJmWTIsXPuGqu++uqu6uqr746r4PTXdvTNdMz070zO7AAEA2If5Xf8OHRksrpo4Obu6abthMG6uEnxmKE8vZzdXdQXJU0qSp6RllJUlZRRl5GQk+LSxt7yxnih1VxTW29PulgTfJeyNW872Bij/y25olKu6vPypU0oyKGVFe0V5eXlZaYrfR2H9c+eSuig3DMrb01/yIsrL6RBcT+Xz13Fo7DztnZx9ULI3MYfd3FGurljPG16Hbtp52/3uRE1NTfZ7iEwiAKjBuh3r/vAwOWww/i6kWQEg2w4iA4Ksf53Ozj4ZYPv71Ma7eg11Z74z10wAplDEiWVkOZfVLtw+z/LXdiUJOLybsPGNRza9enNi/39bg38Lv+HtMzK5d+q+n23SDrqF0U5h7fri252qA0Cw5r8sNf+y/Kd1/1wbQPZniYA1GSAH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_2 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXgwgIEFAskQJkkEyCwhIkKgEJbtKVInLCkt8SFSERZQksEgwkERFQJAgKBJliSIioAgsQeISl3Tte+939btf3VX97qruP76fmunema6Z3pma7mqAAADswfwuf4eWAu4uXnBz9/TS9vLw8PIU57Vy9kW7e3kiFSRllSRlpWWUlSVlFGVOy4jzamNu+GF8nZGezhg/X9QNcV4zzJUb7lcNnbEWXtedPZHy8rKySjLOyopXFeXl5eWkD/2+C9OfF5fUc/bycPbzxUoaO6PdDsLjlDf/ug81yveqm/tNZzknjyNe3s6enhjfK+iDTig/1O9GVFRUFL+7yCAMgBosP2G87x45ACv0v3clzABQkMMoQA7zX39na48C/F0F430DJnrTvYz1E4AhAsG/KFHFabcNz7v/3UBJHHbPCVZ6uOXwtRsTe//XEvxLso++aSAqLDW+sIzQYaSf0s4R5NM+OJCjA8AfGv+01f/T9l+O/ePdAIo/9whYUoAD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_3 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLogfgXjCRM0hGEJCcJKwkJbgCCohwkByXHJS8RBUOUUAkI0EEUaKoIJIli6RDWDEQJO2S04JkeO0JVffdeq/q1qt6//H7arp7Z7pmerdrenYAAgBwBPOr/hVyIlgY6jk4urmruru6ursJc/2G9vB0dHdTlBGVlBOVFJdAIkUlZCUuSghzqXq7eHl7oBXd0N5eHlYuwly63tYujjZaaIy+uzPaTVFaWlJSTgKNlLWRlZaWlhI/+esqdH+eXBSFdndFe3lgRG+gPR1OwP2nff66DqmVh42Dow9aytaVxP0O2s3N28Pa84StlZfVr05nzpwh+jVEan4AFGDd433nIQkxbFD9Kv6gB4BoN4QItNL/9XX2jojA300wPTSsjZobpGmcAdShCO5VkWpW0314/OHfHeSE4fBsYWOAXSq7fnvm6P9ag3/Li0O8KqnRveZ4VKyacLiGWrW5r4ql/RM1AO4p/8vW+C/bf9v3z9wAoj9LBKyJADE4AU5Cp8Bp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_4 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NFXf3wfwz6XIEAmVjGVMyJDZ7aJEPyGlJFPKEDJe10W4pcgQoTSZknn+ZuxmKplCZI5CvuZ5nqff7jus9Xt+63nW+q1nreevx/u1zt577bPXOfvcvfa5BzAAsI3yq/4VegpU6F+8ZW3vcNrBzs7BXoTnioUz3trBHisjJiknJikuIS8vJiErcVJChOc04bYLwdkCa29BcHE2uy3Cc4Fw47b1TU0Ldz0HWwt7rLS0pKSchIW87E1ZaWlpKfHdv+7C/MfFxdQtHOwsXJzdxbQs8Ld2oX5q1z/vQ2vmfPOWtauFlLkdjYOjhb09wfkGfpe5mYvZr0F79uyh+DXFfYIASqj+QnB8REOJGoy/CgsmAIo1EgUYMP35OOvbFMDy16MNtHZoq4+2MJUNwr77mKMzomR2ow10/shfY+VE0PTMUaOZUyqmZGVw+39bw78lZlD8jF938ce3Eo/PVLOePfNusFhFx/7lGYC7uH85yv7l+C99f68NUPxRYlBNAZSw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_5 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dZ5NFXd/wfwzyEZkiEiUaREZQgpHq55SGVqMFUadHEzXFzz5SoqhYpSisz1UJJGpQwZnkS4ITLfp7hkuObhcg3fradnre/vu36/tb7rt77f/7xf65y9zzn7nrPPOXfvdQADgEWUpXIpvGxoZXPQheBBNCC6uxM95KWs8d4kAtEDt1tRRV1RZaeyhoai8h7lXcryUga+bj6+3nicB97Xx/uUm7yUpe9pN4LjfnzgYaIr3gOnpqaioq6M19jjuEdNTU11J8fSVYR+nlzRBE90x/t4Byqa4UkuK9B+Tr+/rsNzytvRheCHVz3jzk30xHt4+HqfJq04c8rn1FIjLi4utqUuCsgCaKGyxtczmpsdVfiXVm/4AdhmQ9ngMf9ft8NaZAPhX7fW/eWruUlfg2AxHQTCMekRhXzxY3PouM+vturyqHtnUKV+g2pyIZO++P8t4V+yGKppSBSpLJHdGWso8H6/Id/oH3otxHhDgHM6/7QU/9PyP/b9/W6A7ecaQyUb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB1600_145_CH_6 {
            get {
                return ResourceManager.GetString("ABB_IRB1600_145_CH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1llNvKFq5ry7Jk2ZZBsjvMzMzMzMzMzMzMzFlhZmZaYeZkhZmZmc5blX3HOPf+vP2Mz3PWrJLsTnayupNOb4ficDj+8CaqeDOdPFSv1KJlu/aF27dt275dmgTVmnbq3LJ9u7zZ0mXKkS5Thow5c6bLmD1jloxpEhTu2qZL105N87Zr2rVLp4Zt0iSo0LVRm5aNSzftWaV966bt8mbNmilTjoxNc2ZvnD1r1qyZM2jiWcLy5umKN23ftmmXTj3TlW3auYWLubvb3+fxNuzUuEXLbk0zN2nrad+habt2XTs16uxq0rBLQ3HIMAyneImh5A5HHurprh3GeFSaoHj4WFV1OL/3dzqeVlXlu/Pjj9MR+d+79vDSlXLFn1209j1yhAYrid6m3RG7zk/21//vbI7YibhDNIfjQtzMc/d8ffTn/291/H/ekp6Lc+jz/k0H14y+sWdX7t2Fxx3dVFj5d2dhh2NA/v8r+/6v/L9m/8/PjcMpHxWq06E6XA4NOp0b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_0 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1llNvKtq5hWbYsS7ZMcpiZmZmZmZmZmTlZYWZmZmZmTlaYmZnpvFVZd4xz78/bz5ieX80qyU53dro7K8lWHIqi/OFNdPHmU3moVrF5i7btCrVr06Zd29Txqzbp2KlFu7Z5sqbNmD1txvQZcuRImyFbhswZUscv1KV15y4dm+Rp26RL544NWqeOX75Lw9YtGpVq0qNyu1ZN2ubJkiVjxuwZmuTI1ihblixZMqXXxLPY8uZpizVp16ZJ54490pZp0qm5i7ne9e/zmA06NmreomuTTI3bGO3aN2nbtkvHhp1cjRt0biAOeTweVbzEYDJFyU0/3aX9KMNJCIiHD7Ndivq9n6o8me2SP5wff1Ql8t8P7eGlK2WLPbsY2vtICQ5yJHybZnus2j/ZX/vf2exqKkX5Gk9RLsTJNGf310d//n+78v+8bU9nHGrne3hw0euqhfJ+dRWeM2B9oWGb+hRWlP75/lft/V/1f83+z8dGUeWjg67KlRMuRVPccFE6NMWj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_1 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1zlFxZ2OjhozJPxbZt27Yzse2Jbdu2zYkxcSa27UysCb7ffpO71nfvn7eftevFxjlV3VF3OtF0TdN+8qaievMbPNSo3KJlu/ZF2rdt275d2oTVm3bq3LJ9u3zZ02fOmT5zxky5cqXPlCNT1kxpExbp2qZL105N87Vr2rVLp4Zt0ias2LVRm5aNyzTtUbV966bt8mXLljlzzkxNc+VonCNbtmxZMjrUVaLI4elLNG3ftmmXTj3Sl2vauYVF39Xt13W8DTs1btGyW9MsTdp62ndo2q5d106NOltNGnZpqBa53W5D3WI4hablJZ7q2mG0xyQJqYdzMQ3N+NrP0A7HNOTp/PfT0KL+fmoPLlwuX+LpeXvvQy08SE/8Ot2OOHW/MT/299qchaJo2vwgp8TLMnf354c//3+j9v+85W3TtXDYvH7QPB61aJkW/qJ5/5t34O40bzFN61/gf429/2v8X73/877Rft2nTjQ0U7M0B5yaS3MLj+aFT/NrAQS1kBaG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_2 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN1jlGTJF/f7wzRO5sm2bdu2bdu2bdu2bfe0bdu28Xwj+n/Xeu59efuzfrl37Ihzsjq7p6eqprpGURVF+csPUcUPn8ZDtYrNW7RtV6hdmzbt2qaOX7VJx04t2rXNkzVtxuxpM6bPkCNH2gzZMmTOkDp+oS6tO3fp2CRP2yZdOnds0Dp1/PJdGrZu0ahUkx6V27Vq0jZPliwZM2bP0CRHtkbZsmTJkim9KZ7FljdPW6xJuzZNOnfskbZMk07NDebOrv+ex9OgY6PmLbo2ydS4jbtd+yZt23bp2LCT0bhB5wbikMvl0sSbaCVTlNzU013aj3brNEHxcJY3X/vRT1MOyZ+Hovz8qymR//3UHl26WrbY84uhfY8Va5Ca8F2aHbFq/2J/1P/OZt8qTgYU5UKcTHP3fHv89/9vVf4/P+6+VguqythDzexXhbUNnsIXPqwp1PVE9CKK0j/f/5V9/1f+X7P/59dG+fd2qlRNrnSoiqGYUImYOxSn4oKDuOFUPIoX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_3 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN11uBNX1O/xTGaSycQzObi7u7u7uxR3d3enSClWWigUl+JuLU5xdyvuDsX1/e4F93nee/+8fJ6d9dtr75ETSjjhHKhDczgcX/mhqvrhd/JQp3qbtp06l+jcsWPnThmT1m7ZrXvbzp0K5c6cPW/m7Fmz5cuXOVuebDmzZUxaomeHHj27tSzUqWXPHt2adsiYtGrPZh3aNq/Qsm/Nzu1bdiqUK1f27HmztcyXp3meXLly5cjqUleJyskzl2nZuWPLHt36Zq7Usnsbg77Z69t1vE27NW/TtlfLHC06Wp27tOzUqWe3Zt2NFk17NFWbPB6PU91iOI3DUZB6tGeX8ZZOCKmHtnucDueHwU5Hwz1O+XA+fnU6Yr5/aLfPnK9c5sHpyI47jvBwLfnzTFsSNPjEeqrve/NOSeBwDIk6HKcS5fhj27s7X/9/q+P/+VHma47iN73V9kxoYJTS2jhKzXLmL+FLFbsUVyvyv8aO/zX+r97/+blxfLtPjep06DJ3OgyH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_4 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3PJVv/D/we4+kXVo0KE1KSUN8WjRJUwOVnVVJktXeoqSo0NbW1kJbJRmVSKKJiELZ/F73le/j8f39/vz1fFzn/bre13Xf5z4n6ZxyKJqiqCb8UqryqyWDm/mznJzdPSZ4uLl5uA/qOc9+laezh/vYETp6I3X0hgwdNUpnqMHQ4UMH9Zzg5braa5X9WHd7r9WrlroO6jnTa5mrs+00e585Hi727mP19fX0Rg61H2Vga6Cvrz9sCK/cS3tych1Tew83+9WrfHRm2Hs6ceiLa/7dT4ulq2ydnNfYD7Nzkz1W2Lu7e61a5snZLV29VNkkSRKjXGIbbYoyRE3xWrFbZhFaKzdpFE0xtYEM9Zj694DqmhiqQ/ND+/rmnZlp0eu2id+oNpvo3r8G3+62uB7ru5v3jiyRKeqZSFEZ6sOi4qu/Nf3/Vur/+RVm92FiHvPsYZO5OMmzCzNpMZM0XmNI+0kUtd74f43E/zX+r97//N5QDLnFQwSW4igeBCSe4CgR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_5 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNl3PFb/Gzj+c+77HBpEyUpoK1sZkdFCMkqUjGQkZJW9KUqFyN4qKzsrKymzzGTLzCZ7799135/39/Ebf/48H9d9Xa/r9Tqvc859F50gKIIgO/BFyqQvKgK8qN0yMja3uGJhZmZhzn3kjoGllbGFuYQw79nzvGf5BURFeQVEBAQFuI9csTG1trE0kDA3sLG21DXlPnLTRs/UWF/ewEHVwsTAXEJI6OzZ8wIGoiL6IkJCQuf4cdJZ6Mib88oaWJgZWFs68CoaWBlh0Ke0/d959uha6hsZ2xqce2C22+Kxgbm5jaWeFfZA11qXtGjXrl0E0iXSciCIOOR6m8c+u4lQ0JBe/LwRhLDuRkA8vP93Oxs7BOTgf7c21NKuJDvevL90GKH1QI/N8hSyaG3CvPx/a8+zUsAi2OY367mYktXhnf+/Gfn/fI2WotLcsj/KeLcopM/twqRzN6ovZ3vQSSOIu9T/I0r/H/H/6v2fzwYhkF9RyASEiGAIDigQSmQX2I3s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_6 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFXdwwfwfaWkTCVj1xySDJdkHkqRyBARQubZxXUNVyLzUCES4t5H5hSPpEgoUzyGi2tKZqJMN5nH++6e4V2/97fed613vWu9//l+1jl7r3P2Onufu9fZ51yAAABQYH6Vv0JHBXcm152cPdDqaHd3tMdZXmN7b4wz2kP5vLiUnLiUJEpeXhwlizqHOsurjnXzwXrbK3vYY328rd3O8upjbdycbbXtA4zQrvYeyjIyUlJyKHt5WVtZGRkZacmDv3ph/vPi4pr2aHd7H+8A8Wv2GCdqeJzG969+jlh72zo5+9pL27nToj3tPTyw3jYYajtrH+tfjQ4fPkz1a4hMwgAowbId63mf9gCsMP7ahTMDQLUVTAX8mf+6nW0KFTjx961N9fTran4nHav9CpjCEPw/xCpP3tqB59X+bit3Fg7PDla6uaTx1RtfKf/XEvxbkEvIhgne1/UXnx6uEX3wXt2Q7rV6ObZKHYAQ1X/Zav9l+y/H/pkbQPXnHgFLKnAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_0 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBTLogfgXiRIBslpSQooAi4IkhFJIlFA4JAUZMmwkkGSGABBMhKUHBQkKTkuh6TkJIjEVWRBAQXJmdd6zn11q+599ULV+4/fV9M9O9M105N6ahYgAABHML/qX6EggIWRnp29C0YJ4+yMcTnPZYh2c7fHuMhJCItKCoteQElJCaMuoS6iznMpeTp5eLqh5VzQnh5ulk7nuXQ9rZzsb2ugfQ0wjmgXOXFxUVFJFFrq0u1L4uLiYheIfu2F7vfGhdXQGGe0h5uvsBba3Y4QLifx+ms/ZJZut+3svdBi1s6kmDtoFxdPNyt3QmtLD8tfjU6ePEnwq4s0/ADIwrrX884T0hNwhvpXkcAAAMFuEAEIY/jrcPaOCAD934c2OzyqrfbtPW0THtA8QPCsCNWyme3D9bp/t5U8D7tnDWeGOMTSG7fxR//XGvxL7in809T0T9N/t/z371/X5/dmCH6XCFgTgBOAEBBBxIAEnIRIARkghygAJaCCqAENoIVOATp4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_1 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3VBPLowfwCaKAiIBURapSpQpIB6VcmoKASpGONClBIEKkqXQpASmGGqUXURSQDgIixQCClEvX0AzFqKEICLzRe3/v/M75vXfe771z3n98P2d3NruT2dlMMns2AAEA2IP5Vf7KEQq4MjV2cfVEaiA9PJCeojzXHL19XJGeKufEz8qLn5WUUlAQl5KTkpES5dFAufuivB1VPB1Rvt527qI8l1H27q4O+o7oK0g3R08VWdmzZ+WlHBXkHORkZWWlJQ/+OgvT78bFtR2RHo6+3mjxS44+LpRwP9Xtv85z2M7bwcX1tqP0DQ8apJejpyfK296H8oadr92vStTU1BS/usggCIAyLHtQXrE0B+AG/a9VJAsAFFshFCCA5a/L2d6jAMx/X9rs4IiBNvEDY/McYAhF8H0Vq+Ww/AmPa/xdV14Udu8G3BjglM5u/DG3938twb/krto/Lc3/tPxP+3+//jU+v5uh+L1GwJICHACU4CB0CFABaogGHAa00BFAB45C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_2 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh3UBRNgwfgXhBQFBbJOaoLSkZEchJQlKwESRKWuOQkQYIoCAqSJChBJSNBguSggpIEFBAkB8kZBBaWsNf6vt/VV/Xd1YWq++v4PTXTszNdMz3TMz01CxAAADzM7/J3ThHAmZ62ja2jk6KTg4OTIy+7LtrVzdbJUfoSv/BlfmFBIXFxfiExoYtCvOyKHhh3D1e0tCPaw93VDMPLrulhjrG1uI72vulkj3aUFhUVFr4shBYXsxATFRUVEST6fRSqPzvnV0E7OaDdXb351dBuNsfgehLPv45DauZqYWPriRaxdDjh5Ix2dPRwNXc7Zmnmbva70vHjxwl+N5ECBYAULDs8nJ+cIIQLyN8zFxoACHABBABN89fp7OEJAPXfpzbV26+uMt9zumEaUAQjONf4qpiM9uF2vr/rXuaFzbOEC90sIql1O9P4/20J/iWBsv80NfzT9F+t//P7d//82Q3BnzkClgSAEBwDRBAxIAHHoROAFJyETgEyQA4hAQU4DVEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_3 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dh5NFTv4wfwZxBJlihkz67sS9ZJSMgeImu2jxRGBmUbREjZKmuiUoQpH7usFYXs28hSsoQY+zKGYX5PfT7f3/me8/39zm8553fO7w/v17n3eebe5zz3PvfOPPfcAQgAABnmV/krhyngyvLiVXcvlBbK0xPlJc53ydUH7Y7yQp6WlFWSlJWWUVaWlFGUkZcR59Py8/D183FFern6+fo4eojzmfg5ebg767sGmKOuu3ohFRRkZZVkXJUVnRUVFBTkpA/8OgrL784ldVxRnq6+PgGShq7oq1RwO43/X8c55OjjfNXd31XOxZMW5e3q5eXn44SmcnH0dfzV6ODBgxS/TpFJBAA1WHb4ed+npYQVxl8r+qMAUGyHUgDE0b+Gs0OmAH9XwVT/oJHOz74jDT8AUwSCf1niLactCe5vZflrv5I4PD0XWOnllsuq2/pB/t+W4F8Spv5PS8M/Lf/V9t+ff92f391Q/F4jYEkBKAEVOABRAxpwEKIFhwAddBjQAwaI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_4 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLogfgXhABUZCMBAGRpBwUEJa8BAEPUZBoQoQlwyJB4oKSJWMgS46HpKRDxgMoSE6CZMUlhyUIuEt67Tnnvrrv1n1Vt17V+4/fVz3dNdM707NT010DEACAI5if9c+cJoEbIz1rG0eMMsbBAeMoxGWIdnaxwTjKSQiLSgqLXhWRkhIWQYpcExHiUnazd3VzRss5ot1cnc3shbhuuj20tzHXQHvqY+zQjnLi4qKikiJoKaQ5UlxcXOwq2c+r0P95cmE1NMYB7ersKayFdrE+AfeTP/7rOqfMnM2tbR6jxSwcKDFOaEdHN+eHLicszFzNfnaioKAg+TnEs/wAyMK6280pgpIUNmh+bmIYACAh+pGAQIa/bmfviAT83QS4oRFttcVB2qZZcDYAcWH9lxq2u/vwuObfHSSF4PAsYGOAQyy14cfs0f+1Bv+SduGJ63dSOpr1hMlVRFhIVP4QblOqu0yvAsAT1D+Vpn8q/2PfP54NIPlzi4A1CSAFJwAZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_5 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFT//wfw11Ah+5IlRFEKiWSZMJSElLLkgyyhsWdsQ2JQKJWQPTFCSUmSkOxbliyRkj3rSD5kHVt8332W7/n+vuf7O+d7fuf8/vN8nPdy7n3Pve8799z3nQEMAGyg/Gp/hYkGVb/p2zu4ENQJly8TXCSFjfDuHg4EFxV5qcOKUoelZbBYKRkFmSMyksLqRGdPojtexQVP9HS3cpYUPke0dnaw0cH7GBKc8C4qcnKHDyvK4LEKNgpycnKy0lt/nYXzj4NLaeIJl/Ge7j5SZ/Ae9lvQdjqvP8+z3crdxt7BCy976TIDwRXv4kJ0t/bYcsnK0+rXIHp6eppfU2QTA1BGbTPRNYyBFnVYf1URHAA0KwE0EMTx5+WsbtAA11+XNtLRqav57SN7+SiwBWH2/DhYxG+2hvbr/DVWURJN7xLqtAvKkkuXRjf+ry38W+rKMBoYqK9i+rlNg45+y6/+8et3ODUAAlX/pZT/S/kf2/6+N0DzR41BLQ3QwhbYimwD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABB_IRB6700_320_150_CH_6 {
            get {
                return ResourceManager.GetString("ABB_IRB6700_320_150_CH_6", resourceCulture);
            }
        }
    }
}
