//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_Yaskawa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_Yaskawa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNx3XE5//Dfws/c5IXtky4wyMsveysguO6RlFBHZMyQre2Rkb1mVGdkiSshoapglEv1e5+N7Px6/+/7z9ny8r9fr8znnOtcoiS9fiqYoqgQ/zDR/aAxuhg6c7OHj28XX29vXp3GNIe7TZ3j4+nRoZdPczsauWfMWzWzsbJs1s21co4u/l5//dPcOPu7+ftPHejWu0d9/nJfH+D7us118Pd19OrRsaWfX2ta9jf14+5YtWzZvxpuPYkkubtPD3dfb3W/6bJt+7jMmc9gXZ/57HGXs9PGTPWa6N5/gLftOdffx8Z8+bgY3YazfWPMkSZIY8ymWsqao9kg6YMFqmUWxMG8uTqcppmg+Qx2b/u8F/S5hqLL/vbS0hESnHh+flb6aTpVaTNf60uRSFddiHPf779zWnAVFucgU9bRa813RP9NL/n+T+n9+BPs+vjk23fLm7ZC71xK0iV1cR27tcvvd3C4UtcDxf83V/zX/197/+dhQDLnFSwQWQwNHOkuZJ/Eg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_0 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nN11dBtHwO7h1WpXtJIW5DAnDTTMzMxJw8zMzMzMzGmYOQ0zMzMzMzX4/Waae8537583z5l935kFyY6tWpbjKi5FUX7xR6T4E1TZVK3QrHmbtoXatm7dtk3qhFUad+jYvG2bPFnTZsqYNmP6TJnTp82YIX36DKkTFurcqlPnDo3ztGncuVOH+q1SJyzfuUGr5g1LNe5eqW3Lxm3yZMmSMWP2DI1zZGuYLUuWLJnS6+JWIvLiaYs1btu6cacO3dOWadyxmca6t8t/txOo36Fhs+ZdGmdq1Nrftl3jNm06d2jQUWtUv1N9cZDP51PFXbSSK0pu0tWt3yi/m2KKTWq/qqhf+6pKQr8q35xvv1Ql6veb9uDC5bLFnp63dz9UrIGuxG/SbI1T6zv7n/j+OzZ7Mo48FlSUc/Eyzdn55eGv/99U/p8/NwaM27+oXPP9B1b3KhS36+xCMWLPKXR9TbrCitIv3/8au//X+L/W/s/fjfLf/XSRqiIW3XAxNOiKR/HC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_1 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5WEx9/Dfwc+bMnDNnFEJJqSgkJQqRypZsUcgSlSjZ2mhRIdlLRbJlaaGINhTKkrK0kCWFFlIqlVLSrhK/9zm357p+z/Pn0+v6zPvzXc6ZM6NmJrebIAmC+IsvLrkvKQFuVi/fstXF1djV2dnVRWvEKgc3962uLkZ62pN0tXUnTpo8UVtXZ+JEHa0Rxp5OHp5uDkYuDp4ebhuctEYs9bRz2mpv6uCzwtXRwcVoyhRd3Wk6DvpT7adOmTJl0kQRdy+D+ZNrz3dwdXbwcPPRXuLgvkWIeWbnf/cj2eBmv2XrTodJG51Z1+0OLi6ebnbuwo0bPDZwm8RisYC7xIHqBGGIJL33BbMUmgHcjYM0SQh6/ATEGun/HlDvXwEx5N9D+/q+2Gx+/TuZzBpi4EFS9ef4+4rWv7E+8t/eaUkSghAzBFGoNCny0a+av/+/Sfw/X4cKCp/MW3rgWb7WXeM15yKM3+1bNWeUpGouQeyb+b8q83/V/zX3f/5sCAF/i4fI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_2 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxztORKwO7hdNLp7qTTSXps27Zt27ZtnLFt27Zt27Ztfb+qmbvWd++fd55Ved+qVNLde5+Zs/eZ3kfxKIryh18ixS9L5VC1QrPmbdoWbNu6dds2qeJVadyhY/O2bXJnSZMxQ5oM6TJmSpcmQ/p06dKnilewc6tOnTs0zt2mcedOHeq3ShWvXOcGrZo3LNm4e6W2LRu3yZ05c4YM2dI3zp61YdbMmTNnTKeLR4kob56maOO2rRt36tA9TenGHZt5Wfd3+fs4Zv0ODZs179I4Y6PWRtt2jdu06dyhQUdvo/qd6otNgUBAFU/RTaoouUhPt34jDY3iiMOu/R5F/d5XVdbt//uCfvxRlUj/XtrDi1fKFH12IbznkeIO8CR4m3pbzFo/Od/9395sS8KKsjSoKOdjZ5y96+ujP/+/qfw/vxI/zJM/cbzBB0ZruwsdPR6vUP90MwpeqqUUVpR+ef/X2PO/xv+19n8+N4oqj7xEaIpX0eFT/EoAhmIqQVhKSLHh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_3 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt3XE5//Dfws9eF7FVZIYpQdsNeKYQiK5VKWpIoGmZWNmUlIrMkCokyi6LsyiYkoRKR1u91Pl/34/G77z9vz8fnvN6fcc51znWdLlff74WiKYqqxx811T8NGGymTZ7v7u0zwsfLy8e7Rwc7l0V+7j7e5v2NTIyNjHub9O1tZNynd+8+PTqM8Pdc7L/IxdzbxX/xIkfPHh0m+Tt5ujuPdwmc6uPh4m3er5+x8cA+LoMGOA/o16+fSW9efZRm5OBGY1x8vFwWLwo0snbxm89hXFzy3+Mojouc57svcTGZ5yX7LHTx9vZf5OTHzXNc7KgukiSJUU+xsT5FmSHpgBXhMotCS90s70pTzN9QhvLp+t8FVdczVPN/l/bhSd6EMcWPm6R/pBqvpjuV9UzRnlWD+QH/1g48qaGosyJFPdI1OXj1z8f6/9+k/p8/h5a1H3l61Zrr23Z+GjmrrGbkw379RoQE1I2kqBVD/ldL/1/t/xr7P68NxZAtLhFYiqN4ECiR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_4 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNt5OFT/Hz/8c+Zsc+ZMaVG0aVGUNUSRpUJatRdaFKlUCBFaVNpEuyQppUJaqRQpLUpFi5RCK6JotVT23/Ocz/e+rt99/3l7XK95Pd/LOWdMmTESQRIE0Y4PsYsfShlu5kxf5untY+vj5eXjrddvtoefv6ePt5WZgYmxgfFQk2FDDYyNhg410utnG7BydYCfh5W3R8Bqv0Ur9fpNDXBb6ek+0SN4ps8KD28rU1Nj4xFGHubD3YebmpqaDGXEq3SVTm7g4OHj5bHaL9hgsof/MhrzXOB/11Es8nNf5hnoYbLYi/dZ5eHtHeDn5k8vXrR6kbhJLpfLxLvYSZsgLNHJoI2RPIWgIt6s7kUSsqZQGbGs13+fUHO7jFD936dW8fK1o8PXws7Zn4lOYeSAX/oZvea1YH3o//aOmKMkCCeOIF70MTl289/n9v+/nfj/fKy/891uu/u+0Y8ufLV7MZSwDzTuars+o9GOIDba/F+V/X/V/2vu//mzIWTSLT5FoAia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_5 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp1UFXf3+/3RgFRQkBUOgVpEClpAUERkE7p7u5QUbqRUOKQ0iAgSHcpCCJKSXd317mL8/3+Zp77zHNn7tyZ+x/v13zW+71i77XO5qD7DyAYgiAk0IVfCBsNNGqKZuY2tuK21ta2NixUqsYOjua2NkI8bFwP2B5wcD3kYHvAycHByUIl7mzl5OxgLGRj7OzkoG/FQvXC2cDK3FDG2F3Z1tLYRoib+8EDPk5jfl5DXm5ubi4O9ItdCFE3Z5MytrU2dnJwZ5M1djS7CsYxXf7Z57q+g6GZuYsxl5E1lq2dsY2Ns4OB41UjfSf9i0XXrl1DuzjiTQYIEgQOu70KxboCAt5F080JQWjHvmhQI+c/H+cEiQbd+vejzf4elJNa6sdvmINu+sE0m6xVpNqnYD7w37V8w+B4mqB+kXOl1B3OIf9fHfpv2qJASmilnov9fbUigRcJSeIHXhVPWj+QgKBXIv+lGv5L/W9j//nZQGioFgaOBtor0FUAOirDEAZI/zgm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_6 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NFT//wfw91hSiISQLSQpu8bOWJOEECLZBylLxhBhMBUVIjtjJCplaZF9y1p2MYgskXVsZd/93n2/n+/vfH/f8/ue8z2/c37/eT7Ofb/vufd97n3duXPf91yAAADswfzp/4SeAjZmRs433Nw13F1d3d1ETpiiPTE33N2UZcSkpcSkJKTPSYhJSUpISIqc0MDe8sJ6opXd0FgvT9tbIicuY+1u3bDXRftecb+JdlNGIqWk5CTR8rL2skgkUlqC+s9ZmP92cDFttLsr2svTV0wPjXGmgttpvP9+HlpbT3vnG95oaQfXQ+4eaDc3rKcdhsrB1sv2z6CDBw9S/CnxiBAASrBH3AkKP0QJVxj/NEmsAFBs4ihABOvfL2drjwKw/HVpY6Refe3pLqaqcXAEj+D/JVrCabkN95v8NVZOBJbnAFc6uaWJFevje//XHvxL7vi019JRsNbioxs/3ah11BgRTdJ48DRQA4Ag1D8tVf+0/I9t/7g3gOJvLQL2FIAS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_0 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBRNgwfgXiSIBFHJQSQrGVYkJxcFREAyiILkzCo5L0oOCi+ogBJEsgIiIEhYEAEJIktGchAWyUlyuvYNVd99dVd1dVX31/F7arqnZrpmelJPNUAAAI5gfte/Q04ACwNtWztnNArt5IR25r+gb+Xiaod2lr0iiBQVFBVGXhYWFBURFhbhv4Byd3Rzd7GSdbZyd3Mxc+S/cMvd3NHOQs3KWxftYOUsKyYmKiohYiUpbiEuJiaGFCb6fZZzfx5cUNkK7WTl5uItqG7laksIt5N4/HWeU2YuFrZ2HlZISydS9H0rZ2d3F3NXQkszN7PfjU6ePEnwu4tUPADIwBrhFRhNegKunP5duNAAQLCLIQDWNH9dzt4RAaD++9Kmevo1lGe7z9ROA6ogBPuKQAXTnX24X/DvthL8sHuWcKWLBZmK3Z4++t/W4N+CLfijvirRrt5v2xelK5OCaqVPRQ29E1ICIFD+X5baf1n+07Z/ng0g+LNEwJoAnACEgAgiBiTg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_1 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXhQDShTFlQwiiIDIimRWQAQFXJAkWcIKSM5RJGMABAGRtIAEQUAQAVkkKU+SwpIk5yg5xwX22vfe7+p3v7qr+tVV3R9XxfdTM9010zvTs1PTXQ0QAAASzO/yd06SwZ32XQtLWzs5OxsbO1s+Ni2so5Olna3UNQGUkICQIOqqoIDQFUHBK3xsci7Wzi6OWClbrIuzo7E1H5uqi4m1pakS1kPDzgprKyUsLCQkegUrJmIqIiwsjBIk/32XU39eXEABa2eDdXb0EFDBOlkchsePuv51HwpjR1MLS1csyszmuJ091tbWxdHE6bCZsbPx70bHjh0j+91FGm4AJGGJcPcNPX4IVqh/79CnASDbeUwGUKf/ehwiiQzQ//1o4x1ddxSm22mrJgBNAIJjiR/PqL8LzxP/biDKB7tnBittzChcxdYE6X9bgn9JYGvbFwnpgBoCX7Hc6O0kOTZfLVn56ZEbAPii/2mr+qftvxz7x7sBZH/uEbAkA4fA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_2 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBTLgwfwXoKIgICAyCODhFVyFNglKIgICoLkjK6ACEtGcjSSYZGcBAURUUwECSoiQVhydAEFlpUgOUjca997v6vf/equ6ldXdX8d30/NdNdM10xPT3VPDUAAAMgwv8vfoaeAO1NDJ2c37BmsqyvWTYzPBOPp5Yx1QytIyMpIyEjJyklJyEhLSUmL8Z3xueHt44lBu2F8vD3tb4jxGfg43HC+oovxv4x1wbih5eVlZE5JY5QUryjKy8vLSlH/vgvLnxeX0MZgXTHenv4SFzBeTlTwOI3vX/c5ZO95xcnZFyN71ZUW645xc/PxdPCiumrvbf+70cGDByl+d5FJBAAULBE3w2JoKWGF8ffOlQ0Aiq1QCmDP9tfjbJMpAOvfjzbZO3BRe7qHuZ4ImCIRAoviVZxWO/A88u+2p8Rg967CSje3bE7tLyL5f1uCfwlGQ1rj4uPbDZOVtZqWCvyaQtaZZ65aAy0AwtT+aav/p+2/HPvHuwEUf+4RsKQAlIAK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_3 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd5NJXdowfwfciUOcqcMoQyHFMoY9JRCAllOiFTxhwzxxCpzEMhY5kLDQoZTyLzTMpcwjG9DglxDufu3vf93fW7v3XvWr9117r/3OX7Wc+z99rPXs+zn2k/6wEIAAAZ5nf5OwwUcGV6xdHJzV3T3dXV3U38mImdJ8bJ3U3ltKSsjKQMUlYOKSkjjURKix/T9Hbx8va0U3Gz8/bytHYRP2bgbePiZKtj53/V3dnOTUVeXkZGUdpOScFWQV5eXhZJ9fsobH/uXBJl5+5q5+XpL6lnh3E8ANtpfP46zkFrT1tHJx872ZuudO4edm5u3p42mAM3rb2sf3eipaWl+D1EFhEAlGGJ8AuNoaOEFebfK63DAFDshFAApcN/nQ6RTAHY/z61maHPl1ELg6y4WcASjhBYlajmsSDB7Yi/+yqKw+HdhJUBPtns+l+z5P9tCf4lNBb85094RTQKPpw7T9wgne+Sltd0CN47D0Co2j8tuH9a/kvbP+4NoPhzjYAlBaAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_4 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UFTLggfgHhBUQBBBUfKABMk5D0GQQRQkCSJJkAEFASXnQRGHHCRJVkFAkEEQJcNVQIYgSM5BJEjGAclh23vv23r7arfq1Vbt/sXvq3O6q0/XOT3T1X3qAAQA4ADmd/k7VCTwZKR3566jk6qTg4OTowC7IcbZ5a6TI0pKSFxMSExEXEJESExURERUgF3V7Z6rmzMG5Yhxc3W2vCfAruNmde/u7SsYLwMne4wjSlJSTExGFCMrfVtaUlJSXITs91Po/ry5EBrj5IBxdfYS0sK43DkC24+6//UcCkvn23fuumPErR2OO93HODq6OVu5HLG2dLX83enYsWMkv4d4kgcABVgiPAPCj5PCCs3v0wI9ACTbWBIwTv/Xz9k5IAF/V8Fkd582eraLtnYKnAxEcKwIljOZ7sLruX93kBGAw7OGlU4W8fTqzamD/20J/iVDVYtq7n3RKk34WbVpEXBJwIBO1a98Sw2AAKV/Omr/6fgvbf+YG0Dy5xkBSxJACo4A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_5 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dd3UBNdvwfwE6o8IIIgvQoqCFKkSGhRAUGRoqhI770ECEgvgoqFoqBIB0VBQVFAVEpAutLyCNKbCCRI7wmQhHt8yp33vnPfmXfeufc/vp/ZPZvNmd092Tm/zQIEAGAH5lf7Kyw0cGV60dXNG62F9vJCe0uLXHHyw7ihvTWUZRSOyxyXU1CUkzkuLycnLy2iFeDpH+DnpOHtFODvZ+cpLWIcYO/p5qDvFHwJ7eHkraGkdPy4irwT8oTDCSUlJQU5+l9n4fjj4DK6TmgvJ3+/YBkDJ4wrHdzPeO3P8/xm5+fg6nbNScHRiwnt4+TtHeBnj6FztPO3+9Vpz549NL8uke0IAOqwRQRFxTHRwo19v1ZfOACg2YqkAViOP4ezvUMDOP8a2uS3PkPdn93stVOALQZxcOlYBb8lGX5/86++KtLw8hzhRpegQjaWNLXzn7bgn7IstKNtkUs9NRQ1qy1wH+iw36bTylwgagMQhfqHpfYflv+x7+97A2j+WCNgSwNo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YASKAWA_GP20HL_ASSY_ASM_CH_6 {
            get {
                return ResourceManager.GetString("YASKAWA_GP20HL_ASSY_ASM_CH_6", resourceCulture);
            }
        }
    }
}
