//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm_JAKA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotArm_JAKA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ0FsJxYt7ahm6ZpoIETd3d3d8/E3d3d3T2ZuLu7u7snE3d394l7cp+9M3/VrVv156m133etvdhANx/wReYoqqIov/klVPyyfQxVKzZv0bZd4XZt2rRrmyZB1SYdO7Vo1zZv9nSZcqbLlDljhuzpMmfIkDFNgsJdWnfu0rFJ3rZNunTu2KB1mgTluzRs3aJRqSY9Krdr1aRt3qxZM2XKkbFJzuyNsmfNmjVzhoDYSWS5drriTdq1adK5Y490ZZp0aq5RD3b9sxuzQcdGzVt0bZK5cZtQu/ZN2rbt0rFhJ61xg84NRJNhGD5xhF5yRcmDjh/SeUzIj3HFUPqrT/F96+dTCnz1ybP5/tunRPnvzB5evFK2+LMLEXsfKd4gNdG/abfHrv2DeeO/3hzLIhRFJ87HzTxn95dHv/9/KrsTNN+XbGSNLckP9C/w/3Kp8wYUUP7Pr0u/9x9QlV0HLhxOuP3o7/2F8IVOl05QSFH65/9fsfd/xf+p/ffrz3GqqE/x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_0 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLoHOFb/H/9/zrlvijKzkhFCJCM7MyrKLLIjyShZSdlCSEiSJCspGmZIdsheieyRXcmWPf6vc3++v+v6/f/X9fe43uf5fL/er/c44z7nPt0hKIIgu/CHK/63H4ONwUW7645Oqk4ODk6OQocNrG+5XndyVJAWPiErfEJcTFRaWFxUVEzosKrbzdtut6wVHK3dbt+yvCl0WNft6s3rVhrWHvpO9taOCpKSJ07IiFnLSltJS0pKiouS4ZMcII0trGbt5GB9+5aHsJa1qx0R4nvu/DcNpeUtK7vrd6zFrzlQODlbOzq63brqSrxmedsST9q7dy+Gr5CWH0HkQaOCbj+iIIChwTe8HQiCbfhhyMGO//ZmcxdDGP63Z+Od3dpqvzvoKiYQ2kCUe/540SGzLWgf+f5fu8xnWIY3lO/s4kllaxO7/38aw0PYP55o9aVVIeZUYLCH8j1D6shqCbMvJwbmTydm+yoj/58/v/m4KhMkqerfDqdKM1e8ChtPvMo1GSdV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_1 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ0F9BVV1LdvzJ2Ze6cuDX+6uxvpkEZASlBCQbq7uxEQpEMQpLu7G6W7G+lGmvfZB7+13u9b6+NZZ36/vc8+Z87EGVAEfX6fz/eZH6Lyww5wqFW9WfM2bUu1bd26bZssKWo16dCxeds2RfJny1UwW67cOXPkz5Y7R46cWVKU6tyqU+cOTYq0adK5U4dGrbKkqNr5x1bNf6rYpHuNti2btCmSN2+uXAVyNimY/6f8efPmzZ0jJCeJo+bOVrZJ29ZNOnXonq1yk47NNPJGly+niTTq8FOz5l2a5G7cOty2XZM2bTp3+LGj1rhRp0ZSZJpmQFYYTe/zFUZ/HdxpdDiI8eSwP6XmC7zrG/BtTqmpq3n/OeCL+9+V3Tp1tkrZeydjbb/tiw70p3qadWPi7z/QP/C/2gJZEvt85WN8vhNJc8/c+ub25/+frm6U70qOrZ12NLqQrH/lS72K96/tjtmd5/sduS49LT1jeZ/ivv/nx0p92q7ZiUbuPlJ8QEl8yc+f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_2 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJsJVE5f2PbP8JzzqDTJrEGliAqlFAlFKGVKJEQDooEyNRNJGSJDhVQoYypJijIkFRGRJApFGiSlEtF77eP/rfV+31qf39r7uu5777Of++yTnulE0RRF9eIfUfKvL4PObuE6N08vcy8PDy9P7eF2rt4+bl6eUybq6hnr6umPHzdRV3/cuPHaw823uG/e4u06xdN1y2bv1e7aw+dvcXJ3c7Zy9bX12uDqOcXAQE/PaLyr8UTniQYGBvrjOPIgCsLaurNcvTxcN3v76lq7+qwTIS/e+u9hJFd7O69z2+qq7+Ih4bXR1dNzi7eTj8hl9ebVZFKfPn0YUqHcSIoygR4O3XxQgoWRJZ3ZXJpifgUzlOHcf+fzu5eh+v93ZnUvK2xmNbyQv/OJkttFq7XqZA9b3oPxv1b/5hptFlNUFVqZkv7p3J+fev9/mt1Htk7++5q7XXFycx4ZBU7L3Xuxy0rj4F2RTKLlE6OAadT/809G+uh9mjpz/3ajxoxM9qiZ19bR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_3 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLx1VFVP2Pe9Nx0SIgIiKd0g3SLSpSIN0l3SICUgIC2NtAICUtIgKSkhKd0hndL9zOF332s977PWez5r9vc711x775nh7LNn/EMIhiDoBnwQivjcQQIH9ZcWlnb2kva2tvZ2rFTqpo5OlvZ2ovzsjwXZH3NzcfKzc3NycrFSSbrYOLs4morambo4OxrasFI9dzGysTRWMPV4ZW9taifKy/v4sQCXqSC/MT8vLy83JyriJvdur80uY2pva+rs6MGuZOpkgQLi6K7/3QbL0NHYwtLVlNvEFtP+jamdnYujkROKiaGzISIJAwMDCdFDfAYIEgEaHegciYkMDB7i8MwMgpDOfZEgAbP/RnNxgwQR/s/Ilv+MKcusD99t+gvhB8CP9thqH+pegnbof3IFBJH+G/4QOXd6w+nfm/8/RdwfapZunlxuChpysn0C/U99+ahDTiHd8Qn0/3wmXYRbXlU8bv3wJPUZyivhpzc3n1swKwueQdA78f+rNP1f5f8T+98/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_4 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dLkFVFXPF/d9zr0gChJKt4igIK2ASIkoIFKC0iVIS5e0BUqHCkorJQICitIlgiLdSId0d8O77/39n7We913r9bP27O/s2TNzzpm5l7lHBEUQ5Aj+4Tzu30kMFJrqllZ29rL2trb2djxnNM2cnK3s7SRF+YTE+IQuCQqI8l0SEBDkOSPr+tDF1clM0s7M1cXp/kOeM2quJg+tTG+bedy1tzGzkxQWFhK6ImgmJmoqKiwsfEmAEDcJJX5sPnkze1szFycPPmUzZ0sCiBO5/TcN8X0nU0srN7NLD2xP2DuY2dm5Opk4Ezy473Ifl3T8+HEM7gopziOIBPhIf5ewE1gQ5LhisARBMLt+GKSt5L+72TvCIFT/u7N/nT0q8jMdpyonEIpn6Nll3mJG/X1of/e/3Cu2MMRZsHbmS4nl2xNH/38eNz9SJVdFO82URaJrew35X/2Hse95uUSna8j/599vJ/EfKHKjprEg68a4hfh1t8bAH8fmCm8gyGPp/8sq/y/7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_5 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJwJVE7f+/bP8JzpKzLPhJS5KERU5lDGCBkylUiFiiaSeR4yhgZChkiaiCIpylAKRWRuEM1UlP7X3vWu9X/ftV6fdZ/ruq99n1PPU+v7k/b+MSzDMPX4Q5T8UeNwsZxpt9LRaayTg4OTY/9uljbrnFc6ORoZ6OgN19HTHzTQQEd/4MBB/buNdV3t4rrOxsjRxtVl3ZLV/btNd126euUyMxv3WU72No5GQ4bo6Q0bZDPcYJnBkCFD9AcK5IO0os/WMbVxcrBxWeeuM8XG2U6FXFrf8GH+W7Jumd3K9Tb6yx0UpzU2jo6u65Y6q5YvcVlChmRZ5shn2LwXw4yEHt7uckDhYdTJ5bszy3B/vDkm17nh9fyt55jWja/s68usqaaFmS3ufWOab2V7lA643WlBLdYvNs4Oq1AYplxmmIwu+gFx1d/q/39Kp+9PuP/5lqvVEk+HUT+W9NpXNED3/t9Tea516y1HMf/Pn9UfhjxgGfvEr7NCx8GPqa4fm3g1IWYc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_6 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp5NFThAz/+u46kUCrJMgpJhSRZYqaopEQoSpYiqZQ1+1apkGwpIkubUJYKyTrJHpnKLtmZGNtgMMaY39Pn+/me8/39fud7zvf8zvn95/069945M888d3me+9w7CwRDEMQF+bf8lzUImJkaX7nq6KTjdOOGk+NuSVM7V7erTo5aqgp71RX2KivtUVVQ3rNHabekjvv1m+6udlqOdu43XS9e3y15yt3m+lXbE3bep50c7By1VFT27lVTslNXtVVVUVFR3oP/W4nQf+pW0LVzumF309Vb4aSd2xUMPM/j8T9Ws/qiq+2Vqx52ypdu8Do52zk6urvauGGXLt68+K/QqlWrkH9bKCgLQZpgGX3vZgQvCh4I/Ju1HoQgZDEQgb4d/B97w+Yi0Ib/7tlgc5uB7kjTOsoQJBgEb5uSLxS1WAKvP/pvWTVzAgRJgMp/iSsnly4Mcf+/LqH/R1q45V9hqORrU9XWwhpuuTZ4rN2oL6kNQbfI/8tE+V+m/9tz/5rn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_0 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dt5NJT/4/D/a32rVJSKsraKiiLZtxSVpLJVRJGEsu/LjKIoZE9kiZSdsmSn7BGTrFmzjn3sgzEz9+v9+X7vc+7ffc59zv37nfP7z/NxZl5zxmWu65prMxIEQxDEBP07/tt2BNzp3nxkbmWtYv3kibXVSQFdUzt7c2sreUkRMWkRMfEzpyVFxE+fPnNSQMXxsYOjnam8lamjg939xycFrjsaPzY3UTd11ba2NLWSl5AQE5M6YyotaSIpISEhfhr/dyYc/3ltETVT6yemDnauIhqm9o8w8DyL03/NZtt9O5NH5k6m4g+ebLW2MbWycrQztsce3He4/+9EW7ZsQf5dQnZBCJIDY8hzh9dbUfCA7d+7dfAUsk5EoFm5/1obGhOB9vz3mo20dV5Tm2jdVTEKsXvDh+ZOFXEbbICvf/3vaaV+4RA0BxbxN694XNnqKPP/6wj9bxHnoirvQHGVywz+8z8PvjvPc/jd+QdS1ioQ5KX4v9wq/pfb/+O5fzfPf14I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_1 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp5PBVv+Dj8Wc6ZObNIJVlTKFotSZKtUmmlUlkSIRQiZN8qLWRLKkuWT6sKiVKRpbJnS0QhKqLssmV/rr7f3x+/5/nzud+vM3Nec445M/dcc93LQFAEQWah/Fv/KywGi8MHTpx0cNR2PHXK0WH1ksNWzi4nHR00VOTWqsqtVVJUUJFTUlBQXL1E29X+jKuzlYaDlesZZ3P71Uv2uVrYn7TcbeV50NHOykFDWXnt2g2KVqoqlirKyspKCtx/PyLwP/uW07FyPGV1xtlTbq+VywkObCfd/vdnaHNnyxMn3ayUjp+iHE9bOTi4Olu4cI6bnzH/9yUej4f9O8K5sgiiDuuIi2fCKBze8P9bWF5GEGzCH0MMLv/v2UzOYsiC/3Nm7XUNujq/a+fl/0TmBqBSA2uyxEym4PPF/+e7G5bwIcgxOJSPi5QScv/+nP3/u0b+PyWduPXutkhwQdWm81vg/ZbZ2fh3ouW7tyLIWa3/65X/f73+X9v+XZ7/2RH2P0sU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_2 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tNsHTBRR+zD66bMWxE4TUBFREBERkK6iYAUVadKUIgoCAtKbFVRARERAmqj0piAiXUXpRaWsIEWk997bfXz/702++yVfcnOTe36Zncnu7CnPnjI7m0VQBEGWIf3b/0urMXjQOH/1mqWVopWFhZXlnq0aJja216ws5ST37pfau19MdJ/kXrF9+0T3bFW0u37TzsZEztLE7qbN5et7tp61M7x+zeiUidMFK3MTSzlx8f37D4qaSEkaSYqLi4vtI/8VsuE/ee9VNrGyMLlp47T3jIntVQKep+3/p5iVl22Mrl6zNxEztlhhdcPE0tLOxtCWML588/K/kxgMBvavhmsFEEQW9v73bz5egcMB678HQg9BsDkPDJnR/Z/WzC9jyMb/tqyjlqmi3FuzrqATWXsX3T4inMWluwCvf/rvuQfzGQjSB5n/5BaLyJvpXP7/ukf+t7SG5dkXFHn1JbeP/2gG/uyIlb3gES3v+KMIckvhf9kK/pft//Hcv4/nPxlh/3lE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_3 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp3UNReozfwFBVUBBEEld5EROqKdFZABKVLUaQJiEiXLl0EWXpVEKSIiKA0FZEOIh0RlCpdYHHpve/C3uPvee7Mfe/Mnbnzzrx/vXw/k5yQhJPknCQku0AwBEFkkL/l31AhYKR/4761g6Oio729o8MFdn1LZxdrRwdZcUFRSUFRjIiwuCBGWFjkAruim52rm7OlrIOlm6uzmd0Fdi03cztrC1VLT11HW0sHWTExUVEJEUtJcQtxMTExjPDBvxuh+6duQWVLR3tLV2dPQXVLl/sHwHwK939t5oiZs8V9a3dLzF37w44PLB0c3JzNXQ7cNXM1+7sSJSUl8ncPj/NCkAwoY5+4Rh1GwQTN39GrcxCE7PgjUMK5fx0NkYxA9P8+Mnx3n4bydBdtzSR0PBDmXBIoYzIigeUm/15XohNUcRXsYicLJq1qa5L8f1tC/y0DbtJfdT+J1oVcTrlyQFdagUzO+Hq4OPcKBD3C/peh5r8M/8e8v93zT0XIP2MYlAiE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_4 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp1UFTx4+j9UysgIiIoKA1KiLRILSUgJmEQ0iChdDeoqCgpgoQ0SCglgiC5Kt0q3dLdnXs/fn+/O3OfO3Nn7jzzPP/xfs2eA2eXPYdTu4cFgiEIIoL+jf91DAED9Tvmj6xt5G2srGysL7Kom9g7PLKxlhLlExLnExIWFBDlExYQELzIIu9k6ehkbyJlbeLkaG9oeZFF1cnI8pHxTRO3ezYWJtZSIiJCQmKCJuKixqIiIiLCArh/M6H+z3PzKZnYWJk42rvx3TZxMMfAdBLn/5rNUUN7Y/NHzibCD63IbGxNrK2d7I0csIeGjob/HkRKSor8W8ITnBCEB+PQF47BZCj4gvLfgBZMQnZ8EIgc/1+/zS4RgWj++zcba+9SVppuoyKMQyd8YbYl3mJ6nT1wf5vkf90vJouDoO9gEf8wCseXb40T/9+Oof+tOnvJnzCkUNlUkKkwaiZ5xbnp9c8js0UKEPRE5n+5Ef6X2/9j2r/N858nQv4zhMEYgVAIg3DA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_5 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7dp5NFXR4z/8M1IpFIXMCqlMSWYqRTKnUsKtEFGGZJ4qCZlJZjepzEkImSrzEJUxY8ab8Zq5hnuf3ef7/T3r9/zW+q31W89az3r+8X6te89x7l77nn3O3vuecxYIhiCIBvJv+S+7EfB29ZLVXVs7Vbv79+1sj/NdtXjgeNfOVklG7ISc2AkpSQkZMSkJCcnjfKpO9x46PbBQsrVwevjg1r3jfHpOt+/dNdO0cLtsZ2NhqyQtfeKErKSFnIyZjLS0tJQE/u9LWP5Tt5i6hd19i4cP3MS0LRytMLCd3vm/vmbXrQdmVnedLaTM7++0s7ewtXV6cNsRM7/18Na/Qjt27ED+7SGzMAQpgmWE38PQnShYYfr3dlEJgpB1HwRSVvqv1mzQEIj1v1s22t6loz7RtrdyDGL2hQXmREs4jTfB53T/XVaWhw6CdoHKf3FLJZevjdH+3y6h/yX3BqW/wZBN1ejl7HNg/ewaTbUq62vROQh6pPI/vSr/p9f/Y9u/0/Of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JAKA_Zu12_CH_6 {
            get {
                return ResourceManager.GetString("JAKA_Zu12_CH_6", resourceCulture);
            }
        }
    }
}
